### ISSUE TITLE
somatic calling

### ISSUE THREAD

**Issue by ekg** [freebayes/freebayes#107]
There should be somatic (or tumor/normal) calling supported by freebayes in a coherent way.

Right now we have some experience with doing it using a command line similar to this:

```
freebayes -f ref.fa --pooled-continuous --pooled-discrete -F 0.03 -C 2 tumor.bam normal.bam >out.vcf
```

The problem is that to get good performance you need to implement something like the (mutect filter)[https://www.broadinstitute.org/cancer/cga/mutect] criteria based on the GLs. This could easily be supported internally if additional parameters were specified. For instance:

```
freebayes ... --tumor [tumor sample name in BAM] --normal [normal sample name in BAM] ...
```

An additional parameter, say `--somatic-lod-filter-mut-rate 1e-7 --somatic-lod-filter-target-fp 0.01` could be used to specify the thresholds which are important for the method to work.

**Comment by mdshw5** [comment]
We're also interested in a sane way to do paired somatic variant calling using Freebayes, without coming up with our own arbitrary filters. I like the idea of a parameter to control the FP rate, and in general making assumptions about biological mechanisms (i.e. your mutation rate example) also seem like a good idea as a common issue in our group (@swheelan) is "Freebayes gave us sooooooooo many variants: 1. how do I filter them? 2. Even after filtering, is this close to a reasonable number of variants?"

**Comment by chapmanb** [comment]
Matt, Erik and all;
We've done a lot of work on filtering somatic calls with FreeBayes and have an in-progress writeup on the results validating against the DREAM synthetic 3 data here:

https://github.com/chapmanb/bcbb/blob/master/posts/cancer_validation.org

There is a section specifically about improvements we were able to get with FreeBayes, in additional to comparisons to other callers.

The code we use to call FreeBayes is here: https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/freebayes.py#L118 and our filter is here:  https://github.com/chapmanb/bcbio-nextgen/blob/97060a79fe3dc82fb7cf7953495d52f0ba8c40ad/bcbio/variation/freebayes.py#L217

Hope this is helpful to folks. Happy to work with anyone to improve calling.

**Comment by dakl** [comment]
Great work, very interesting read. Two questions:

1. Have you tried pindel for somatic indel calling? I'd be interested in
learning how it performs.
2. Is the pipeline for timor-only calling available?


Thanks,

Daniel

**Comment by chapmanb** [comment]
Daniel;
Glad this is useful:

- We did do some initial validation with pindel. With the default settings it was very accurate but less sensitive than Scalpel. We didn't explore more because it was slow for larger datasets. We were not able to turn off code that checks for larger structural variants when trying to use it just for smaller indel detection. You can see the work in progress here: https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/structural/pindel.py.

- The tumor-only prioritization happens by default when running within bcbio with a sample missing a matched normal. Apologies, I should have been more explicit about that and added a note to the write up.

Thanks again.

**Comment by cellnetix-shruti** [comment]
@chapmanb: Are you able to call any linked mutations using Freebayes for Tumor-only calling like KRAS G12C, G12D etc?

**Comment by chapmanb** [comment]
I'm not exactly sure from your question what outputs your looking for, but I did do work to call tumor-only variants and prioritize non-germline calls using data from ExAC and 1000 genomes. This is integrated as part of bcbio (https://github.com/chapmanb/bcbio-nextgen) and a write up on the approach is here:

http://bcb.io/2015/03/05/cancerval/

We run bcbio in the same way for tumor/normal and tumor-only, but need to do the post filtering with known population variants to try and remove germline. The options we use for FreeBayes somatic calling are here:

https://github.com/chapmanb/bcbio-nextgen/blob/f9e0cae9fd7c3770a1ef19244787484a295fb4c6/bcbio/variation/freebayes.py#L47

Hope this helps.

**Comment by cellnetix-shruti** [comment]
Hi Brad,
Thanks for your reply. I will check that out.
I want to generate VCF files. Currently I am looking for a caller to replace Illumina's Somatic variant caller which is inbuilt on the Miseq Reporter.
We run only Tumor samples in our assay and I wanted to be able to detect variants as low as 3%
I already tried running the software using --pooled-continuous and -F 0.001 in the default diploid mode.
I noticed though that the vcf Files does have some calls with multiple Variant alleles separated by a comma. Do I just ignore those? I think your write-up clarifies a lot of my questions.
Thanks again.

**Comment by ekg** [comment]
You could filter the alleles using hard filters or other classifier
approaches based on annotations in the vcf file.

The idea with the open caller settings is more for freebayes to work as a
kind of first level compressor and filter over the sequencing data. In
effect freebayes turns the reference and read data into a description of a
series of bubbles bounded by the reference, with only minimal filtering.

**Comment by cellnetix-shruti** [comment]
Great! Thanks Brad!

**Comment by cellnetix-shruti** [comment]
Thanks Erik.
I have some clarity after reading Brads post too.
