### ISSUE TITLE
freebayes parallel

### ISSUE THREAD

**Issue by pziarsolo** [freebayes/freebayes#113]
Hi,
I am trying to use freebayes parallel but I have found some issues:
1- git clones different files if you clone vcflib or freebayes:
[peio]@[udalaitz]:~$ git clone --recursive git://github.com/ekg/vcflib.git 
[...]
[peio]@[udalaitz]:~$ ls vcflib/bin  
bed2region     vcfclearid       vcfindelproximity   vcfnobiallelicsnps       vcfplotaltdiscrepancy.sh   vcfqualfilter                 vcfremovenonATGC
plot_roc.r     vcfclearinfo     vcfindels           vcfnoindels              vcfplotsitediscrepancy.r   vcfregionreduce               vcfsnps
vcf2bed.py     vcfcomplex       vcfmultiallelic     vcfnosnps                vcfplottstv.sh             vcfregionreduce_and_cut       vcfsort
vcf2sqlite.py  vcffirstheader   vcfmultiway         vcfnulldotslashdot       vcfprintaltdiscrepancy.r   vcfregionreduce_pipe          vcf_strip_extra_headers
vcfbiallelic   vcfgtcompare.sh  vcfmultiwayscripts  vcfplotaltdiscrepancy.r  vcfprintaltdiscrepancy.sh  vcfregionreduce_uncompressed  vcfvarstats

[peio]@[udalaitz]:~$ git clone --recursive git://github.com/ekg/freebayes.git
[...]
[peio]@[udalaitz]:~$ ls freebayes/vcflib/bin  
plot_roc.r     vcfcomplex         vcfmultiway         vcfnulldotslashdot        vcfprintaltdiscrepancy.r   vcfregionreduce_pipe          vcfvarstats
vcf2sqlite.py  vcfgtcompare.sh    vcfmultiwayscripts  vcfplotaltdiscrepancy.r   vcfprintaltdiscrepancy.sh  vcfregionreduce_uncompressed
vcfbiallelic   vcfindelproximity  vcfnobiallelicsnps  vcfplotaltdiscrepancy.sh  vcfqualfilter              vcfsnps
vcfclearid     vcfindels          vcfnoindels         vcfplotsitediscrepancy.r  vcfregionreduce            vcfsort
vcfclearinfo   vcfmultiallelic    vcfnosnps           vcfplottstv.sh            vcfregionreduce_and_cut    vcf_strip_extra_headers

vcffirstheader is not in the freebayes standar instalation.

2- After copyng vcffisrheader to the path I am able to run freebayes parallel but it breaks when trying to write the vcffile:

[jope]@[emmy]:~/rafa_celegans/snv_calling$ freebayes-parallel <(fasta_generate_regions.py ../mapping/reference/c_elegans.WS245.fasta.fai 1000000) 104 -f ../mapping/reference/c_elegans.WS245.fasta --min-mapping-quality 30 --min-base-quality 20 --min-alternate-count 3 --min-alternate-fraction 0.2 --mismatch-base-quality-threshold 15 --read-max-mismatch-fraction 0.05 --min-coverage 6 --report-monomorphic --genotype-qualities --report-genotype-likelihood-max ../mapping/bams/*.bam |vcffilter -f "QUAL > 20" |bgzip >celegans_parallel.vcf.gz
error: more sample names in header than sample fields
samples: AM141 RVM10_5x RVM12_5x RVM12_original RVM1_5x RVM1_original RVM7_6x
line: I 1342206 .       C       .       3.23224e-15     .       DP=320;DPB=320;EPPR=3.03744;GTI=0;MQMR=60;NS=7;NUMALT=0;ODDS=0;PAIREDR=0.99375;PQR=0;PRO=0;QR=11149;RO=320;RPPR=6.91895        GT:GQ:DP:RO:QR:AO:QA:GL 0/0:151.283:50:50:1757:.:.:0    0/0:151.283:47:47:1666:.:.:0    0/0:151.283:65:65:2291:.:.:0    0##fileformat=VCFv4.1
Traceback (most recent call last):
  File "/usr/local/bin/vcffirstheader", line 16, in <module>
    print line.strip()
IOError: [Errno 32] Broken pipe

Any advice to solve this? 

Peio

**Comment by tseemann** [comment]
This is essentially the same problem as #130
