### ISSUE TITLE
GT assignment and AO counts are inconsistent

### ISSUE THREAD

**Issue by sprouffske** [freebayes/freebayes#143]
Erik,

The GT value sometimes is non-zero (i.e., references an alternative allele) although there are no AO counts (meaning that no alternative alleles were observed in the bam files!).  How can you call an alternative allele without observing any instances of it in the data? This seems impossible...  

The call I'm making is:
freebayes
--region chr:0-200000
--fasta-reference ref.fa
--pooled-continuous
--haplotype-length 0
--min-base-quality 30
--min-mapping-quality 20
--min-alternate-fraction 0
--min-coverage 100
--min-alternate-count 1
--ploidy 1
--dont-left-align-indels
--bam-list list-of-bam-files.txt
--vcf output.vcf

In many output lines I double-checked, the GT value references an alternative allele while the AO value reports no counts for that allele for at least one sample.  I've pulled the genotype information for two examples from my output data. The format for both is: GT:DP:RO:QR:AO:QA:GL.

REF: GCC, ALT: CG,TGG,CGA,CGC
4:20:20:706:0,0,0,0:0,0,0,0:0,-10,-10,-10,-10 (GT is CGC; AO for CGC is 0)

REF T, ALT C
1:4:4:138:0:0:0,-10 (GT is C, AO for C is 0)

**Comment by tseemann** [comment]
@ksprout  The ```--haplotype 0 --pooled-continuous``` is referred to as "_naive variant calling: simply annotate observation counts_" in the manual. I wonder if the GT field is meaningless in that mode?

**Comment by ksprout** [comment]
That's true that the GT field doesn't have a clear meaning in this case. However, as the genotype likelihood (GL) is also reported, it would be logical for the GT field to point to the genotype with the maximum likelihood (or possibly the maximum read depth, depending on how things are actually implemented with these flags).

**Comment by ekg** [comment]
@tseemann Perhaps the `--pooled-continuous` flag is at fault here. Interesting. I'll check if I can get a test case.

@ksprout Would you please send me this example. I don't understand how AO is 0 and an alternate allele was considered. That shouldn't be possible.

What version of freebayes are you using? The current versions should produce the GL max in the output considering only the alleles that would be in the maximum a posteriori estimate of the mutual genotyping across all samples. Perhaps the `--pooled-continuous` use here is something I haven't considered.

Also, I would be extremely careful about `--dont-left-align-indels`. That's there for debugging and testing of the (default) left realignment.

**Comment by MinocheAE** [comment]
Hi,
I also found a inconsistency: 
0/1:29:0:0:29:1065:-96.2172,-8.72987,0 (GT:DP:RO:QR:AO:QA:GL)

It definitely should be GT=1/1

I was using version:  v0.9.16-1-gf46d24f-dirty and running "freebayes-parallel <(cat regions.txt) 32 -f hg19.fasta  dir1/*.bam dir2/*.bam" with default settings.

Best,
André

**Comment by dwaggott** [comment]
Not quite the same but I posted a similar issue (with example) that came up from a vcf called using bcbio's  joint freebayes pipeline. There is only one AO value for multiallelic sites when the header says `number=A`.

samtools/bcftools#290

```
##FORMAT=<ID=AO,Number=A,Type=Integer,Description="Alternate allele observation count">
1       10177   .       AC      ACCC,ACC        1       PASS  ....  2|2:2:3:73:0:0   ./.:0:1:0:0:0  ./.:1:1:6:0:0
```

**Comment by blessu** [comment]
Similar issue. Look around that row, you may find other variants with the same AO strings.
Generally sum(number_of_ALT) == number_of_AO, though in some cases even this is not true...

**Comment by biocdeniz** [comment]
Hi @ekg , 

I have variant data processed by someone else (I got it from NIH). However, I see a lot of inconsistencies and I don't know how these results should be interpreted based on **AO** and allele calls themselves:
```
##CHROM	POS	    ID	  REF	 ALT	FORMAT			S1				S2		
6       51586771    .       GC      AC	GT:AO:DP:GQ:QA:QR:RO    1/1:41,0:41:99:1312,0:0:0       0/1:18,0:36:0:559,0:644:18
6       109767930   .       GC      TC	GT:AO:DP:GQ:QA:QR:RO	0/1:0,38:96:99:0,1262:2002:58   0/1:0,56:102:99:0,1824:1560:45
1       12837634    .       T       A 	GT:AO:DP:GQ:QA:QR:RO	0/1:24,0:53:99:675,0:945:29     1/1:49,0:49:99:1550,0:0:0
2       171822466   .       CGA     TGA	GT:AO:DP:GQ:QA:QR:RO	1/1:180,16:201:0:5294,57:0:0    1/1:158,11:177:99:4463,42:24:1
``` 
From this post <https://github.com/ekg/freebayes/issues/459> you say: "AO is the number of alternate observations, with **one record per alternate allele**". It is clear here that ALL these calls are SNPs and only one alternate allele is available. Nevertheless, **AO** has two numbers/records. Any guidance on how these cases should be processed? I have way too many other calls that look like this.

Cheers!
