### ISSUE TITLE
Variant missed when using -r option

### ISSUE THREAD

**Issue by marc-sturm** [freebayes/freebayes#145]
Hi Erik,

I found a case where a good SNP is missed when using the the commandline parameter "-r" for the target region. The SNP is at chr1:155205634 (hg19). It is detected when using the target region chr1:155205616-155205660 and missed when using the target region chr1:155205617-155205660. That seems odd because both regions contain the SNP position...

Here you can download the minimal example:
https://drive.google.com/file/d/0B-iHdfk93LueNk16a3QxU1lqVVk/view?usp=sharing

Best,
  Marc

**Comment by ekg** [comment]
@marc-sturm Thanks for the case, I'll check it out now.
