### ISSUE TITLE
--no-snps still results in snps when a variant file is specified

### ISSUE THREAD

**Issue by EReckase** [freebayes/freebayes#150]
I've run across a case where I have a deletion in the same location as a SNP specified in a variant input file, and --only-use-input-alleles is set.  When I call freebayes with --no-snps, I get a SNP but with an alternate allele of '.', and the GL line accordingly has too many values.  --no-indels also reports the same SNP.  Shouldn't a SNP be required to have a non-null alternate allele?

**Comment by ekg** [comment]
@EReckase That's... odd. It sounds like a lot is going on here. As usual, would you be willing to send me a test?

**Comment by EReckase** [comment]
I'll try to put together a test set for you - sorry for the delay, other dev tasks were taking priority. :dollar:
