### ISSUE TITLE
Mac installation -- missing directories

### ISSUE THREAD

**Issue by kkwinner** [freebayes/freebayes#151]
Hi!  I'm trying to build freebayes on a Mac, OS X 10.10.2 (and also tried on a machine with 10.10.1).
after "sudo make install",
I get the error:
cp bin/freebayes bin/bamleftalign /usr/local/bin/
cp: bin/freebayes is a directory (not copied).
cp: bin/bamleftalign: No such file or directory
make: **\* [install] Error 1

bin is completely empty.  To install the freebayes folder, I used git:
git clone --recursive git://github.com/ekg/freebayes.git
I didn't see any errors during the cloning.

Is there anything I can do to fix it? 

Thanks, 
Kim

**Comment by ekg** [comment]
I would just "make" and then copy the files in the bin folder to where you
want them to be (perhaps /usr/local/bin, it depends on your system).

**Comment by tseemann** [comment]
@ekg perhaps just modify the Makefile

OLD
```
install:
        cp bin/freebayes bin/bamleftalign /usr/local/bin/
```

NEW
```
install: bin/freebayes bin/bamleftalign
        install $^ /usr/local/bin/
```
