### ISSUE TITLE
GL output for polyploids

### ISSUE THREAD

**Issue by ekg** [freebayes/freebayes#152]
This is possible in theory, but needs to be tested and vetted.

**Comment by DSLituiev** [comment]
Hi Eric, I started to look if I can help here myself, but got stuck at one point.

As I understand, the corresponding block of code starts in `ResultData.cpp` at lines `480` (the switch) and `538` (output per se, an integer-indexed map), with analogous block at line `572` for  named (?) output. 

Also, if I see it correctly, an indexing order for 'polyploid' mode needs to be added after the line `487`. This must correspond to the order in the specification
https://samtools.github.io/hts-specs/VCFv4.2.pdf

What does `k` and `j` mean?

**Comment by ekg** [comment]
Thank you hugely for your help. `k` and `j` are from the VCF specification if I remember correctly. https://github.com/samtools/hts-specs/blob/master/VCFv4.2.tex#L222 I never interpreted them.

There is a simple extension to polyploids but I am forgetting it.

GLE was meant to handle this but should be changed to use a more sensible separator. It deals with the general case of arbitrary relationships between GLs and genotypes of variable copy number.

In any case, what you implement can be added to the VCF specification. Then others who want to do this will have a guide. At the moment imputation and phasing genotyping systems only handle diploid and haploid likelihoods. At least I don't know about any examples of other tools reading these. Do you have an application in mind?

**Comment by ekg** [comment]
Also you are correct about the bit in `ResultData.cpp`.

**Comment by DSLituiev** [comment]
I did not hear about other applications yet. Definitely apart from the case of pooled segregants I am dealing with, there might be interest from the plant breeding community, where potato, tomato, and friends are polyploids.

I still struggle with understanding the output order , i.e. how `F(j/k) = (k*(k+1)/2)+j` in specification and the code translates to `AA,AB,BB,AC,BC,CC`, and how to extend it to the polyploid case. 
What is `F` exactly?

As I see from the `freebayes.cpp`, all possible allele combinations aka genotypes are generated by `multichoose.cpp`. Does this ordering, `F(j/k) = (k*(k+1)/2)+j`, relate to it somehow?

I see that `k` and `j` are taken from `gtspec` vector returned by `Genotype::relativeGenotype` in line [126](https://github.com/ekg/freebayes/blob/3e35e7255180200bb11ec7825a9aca5f05ecebee/src/Genotype.cpp#L126), and I do not see what this function exactly does.

**Comment by DSLituiev** [comment]
OK, it seems I have got it, please let me know if it is right:

`j` and `k` are allele indices (e.g.: 0 -- A [reference], 1 -- B, 2 -- C)
`j/k` is notation for allele combination: 

    (0)    0/0 -- AA                (6)    0/3 -- AD                (15)    0/5-- AF
    (1)    0/1 -- AB                (7)    1/3 -- BD                ...
    (2)    1/1 -- BB                (8)    2/3 -- CD                (21)    0/6-- AG
    (3)    0/2 -- AC                (9)    3/3 -- DD                ...
    (4)    1/2 -- BC                (10)   0/4 -- AE                (28)    0/7-- AH
    (5)    2/2 -- CC                ...                             ...

Now the problem is to device a scheme for polyploids. For generality, instead of `j,k` in case of diploids, let us use `k_1, k_2, k_3, ...k_n` for `n`-ploids :

    n = 2:
    index(k_1, k_2)          =  k_1   +    k_2*(k_2 + 1)/2
    n = 3:
    index(k_1, k_2, k_3)   =  k_1   +    k_2*(k_2 + 1)/2   +    k_3*(k_3 + 1)/6
    ...
    index(k_1, ..., k_n)   = \sum_{m=1}^{n} nchoosek( k_m - 1,  m )
                           = \sum_{m=1}^{n} ( k_m - 1 + m)! /( k_m - 1)* m!  =
                           = \sum_{m=1}^{n} S_1( k_m , m) / m!

Where S_1 is Stirling function of 1st type / 'upper factorial'

**Comment by DSLituiev** [comment]
example code in Python

    import math
    
    def stirling1(x, m):
        out = 1
        for y in range(x, m+x):
            out = out * y
            # print(y, out)
        return out
    
    def ai(*args):
        out = 0
        for m,k in enumerate(args):
            # print(m, k)
            out += stirling1(k, m+1) / math.factorial(m+1)
        return int(out)
            
    
    ai(0,0)
    ai(0,0,1,2)

**Comment by ekg** [comment]
Wow! Right on. This looks to be the sensible way to do this.

I can port this to C++. However, I am slow with maintenance and so if you
need this quickly, please provide a patch. I can help with that if you have
any questions.

We should patch the vcf spec as well. This generalizes things sensibly for
this enumeration format.

**Comment by DSLituiev** [comment]
I modified the routine accordingly in the [ResultsData.cpp around l.482]
(https://github.com/ekg/freebayes/blob/master/src/ResultData.cpp#L482), but it had no effect on the output of GL field... Now I found a redundant function at [`vcflib/src/Variant.cpp` l.1686]
(https://github.com/ekg/vcflib/blob/7b11fb6aaf3e6633743577490907c89daa0e6c0a/src/Variant.cpp#L1686)
which is not called from the freebayes source code proper, but only from `src/vcfflatten.cpp l.68`. I guess it may benefit from consolidation, but I am not sure if there any hidden reason to keep them in copies.

I also wonder what is the purpose of a function like [`glorder`](https://github.com/ekg/vcflib/blob/7b11fb6aaf3e6633743577490907c89daa0e6c0a/src/Variant.cpp#L2054), and if I need to understand the story about ['new and old' GL ordering](https://github.com/ekg/vcflib/blob/7b11fb6aaf3e6633743577490907c89daa0e6c0a/src/Variant.cpp#L2078) to make it work.

**Comment by ekg** [comment]
@DSLituiev the [VCF spec has already been updated to deal with polyploid GLs](http://samtools.github.io/hts-specs/VCFv4.3.pdf)! See page 9 of the linked PDF, under the GL section. I'm looking for the tex version.

Would you confirm that your solution is equivalent? I can help out with the output issues.

**Comment by ekg** [comment]
This is the relevant bit (in TEX): https://github.com/samtools/hts-specs/blob/VCFv4.3/VCFv4.3.tex#L288-L306

**Comment by DSLituiev** [comment]
Hmm, it does. I also did [my pull request](https://github.com/samtools/hts-specs/pull/83) to the specification earlier with the summary of what I suggested in this issue thread:


 Here is a bit expanded pseudocode:
    
    \begin{lstlisting}
        for $a_1 = 0\ldots N$
            for $a_2 = 0\ldots a_1$
                $\ldots$
                    for $a_P = 0\ldots a_{P-1}$
                        println $a_1 a_2  \ldots  a_P$ ,
    \end{lstlisting}



And here is an implementable version of your pseudocode in Python:

    def recursive_GL_order(number_of_alleles, ploidy, suffix = ''):
        ploidy = ploidy-1
        if ploidy > 0:
            for a_p in range(0, number_of_alleles+1):
                recursive_GL_order(a_p, ploidy, '%u ' % (a_p) + suffix)
        else:
            for a_p in range(0, number_of_alleles+1):
                print(a_p, suffix)

**Comment by DSLituiev** [comment]
Please note that the order of loops in the previous comment is reverse compared to your version: the first allele is the 'fastest' running, while the last is the 'slowest'.

Only this way it conforms the order presented in your example and the formula for finding order index I suggested above and in the pull request.

**Comment by trevorfaske** [comment]
Hey, just revisiting this issue because I am currently trying to call SNPs on mixed-ploidy individuals using --cnv-map. I got everything working just fine but would there is still no GL output in my vcf file. I need this field for downstream processing to incorporate uncertainty in my data. Wondering if there was ever an update or work around to get GL from the vcf. Thank you!
