### ISSUE TITLE
v0.9.21-12-g92eb53a failing with -t option

### ISSUE THREAD

**Issue by jpuritz** [freebayes/freebayes#163]
Hey Erik,

All of my FreeBayes runs are now failing after a few variants when using the -t option.  Something changed between v0.9.21-12-g92eb53a and v0.9.20-4-g42d6a54

**Comment by jpuritz** [comment]
Any version of 0.9.21 fails.

**Comment by ekg** [comment]
Is there a quick way I could reproduce this? I'm trying to add test cases,
but I already am testing --targets so I'll need another example to add.

**Comment by jpuritz** [comment]
Erik,

Thanks for the quick reply.  I've linked a test case with output and log files from runs with and without targets using the latest version and version 0.9.20.

Thanks!

https://www.dropbox.com/s/r4znronfga5zujr/testcase.tar.gz?dl=0

**Comment by jpuritz** [comment]
Hey Erik,

I took a quick look at the fix and it seems to be working correctly.  I'm getting slightly different results from the two different versions ( on a small test data set) in terms of genotypes and variant calls, but it is somewhere over 99% concordance.  The discordance is highest, it seems, at sites that are INDEL or complex at the end of a reference contig.  Not too surprising.  I'll keep looking into this next week and will keep you informed.  

Thanks,

Jon

**Comment by ekg** [comment]
Hey Jonathan,

Thanks for the quick feedback. Note that you'll need to pull in the current
git head if you need --variant-input. The discordance at the end of the
contigs is concerning. If it looks like a regression let me know.

Erik
