### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by linfengdoc** [freebayes/freebayes#169]
Hi,

I got a problem when compiling freebayes from source code (freebayes-5d5b8ac0.tar.gz). Here is the error message.

[root@node76 freebayes]# make
cd src && make
make[1]: Entering directory `/public/software/freebayes/src'
DETECTED_VERSION = v9.9.2-27-g5d5b8ac-dirty
CURRENT_VERSION  = v9.9.2-27-g5d5b8ac-dirty
cd ../bamtools && mkdir -p build && cd build && cmake .. && make
-- Configuring done
-- Generating done
-- Build files have been written to: /public/software/freebayes/bamtools/build
make[2]: Entering directory`/public/software/freebayes/bamtools/build'
make[3]: Entering directory `/public/software/freebayes/bamtools/build'
make[4]: Entering directory`/public/software/freebayes/bamtools/build'
make[4]: Leaving directory `/public/software/freebayes/bamtools/build'
make[4]: Entering directory`/public/software/freebayes/bamtools/build'
make[4]: Leaving directory `/public/software/freebayes/bamtools/build'
[  0%] Built target SharedHeaders
make[4]: Entering directory`/public/software/freebayes/bamtools/build'
make[4]: Leaving directory `/public/software/freebayes/bamtools/build'
make[4]: Entering directory`/public/software/freebayes/bamtools/build'
make[4]: Leaving directory `/public/software/freebayes/bamtools/build'
[  0%] Built target APIHeaders
make[4]: Entering directory`/public/software/freebayes/bamtools/build'
make[4]: Leaving directory `/public/software/freebayes/bamtools/build'
make[4]: Entering directory`/public/software/freebayes/bamtools/build'
make[4]: Leaving directory `/public/software/freebayes/bamtools/build'
[  0%] Built target AlgorithmsHeaders
make[4]: Entering directory`/public/software/freebayes/bamtools/build'
make[4]: Leaving directory `/public/software/freebayes/bamtools/build'
make[4]: Entering directory`/public/software/freebayes/bamtools/build'
[  1%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamAlignment.cpp.o
[  2%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamMultiReader.cpp.o
[  3%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamReader.cpp.o
[  4%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamWriter.cpp.o
[  5%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamHeader.cpp.o
[  6%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamProgram.cpp.o
[  7%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamProgramChain.cpp.o
[  8%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamReadGroup.cpp.o
[  9%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamReadGroupDictionary.cpp.o
[ 10%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamSequence.cpp.o
[ 11%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamSequenceDictionary.cpp.o
[ 12%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamHeader_p.cpp.o
[ 13%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamMultiReader_p.cpp.o
[ 14%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamRandomAccessController_p.cpp.o
[ 15%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamReader_p.cpp.o
[ 16%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamWriter_p.cpp.o
[ 17%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamIndexFactory_p.cpp.o
[ 18%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamStandardIndex_p.cpp.o
/public/software/freebayes/bamtools/src/api/internal/index/BamStandardIndex_p.cpp: In member function 'void BamTools::Internal::BamStandardIndex::WriteLinearOffsets(const int&, BamTools::Internal::BaiLinearOffsetVector&)':
/public/software/freebayes/bamtools/src/api/internal/index/BamStandardIndex_p.cpp:958: warning: comparison between signed and unsigned integer expressions
[ 19%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamToolsIndex_p.cpp.o
[ 20%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamDeviceFactory_p.cpp.o
[ 21%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamFile_p.cpp.o
[ 22%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamFtp_p.cpp.o
[ 23%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamHttp_p.cpp.o
/public/software/freebayes/bamtools/src/api/internal/io/BamHttp_p.cpp: In member function 'bool BamTools::Internal::BamHttp::SendGetRequest(size_t)':
/public/software/freebayes/bamtools/src/api/internal/io/BamHttp_p.cpp:409: warning: comparison between signed and unsigned integer expressions
/public/software/freebayes/bamtools/src/api/internal/io/BamHttp_p.cpp: In member function 'bool BamTools::Internal::BamHttp::SendHeadRequest()':
/public/software/freebayes/bamtools/src/api/internal/io/BamHttp_p.cpp:501: warning: comparison between signed and unsigned integer expressions
[ 24%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamPipe_p.cpp.o
[ 25%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BgzfStream_p.cpp.o
[ 26%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/ByteArray_p.cpp.o
[ 27%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/HostAddress_p.cpp.o
[ 28%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/HostInfo_p.cpp.o
[ 29%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/HttpHeader_p.cpp.o
[ 30%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/ILocalIODevice_p.cpp.o
[ 31%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/RollingBuffer_p.cpp.o
[ 32%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/TcpSocket_p.cpp.o
/public/software/freebayes/bamtools/src/api/internal/io/TcpSocket_p.cpp: In member function 'std::string BamTools::Internal::TcpSocket::ReadLine(int64_t)':
/public/software/freebayes/bamtools/src/api/internal/io/TcpSocket_p.cpp:336: warning: comparison between signed and unsigned integer expressions
[ 34%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/TcpSocketEngine_p.cpp.o
[ 35%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/TcpSocketEngine_unix_p.cpp.o
[ 36%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/sam/SamFormatParser_p.cpp.o
[ 37%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/sam/SamFormatPrinter_p.cpp.o
[ 38%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/sam/SamHeaderValidator_p.cpp.o
[ 39%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/utils/BamException_p.cpp.o
Linking CXX shared library ../../../lib/libbamtools.so
/usr/bin/ld: cannot find -lz
collect2: ld returned 1 exit status
make[4]: **\* [../lib/libbamtools.so.2.3.0] Error 1
make[4]: Leaving directory `/public/software/freebayes/bamtools/build'
make[3]: *** [src/api/CMakeFiles/BamTools.dir/all] Error 2
make[3]: Leaving directory`/public/software/freebayes/bamtools/build'
make[2]: **\* [all] Error 2
make[2]: Leaving directory `/public/software/freebayes/bamtools/build'
make[1]: *** [../bamtools/lib/libbamtools.a] Error 2
make[1]: Leaving directory`/public/software/freebayes/src'
make: **\* [all] Error 2

Could you please help me solve this problem? Thank you very much.

Feng

**Comment by tseemann** [comment]
```/usr/bin/ld: cannot find -lz```

Do you have the -dev packages installed for libz ?   eg.  libz-dev or libz-devel ?
