### ISSUE TITLE
Freebayes skips some contigs?

### ISSUE THREAD

**Issue by nicolasnzt** [freebayes/freebayes#170]
Hi,
I've similarly issue that the post #168.

I tried to use freebayes to call variants on a custom genome (with more than 80000 contigs) but I think freebayes skips the analysis of some contigs.
In my reference file, I’ve 81730 contigs (63232 contigs with reads), but in the freebayes log file (-d option) I can see information about only 5091 contigs.

Consequently I tried to run freebayes against one only contig (which don’t output previously results) specify “-r MyContig” option. In this case freebayes outputs variants!

Please, can you help me to solve this issue?

Best regards
Nicolas

**Comment by ekg** [comment]
Hi Nicolas,

Would you be able to make a small test that reproduces the issue?

This is concerning. I think there is a problem with the fasta index traversal.

**Comment by nicolasnzt** [comment]
Hi Erik,
I'm trying to create a small dataset, but when I extract reads corresponding to a subset of contigs  freebayes runs successfully. 
Do you think freebayes bugs with a lot of contigs (80000)?

Cheers!
Nicolas

**Comment by ekg** [comment]
It could. I never tested it but on the other hand I don't see why it should
be a problem. It hasn't been reported by others who are testing in that
context.

Is there a particular count where things begin to fail?

There are some limits on the number of contigs supported by BAM.

**Comment by jpuritz** [comment]
This might also be related to [Issue 163](https://github.com/ekg/freebayes/issues/163).  It's using the -t target option but also having to traverse a lot of reference contigs.

**Comment by ekg** [comment]
I believe you sent me a test case, so I'll work from that.

**Comment by nicolasnzt** [comment]
I checked quickly jpuritz log files: it’s an analogous problem.

**Comment by ekg** [comment]
All right. I wonder if this is related to what @bchapman is seeing too.

**Comment by cboustred** [comment]
I think its @chapmanb no bchapman

**Comment by nicolasnzt** [comment]
Hi Erik,
Thanks for this fix. But I always have the same issue. 
Nicolas

**Comment by ekg** [comment]
I have another test from @chapmanb, so hopefully that one is the same as
your issue.
