### ISSUE TITLE
Null genotypes coded a '.' regardless of ploidy

### ISSUE THREAD

**Issue by travc** [freebayes/freebayes#172]
As the title says.  The coding of null/missing genotypes as simply '.' is causing me headaches downstream.  I'm even setting --ploidy explicitly.
It is entirely possible I'm just missing something obvious, but this behaviour seems wrong and is certainly not what most downstream tools expect.

ETA: `vt normalize` fixes the problem... so not a critical problem.  Still, outputting nominally formatted missing genotypes would be a  reasonable enhancement.

**Comment by ekg** [comment]
I believe this is in the standard. But, I don't have any preference.
Patches accepted. It would be a straightforward change in ResultData.cpp.

**Comment by travc** [comment]
I'm not 100% sure what the standard is supposed to be.  Half of my reason for posting is to check if I'm being crazy or if it is really a problem.  If the latter, then I'll to write a fix tool and maybe adjust the output of freebayes (thanks for pointing out where in the code that would go).

I do keep running into downstream tools which choke on it... this time it is pFst, which I'd expect to have a better chance than most of handling freebayes output since it is based on vcflib.

Maybe I'll take this opportunity to learn a bit about your vcflib code and write a simple fix tool (```vcfglxgt``` seems like a likely good starting point)

**Comment by ekg** [comment]
If you are writing c++ code using the vcflib api, you can just aw easily
patch freebayes as write a new utility to make the conversion. That said,
whatever you do please share it :).

Does anyone else have this problem? Should we switch to outputting
`./.:.:.:.:.` instead of `.`?

**Comment by travc** [comment]
I just noticed that vcflib has ```vcfnulldotslashdot```.  That should do the trick for my current problem.  Though, I didn't see any documentation of that command... do you not consider it mature enough to add to the readme, or is it just not in there because there is no --help output for that command?

I will note that ```vcfnulldotslashdot``` is a bit improper and therefore does not play nice with ```vt normalize``` (and probably lots of other tools).  The obvious fix is to make ```vcfnulldotslashdot``` properly fill in all the FORMAT fields (as opposed to just replacing '.' with a GT:GL pair '0/0:0,0,0'.  I'll see about fixing that (and adding --help output) when I get a free moment.

Since I'm not really sure what 'proper' formatting is, and I actually think the single '.' for null genotypes makes the most sense, I don't think freebayes really needs to be changed.  Best if the downstream tools handled it properly, and good enough if there is a simple workaround like ```vcfnulldotslashdot```.

PS: Thanks for the feedback (and help on previous occasions).  Your maintenance/curation is a big reason I prefer using freebayes (and vcflib).

**Comment by travc** [comment]
Ok... that last comment of mine is wrong...
From the vcf4.2 spec (page 6): http://samtools.github.io/hts-specs/VCFv4.2.pdf

"If genotype information is present, then the same types of data must be present for all samples."

"Trailing fields can be dropped (with the exception of the GT field, which should always be present if specified in the FORMAT field)."

"If a call cannot be made for a sample at a given locus, `.'  should be specified for each missing allele in the GT field (for example `./.' for a diploid genotype and `.'  for haploid genotype)."

Taken together, missing genotypes as just '.' will/should be interpreted as GT='.' with the rest of the FORMAT fields being omitted... ie. haploid no-call.  So freebayes probably should be outputting at least the full GT (ie './.' for diploid).  However, I'd advocate for going a bit further and not omit the trailing fields (ie. if FORMAT=GT:DP:GL and diploid, output './.:.:.'.).  Of course, you could do even better and output real values for DP, GL, and whatever else might actually have real values even when the GT is uncalled.

**Comment by travc** [comment]
I'm putting in a pull request for vcflib which adds a tool to normalize/fix the genotype fields.  That should provide a workaround for this issue.

https://github.com/ekg/vcflib/pull/92

**Comment by tyrwh** [comment]
Adding on my two cents to this issue- I'm comparing Freebayes to the TASSEL pipeline for GBS reads, and TASSEL does also choke on the '.' fields until I manually change them to './.' with sed. So I would vote for './.' to follow the VCF specs.

**Comment by timothymillar** [comment]
Any chance of a resolution on this? I have run into the same issue with downstream analysis.

**Comment by StefanReuscher** [comment]
Me too. It's an akward thing that causes issues with downstream analyses, e.g. Beagle.
