### ISSUE TITLE
Discrepancy between alignment coverage and reported DP

### ISSUE THREAD

**Issue by afkoeppel** [freebayes/freebayes#174]
Hi there. I have a question about how the per-sample DP values in the VCF file are calculated by freebayes. In particular I'm noticing that the number of ref and alt reads reported for a given variant for a given sample is significantly lower than expected. I ran bedtools genomecov with the -d flag to get a table of read depths at all positions in the reference, using the same bam files that I had given to Freebayes as input to generate the VCF. For a particular sample that I was interested in, the coverage at the variant position was over 2000 reads, yet that same variant's info field for that sample read (GT:GQ:DP:RO:QR:AO:QA:GL) 0:1.76091:16:16:533:0,0:0,0:0,-10,-10 indicating 16 reads total, all 16 of them ref. Can anyone provide any insight into what the source of the discrepancy might be?

My inputs are amplicon data from 11 genes, aligned to a custom reference, with the sequences of the 11 genes treated as chromosomes (separate entries in the reference fasta file). I've noticed that the biggest discrepancies between the bedtools coverage and the DP for variants seem to be in variants nearer to the start position of each gene.

**Comment by jpuritz** [comment]
I've seen a similar problem previously.  I found that fb would ignore reads aligning at exactly the first 5' base of the reference.  Try adding a N to the beginning of your reference sequences, and see if it makes a difference.

**Comment by afkoeppel** [comment]
Thanks for the tip.  I'll give that a try.  Just out of curiosity, would you recommend doing just the variant calling on the adjusted reference, or would it make sense to go back and align to the reference with the N's first.  Would the only consequence of variant calling using the adjusted reference, with bam files from the original reference be that the positions in the VCF are off by one?

**Comment by jpuritz** [comment]
You will want to realign.

Sent from my iPhone

On Jun 1, 2015, at 13:48, afkoeppel <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the tip. I'll give that a try. Just out of curiosity, would you recommend doing just the variant calling on the adjusted reference, or would it make sense to go back and align to the reference with the N's first. Would the only consequence of variant calling using the adjusted reference, with bam files from the original reference be that the positions in the VCF are off by one?

-

**Comment by afkoeppel** [comment]
Realigned, and recalled the variants after putting an N at the front of each reference sequence.  That seems to have done the trick.  My DP counts are now in line with what bedtools is calculating.  Thanks so much.
