### ISSUE TITLE
freebayes VCF file contain many DNA sequences ,it show type =complex

### ISSUE THREAD

**Issue by liuguoqiang** [freebayes/freebayes#176]
when I calling the snp with the freebayes in a pooled sample (I didn't know the number of samples in the pool),so I use the command :freebayes -f ref.fa -F 0.01 -C 1 --pooled-continuous aln.bam >var.vcf.
the freebayes run normally,but the output VCF file contain many DNA sequence,it show type =complex,you can see the problem in the attachment images,thanks for your suggestions ,they will be very helpful to me.
![Uploading freebayes.JPG…]()
![Uploading freebayes.JPG…]()

**Comment by ekg** [comment]
This is expected. Anything passing the input filters in this configuration
will be reported. You can probably improve things by just setting -C 2.
