### ISSUE TITLE
freebayes crash with option -t

### ISSUE THREAD

**Issue by marc-sturm** [freebayes/freebayes#178]
Hi Eric,

i just wanted to update to the latest freebayes version, but the head crashes without error message in chr1. The output of an example I created is below. You can download the complete (except for the reference genome) example from: 
https://drive.google.com/file/d/0B-iHdfk93LueU1ZXVjNxc1pLMVE/view?usp=sharing

Could you please have a look at what's wrong.

Thanks,
  Marc

P.S.: One other thing I was wondering about: why does the AF field always contain '0.5' or '1'? Would it be possible to give the real allele frequency?
# 

> make old
> /mnt/share/opt/freebayes20150204/bin/freebayes --version
> version:  v0.9.20-16-g3e35e72
> /mnt/share/opt/freebayes20150204/bin/freebayes -b ./NA12878_03.bam -f /mnt/share/data/dbs//genomes/hg19.fa -t roi.bed > old.vcf
> WARNING(freebayes): Could not find any mapped reads in target region chr1:120534074..120534115
> WARNING(freebayes): Could not find any mapped reads in target region chr1:120534221..120534266
> WARNING(freebayes): Could not find any mapped reads in target region chr1:120547940..120548221
> WARNING(freebayes): Could not find any mapped reads in target region chr1:120572517..120572620
> WARNING(freebayes): Could not find any mapped reads in target region chr11:117078436..117078461
> WARNING(freebayes): Could not find any mapped reads in target region chr11:117078674..117078790
> egrep "^chr" old.vcf | wc -l
> 179
> 
> make new
> /mnt/share/opt/freebayes20150623/bin/freebayes --version
> version:  v0.9.21-19-gc003c1e
> /mnt/share/opt/freebayes20150623/bin/freebayes -b ./NA12878_03.bam -f /mnt/share/data/dbs//genomes/hg19.fa -t roi.bed > new.vcf
> egrep "^chr" new.vcf | wc -l
> 18

**Comment by pjotrp** [comment]
Hi @marc-sturm. Can you send me an example that reproduces this issue using the test data in the repo or a small example from your data that I can add to the tests? We need to be TDD. See https://en.wikipedia.org/wiki/Test-driven_development. Be great if you can help us progress freebayes.

**Comment by marc-sturm** [comment]
Hi Pjotr,

I could replicate the bug it with the version mentioned above.
However freebayes 1.2.0 and 1.3.2 work fine.
Looks like it was already fixed somewhen.

Best,
  Marc

**Comment by pjotrp** [comment]
Thanks for looking into it @marc-sturm! I love it when an issue disappears :). Closing.
