### ISSUE TITLE
vcffilter not existing in /vcflib

### ISSUE THREAD

**Issue by michieitel** [freebayes/freebayes#179]
I compiled freebayes on Mac OS X 10.10. Worked fine, but when I try to run
freebayes -f ref.fa aln.bam | vcffilter -f "QUAL > 20" >results.vcf

I get the error telling that vcffilter command is not found. In the /vcflib folder it is was not built. 

Should/Can I use

freebayes -f ref.fa aln.bam | vcfqualfilter -c 20 >results.vcf

Thanks
Michael

**Comment by ekg** [comment]
Go into vcflib and `make`. Then look in vcflib/bin/.

**Comment by michieitel** [comment]
Thanks Erik! That did the trick ;-)

One more question. Is there a way to parallelise the job? Running it on 1 core takes quite a while…

**Comment by jsage8** [comment]
You can parallelize freebayes using gnu parallel.

**Comment by michieitel** [comment]
Thanks Jonathan!

**Comment by tseemann** [comment]
@michieitel there is a script in the download called `freebayes-parallel` and some helper scripts to create the inputs.
