### ISSUE TITLE
freebayes getting stuck

### ISSUE THREAD

**Issue by jaholliday** [freebayes/freebayes#181]
Hello,

I'm trying to call SNPs in a sample of 96 diploid individuals. The reference genome is ~40,000 scaffolds, and freebayes is hanging up for hours in some cases on particular sites. Last night it made it to scaffold 8000 before hanging up. Today it's hung on about scaffold 1000. Any ideas on why this could be? Can you suggest some parameters under 'algorithmic features' that might help get past these troublesome sites?

Thanks
Jason

**Comment by jaholliday** [comment]
Just an update - it seems the program exits on the same (or approximately the same) scaffold - around 8000 - when I run all 96 samples together. If I run them separately each gets to the end (scaffold 40000) and if I run 10 at once it works as well. Could this be a memory issue? The program doesn't seem to ever be close to maxing out my server but perhaps when I'm not looking.

**Comment by ekg** [comment]
It could be a memory issue. Is there high coverage on this scaffold?

**Comment by jaholliday** [comment]
This could be the problem. I'm not seeing an option to omit bases over a certain read depth.

**Comment by ekg** [comment]
The problem is that you pay to determine how deep the coverage is, so this
turns out to be a rather difficult thing to implement in the current
design. There would need to be two passes over the data to do this
efficiently.

I suspect you will get through the region in question if you specify
--use-best-n-alleles 6 or such. The problem is usually the apparent allelic
complexity in these collapsed complex regions, not the depth.

**Comment by jaholliday** [comment]
Thanks I'm trying that now on a machine with more RAM.

**Comment by jaholliday** [comment]
Unfortunately, the program is still exiting without throwing any error on this particular contig with very high read depth. Any other suggestions for parameters I could tweak to get past it?

**Comment by jaholliday** [comment]
For everyone's information, in case you run into this, I just put this on one of our cluster's new high memory nodes (requested 1Tb of memory) and it worked out great. So I guess it was a memory issue.
