### ISSUE TITLE
False negative indel calls at homopolymers

### ISSUE THREAD

**Issue by MinocheAE** [freebayes/freebayes#183]
When comparing FreeBayes (v0.9.21-19-gc003c1e)  NA12878 indels with the NIST gold standard, I found a pattern among the false negatives (FNs).

The first 6 FN indels I looked at mainly were at homopolymers and one was spanning a freebayes-parallel interval breakpoint.

Here the coordinates (reference hs37d5)
1:62924185-62924225   # homo polymer
1:20171526-20171565 # tandem repeat
1:34981009-34981048 # homo polymer
1:62593070-62593109 # homo polymer
1:68021326-68021363 # ?
1:85399989-85400028 # spanning breakpoint of freebayes-parallel. Called correctly when using using freebayes directly

Inspecting these regions in IGV I can only confirm that the containing indels look real and it shouldn't be difficult to call them. FreeBayes may overestimate potential homopolymer error in recent Illumina reads.

In total there were 28,855 false negatives indels of 709,424 indel calls.

I really like freebayes, mainly because it doesn't need any extra base recalibration and indel realignment.
I hope this indel issue is not too complicated to fix.

**Comment by ekg** [comment]
Would you please point me to the data you used to run your test?

**Comment by MinocheAE** [comment]
I made another interesting observation: about 50% of all FN indels were actually called by FreeBayes but the genotype differs to the NIST gold standard. 

In many of these cases homozygous NIST calls were called heterozygous in FreeBayes. Here are two example regions: 1:5,299,641-5,299,681 1:8,996,802-8,996,842

Visualizing these regions in IGV I tend to say the calls are rather homozygous.

Maybe the internal FreeBayes indel realigner or indel caller can be fine tuned to improve on these, too.

**Comment by ekg** [comment]
Try adding --min-repeat-entropy 1. This will extend the called haplotype
across lower complexity sequences even if they are not perfect repeats.

I would like to enable this option by default, but it needs to be done in a
more sensible way so calls are not strongly directionally biased.

That said I don't know if this will resolve the problem. I am not working
for the next few days so I cannot test it myself.

To be clear what freebayes commit ID are you using?

**Comment by MinocheAE** [comment]
The commit ID of the version I generally use:
git log --format="%H" -n 1 # I hope that is what you were asking for
c15a283630ed938ce0cc09548a94c764faa09ac5 
The ID of the version I confirm single FNs reported on this site:
c003c1e602ab1fc9a4d3389adb0582c40d65123f

The "--min-repeat-entropy 1" option slightly increases the overall false negative numbers and does not solve for instance 1:5,299,641-5,299,681

To summarize I could distinguish 3 types of false negative FreeBayes indels:
1) Wrong GT call, often heterozygous instead of homozygous (e.g. 1:5,299,641-5,299,681)
2) missed indels at homoplymers/ tandem repeats (e.g. 1:62593070-62593109)
3) missed indel at freebayes-parallel reference sequence breakpoint (e.g. 1:85399989-85400028)

Regarding 1)
For the CT deletion in region 1:5,299,641-5,299,681 FreeBayes reports SRR=1 and SRF=3. I can not find any reads that definitely represent the reference allele "ACTCTCA". There are a couple of alignments that reach into or start from within the deletion. They align without deletion, but since they do not span the deletion, one does not know if they actually have the correct numbers of CT repeats. 
Additionally there are 3 soft clipped reads that also rather indicate the deletion. So this CT deletion should be homozygous.

Regarding 2)
If for an indel the surrounding base quality is generally >30 and if the indel occurs on both strands, then I think it should get reported by the variant caller.

Regarding 3)
What about breaking the reference at N stretches longer than e.g. 2 times the read length?
