### ISSUE TITLE
Incorrect output when processing cigar strings with "=" and "X" symbols.

### ISSUE THREAD

**Issue by bbushnell** [freebayes/freebayes#189]
I've been notified that when FreeBayes is fed sam files containing "X" and "=" cigar symbols (for mismatch and match), as opposed to just "M", it will not call any indels.  The same input with X and = transformed into M will generate indel calls.

To replicate this, you can use BBMap; the default sam output uses X and = symbols, while the flag "sam=1.3" will generate legacy-compatible sam output using only the M symbol for both matches and mismatches.

**Comment by ekg** [comment]
Ah, great. This is correct, thanks for the heads up.
