### ISSUE TITLE
Allow MNPs to be reported as SNPs

### ISSUE THREAD

**Issue by jamescasbon** [freebayes/freebayes#19]
I have a good quality GG/TC MNP: 

```
$ freebayes -f /data/reference/ucsc/hg19/hg19.fa -r chr22:42526560..42526563 -F 0.3  reads.bam 2> /dev/null| cut -f1-6 | grep -v "##"
chr22   42526561    .   GG  TC  49314.7
```

But I don't want MNPs, I want two SNPs.  So I'll use the --no-mnps flag, right?  Doesn't work:

```
$ freebayes -f /data/reference/ucsc/hg19/hg19.fa -r chr22:42526560..42526563 -F 0.3 --no-mnps reads.bam 2> /dev/null| cut -f1-6 | grep -v "##"
chr22   42526561    .   GGTGGTGGGGCATCCTCAGG    TCTGTAGGGGCATCCTCAGG,TCTCGGTAGGGGAGCCTCAGG,TCTGTAGGGAGCCTCAGG,TCTGGCAGGGGAGCCTCAGG,TCCGGTAGGGGAGCCTCAGG,TCTGTACGGGGAGCCTCAGG,TCAGGTAGGGGAGCCTCAGG,TCTGGGTAGGGGAGCCTCAGG,TCTAGTAGGGGAGCCTCAGG,TCTGGTTAGGGGAGCCTCAGG,TCCGGTAGGGGAGCCTTAGC,TCTGGGAGGGGAGCCTCAGG,TCTGTTAGGGGAGCCTCAGG,TCTGTAGGGAGCTCAGG,TCTTGTAGGGGAGCCTCAGG,TCTCGGTAGGGGAGCCGTCAGG,TCTCGGTACGGGGAGCCTCAGG,TTCGGTACGGGGAGCCGCTCAGG  14761.8
```

OK, so how about adding in --no-complex?  That doesn't even give the best SNPs: 

```
$ freebayes -f /data/reference/ucsc/hg19/hg19.fa -r chr22:42526560..42526563 -F 0.3 --no-mnps --no-complex reads.bam 2> /dev/null| cut -f1-6 | grep -v "##"
chr22   42526561    .   G   C   62.4447
chr22   42526562    .   G   C   0.0781914
```

Weird, so what about trying to force it to produce the best alleles? 

```
$ freebayes -f /data/reference/ucsc/hg19/hg19.fa -r chr22:42526560..42526563 -F 0.3 --use-best-n-alleles 1 --no-mnps --no-complex reads.bam 2> /dev/null| cut -f1-6 | grep -v "##"
chr22   42526561    .   G   C   62.4447
chr22   42526562    .   G   C   0.0781914
```

So how I can get freebayes to report the GG/TC as two individual SNPs?

**Comment by mmokrejs** [comment]
Hi,
  I found this thread when having the below predicted by freebayes v1.0.2-33-gdbb6160. 

ref: **G**GCTCACATCACCGTAGTGGTTTTGT**T**
alt1 **A**GCTCACATCACCGTAGTGGTTTTGT**C**
alt2 **T**GCTCACATCACCGTAGTGGTTTTGT**T**


The first and last nucleotide are SNPs, the rest of the sequence in between is just unchanged and I wonder why freebayes differs in this behavior from UnifiedGenotype/HaplotypeCaller/'bcftools -m'.

`chr1    63671   .       GGCTCACATCACCGTAGTGGTTTTGTT     AGCTCACATCACCGTAGTGGTTTTGTC,TGCTCACATCACCGTAGTGGTTTTGTT 27.18   .       AB=0.125,0.0833333;ABP=32.3252,39.2015;AC=1,0;AF=0.5,0;AN=2;AO=3,2;CIGAR=1X25M1X,1X26M;DP=24;DPB=31.2593;DPRA=0,0;EPP=3.73412,3.0103;EPPR=7.35324;GTI=0;LEN=27,1;MEANALT=3,3;MQM=48,49;MQMR=45.7778;NS=1;NUMALT=2;ODDS=6.25546;PAIRED=1,1;PAIREDR=1;PAO=5,0;PQA=140,0;PQR=286;PRO=10;QA=92,55;QR=549;RO=18;RPL=3,2;RPP=9.52472,7.35324;RPPR=4.9405;RPR=0,0;RUN=1,1;SAF=1,1;SAP=3.73412,3.0103;SAR=2,1;SNPEFF_EFFECT=INTERGENIC;SNPEFF_FUNCTIONAL_CLASS=NONE;SNPEFF_IMPACT=MODIFIER;SRF=5;SRP=10.7311;SRR=13;TYPE=complex,snp;technology.ILLUMINA=1,1  GT:AO:DP:DPR:PL:QA:QR:RO   0/1:3,2:24:24,3,2:97,0,636,138,617,791:92,55:549:18
`
