### ISSUE TITLE
Identical alternates with different cigar strings

### ISSUE THREAD

**Issue by EReckase** [freebayes/freebayes#192]
I recently got the following call line in an output vcf (truncated for simplicity):

```
chr5    112175675   .   AAGAGA  AA,AA   2.85084e-14 PASS    AB=0,0;ABP=0,0;AC=0,1;AF=0,0.5;AN=2;AO=0,0;CIGAR=1M2D1M,1M4D1M;DP=176
```

Both alternates are listed as AA, which causes problems with some external tools (vcftools in particular).  Shouldn't the cigar be consistent with the length of the reference (AAGAGA)?  Or should the alternates be different?

**Comment by ekg** [comment]
This is a bad bug. Could you share the input data that's causing this?
(Just a minimal bit of it that's enough to make these alleles show up.)

**Comment by EReckase** [comment]
Here's the sample data that reproduces the issue:
https://www.dropbox.com/s/c9ykhsjbig600k6/dupe_alternate_data.tar.gz?dl=0

There's a SAM in there and a targeted mutation vcf.  We do have two deletions listed in the targeted file at the same location, so that might be part of the problem.

```
freebayes -f <indexed hg19> --ploidy 2 --min-base-quality 20 --no-snps --variant-input adenomah.vcf.gz --only-use-input-alleles --min-mapping-quality 20 ecs.bam
```

**Comment by EReckase** [comment]
Any update on this issue?
