### ISSUE TITLE
Compilation issue on Mac OS 10.10.5

### ISSUE THREAD

**Issue by bede** [freebayes/freebayes#194]
Compilation fails for me. I've tried setting CC and CXX to point to GCC5 to no avail.

Any thoughts?

```
c++    -c -o IndelAllele.o IndelAllele.cpp
g++ -c -o disorder.o disorder.c
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
  * linking smithwaterman
ld: warning: option -s is obsolete and being ignored
ld: internal error: atom not found in symbolIndex(__ZNKSt3__16vectorINS_4pairIicEENS_9allocatorIS2_EEE8max_sizeEv) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [smithwaterman] Error 1
make[1]: *** [../vcflib/smithwaterman/SmithWatermanGotoh.o] Error 2
make: *** [all] Error 2

```

**Comment by bobthacker** [comment]
I am receiving the same compilation error in Mac OS 10.11.3.

Any suggestions would be appreciated.

**Comment by ekg** [comment]
I would love to help.

The amount of support problems related to OSX has increased a huge amount over the past year, and I think it's time that I set up a series of VM images that I can use to test builds. Does anyone know of a way to do this? Is it even legal for me to run copies of OSX if I don't have a license?

`g++` and `gcc` on current versions of OSX are actually binaries that call clang. Is it possible this is what is happening?

**Comment by chapmanb** [comment]
We have a pre-built version of FreeBayes in Bioconda for OSX. It's built on OSX machines at Travis and avoids needing to compile locally. Documentation of installing bioconda packages is here:

https://bioconda.github.io/

You need to install conda then do:
```
conda install -c bioconda freebayes
```
Erik, the FreeBayes recipe is here but we really have only one small tweak for OSX compilation:

https://github.com/bioconda/bioconda-recipes/tree/master/recipes/freebayes

Hope this helps.

**Comment by bobthacker** [comment]
It looks like I found issue #83 again:
https://github.com/ekg/freebayes/issues/83

Commenting out the -s flag from the MakeFile in /vcflib/smithwaterman allowed it to compile.
LDFLAGS=-Wl #,-s

**Comment by bede** [comment]
I don't know about virtualisation, but I'd be happy to give you user account on my workstation for testing purposes.

Anyone who builds free software routinely on OS X knows to try GCC when a clang build fails. This is a moderately complicated build and forcing GCC isn't quite as straightforward as usual.

**Comment by bede** [comment]
Ok, a workaround for the problem building SmithWaterman, which ignores CC and CXX:

Where `/usr/local/bin/gcc-5` is the path to my GCC installation (installed with `brew install gcc`):
```
sudo mv /usr/bin/gcc /usr/bin/gcc.bak
sudo mv /usr/bin/g++ /usr/bin/g++.bak
sudo ln -s /usr/local/bin/gcc-5 /usr/bin/gcc
sudo ln -s /usr/local/bin/g++-5 /usr/bin/g++
```

Then `make`. This still fails, but at a later stage.
https://gist.github.com/bede/7f7b5b71d12b73787f25

Then put things back to how they were:
```
sudo rm /usr/bin/gcc /usr/bin/g++
sudo mv /usr/bin/gcc.bak /usr/bin/gcc 
sudo mv /usr/bin/g++.bak /usr/bin/g++
```

**Comment by thierrygosselin** [comment]
Travis can test on macOS
