### ISSUE TITLE
infinite loop 

### ISSUE THREAD

**Issue by kspham** [freebayes/freebayes#195]
freebayes -f /media/proj2/reference/GRCh37.fa         --pooled-discrete         --genotype-qualities         --min-repeat-entropy 1         --min-alternate-fraction 0.05         --min-alternate-count 2         --region 1:0..249250621         2s.bam 2ns.bam > test.vcf

This command line never finishes (at least 40 hours already). 
I "tail test.vcf" and see that the last output is at position 121Mbp: 
1       121485227       .       A       T 
and freebayes stays there !

Thanks,

**Comment by ekg** [comment]
Try adding `--use-best-n-alleles 3` and running just before the last
printed position onto the end of the chromosome.

**Comment by kspham** [comment]
freebayes -f  /media/proj2/reference/GRCh37.fa      --pooled-discrete         --genotype-qualities         --min-repeat-entropy 1         --min-alternate-fraction 0.05         --min-alternate-count 2         --region 1:121485333..249250621   --use-best-n-alleles 3      2s.bam 2ns.bam  > 1test.vcf
Still got stuck at that point, not going any further :(

**Comment by ekg** [comment]
What is the depth in this region?

**Comment by kspham** [comment]
Seems that it's not the depth problem, I just tried an old version (v0.9.21) -- it works like a charm .I will dig in the code to see where the infinite loop is.

**Comment by rgiannico** [comment]
I had the same problem in the same position with only one of my samples and I really don't know why. 
It happens with or without the "--use-best-n-alleles 3" parameter

`$ freebayes -f genome.fa -b sample002_chr1_121485200-121485500.bam --vcf sample002_chr1_121485200-121485300.fb.vcf`

Here is the small BAM producing the infinite loop (last base called: chr1:121485214) 
[sample002_chr1_121485200-121485300.bam.gz](https://github.com/ekg/freebayes/files/2013703/sample002_chr1_121485200-121485300.bam.gz)

Here it's the IGV visualization of the BAM whith the last called position and the following position where I think the loop occurs
![sample_002_chr1_freebayes_loop](https://user-images.githubusercontent.com/2571713/40185519-151e88c6-59f3-11e8-9fed-c24570612d78.jpg)

Any ideas?
