### ISSUE TITLE
freebayes quits after only one contig

### ISSUE THREAD

**Issue by wrf** [freebayes/freebayes#197]
Hello,
This might be similar to issue [170](https://github.com/ekg/freebayes/issues/170).
Freebayes normally works fine (or at least as I expected), however on a different data set it quits after calling variants for only one contig, which is the first one.

This dataset was generated differently than the others, since it was Sanger fasta+qual from 2005, merged into fastq and then mapped on to the reference genome (built from the same reads) to detect haplotypes. Mapping was done just as I did the others, with bowtie2 and the same settings, only for single end rather than paired.

Is this a filtering problem? or is something else instructing the program to quit after the first contig?

This is the last read in the bam file before it stops:
gnl|ti|1479533009   0   Contig533   115 0   36M3I228M1D15M1I272M1D122M14I2M4I7M1D88M10I35M2D59M4I7M
27I8M   \*   0   0   NCCTAGTAG...    !%'%')''((*%%...    AS:i:-535   XN:i:0  XM:i:71 XO:i:11 XG:i:68 NM:i:139    MD:Z:0T1A0G0G0C1G0T2T0A0A0A1G0A1A0A1G2G
1T0C0G0A1G0C72T0G8T2G58C2T9A8A1C61^A4C21C50T39G25G8C0A79G29T23^A30A3T16A5C4C6C9C3G2G1A24G1A2T12^G5A7T38T23T17T20T7^AT40
A9A1A2T4C1T4G0C0T1T1G0  YT:Z:UU

mapping onto a contig which starts like:

> Contig533 dna:scaffold scaffold:Aqu1:Contig533:1:1000:1
> CTTGGAATACTGGCAGAGTTAACTGGTAAATGAAACTTTAAGAATAAAGAAAGAGAAGAA...

The full dataset was ~3M reads, where 1.8M mapped onto 13k contigs.
Thanks!

**Comment by ekg** [comment]
Work around this by running one job per contig such as using gnu parallel
(so as to not make tens of thousands of jobs for a cluster).

If running --region for a particular contig does not produce results still,
it may be another issue.

I will be addressing these related issues in the coming week.

**Comment by wrf** [comment]
It works for that contig if I specify one, not sure why it isn't iterating through them like the other libraries.

Is there something funny with the naming of the files or reads that could make it stop after just one contig? In the --debug it says:
Opening BAM fomat alignment input file: fasta/reniera_sp__jgi-2005.fastq.sorted.filtered.bam ...
 done
Number of ref seqs: 13397
Number of target regions: 0

but if I specify the region it says:
Number of ref seqs: 13397
will process reference sequence Contig13245:0..132822
Number of target regions: 1

Does the --target option just require a 3-column BED file for any/all contigs?

**Comment by ekg** [comment]
The --targets option requires the three column bed file. Unfortunately
while many users need this I have almost never used the feature, opting
instead to run across the entire contig set and then filter post-call, or
run one job/process per region of interest. These options should work. Have
you tried not supplying targets?

As I said I will be working on this issue in the next few days so if you
can reproduce the problem with little data please email me a test.

**Comment by wrf** [comment]
I only tried the targets to see if that forced it to iterate through all of the contigs, but this stops as the first one in the same way as if I don't use -t.

**Comment by ekg** [comment]
Does the fasta index contain all the references? Is it valid?

**Comment by wrf** [comment]
looks fine as far as I can tell, at least no different from the ones that worked.

$ wc Amphimedon_queenslandica.Aqu1.23.dna.genome.fa.fai
 13397  66985 411972 Amphimedon_queenslandica.Aqu1.23.dna.genome.fa.fai
$ grep -c ">" Amphimedon_queenslandica.Aqu1.23.dna.genome.fa
13397
$ grep ">" Amphimedon_queenslandica.Aqu1.23.dna.genome.fa | head
>Contig1 dna:scaffold scaffold:Aqu1:Contig1:1:633:1
>Contig3 dna:scaffold scaffold:Aqu1:Contig3:1:652:1
>Contig4 dna:scaffold scaffold:Aqu1:Contig4:1:654:1
>Contig5 dna:scaffold scaffold:Aqu1:Contig5:1:662:1
>Contig6 dna:scaffold scaffold:Aqu1:Contig6:1:665:1
>Contig7 dna:scaffold scaffold:Aqu1:Contig7:1:715:1
>Contig8 dna:scaffold scaffold:Aqu1:Contig8:1:717:1
>Contig9 dna:scaffold scaffold:Aqu1:Contig9:1:718:1
>Contig10 dna:scaffold scaffold:Aqu1:Contig10:1:720:1
>Contig11 dna:scaffold scaffold:Aqu1:Contig11:1:743:1
$ head Amphimedon_queenslandica.Aqu1.23.dna.genome.fa.fai
Contig1	633	52	60	61
Contig3	652	748	60	61
Contig4	654	1463	60	61
Contig5	662	2180	60	61
Contig6	665	2906	60	61
Contig7	715	3635	60	61
Contig8	717	4414	60	61
Contig9	718	5195	60	61
Contig10	720	5979	60	61
Contig11	743	6765	60	61

For some reason the person who made this seemed to number them in reverse order, rather than the longest one first. Since these were Sanger reads, could there be a problem if some read were longer than the contig?

**Comment by ekg** [comment]
I don't think so. Are you using the most recent version?

**Comment by wrf** [comment]
I pulled again and remade the .fai file and there is no difference; it still stops after the first contig.

**Comment by ekg** [comment]
Would it be possible to share some of the data as a test case? Say, the
first three contigs?

**Comment by ramadatta** [comment]
Hi, I am facing similar problem. It appears freebayes parallel is not able to iterate through all of the regions in the regions file specified. Can I kindly know if there is a work around for this?
