### ISSUE TITLE
-@ re-genotyping hung for pooled-discrete 

### ISSUE THREAD

**Issue by peterdfields** [freebayes/freebayes#201]
Hi,

I'm trying to generate allele counts using freebayes as previously described here:

https://github.com/ekg/freebayes/issues/200

Because the pools have different numbers of genotypes present in certain cases I need to run individual pooled-discrete instances. I then merge the individual runs using vcfcombine, generate the bgzipped vcf and tabix index, which all seems to look normal. When I try to start the freebayes target genotyping with -@ as in the following,

freebayes -f ref.fa -p 20 --use-best-n-alleles 4 --pooled-discrete -@ target.vcf.gz pooled_sample1.bam > pooled_sample1.target.vcf

the header of the vcf is generated but then nothing else is printed though the process continues without printing errors. The version of freebayes I'm using is v0.9.21-23-gfc96016.

Please let me know if further information would be useful.

**Comment by ekg** [comment]
Please update freebayes and test again.

**Comment by peterdfields** [comment]
The pull from github generated freebayes version v0.9.21-24-g840b412-dirty. There is still no output beyond the header.

**Comment by ekg** [comment]
What does the debugging output show?

**Comment by peterdfields** [comment]
It doesn't seem abnormal:

loading fasta reference ref.fa
Opening BAM fomat alignment input file: pooled_sample1.bam ...
 done
Number of ref seqs: 22137
Number of target regions: 0
no sample list file given, reading sample names from bam file
found 1 samples in BAM file
loading first target
to next target
input allele:  snp:1X:4687:1:T
input allele:  reference:1M:4688:1:A
input allele:  reference:1M:4689:1:T
input allele:  snp:1X:4690:1:T
input allele:  snp:1X:4951:1:T
input allele:  snp:1X:5410:1:T
input allele:  reference:1M:5411:1:A ...

and so on continuously.

**Comment by ekg** [comment]
Do you get the expected behavior when running with --region set to a single
reference sequence?

**Comment by peterdfields** [comment]
I can try it. This would mean removing the -@ vcf.gz approach, and setting say a single contig/scaffold with a .bed file?
