### ISSUE TITLE
-A and --cnv-map behavior with merged vs. non-merged bam

### ISSUE THREAD

**Issue by peterdfields** [freebayes/freebayes#202]
Hi,

I'm working on generating allele frequency data from pooled Illumina sequencing on a few projects using freebayes --pooled-discrete. I've run into a few bumps getting things to work as described in the following:

https://groups.google.com/forum/#!topic/freebayes/dtzt4auFlZI
https://github.com/ekg/freebayes/issues/201

What I've found now is that while using the -A or --cnv-map .bed file works when the bam files are merged, I cannot seem to get it to work when the bam files are referred to using the -b flag or a regular expression. I.e only the first sample in the regular expression or the explicit -b is called in the vcf.

**Comment by ekg** [comment]
It sounds like there might be a problem with the read groups. Are they
unique across all BAM files?

**Comment by peterdfields** [comment]
In the present test case I'm not sure that's the problem, but maybe I've got something wrong. There are only two samples, again just a test, and the read groups were added individually with the picard tools AddOrReplaceReadGroups utility (as it was with the larger sample). The merged bam was created with samtools merge, without using the -rh flag given the RG info should be present in each bam already. Running freebayes with the same settings on individual bam files seems at least to suggest that the RG is specified properly, in that the expected RG is printed in the vcf file. Are there any particular tests you might suggest to see if the read group specification is the issue?

**Comment by ekg** [comment]
Would you paste the headers from the two files?

**Comment by peterdfields** [comment]
You can see the files using the following links:

two input bams:
https://gist.github.com/peterdfields/c155c1cdec42b66f992b
https://gist.github.com/peterdfields/59c1ba586a1aea68597a

merged bam:
https://gist.github.com/peterdfields/aec13490e53428fd5b08

**Comment by peterdfields** [comment]
Just a quick update. I was able to get expected outputs (no analysis, just the expected GT fields, vcf header, etc.) by generating an interleaved like format of the .bed file and with a merged bam file. Specifying individual rather than a merged bam file does not work with the -A or --cnv-map options.

**Comment by ekg** [comment]
It looks like you have a conflict in ID/Sample space in the headers that is resolved by the merging.

Only in the merged file do you have two samples defined with different `ID:` fields. This allows the calling process and CNV map (which is defined by sample) to work properly.

https://gist.github.com/peterdfields/aec13490e53428fd5b08#file-merged-header-txt-L22139-L22140

```
@RG	ID:1	PL:Illumina	PU:TTAGGC	LB:Lane1	SM:NF01
@RG	ID:1-46D767FF	PL:Illumina	PU:TTAGGC	LB:Lane1	SM:NF02
```

However note that in the inputs the IDs are overlapping and so the two samples cannot be resolved if we merge the file without trying to disambiguate the ID space.

https://gist.github.com/peterdfields/59c1ba586a1aea68597a#file-nf02-header-txt-L22139

```
@RG	ID:1	PL:Illumina	PU:TTAGGC	LB:Lane1	SM:NF02
```

https://gist.github.com/peterdfields/c155c1cdec42b66f992b#file-nf01-header-txt-L22139

```
@RG	ID:1	PL:Illumina	PU:TTAGGC	LB:Lane1	SM:NF01
```

It looks like the tool you are using does this. [`bamaddrg`](https://github.com/ekg/bamaddrg) also does, if you need a streaming alternative (you could open the files with bamaddrg and pipe the output into freebayes).
