### ISSUE TITLE
SNV near deletion with good support missed

### ISSUE THREAD

**Issue by wheaton5** [freebayes/freebayes#203]
Erik was kind enough to explain this issue already but wanted it public for other's benefit. 

So I have an SNV near a deletion with 24% allele frequency.
![screen shot 2015-10-09 at 12 34 59 pm](https://cloud.githubusercontent.com/assets/4810406/10418587/1127c370-7014-11e5-9b67-41c3bb148f94.png)

It turns out that because freebayes is considering the deletion and snv as part of the same complex variant and the homopolymer sequence causing a lot of noise in the variant call (many different potential complex variants), none of them pass the 20% allele frequency threshold. If I reduce the allele frequency threshold to 0.1 the variant is picked up (both deletion and snv as a complex variant that vcfallelicprimitives breaks back into their simplest representation.

Thanks Erik!

**Comment by ekg** [comment]
I think this should be resolved in a more-general way. Tweaking the thresholds doesn't make sense for general performance. Ideas are welcome.
