### ISSUE TITLE
bug: first entry in `--targets` is skipped

### ISSUE THREAD

**Issue by travc** [freebayes/freebayes#210]
The first entry in a BED `--targets` file is getting skipped.  It looks like it happens pretty deep down, not at the stage of reading in the file.  I've tried reordering and confirmed that it is skipping whatever happens to come first.

Here is some relevant debugging output:

`freebayes -dd --targets test.bed --fasta-reference AgamP4.fa --ploidy 2 --theta 0.01 --report-monomorphic --use-mapping-quality --genotype-qualities --max-complex-gap 0 --report-genotype-likelihood-max --no-population-priors --standard-filters {lots of --bam files}`

```
...
Making BedReader object for target file: test.bed ...
done
Number of target regions: 4
...
at start of main loop
current reference base is N
loading first target
to next target
clearing registered alignments and alleles
processing target 10317-546 Note=M:T,S:C ^M 3L 413943 413944
loading target reference subsequence
setting new position 413943
set region
got first alignment in target region
next position 413944 outside of current target right bound 413944
to next target
clearing registered alignments and alleles
processing target 01039-358 Note=M:G,S:T ^M X 20015633 20015634
loading target reference subsequence
setting new position 20015633
set region
got first alignment in target region
processing position 20015634 in sequence X
updating alignment queue
currentPosition = 20015633; currentSequenceStart = 0; currentSequence end = 24393108
currentAlignment.Position == 20015486, currentAlignment.AlignedBases.size() == 150, currentPosition == 20015633, currentSequenceStart == 0 .. + currentSequence.size() == 24393108
top of alignment parsing loop
alignment: J00113:30:H37C7BBXX:2:1225:23066:14097
registering alignment 0 20015486 20015486
alignment readName J00113:30:H37C7BBXX:2:1225:23066:14097
...
```

If I swap the first two lines in my targets BED file, I get...

```
...
at start of main loop
current reference base is N
loading first target
to next target
clearing registered alignments and alleles
processing target 01039-358 Note=M:G,S:T ^M X 20015633 20015634
loading target reference subsequence
setting new position 20015633
set region
got first alignment in target region
next position 20015634 outside of current target right bound 20015634
to next target
clearing registered alignments and alleles
processing target 10317-546 Note=M:T,S:C ^M 3L 413943 413944
loading target reference subsequence
setting new position 413943
set region
got first alignment in target region
processing position 413944 in sequence 3L
updating alignment queue
currentPosition = 413943; currentSequenceStart = 0; currentSequence end = 41963435
currentAlignment.Position == 413795, currentAlignment.AlignedBases.size() == 150, currentPosition == 413943, currentSequenceStart == 0 .. + currentSequence.size() == 41963435
top of alignment parsing loop
alignment: HS3:544:HAPGPADXX:2:2211:14235:79214
...
```

ETA: This is for a freshly pulled build v0.9.21-30-g4d99c14

**Comment by ekg** [comment]
I'm surprised at this because there are tests that should catch this. I can
verify that this isn't the case.

**Comment by travc** [comment]
Just sticking a newline at the beginning of the BED file works as a workaround.  Odd since I would think that the BedReader would fail to parse a blank line.  Instead, it outputs `Number of target regions: 5` (though there are only 4 lines with with anything on them).

```
...
at start of main loop
current reference base is N
loading first target
to next target
clearing registered alignments and alleles
processing target 01039-358 Note=M:G,S:T X 20015633 20015634
loading target reference subsequence
setting new position 20015633
set region
...
```

It just seems like you have to give it something to skip over.

**Comment by travc** [comment]
Ah... The problem arises when the first entry is a single base (size 1 region).

works fine:
```
X   20015633    20015634
3L  413943  413944
````

skips first line:
```
X   20015633    20015634
3L  413943  413944
```

I'm not 100% sure how your tests work, but I think `by_region` fails if you try a size 1 region (set one of the regions to `q:185-186`).

PS: It might be too late now, but using 0-based coordinates in combination with the `htslib`/`samtools` style chr:start-end format is probably a bad idea.  That format pretty much implies 1-based IMO since that is the standard.

**Comment by travc** [comment]
A bit more oddness...
running from within the test directory:

`../bin/freebayes  --bam tiny/NA12878.chr22.tiny.bam -f tiny/q.fa -r q:184-190`  
1 variant is found `q       186     .       T       ...`

but...
`../bin/freebayes  --bam tiny/NA12878.chr22.tiny.bam -f tiny/q.fa -r q:185-190`
finds no variants.

Shouldn't 0-base 185-190 include pos 186?
