### ISSUE TITLE
Kill 9 error and running in parallel

### ISSUE THREAD

**Issue by yaseen-ladak** [freebayes/freebayes#221]
Hi @ekg @AlistairNWard 

I am now able to run freebayes on El Cpitan OS X on Mac. However, in between the process stops and gives me Kill 9 error on terminal and I get the pompt again. I ran this twice. Every time its stops at a different location and the VCF is created but partial.

Also, can you help me with the command to run freebayes in parallel using freebayes-parallel

freebayes - f hg38.fa S1.bam S2.bam S3.bam S4.bam

I am using the entire hg38.fa as the reference.

On some other biostars forum I read:

parallel --keep-order --max-procs 11 "freebayes --fasta-reference $REF \

```
--genotype-qualities --experimental-gls \
--region {} $BAM  " ::: $seqnames \
| vcffirstheader \
| vt normalize -r $REF - > $VCF
```

I am a bit confused I have two BAM files that need to be run with freebayes in one case I dont want to use vcffirstheader and vt normalise and in the second run I want to
Lets say the files are S1.bam and S2.bam and the reference is hg38.fa. Also do I need 

--region {} $BAM ?
parallel --keep-order --max-procs 0  "freebayes --fasta-reference hg38.fa  " ::: S1.bam S2.bam > output_1.vcf

with the vcffirst header and vt normalise would it look like:

parallel --keep-order --max-procs 11 "freebayes --fasta-reference  hg38.fa " ::: S1.bam S2.bam | vcffirstheader | vt normalize -r hg38.fa - > output_2.vcf

Thanks,
Yaseen

**Comment by ekg** [comment]
Did you run without this parameter: --experimental-gls ? It no longer
exists.

**Comment by yaseen-ladak** [comment]
Even without using parallel just simple command like

1. freebayes - f hg38.fa S1.bam S2.bam fails with kill 9. I have two questions can I run using parallel this command of freebayes  and specify the number of cores.

2. I have just updated in the previous thread about make and make test.

**Comment by yaseen-ladak** [comment]
@ekg  @AlistairNWard 

any suggestions on how to run in parallel ?
