### ISSUE TITLE
Install error undefined reference to `gzopen64' in tabixx make

### ISSUE THREAD

**Issue by mkortas** [freebayes/freebayes#224]
freebayes/vcflib/tabixpp/bedidx.c:103: undefined reference to `gzopen64'

./libtabix.a(bedidx.o): In function `bed_read':
/cm/shared/apps/freebayz/freebayes/vcflib/tabixpp/bedidx.c:103: undefined reference to`gzopen64'
collect2: ld returned 1 exit status
make[3]: **\* [tabix] Error 1

**Comment by ekg** [comment]
Are you certain you have the 64-bit compatible version of zlib installed?

**Comment by mkortas** [comment]
I believe so:

[root@cruncher bin]# yum list installed|grep zlib
zlib.i686                               1.2.3-29.el6               installed
zlib.x86_64                             1.2.3-29.el6               @base
zlib-devel.i686                         1.2.3-29.el6               @base
zlib-devel.x86_64                       1.2.3-29.el6               installed

**Comment by ekg** [comment]
Can you build tabixpp independently? There have been some patches against
it recently that may address this.

**Comment by mkortas** [comment]
I have descended into the tabixpp directory that is provided under freebayes (/freebayes/vcflib/tabixpp) and run the make from there, but with no success.

I then tried installing it independently via “git clone --recursive https://github.com/tseemann/tabixpp.git” which seemed to work. At least no errors were generated.

[root@cruncher tabixpp]# /cm/shared/apps/tabixpp/tabixpp/tabix++
/cm/shared/apps/tabixpp/tabixpp/tabix++ [file] [ [region] ... ]
Writes out regions from bgzf-compressed, tabix-indexed file.
Supply 'header' to print out the header, and no regions to
print the contents of the entire file.

**Comment by ekg** [comment]
In tabixpp in the freebayes repo, try `git pull origin master`. Then try
rebuilding and running freebayes.

**Comment by mkortas** [comment]
Did as instructed. I got an error regarding missing htslib…

../vcflib/tabixpp/tabix.hpp:4:25: error: htslib/bgzf.h: No such file or directory
../vcflib/tabixpp/tabix.hpp:5:24: error: htslib/tbx.h: No such file or directory
../vcflib/tabixpp/tabix.hpp:6:25: error: htslib/kseq.h: No such file or directory

So I tried:

[root@cruncher freebayes]# git submodule update --recursive
From git://github.com/ekg/tabixpp
   c2d6c12..ef377b4  master     -> origin/master
Submodule path 'tabixpp': checked out 'c2d6c12eb827805fb13db4bab20f74b212b8b6d0'

Which got me back to the original error:

freebayes/vcflib/tabixpp/bedidx.c:103: undefined reference to `gzopen64'

**Comment by mdshw5** [comment]
@mkortas You probably have an older version of system zlib. If you've installed a newer version, then it's possible the linker can't find it. I fixed this by replacing all occurrences of `-lz` in `vcflib/tabixpp/Makefile` with the `/path/to/zlib.so` for the newer version of zlib.
