### ISSUE TITLE
Strand info for samples in FORMAT

### ISSUE THREAD

**Issue by AlistairNWard** [freebayes/freebayes#227]
Is it currently possible to get freebayes to report the number of observations on each strand? e.g. instead of:

RO=5:AO=7

it would be great to see:

RO=2,3:AO=4,3

showing the observations on the forward and reverse strand respectively. Am I missing the argument to do this, or is not currently possible? If it isn't possible - could it be introduced?

**Comment by atks** [comment]
Can freebayes switch to the AD, ADF and ADR INFO tags specified in VCFv4.3?

http://samtools.github.io/hts-specs/VCFv4.3.pdf (Page 9)

**Comment by AlistairNWard** [comment]
+1

**Comment by ekg** [comment]
I have to say I am not a fan of arbitrary numbers attached to the vcf
fields. That said I am planning to move.

Currently this information is available as SAR SAF SRR SRF for alternate
and reference reverse and forward counts.

**Comment by AlistairNWard** [comment]
I'm not sure what you mean by arbitrary. SAR etc. are very useful, but we really need the information on a per sample basis and as Adrian pointed out, these fields are already available defined in the VCF spec., so I would argue there is nothing arbitrary about them. It wouldn't have to be default behaviour, but maybe specify a command line flag and the AD, ADF and ADR fields are included in the genotype fields.

**Comment by ekg** [comment]
Sorry! I was confused! I see from the documentation that is number R. I'll
move over to this.

**Comment by AlistairNWard** [comment]
Awesome - thanks Erik.

**Comment by atks** [comment]
one more thing Erik, AD, ADF and ADR are also specified for the INFO fields too in VCFv4.3, so you might want to rename and organize(organise) SAR, SAF, SRR and SRF.
