### ISSUE TITLE
multi-sample (multi-timepoint) somatic variant calling

### ISSUE THREAD

**Issue by brentp** [freebayes/freebayes#228]
currently, somatic variant callers only do pairwise (tumor-normal) calling. It is more and more common to have a normal and multiple time-points (or multiple spatial samples) of the tumor.

It would be great if freebayes had a model for calling these types of datasets.
This would require specifying which was the normal sample and which were the tumor samples associated with each normal.

I'd be happy to help to try to validate/compare to existing methods.

**Comment by ekg** [comment]
Thanks @brentp (we just discussed this here at Utah). I think it's doable if the priors are modified to use a kind of two-level Ewens sampling formula. The first would be typical, and would apply to the specified normal sample. The second would use a different prior for the rate of somatic variation and would apply to the other (somatic) samples. We'd also need a way to specify which sample was which on the command line. The nice thing about this is that it would generalize to two or many samples.
