### ISSUE TITLE
Too Many files open v1.0.1

### ISSUE THREAD

**Issue by yaseen-ladak** [freebayes/freebayes#231]
@ekg @AlistairNWard 

I was trying to run 42 bam files with freebayes parallel script using freebayes v1.0.1. It ran for a while however crashed at some point yesterday evening and on restart generates an OS error about too many open files.

Is this a memory issue of the issue with the freebayes parallel script?

I would be very thankful for your help/

**Comment by noporpoise** [comment]
Have you tried running `ulimit -n` to see how many files a process can have open at once?  `ulimit -n 1024` should set the limit to 1024. Not sure about the original crash though.

**Comment by yaseen-ladak** [comment]
Thanks for the reply. Is this s apart of freebayes or should I run this in a shell. I am sorry I am a bit confused.

**Comment by yaseen-ladak** [comment]
Thanks will give this a go so before running freebayes I should run ulimit -n 1024 in the shell and then run freebayes?

**Comment by noporpoise** [comment]
yes.

**Comment by yaseen-ladak** [comment]
This is set to 1024.

**Comment by ekg** [comment]
What level of parallelism did you set? Each thread will consume something
like 42 x 2 = 84 + 3 file descriptors. You'll need to set this higher than
1024 if you're running more than about 10 threads.

**Comment by rajwhitlock** [comment]
Hi Erik,
Could you provide a little more detail here? I have been running freebayes-parallel for "polyploid" (pool seq) samples, and have also run into the file handle warning issued by parallel while processing only four bam sample files (ulimit -Sn was first raised to my hard limit of 4096; --use-best-n-alleles was reduced to 2; threads 12–24 depending on the run; ploidy = 40–96 in these separate analyses). Here are the questions:
i) In your file descriptor estimate (above), what does the multiplier x 2 stand for, and would it need to be altered depending on ploidy, coverage, # haplotypes considered/ would the estimate still hold as presented?
ii) The warning from parallel does not prevent a vcf being output by freebayes-parallel in due course. Are there any other expected side effects (to the vcf) as the file descriptor limit is reached, beyond the slow-down in parallel implementation (reduced at intervals to 1–2 threads, but mostly running up to speed)? The output vcfs look OK to me, and can be filtered very nicely in bcftools.
Best wishes,
Raj

**Comment by ekg** [comment]
The only thing that should matter for the file handle limit is the number
of BAM files you are opening. If you run with very high parallelism then
this could be come high even if there are only a few BAM files, as each
time we open one we consume towards our file handle limit.

**Comment by mbelmadani** [comment]
I've encountered a similar issue:
```
parallel: Warning: No more file handles. 
parallel: Warning: Raising ulimit -n or /etc/security/limits.conf may help.
```
Using 2 separate Freebayes run on 1 BAM file each (each process returned their own error), using 30 cores each. My ulimit -n is also set to 1024, but I will try to raise it to the system limit (4096, though my sysadmin says the system limit can also be increased). Do you have any recommendations on estimating the proper ulimit based on a number of input BAMs and cores used?  Here's an example of /proc/cpuinfo for one cpu. (In a nutshell, 2 CPUs with 16/32 physical/logical cores each.)

```
processor       : 63
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz
stepping        : 1
microcode       : 0xb000021
cpu MHz         : 2599.980
cache size      : 40960 KB
physical id     : 1
siblings        : 32
core id         : 15
cpu cores       : 16
apicid          : 63
initial apicid  : 63
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts
bogomips        : 4204.21
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
```
Also curious to know if the warning means my results are affected; I'm guessing no, since the CPUs still seem to be used, and  freebayes still seems to be running for a while since this occured..
