### ISSUE TITLE
Assertion `numSites > 0' raised while writing gVCF

### ISSUE THREAD

**Issue by mdshw5** [freebayes/freebayes#236]
`ResultData.cpp:652: vcf::Variant& Results::gvcf(vcf::Variant&, NonCalls&, AlleleParser*): Assertion numSite\
s > 0' failed.`

From looking at the surrounding code it looks like this is a region at the end of a chromosome that has inly non-calls. It's possible that this assertion is testing for a case that shouldn't be considered an error.

**Comment by ekg** [comment]
That sounds right. The assertion isn't needed.

I have also found that the gvcf block start seems to be off by one or two,
so I need to add tests for the targeting.

**Comment by adamantli** [comment]
I had the same error on version v.1.2.0 calling on targeted region like:
chr1	110680113	110680114
...
freebayes: ResultData.cpp:659: vcflib::Variant& Results::gvcf(vcflib::Variant&, NonCalls&, AlleleParser*): Assertion `numSites > 0' failed.
Aborted (core dumped)
