### ISSUE TITLE
QUAL scores for monomorphic sites

### ISSUE THREAD

**Issue by pishotta** [freebayes/freebayes#237]
As usual, it is probably my understanding that is at fault, but If according to the VCF specs: "<b>QUAL [is the] phred-scaled quality score for the assertion made in ALT. i.e. give -10log_10 prob(call in ALT is wrong). If ALT is ”.” (no variant) then this is -10log_10 p(variant), and if ALT is not ”.” this is -10log_10 p(no variant). High QUAL scores indicate high confidence calls</b>",  then why are the QUAL scores of monomorphic loci output by freebayes using the --report-monomorphic switch always so low (zero or very near) when the quality by other measures so obviously high?  Isn't this backwards?  Shouldn't the phred score (the QUAL value) always be high when the quality of the call is high (which seems to be the intention of the VCF spec -- to provide a uniform measure that the assertion made in ALT is wrong)?  This ambiguity is affecting my ability to filter good calls by high QUAL scores and generally driving me buggy.  Google has not directly resolved my confusion, only fed it.  Help?  Please?

**Comment by ekg** [comment]
QUAL is the probability of polymorphism, which is low at monomorphics by
their definition. But you are right that call quality is another thing for
monomorphic sites. It would be 1-QUAL. Does this explain?

**Comment by ekg** [comment]
... if we define call quality to be "the probability that what we say is
happening is happening".

**Comment by pishotta** [comment]
I agree that QUAL is often interpreted as "the probability of polymorphism", and if the locus is a variant, that is correct;  but the the published specs ( e.g. https://samtools.github.io/hts-specs/VCFv4.1.pdf ) seem explicit that QUAL is a measure of the correctness of the call, whether polymorphic or homozygous reference.  That actually makes a lot of sense, because the QUAL value in a VCF file then provides a consistent and unambiguous measure of call quality and a convenient handle which can otherwise be difficult/convoluted to determine.in downstream analytics (I'm using bcftools to process freebayes output).  Having to subtract QUAL from 1(?) just in the case of a monomorphic call requires some unfortunate coding gymnastics..<p>This point is admittedly confusing (God knows), but I think I'm technically right about what QUAL should be in a VCF file.  I hope you will consider this further.  Maybe some VCF pro's could chime it.  I do know it would make VCF processing of monomorphic loci much easier if their QUAL scores were reported in freebayes output in a manner I believe consistent with the published specs.<p>Sorry to be contrary.

**Comment by pishotta** [comment]
Hi @ekg,

There is another peculiarity in the VCF files that might be related to this issue.  Consider these calls where one sample is being processed by freebayes (I apologize for their length):
<pre>
chr1    3545215 .       C       T       2.36566e-14     .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=18;CIGAR=1X;DP=87;DPB=87;DPRA=0;EPP=7.35324;EPPR=3.79707;GTI=0;LEN=1;MEANALT=1
;MQM=58.3889;MQMR=59.7826;NS=1;NUMALT=1;ODDS=63.9598;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=155;QR=1162;RO=69;RPL=12;RPP=7.35324;RPPR=105.258;RPR=6;RUN=1;SAF=0;SAP=
42.0968;SAR=18;SRF=33;SRP=3.29354;SRR=36;TYPE=snp;technology.iontorrent=1       GT:DP:RO:QR:AO:QA       0/0:87:69:1162:18:155
chr1    6528143 .       C       G       9.04528e-16     .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=21;CIGAR=1X;DP=104;DPB=104;DPRA=0;EPP=48.6112;EPPR=5.12945;GTI=0;LEN=1;MEANALT
=1;MQM=60;MQMR=59.988;NS=1;NUMALT=1;ODDS=68.2768;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=334;QR=1562;RO=83;RPL=0;RPP=48.6112;RPPR=3.66436;RPR=21;RUN=1;SAF=0;SAP=48.6
112;SAR=21;SRF=57;SRP=28.1523;SRR=26;TYPE=snp;technology.iontorrent=1   GT:DP:RO:QR:AO:QA       0/0:104:83:1562:21:334
chr1    7890064 .       A       G       1.85633e-14     .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=17;CIGAR=1X;DP=85;DPB=85;DPRA=0;EPP=24.5973;EPPR=150.67;GTI=0;LEN=1;MEANALT=1;
MQM=24.8235;MQMR=32.8529;NS=1;NUMALT=1;ODDS=53.7601;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=290;QR=1406;RO=68;RPL=16;RPP=31.7504;RPPR=150.67;RPR=1;RUN=1;SAF=1;SAP=31
.7504;SAR=16;SRF=0;SRP=150.67;SRR=68;TYPE=snp;technology.iontorrent=1   GT:DP:RO:QR:AO:QA       0/0:85:68:1406:17:290
chr1    10468222        .       G       A       0       .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=14;CIGAR=1X;DP=68;DPB=68;DPRA=0;EPP=33.4109;EPPR=24.6841;GTI=0;LEN=1;MEANALT=2
;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=63.9844;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=125;QR=991;RO=53;RPL=14;RPP=33.4109;RPPR=17.8009;RPR=0;RUN=1;SAF=14;SAP=33.4109;SA
R=0;SRF=21;SRP=7.96781;SRR=32;TYPE=snp;technology.iontorrent=1  GT:DP:RO:QR:AO:QA       0/0:68:53:991:14:125
chr1    11249630        .       A       C       0       .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=11;CIGAR=1X;DP=53;DPB=53;DPRA=0;EPP=26.8965;EPPR=70.0157;GTI=0;LEN=1;MEANALT=1
;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=44.497;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=128;QR=888;RO=42;RPL=0;RPP=26.8965;RPPR=94.2121;RPR=11;RUN=1;SAF=11;SAP=26.8965;SAR
=0;SRF=3;SRP=70.0157;SRR=39;TYPE=snp;technology.iontorrent=1    GT:DP:RO:QR:AO:QA       0/0:53:42:888:11:128
</pre>
Such results are fairly common, but I don't know quite what to make of them.  In all cases:
<ul><li>
The GT call is 0/0, indicating homozygous reference, but</li>
<li>The "TYPE" INFO field labels them as "snp",</li>
<li>The QUAL score is a very low number, and</li>
<li>The ALT field contains a value (not "."), even though the VCF docs specify "<i>ALT - alternate base(s): Comma separated list of alternate non-reference alleles <b>called</b> on at least one of the samples ...</i>",
</li></ul>
My guess is that when an alternate allele is <b>merely observed</b> in one or more of the aligned reads at the locus being considered, it makes its way into the ALT column even though never actually called  (as the spec lists is a necessary condition for inclusion there).  Similarly NUMALT is reported as 1, even though there are no non-reference alleles called.  Alleles "observed" is not necessarily alleles "called". So if GT = "0/0" for all samples in a call record (one, in these cases), shouldn't ALT = ".", TYPE be omitted (since there is no called variant), NUMALT = 0, and QUAL be calculated as for a monomorphic call? Anyway, current reporting makes for some confusing records and complicates downstream processing.

I am not precisely sure what set of circumstances in the input data produces these apparently malformed records.  To be consistent in my stance, they should be brought into conformity with the specs; but on the other hand:  it may not matter.as much as some other things.  If, as I suspect, they are ultimately the byproduct of some very low confidence calls, then once the QUAL scoring is properly sorted out, they should be eliminated by any reasonable filter -- hopefully.

Again, my thanks to you and @lh3 for helping me understand this.

-- Fred @pishotta

**Comment by AlistairNWard** [comment]
I may not have this entirely correct, but this is my understanding of what
you are seeing. As Freebayes process the locus, it determines that there is
sufficient evidence to consider the alternate allele. Having established
the possible alleles, Freebayes determines the genotypes of all samples (in
this case, there is only one). In the genotype fields, you can see that
there is depth for the alternate allele (and so if no allele was reported
in the ref field, you'd have no idea what the alternate observations (AO)
would refer to). Ultimately, Freebayes determined that the most likely
genotype is 0/0 and so this is reported, but with a very low variant
quality.

I don't think that these are malformed records. All the fields in the INFO
and FORMAT fields relate to the alternate allele defined in ALT. Freebayes
is giving you these calls, because it determined that there was sufficient
evidence to consider them (for example, the final A/C SNP in your example
has a depth of 53 of which 42 are reference and 11 are alt). If you output
the genotype likelihoods, you then get a better idea of how likely each of
the considered genotypes are. Best practice is to perform post processing
on your VCF to filter out records considered of low quality. A very simple
QUAL filter would remove all of these calls.


Alistair Ward
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by lh3** [comment]
These are correct VCF. What is not right is @pishotta's example in samtools/bcftools#370:
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT
chr1    69442   .       G       .       0       .       DP=177;DPB=177;EPPR=3.61144;GTI=0;MQMR=4.53107;NS=1;NUMALT=0;ODDS=0;PAIREDR=0;PQR=0;PRO=0;QR=4224;RO=177;RPPR=233.272   GT:DP:RO:QR:AO:QA       0/0:177:177:4224:.:.
chr1    69443   .       C       .       0       .       DP=178;DPB=178;EPPR=3.0591;GTI=0;MQMR=4.70787;NS=1;NUMALT=0;ODDS=0;PAIREDR=0;PQR=0;PRO=0;QR=4329;RO=178;RPPR=209.178    GT:DP:RO:QR:AO:QA       0/0:178:178:4329:.:.
chr1    69444   .       A       .       0       .       DP=178;DPB=178;EPPR=3.44947;GTI=0;MQMR=4.70225;NS=1;NUMALT=0;ODDS=0;PAIREDR=0;PQR=0;PRO=0;QR=4163;RO=178;RPPR=190.586   GT:DP:RO:QR:AO:QA       0/0:178:178:4163:.:.
chr1    69445   .       A       .       0       .       DP=179;DPB=179;EPPR=3.99292;GTI=0;MQMR=4.69832;NS=1;NUMALT=0;ODDS=0;PAIREDR=0;PQR=0;PRO=0;QR=3938;RO=179;RPPR=180.622   GT:DP:RO:QR:AO:QA       0/0:179:179:3938:.:.
```
where freebayes gives QUAL=0 for ALT=".". @ekg, you don't need to change freebayes without the option `--report-monomorphic`. With this option, you need to flip QUAL at "ALT=." lines.

**Comment by pishotta** [comment]
@AlistairNWard and @lh3,  I agree with your description of what logic freebayes is probably exercising to produce these records.  I am not concerned with that, but I do worry about the ambiguities in the resultant VCF call record that does precipitate some errors in downstream processing by software that strictly follows the formal VCF specification, e.g., bcftools.  I will include a trivial example later.

First, consider this one call record:
<pre>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  F01_1
chr1    1147523 .       T       G       0       .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=12;CIGAR=1X;
          DP=60;DPB=60;DPRA=0;EPP=14.5915;EPPR=7.5342;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=1;
          NUMALT=1;ODDS=48.1507;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=113;QR=909;RO=48;
          RPL=0;RPP=29.068;RPPR=90.593;RPR=12;RUN=1;SAF=2;SAP=14.5915;SAR=10;SRF=27;SRP=4.6389;
          SRR=21;TYPE=snp;technology.iontorrent=1   GT:DP:RO:QR:AO:QA    0/0:60:48:909:12:113
</pre>
Is there a variant call, and if so, what is it?  As you say, it looks like G was being considered and is probably what accounts for the AO count, but in fact, the GT is "0/0" and no variant was called.  My point here is not how QUAL is being calculated.  That point is already being addressed by @ekg. My point is that as interesting and well-intentioned as it may be, "G" does not belong in the ALT column, which should be "." (because no variant was called for that row), with QUAL calculated as previously discussed.  If it is important to know what un-called alternates were being considered, the VCF spec provides for the inclusion of additional INFO or FORMAT strings that could be used for that purpose.  ALT is strictly for "called", not "considered", variants, or you're in for some downstream complications.

What difference does it make?  Suppose, for example, you want to extract all the records  from a VCF file where a range of loci shows SNP variants in preparation for some kind of population distribution study or something -- not an uncommon desire.  A command like "bcftools view -H -v snps foo.vcf.gz" and counting the returning records should do the trick (in part).  That command should return just those records for loci where a SNP is called for someone, right?  But if that file contains records like the above, that number would be wrong.  Why?  Because bcftools expects the REF and ALT fields to conform to the spec and uses those to determine if the row contains a snp, not by evaluating the GT fields, so the count would be off by as many records the file contains that are similar to the above.  This is a trivial example and easily worked around with GT and/or QUAL filters which would generally be in place anyway, but shows why one has to be concerned about the possibility of other unintended and undetected negative consequences of any deviation from the specs.  Under some circumstances, freebayes is producing call records that bcftools cannot interpret correctly, sometimes involving the QUAL field, sometimes the ALT field.

I am not sure what the correct resolution to these records should be, whether low confidence snp calls or low-quality monomorphic calls or whatever, but I do believe they should be internally consistent and not known to deviate from the formal VCF specs (which these records do).  Otherwise, as demonstrated, trouble ensues.

-- Fred P.

**Comment by pishotta** [comment]
Hi @AlistairNWard, @lh3 ,

It turns out that not all such malformed records do have low QUAL scores that would be caught by a bcftools filter.  Here are a few freebayes output call records of the problematic type (with GTs = "0/0" but ALT != ".") having relatively high QUAL scores.
<pre>
chr8    12288064        .       G       A       370.572 .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=101;CIGAR=1X;DP=261;DPB=261;DPRA=0;EPP=93.8466;EPPR=276.67;GTI=0;LEN=1;MEANALT=1;MQM=3.65347;MQMR=4.18125;NS=1;NUMALT=1;ODDS=85.3273;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=2352;QR=3875;RO=160;RPL=101;RPP=222.329;RPPR=350.446;RPR=0;RUN=1;SAF=83;SAP=93.8466;SAR=18;SRF=151;SRP=276.67;SRR=9;TYPE=snp;technology.iontorrent=1  GT:DP:RO:QR:AO:QA       0/0:261:160:3875:101:2352
chr9    43853788        .       C       T       352.615 .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=32;CIGAR=1X;DP=142;DPB=142;DPRA=0;EPP=56.2114;EPPR=241.872;GTI=0;LEN=1;MEANALT=1;MQM=5.65625;MQMR=5.94545;NS=1;NUMALT=1;ODDS=81.1925;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=782;QR=2168;RO=110;RPL=32;RPP=72.4974;RPPR=241.872;RPR=0;RUN=1;SAF=2;SAP=56.2114;SAR=30;SRF=0;SRP=241.872;SRR=110;TYPE=snp;technology.iontorrent=1    GT:DP:RO:QR:AO:QA       0/0:142:110:2168:32:782
chr9    69207129        .       T       G       66.5314 .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=15;CIGAR=1X;DP=62;DPB=62;DPRA=0;EPP=14.7363;EPPR=5.27418;GTI=0;LEN=1;MEANALT=1;MQM=1.86667;MQMR=1;NS=1;NUMALT=1;ODDS=15.3194;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=275;QR=794;RO=47;RPL=15;RPP=35.5824;RPPR=105.07;RPR=0;RUN=1;SAF=3;SAP=14.7363;SAR=12;SRF=20;SRP=5.27418;SRR=27;TYPE=snp;technology.iontorrent=1       GT:DP:RO:QR:AO:QA       0/0:62:47:794:15:275
chr10   47915898        .       A       G       24.3136 .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=10;CIGAR=1X;DP=24;DPB=24;DPRA=0;EPP=24.725;EPPR=33.4109;GTI=0;LEN=1;MEANALT=1;MQM=6.2;MQMR=5.35714;NS=1;NUMALT=1;ODDS=5.5947;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=230;QR=326;RO=14;RPL=10;RPP=24.725;RPPR=33.4109;RPR=0;RUN=1;SAF=0;SAP=24.725;SAR=10;SRF=0;SRP=33.4109;SRR=14;TYPE=snp;technology.iontorrent=1 GT:DP:RO:QR:AO:QA       0/0:24:14:326:10:230
chr10   49389016        .       T       C       65.0204 .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=34;CIGAR=1X;DP=66;DPB=66;DPRA=0;EPP=5.30951;EPPR=24.9965;GTI=0;LEN=1;MEANALT=1;MQM=3.70588;MQMR=3.875;NS=1;NUMALT=1;ODDS=14.9715;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=773;QR=758;RO=32;RPL=29;RPP=39.7976;RPPR=64.083;RPR=5;RUN=1;SAF=9;SAP=19.3602;SAR=25;SRF=6;SRP=30.1537;SRR=26;TYPE=snp;technology.iontorrent=1    GT:DP:RO:QR:AO:QA       0/0:66:32:758:34:773
chr11   89402728        .       A       G       31.6874 .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=26;CIGAR=1X;DP=55;DPB=55;DPRA=0;EPP=6.01695;EPPR=19.8579;GTI=0;LEN=1;MEANALT=1;MQM=5.46154;MQMR=5.06897;NS=1;NUMALT=1;ODDS=7.29562;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=578;QR=677;RO=29;RPL=26;RPP=59.4686;RPPR=65.983;RPR=0;RUN=1;SAF=10;SAP=6.01695;SAR=16;SRF=22;SRP=19.8579;SRR=7;TYPE=snp;technology.iontorrent=1 GT:DP:RO:QR:AO:QA       0/0:55:29:677:26:578
chr14   19553372        .       G       A       77.1006 .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=12;CIGAR=1X;DP=29;DPB=29;DPRA=0;EPP=14.5915;EPPR=39.9253;GTI=0;LEN=1;MEANALT=1;MQM=1;MQMR=1;NS=1;NUMALT=1;ODDS=17.7531;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=289;QR=406;RO=17;RPL=0;RPP=29.068;RPPR=39.9253;RPR=12;RUN=1;SAF=2;SAP=14.5915;SAR=10;SRF=0;SRP=39.9253;SRR=17;TYPE=snp;technology.iontorrent=1      GT:DP:RO:QR:AO:QA       0/0:29:17:406:12:289
chr15   43892489        .       C       G       32.9457 .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=6;CIGAR=1X;DP=30;DPB=30;DPRA=0;EPP=16.0391;EPPR=18.9659;GTI=0;LEN=1;MEANALT=2;MQM=2;MQMR=2.17391;NS=1;NUMALT=1;ODDS=7.58551;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=88;QR=333;RO=23;RPL=6;RPP=16.0391;RPPR=52.9542;RPR=0;RUN=1;SAF=6;SAP=16.0391;SAR=0;SRF=18;SRP=18.9659;SRR=5;TYPE=snp;technology.iontorrent=1   GT:DP:RO:QR:AO:QA       0/0:30:23:333:6:88
chr16   1279537         .       C       G       261.444 .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=33;CIGAR=1X;DP=108;DPB=108;DPRA=0;EPP=74.6689;EPPR=165.871;GTI=0;LEN=1;MEANALT=1;MQM=3.72727;MQMR=4.28;NS=1;NUMALT=1;ODDS=60.1997;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=752;QR=838;RO=75;RPL=0;RPP=74.6689;RPPR=165.871;RPR=33;RUN=1;SAF=0;SAP=74.6689;SAR=33;SRF=0;SRP=165.871;SRR=75;TYPE=snp;technology.iontorrent=1  GT:DP:RO:QR:AO:QA       0/0:108:75:838:33:752
chr16   69997537        .       G       C       42.5679 .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=13;CIGAR=1X;DP=45;DPB=45;DPRA=0;EPP=31.2394;EPPR=56.2114;GTI=0;LEN=1;MEANALT=1;MQM=3.30769;MQMR=3.96875;NS=1;NUMALT=1;ODDS=9.80156;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=244;QR=690;RO=32;RPL=13;RPP=31.2394;RPPR=72.4974;RPR=0;RUN=1;SAF=0;SAP=31.2394;SAR=13;SRF=2;SRP=56.2114;SRR=30;TYPE=snp;technology.iontorrent=1 GT:DP:RO:QR:AO:QA       0/0:45:32:690:13:244
chr17   12823214        .       G       T       25.7745 .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=9;CIGAR=1X;DP=41;DPB=41;DPRA=0;EPP=5.18177;EPPR=72.4974;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=5.93214;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=104;QR=349;RO=32;RPL=9;RPP=22.5536;RPPR=72.4974;RPR=0;RUN=1;SAF=3;SAP=5.18177;SAR=6;SRF=32;SRP=72.4974;SRR=0;TYPE=snp;technology.iontorrent=1      GT:DP:RO:QR:AO:QA       0/0:41:32:349:9:104
chr17   44409004        .       T       C       134.229 .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=14;CIGAR=1X;DP=64;DPB=64;DPRA=0;EPP=25.3454;EPPR=87.0897;GTI=0;LEN=1;MEANALT=1;MQM=3.35714;MQMR=3.8;NS=1;NUMALT=1;ODDS=30.9074;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=231;QR=1103;RO=50;RPL=14;RPP=33.4109;RPPR=111.584;RPR=0;RUN=1;SAF=13;SAP=25.3454;SAR=1;SRF=47;SRP=87.0897;SRR=3;TYPE=snp;technology.iontorrent=1    GT:DP:RO:QR:AO:QA       0/0:64:50:1103:14:231
</pre>
I don't know what set of circumstances results in these, but it does show that a reasonable QUAL score filter won't always eliminate them.  Better to adhere to the VCF Specs,

-- Fred P.

**Comment by ekg** [comment]
Hi Fred,

I'm having some trouble interpreting the results because I don't understand
how freebayes was run here. Where are the GLs?

Erik

**Comment by AlistairNWard** [comment]
Not addressing the philosophical implications of your comments (I
personally prefer to not have ALT='.' - even if the genotypes are 0/0,
since I want to see the considered alt allele up front and not dig through
INFO fields), but just practicality of using a VCF coming out of Freebayes
- or any variant caller. It is always good to post process the files, with
more than just a QUAL filter. I would always recommend using the vt package
to normalize variants (vt normalize) and you can also subset the file with
vt subset. This will output only those variants for which the genotype is
not 0/0.


Alistair Ward
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by ekg** [comment]
> (I personally prefer to not have ALT='.' - even if the genotypes are 0/0, since I want to see the considered alt allele up front and not dig through INFO fields)

This is also concerning to me. We will need a new mechanism to communicate which alleles were used when a call is attempted but comes back with the monomorphic state as the most probable posterior.

**Comment by pishotta** [comment]
Hi @ekg,

No GLs in the VCF file.  Does freebayes need a switch to report them?  Sorry to be such a pain, and as @AlistairNWard points out, there are ways to ameliorate the problem, but maybe the place to report attempted but uncalled alleles is in the FORMAT section of the call record somehow?  That approach would provide the information per sample but not violate the spec.

**Comment by AlistairNWard** [comment]
Which version of Freebayes are you using? Recent versions output GL by
default.


Alistair Ward
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by pishotta** [comment]
v0.9.21-23-gfc96016  -  Just coming off ~10-12 weeks of whole exome processing during which I did not want to change versions.

**Comment by ycl6** [comment]
Hi all, just wanna say that I also found this "discrepancy" in the output when I thought freebayes only outputs called variant when it is observed in at least 1 sample but found otherwise. So, in the end I decided to use vcffilter to filtered these off by running `vcffilter -f "AC > 0" out.vcf` 

The actual reason why I reply to this thread is that @ekg and @AlistairNWard mentioned the output should contain GL (Genotype Likelihood) values, however the VCF produced by the latest version (v1.0.2-16-gd466dde-dirty) doesn't include this information.

**Comment by stephenturner** [comment]
I'm joining this conversation late, and probably missed a few things, but I'm running into the same original problem that @pishotta described here and in samtools/bcftools#370. I didn't use `--report-monomorphic`, but rather, used `-@ sitesOfInterest.vcf` to force-call genotypes at sites of interest. But, at sites that are monomorphic / homozygous reference, the QUAL is 0, as it should be the way QUAL is defined. 

But I need to filter my variant calls using some reasonable thresholds. Any filtering on QUAL (and SAF/SAR/RPL/RPR, as @ekg suggested elsewhere), would get rid of any of my genotypes at sites of interest. 

My current solution is `bedtools intersect -v`'ing _out_ the sites of interest, filtering those using QUAL/SAF/SAR/RPR/RPL/other criteria, then `bedtools intersect`'ing to get _just_ the sites of interest, filtering those just zeroing out genotypes with low depth, and then `bcftools concatenate -a`'ing them together. 

Did others on this thread have any better solution or workaround with filtering by QUAL on monomorphic sites?

**Comment by giyany** [comment]
Years later, any advice on filtering sites, @stephenturner or someone else?
I also ran into the same issue - I'm interested in keeping the non-variant (monomorphic) sites for some population genetic analysis, but need to reasonably filter a vcf file.

**Comment by EveTC** [comment]
@giyany - Did you find a solution to filtering the vcf with monomorphic sites included?  I am thinking to run freebayes with `--report-monomorphic` to then remove them straight away with something like `bcftools view -C1 file.vcf > monomorphic_sites.vcf`

**Comment by giyany** [comment]
Hi @EveTC ,
That's exactly what I did. Not sure that filtering both parts separately is the most robust solution, but it's the only idea that came to mind.

**Comment by EveTC** [comment]
Hi @giyany,
Thank you for your quick response! I am glad that I am not the only one to think of this work around - "Great minds think alike" (or perhaps "fools seldom differ" if you prefer haha). 

How did you filter out bad quality monomorphic sites, if you don't mind me asking? Also did you struggle with the size of your vcf when you included all monomorphic sites? 

Thank you again

**Comment by giyany** [comment]
Happily @EveTC :)
We ended up filtering by coverage (at the site and individual level) and % of missing data using the same criteria as the polymorphic vcf. I'm sure it's individual for different data-sets, though.

and about the size - absolutely! The vcf is ginormous. I prefer to call variants and keep a file for each linkage group (or chr), then run filtering steps on each file using gnu parallel if working locally or an array if working on a cluster. This somehow reduces the absurdly long running times... 
Hope it's helpful.

**Comment by thr44pw00d** [comment]
I wrote a script that filters a vcf file on QUAL using separate cutoffs for monomorphic and polymorphic sites. Attached in case it will be useful for anyone ending up here.

It's used as follows:
`python3 filter_vcf.py <mono_prob_cutoff> <poly_prob_cutoff> <file.vcf> <filtered_file.vcf>`

e.g. to retain only sites with >99% probability (according to QUAL) of being mono- and polymorphic, respectively:
`python3 filter_vcf.py 0.99 0.99 file.vcf filtered_file.vcf`

[filter_vcf.zip](https://github.com/freebayes/freebayes/files/8911672/filter_vcf.zip)
