### ISSUE TITLE
freebayes skips some input BAM files

### ISSUE THREAD

**Issue by andrewparkermorgan** [freebayes/freebayes#243]
I am attempting to run variant-calling on 168 BAM files (each with reads from a single sample), providing the paths to the BAM files via `--bam-list`.  A small number, between 2 and 8, are omitted from the output VCF file.  The specific samples omitted are the same on every invocation of `freebayes`, but change if I randomly shuffle the lines in the file provided to `--bam-list`.  The same behavior occurs if I provide the paths as positional arguments on the command line, or individually via the `-b` option.

No errors are thrown.

If I then invoke `freebayes` on just BAMs skipped in the first call, separate from the BAMs not skipped, the output VCF then contains the samples I expect.

Using `samtools mpileup | bcftools call` (v1.3) I get genotypes for all 168 samples as expected with no errors, so I don't think there are structural problems with the BAM files.

I am using a fresh compile of `freebayes` from commit `0cb2697`, on Red Hat Linux with `gcc` v4.8.1 and `cmake` v2.8.12.2.

**Comment by ekg** [comment]
I'm going to guess that you have a conflict in the read groups. Would you
please verify that every sample has a unique read group?

**Comment by andrewparkermorgan** [comment]
Ugh, that's exactly it.  RG:IDs overlap between samples from different centres.

Can I conclude that `freebayes` expects that each RG:ID is globally unique, independent of the other pieces of the RG entry?

**Comment by ekg** [comment]
It expects that an RG maps to only one sample. One sample can have many
RGs. In fact, I don't know why I haven't added a check for this.

There is a tool (bamaddrg) than can be used to fix this.

**Comment by andrewparkermorgan** [comment]
Thanks so much for the prompt response.

To clarify for others who may find this thread, the problem was a situation like this:

**A.bam**
```
@RG ID:rg1 SM:sampleA
```

**B.bam**
```
@RG ID:rg1 SM:sampleB
```

When running `freebayes A.bam B.bam`, only one of either `sampleA` or `sampleB` (perhaps whichever appears first?) shows up in the output VCF.

**Comment by tfenne** [comment]
Without having the first clue about how difficult this would be - it would be really nice if freebayes only required that `@RG.ID` is unique within an input SAM or BAM file.  Nothing in the SAM spec requires the `ID`s to be unique beyond the header in a given file, and generally speaking they're only surrogate keys to enable navigation from records back to the header - it's just convention that most folks use a meaningful value to reduce collisions.

**Comment by ekg** [comment]
It would be pretty difficult to fix, because freebayes has no knowledge of
which file a particular read comes from. It sees the results of running
bamtools merge on the input BAM files.

As a matter of practice we can apply something like bamaddrg to resolve.
You can even stream through that into freebayes.
