### ISSUE TITLE
Setting --max-coverage removes variants with lower coverage

### ISSUE THREAD

**Issue by magicDGS** [freebayes/freebayes#253]
I realized that when I'm running in a single sample freebayes with `--max-coverage 1000000` everything in the output file is gone. After testing other thresholds in a small region, I found that actually the maximum coverage is removing things that are below the threshold.

My complete command line is:

```
freebayes -b input.bam -f reference.fa -r chr1:0-100 -K -F 0.01 -C 1 -q 20 -R 0
```

And the variants in this region:

```
chr1    25  .   A   T   1135.08 .   AB=0;ABP=0;AC=2;AF=1;AN=2;AO=48;CIGAR=1X;DP=48;DPB=48;DPRA=0;EPP=75.3927;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=46.625;MQMR=0;NS=1;NUMALT=1;ODDS=71.1473;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=1761;QR=0;RO=0;RPL=4;RPP=75.3927;RPPR=0;RPR=44;RUN=1;SAF=48;SAP=107.241;SAR=0;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.Unkown=1   GT:DP:DPR:RO:QR:AO:QA:GL    1/1:48:48,48:0:0:48:1761:-146.278,-14.4494,0
chr1    53  .   AAGA    AA  419.777 .   AB=0.338462;ABP=32.4755;AC=1;AF=0.5;AN=2;AO=44;CIGAR=1M2D1M;DP=130;DPB=111.75;DPRA=0;EPP=26.8965;EPPR=133.905;GTI=0;LEN=2;MEANALT=1;MQM=32.5;MQMR=59.1512;NS=1;NUMALT=1;ODDS=96.6572;PAIRED=1;PAIREDR=1;PAO=2;PQA=17.5;PQR=147.5;PRO=6;QA=1548;QR=3122;RO=86;RPL=11;RPP=26.8965;RPPR=133.905;RPR=33;RUN=1;SAF=44;SAP=98.5551;SAR=0;SRF=86;SRP=189.757;SRR=0;TYPE=del;technology.Unkown=1    GT:DP:DPR:RO:QR:AO:QA:GL    0/1:130:130,44:86:3122:44:1548:-68.0762,0,-249.363
chr1    59  .   TATA    CATC    473.16  .   AB=0.311258;ABP=49.7329;AC=1;AF=0.5;AN=2;AO=47;CIGAR=1X2M1X;DP=151;DPB=157.25;DPRA=0;EPP=31.8863;EPPR=141.331;GTI=0;LEN=4;MEANALT=2;MQM=33.2128;MQMR=59.5922;NS=1;NUMALT=1;ODDS=108.949;PAIRED=1;PAIREDR=1;PAO=1;PQA=34;PQR=238;PRO=11;QA=1736;QR=3827;RO=103;RPL=11;RPP=31.8863;RPPR=141.331;RPR=36;RUN=1;SAF=47;SAP=105.07;SAR=0;SRF=103;SRP=226.672;SRR=0;TYPE=complex;technology.Unkown=1   GT:DP:DPR:RO:QR:AO:QA:GL    0/1:151:151,47:103:3827:47:1736:-77.0853,0,-316.75
```

If I set `--max-coverage 48`, the first variant is removed, but I assume that this parameter should remove the others. Could it be a bug?

**Comment by ekg** [comment]
This looks like a bug. You are using the most recent git HEAD?

**Comment by magicDGS** [comment]
I clone the repository and install it today, so I think so. Just in case, it is version _v1.0.2-6-g3ce827d_ (although the latest commit in my local copy is 3ce827d8ebf89bb3bdc097ee0fe7f46f9f30d5fb, and it is not reflected in the version string).

**Comment by ArynWilder** [comment]
I'm having this issue as well (version v1.0.2-6-g3ce827d). Using the --max-coverage option gives an empty vcf. If I omit the --max-coverage option, freebayes gets stuck in badly aligned regions with thousands of reads that should be skipped over.

**Comment by ekg** [comment]
I think the feature is broken, and it is not easy to implement in the
current design. It can help some, but there is already a problem with high
depth, but depths in the millions, not thousands are the issue. I need to
fix this, but so as to not get stuck waiting for me, here is what I would
do, and typically do already to handle this issue:

You may be running into another problem. Freebayes is trying too many
alternate alleles in these sites. Set --use-best-n-alleles to something
reasonable, like 6, and try running the region again.

If depth is a problem, I'd suggest explicitly excluding regions that you
don't think you can call on. You can do this by generating a callable set
of regions by looking at coverage and average mapping quality, then using
bedtools to generate the inverse of this and call on it.

**Comment by ArynWilder** [comment]
Thanks. I found another one of your posts that suggests using the --use-best-n-alleles option and that seems to be doing the trick.

**Comment by nh13** [comment]
@magicDGS could you provide the input BAM and reference (build for human)?  I'd be happy to try to help out on the original issue since it was my commit originally (https://github.com/ekg/freebayes/commit/41f68a131b6348f7e9c669387e5cae2bc58b0ce9)

**Comment by nh13** [comment]
@ekg @magicDGS I think the issue is here https://github.com/ekg/freebayes/blob/master/src/freebayes.cpp#L185-L187, where we skip the site if the sample coverage is **less than** the maximum coverage.

This was not in the original commit: 41f68a131b6348f7e9c669387e5cae2bc58b0ce9
It was in merge (with conflicts) here: 96e85182c4cd1c462cf49ca06b858da8c7b99c44

The original intention of my commit was to downsample (randomly) to the maximum coverage at sites with too much coverage.  @ekg was your 96e85182c4cd1c462cf49ca06b858da8c7b99c44 commit meant to just skip sites with too much coverage in any sample, or is this a merge bug?

**Comment by magicDGS** [comment]
I also think that the problem is in there, when skipping positions with huge coverage, but I'm not an expert in c++.

Sorry, @nh13, I don't have the BAM file anymore because it was part of a test from a colleague and he remove it. If you need one to test it, I can generate a small input that generates the problem with the version that I have installed.

**Comment by ekg** [comment]
@nh13 this is a merge bug!

**Comment by nh13** [comment]
@ekg I don't like the way I have implemented this feature, and perhaps you can suggest a better way.  Currently, it post-filters the alleles to randomly remove alleles some until it sufficiently reduces the coverage level.  I want two things:
1. To not add alleles past the maximum before every adding it to any list or map (`AlleleParsers.cpp`?).  I wonder if this would further speed up freebayes as it avoids even more parsing.
2. An option to skip sites with too much coverage, and an option to down-sample at sites with too much coverage (I implemented the latter originally, and adding `skip = true` does the former).
@ekg any advice you could offer?  It seems pretty trivial.  You could also wire in `--min-coverage` too.

**Comment by claudiuskerth** [comment]
@nh13 `--max-coverage` is as you describe above downsampling reads on sites with coverage above threshold: 
> ...
>position: Contig_1:2 coverage: 245
coverage 245 for sample par_34-9 was > 25, so we will remove 220 genotypes
coverage for sample par_34-9 is now 25
getting genotype alleles
> ...

However, that is conflicting with the description of this flag: "Do not process sites with greater than this coverage." I think at least the documentation needs to be updated. Filtering sites based on excessive coverage can also be done before or after running `freebayes` as Eric mentioned above, but If you asked me, I would like it if `freebayes` could do that for me :-) 

claudius
