### ISSUE TITLE
VCF output not compatible with bcftools norm

### ISSUE THREAD

**Issue by darked89** [freebayes/freebayes#261]
I have run freebayes v1.0.2-6-g3ce827d-dirty on Linux Lubuntu 15.10, gcc 5.2.1:
```
freebayes -f ../genome/hs37d5.chr_only.fa --region 2:62034413-62036413 test1.bam > test1.vcf

# normalize with bcftools

bcftools  norm -m-both -c w  -f ../genome/hs37d5.chr_only.fa  test1.vcf
# the error:
# bcftools: vcfnorm.c:610: split_format_numeric: Assertion `nvals==(src->n_allele-1)*nsmpl' failed.
```
The test1.vcf contains line triggering it:
```
2   62035409    .   ATTTTTTTTTTTTTTTTG  ATTATTTTTTTTTTTTG,ATTTTTTTTTTTTTG   556.155 .   AB=0.204545,0.340909;ABP=36.372,12.6832;AC=1,1;AF=0.5,0.5;AN=2;AO=9,15;CIGAR=3M1X1D13M,1M3D14M;DP=44;DPB=51.6111;DPRA=0,0;EPP=3.25157,3.15506;EPPR=3.0103;GTI=0;LEN=17,3;MEANALT=10,10;MQM=58.2222,60;MQMR=57.25;NS=1;NUMALT=2;ODDS=32.2525;PAIRED=1,0.933333;PAIREDR=1;PAO=11.6667,5.66667;PQA=406.667,174.667;PQR=174.667;PRO=5.66667;QA=277,444;QR=132;RO=4;RPL=7,11;RPP=9.04217,10.1038;RPPR=5.18177;RPR=2,4;RUN=1,1;SAF=4,8;SAP=3.25157,3.15506;SAR=5,7;SRF=3;SRP=5.18177;SRR=1;TYPE=complex,del;technology.Illumina=1,1   GT:DP:DPR:RO:QR:AO:QA:GL    1/2:44:44,9,15:4:132:9,15:277,444:-61.1446,-24.7609,-18.7955,-37.7655,0,-33.0759
```

If I manually split this line into two preserving all values from columns >5: 
```
2 62035409 . ATTTTTTTTTTTTTTTTG ATTATTTTTTTTTTTTG <snip>
2 62035409 . ATTTTTTTTTTTTTTTTG ATTTTTTTTTTTTTG <snip>
```
it makes bcftools running without the error. So my guess is that for such calls either freebayes VCF lacks some values needed by bcftools. Or there is some VCF versions mix up.

Many thanks for writing the freebayes.

Darek Kedra

edit: markdown formatting fixes

**Comment by hguturu** [comment]
I get a different error, but also with norm:
[E::vcf_parse_format] Invalid character '.' in 'QR' FORMAT field at 1:10001
The problematic line is
1	10001	.	A	<*>	0	.	DP=367;END=10176;MIN=41	GQ:DP:MIN:QR:QA	1.88567e+06:367:41:1.9267e+06:41025.2

This is the output of freebayes with --gvcf --genotype-qualities --gvcf-chunk 100000 --min-mapping-quality 50 

Additionally, it would be nice to have freebayes output be valid with the more stricter bcftools since we currently cannot stream freebayes output into bcftools due to the contig names not being output in the header.

**Comment by darked89** [comment]
This seems to be fixing the problem:
#from latest vcflib: 
vcfbreakmulti my_freebayes.vcf > my_freebayes.multibreak.vcf

#bgftools/htslib 1.3.1
bgzip -i my_freebayes.multibreak.vcf
# creates my_freebayes.multibreak.vcf.gz &  my_freebayes.multibreak.vcf.gz.gzi 

bcftools norm -m-both  -c w -O z -f genome.fasta -o  my_freebayes.multibreak.norm.vcf.gz my_freebayes.multibreak.vcf.gz 

#index it for downstream processing
bcftools  index my_freebayes.multibreak.norm.vcf.gz

So far no errors reported during these steps, plus the output looks sane. 

Hope it helps

DK
