### ISSUE TITLE
freebayes-parallel usage

### ISSUE THREAD

**Issue by ml4wc** [freebayes/freebayes#262]
Line 22: echo "    bamtools coverage -in aln.bam | coverage_to_regions.py ref.fa**_# .fai_** 500 >ref.fa.500.regions"

Need to change the usage to reflect that the input uses an index, not fasta.

**Comment by tseemann** [comment]
Also note that `fasta_generate_regions.py` also needs the `.fai` file.

**Comment by ekg** [comment]
I thought it had been updated to find the fai file automatically.

At this point I should note the existence of bamprofile -e [number of
alignments].

https://github.com/ekg/bamprofile

You can provide a number of alignments and it will emit an region every
time it sees this many alignments. The result are regions which have
exactly the same number of alignments in them.

If you are doing a study this provides a way to ensure that the runtime per
region is approximately the same. You can also filter out extremely short
regions as a way to remove overly high coverage regions. Perhaps I should
add this as an option.

The idea is that you can take a random or representative sample of the
alignment data and use it to generate this calling map.

**Comment by stsmall** [comment]
Hi,
Sorry for naive question, but if I desired to use bamprofile (as you suggest) to place a coverage limit on my regions would the command be something like: 
bamprofile -f ref.fa -e 500 -b aln.bam | coverage_to_regions.py ref.fa.fai 500 >ref.fa.500.regions

**Comment by ml4wc** [comment]
Are gVCFs supported by parallel, does it stitch properly??
