### ISSUE TITLE
Does --use-best-n-alleles  apply to primitive alleles (snp/ indels) or longer combinations of alleles?

### ISSUE THREAD

**Issue by NeillGibson** [freebayes/freebayes#265]
Hi, 

Does --use-best-n-alleles apply to primitive alleles (snp/ indels) or to  longer combinations of primitive alleles? 

For SNP's there are of course just 4 possible alleles (A,C,G,T). For indels there are already much more possible alleles but if you look at longer combinations of primitive alleles there are again much more possible different alleles. 

Therefore I am not really sure what is good cutoff is for this argument in complex and large populations that has a lot of allelic diversity.  I would like to use a number that  excludes false positive alleles in bad maping quality / excessive depth regions but doesn't exclude real alleles. 

What is a sensible number for this argument in complex populations with a lot of allelic diversity?
Or is there are way to guess / determine this?  
Does the species / type of population change what a good number is for this argument?

Thank you.

**Comment by tseemann** [comment]
Also, it is affected by the `--haplotype-length N` option?
