### ISSUE TITLE
Multi-Sample Variant Calling in Tumor only samples

### ISSUE THREAD

**Issue by juliandangelo** [freebayes/freebayes#269]
Hi @ekg ,

I am currently looking to do joint variant calling for ~1450 tumor only samples. I split the process into 10  batches of about 145 and used Freebayes to generate GVCFs for each process. I did the gvcf step in hopes of being able to merge into one large GVCF and then genotype the large gvcf to output a single large VCF across all of my samples. I looked at the thread: https://github.com/chapmanb/bcbio.variation.recall/issues/9 and https://github.com/ekg/freebayes/issues/228 and saw the solution using bcbio.variant.recall in a way analogous to the GATK best practices pipeline for joint variant calling but am wondering if you have had any further developments to be able to use Freebayes to do either do a GVCF merge to create one large GVCF and then do genotyping on the large GVCF to return a VCF, or to just do genotyping on each of the generated GVCFs from each batch of my process?

Please let me know if I need to clarify anything.

Regards,
Julian

**Comment by ekg** [comment]
Hi Julian,

We lack PLs/GLs on the gVCF records and also the experience of taking the
output of freebayes through the process of the merge.

Otherwise it should be nearly ready for what you want to do.

I remain cautious about gVCF.  If you have the samples available at the
same time I would take another route. For 1400 it would not be hard to do a
single joint call.

Erik

**Comment by kevin3** [comment]
Hi @ekg if I have 1500 WGS samples with both illumina and ion torrent data, do you reckon if I can merge all of these into chromosomal bams and do single joint calls per base? 
would the computational resources required be too intensive to make this a herculean task?

**Comment by aslam24** [comment]
Hi @ekg i am a junior bioinformatician and I am looking for parameters to run panel of tumor only samples for free bayes. If possible can you please share the specific parameters in freebayes to run on only somatic data?
