### ISSUE TITLE
What is the format for the --populations input?

### ISSUE THREAD

**Issue by j-a-thia** [freebayes/freebayes#271]
How should the input file be structured? 

The --help doesn't have enough information and couldn't find any details online.

Tried using the following structures:
`[path to BAM file]--tab--[population ID]`
`[path to BAM file]--space--[population ID]`

But get the error:
`unable to open population file: ./variants/freebayes/fb_pops`

Many thanks!
~ j-a-t

**Comment by ekg** [comment]
I can't remember. I think it maps from population name to sample name or
the reverse, not BAM files. Also the error suggests another problem reading
the file than it's format.

**Comment by estolle** [comment]
@j-a-t  did you resolve the issue? I am having the same difficulties to find out which exact format the populations file has to have. I tried several combinations thus far, several separators. Its also unclear if the file should contain samplenames according to which RG tag: ID or SM?

**Comment by j-a-t** [comment]
@estolle -- sorry for slow reply.

I never figured this out. :(

**Comment by stsmall** [comment]
With me it works as:
SAMPLE_NAME\tPOPULATION\n
#note that the sample_name needs to be the same one as in the RG of the bam and you still need to pass the bam files which I do with the bam list option (the text files contains 1 file per line with the full path). Hope that helps.

**Comment by ekg** [comment]
This is correct. Sorry I missed this earlier.

**Comment by estolle** [comment]
oh great, thanks alot for this info!

**Comment by hzpc-joostk** [comment]
FYI. 

After inspecting the source (just to be sure), I found the part parsing the population file [AlleleParser.cpp:229-236](/ekg/freebayes/blob/61527c5fb3d9dd9d060c3ea31ea63d237be7fe65/src/AlleleParser.cpp#L229-L236).

It should be a tab `\t` delimited file with sample IDs (`@RG/SM`) and population name/IDs:

| sample ID | population ID |
|-----------|---------------|
| SampleX   | PopulationA   |
| SampleY   | PopulationA   |
| SampleZ   | PopulationB   |

Samples other than those listed in the population file, [will be assigned](https://github.com/ekg/freebayes/blob/61527c5fb3d9dd9d060c3ea31ea63d237be7fe65/src/AlleleParser.cpp#L249) to a default population "DEFAULT".

Extending the `--help` message just a little bit resolves this issue. Take `--cnv-map` as an example.

```
Read population map from tab delimited FILE, which assigns
samples to a population:
    sample name, population
```

Probably somewhere in the `--help` should be defined that "sample name" refers to the value of `SM` in the `@RG` line of the BAM header. 😉
