### ISSUE TITLE
changing default parameters (entropy, partial observations, min alt count and fraction)

### ISSUE THREAD

**Issue by ekg** [freebayes/freebayes#272]
In recent months there have been numerous issues where calling issues can be resolved by some combination of the following changes to the parameters:
- Adding `--min-repeat-entropy 1`, which requires that we reach 1 bit (shannon) per base of entropy in the haplotype window that we call across when we begin the haplotype in a small repeat. This catches a huge fraction of issues related to local misalignment, as these almost invariably occur where sequence entropy is low.
- Adding `--no-partial-observations`, which causes freebayes to only consider observations that completely cover the haplotype window that's used during calling.
- Changing the `--min-alternate-fraction` to something sensible for the given ploidy, or dropping it lower than the default even for diploids. By default we require 20% of the observations in one sample to support an alternate to consider it. I find this extremely restrictive, and it's cutting off a lot of the tail of lower quality calls; many of them may be true. In diploids, I've been testing at `--min-alternate-fraction 0.1`, and would consider even removing it in favor of simply using `--min-alternate-count 2` as the only pre-filter. At very least, I think it should be adjusted based on the `--ploidy` setting that's used.

To test these I'm considering setting up a CI kind of testing process, where we call against the Genome in a Bottle set. @chapmanb has a test harness for exome sequencing, and having his independent assessment in the past has been very helpful, but perhaps there is a way we could set this up. Perhaps @mlin has an idea, as we are doing something similar with vg.

I'm very curious what others in the community think. I've held of changing these for a long time, but it's become clear that they should be refreshed in light of common practice and resolution of basic problems.

**Comment by ekg** [comment]
I've been in touch with several people recently who couldn't share example data due to institutional access policies :cry: . I'll try to outline one issue here. Hopefully they can jump in and confirm what I'm describing.

In one case, we miss an 8bp somatic indel. It is at low frequency in the sample, maybe 15%, and the call is made using `--ploidy 50` to catch low frequency variants.

Here was the failing call:

```
freebayes --fasta-reference human_g1k_v37.fasta \
    -b NameRedacted.final.bam \
    -m 10 -q 20 -U 5 -Q 10 \
    -t bedfile.bed -v NameRedacted.vcf \
    -p 50 -D 0.3 \
    --min-alternate-fraction 0.01 \
    --min-alternate-count 2 \
    --use-best-n-alleles 3
```

The call was missed. It still isn't completely clear to me why this happened. However, new target defaults resolve the situation, with this producing the expected call:

```
freebayes -f ~/ref/hs37d5.fa deidentified.bam \
    --min-alternate-fraction 0.01 \
    --min-repeat-entropy 1 \
    --no-partial-observations \
    --pooled-discrete \
    -p 50
```

Here, adding `--min-repeat-entropy 1` and `--no-partial-observations` made the difference.

Another non-ergonomic thing is the way that pooled calling and somatic calling are specified. These should be updated as well. We should be able to say `---somatic`, `--pooled-known-ploidy`, and `--pooled-unknown-ploidy`. This isn't super critical now but should be considered going forward.

**Comment by tseemann** [comment]
What's the motivation for setting `-p 50` (ploidy) ?

**Comment by ekg** [comment]
It allows a kind of frequency-based detection that still uses the bayesian
model.

**Comment by ekg** [comment]
To further explain, it's as if we are determining frequency in bins of 2%. The resulting "genotypes" tell us how many copies of each allele we expect. I actually like this method, as it allows us to continue using the model, rather than throwing it out as is the case with `--pooled-continuous`. It means we get meaningful quality scores, which can be helpful. It's interesting because users have gravitated to this via testing but it wasn't something I expected to be ideal up front.

**Comment by chapmanb** [comment]
Erik;
Thanks for this. A CI-style server that runs callers against multiple truth sets on a regular basis would be spectacular. I'm happy to help with this effort. We can do these validations now with bcbio but not in an automated way, so helping move to that would be a nice step forward. Generally the more transparency we can have on options the better we'll do as a community on calling variants.

The specific example of `-p 50` is something I haven't tried. Do you think this would help with FreeBayes somatic calling of low frequency variants? Currently we add these somatic-specific options: https://github.com/chapmanb/bcbio-nextgen/blob/4689e0bc40768b5b8a4a8c3ceadadfce80aa3164/bcbio/variation/freebayes.py#L58. So for calling at 5% this adds:
```
--pooled-discrete --pooled-continuous --report-genotype-likelihood-max --allele-balance-priors-off --min-alternate-fraction 5.0
```
Would you recommend a `-p` setting as well? How do you pick this relative to the frequency? The example above is `100 / (allele fraction * 2)` but not sure if that's a general rule. I'm happy to try it out on the somatic benchmarks we have.Thanks again for this discussion.

**Comment by mlin** [comment]
I can certainly provide infrastructure for continuous integration/validation as needed, along the lines we've set up for [vg](https://github.com/dnanexus-rnd/dxvg) or [viral-ngs](https://github.com/dnanexus/viral-ngs). As you all know I'm severely slammed for the next couple of weeks, but theoretically have more bandwidth after that! :P

The general shape would be to extend the .travis.yml to perform a larger test workflow (perhaps on chromosome 21, or even whole-genome on certain branches) in addition to the basic unit test suite. This would run freebayes-parallel on a pre-staged BAM file, use a tool like rtgeval to compare the resulting VCF against NIST's, then assert some sanity checks on those metrics. Since it may be impractical to do all that within the Travis environment, we can instead use Travis to remote-control DNAnexus, as in those examples.

**Comment by brendanofallon** [comment]
More than happy to contribute lots of simulated data sets to supplement the GiaB data for CI. The simulated data are stratified by variant type (insertions, deletions, duplications, etc...), size, depth & zygosity, and might help to pinpoint errors that crop up only in specific configurations.

**Comment by brendanofallon** [comment]
FWIW, I recently created a bunch of simulated fastqs and truth VCFs that might be handy for CI, check out https://github.com/brendanofallon/varcomp/tree/master/data/. There are data for both hg19 & GRCh38, hets, homs, high & low depth, for multiple variant types and sizes. I think the layout should be pretty straightforward, but let me know if you have any questions.

**Comment by ekg** [comment]
This is still outstanding. Any thoughts about defaults which we should set?

**Comment by MartenHoogeveen** [comment]
I see this issue is still open. I just started using freebayes so I am not an expert but I do have a question. You sure ```-min-repeat-entropy 1``` would be better then ```-min-repeat-entropy 0```?
Because if I use ``-min-repeat-entropy 0``` the ```DP``` value for a deletion is similar as the dept of the surrounding bases that I check with samtools depth. If I use ```-min-repeat-entropy 1``` the ```DP``` value is much lower then the dept I see with samtools.

**Comment by ekg** [comment]
This is because the depth is the number of reads spanning the entire
haplotype window that's called. This means there will be fewer reads, but
the observations will be complete.

**Comment by MartenHoogeveen** [comment]
I can open a new issue if that is better. But I calculate the frequency by doing ```AO/DP```. The frequency value changes if I change the ```-min-repeat-entropy``` parameter. Would you in this case recommend ```-min-repeat-entropy 0``` or ```-min-repeat-entropy 1```. At this moment ```-min-repeat-entropy 0``` makes more sense to me. (I don't use the QUAL score for something)

**Comment by ekg** [comment]
I would say test both ways and use some external validation to determine
which works for your application.

**Comment by tseemann** [comment]
`-min-repeat-entropy 1` reduces false positive calls for me in bacterial variant calling.
