### ISSUE TITLE
data sharing and consultation policy

### ISSUE THREAD

**Issue by ekg** [freebayes/freebayes#273]
Recently there has been a sharp increase in the number of researchers and diagnostic labs who are contacting me directly via email. In many cases they do so because they are unable to share data or details of their experiment. This is a problem for me, because my funding requires that I work in the open, but it has wider-reaching consequences that this arrangement acknowledges.

The lack of data sharing is a very serious issue that has extremely negative consequences for patients receiving diagnostic care via NGS approaches. Imagine two patients with the same condition have their data processed through freebayes or a similar tool at two different centers. The variant responsible for their condition is hard to detect under default parameters in the methods that the diagnostic labs are using. In one case, the diagnostic lab contacts me and we resolve the problem. In the other, a member of the lab searches through these issues and the freebayes mailing list, but does not find a solution in the time they have available to work on the problem, and they do not have time to contact me.

If the problem and resolution that allows the detection of a particular type of variant is communicated only in private, then there is no chance that the second patient will benefit from the diagnosis of the first. In some cases this could have severe health consequences. I do not want to be responsible for these kinds of mistakes. Only by bringing a discussion of the issues involved into the open can we hope to resolve this kind of error. I doubt that anyone seeking insight into their medical condition would prefer diagnostic failure to data sharing. In their interest, and that of the researchers working on these problems, we need to be able to share.

How will I resolve this issue? For one, I will request data in a format that can be made public before providing off-channel support, so that we can move the discussion into the open without issue. If this isn't possible, I will be happy to help but will need to do so under a contracting arrangement that acknowledges the proprietary nature of the support.

In virtually all cases, we can obsfucate the origin of the data and still retain data that is instructive for development purposes. For instance, we can remove the positional information from a VCF file, if that's what's shared, and remove reference to the reference allele. Or, we can scramble the bases in the BAM, a fragment of the reference, and the output VCF in such a way that we can still reproduce the problem. These measures are not ideal, as freebayes does care about the sequences in the analysis.

I am writing about this publicly in the hopes that others comment. What do you think? How should the developers of freebayes handle this issue?

**Comment by tseemann** [comment]
All the clinical genomics initiatives in Australia use GATK, and the NHS in the UK has a license to GATK.

I am surprised that Freebayes is being used in a clinical environment, given it is not published (not a bad thing in my book, but accreditation wouldn't like it) and has some issues/bugs (admitted by yourself), and that it is starved of resources (essentially just you and not full time!).

Contacting you puts an amazing amount of pressure on, given that the results may have medical outcomes for real patients. Although it's an amazing source of "test data cases" it is just not sustainable.

I would think some of your ideas around obsufcation would be sufficient, but often there is no scope for negotiation with human clinical samples.

**Comment by ekg** [comment]
> I am surprised that Freebayes is being used in a clinical environment, given it is not published (not a bad thing in my book, but accreditation wouldn't like it) and has some issues/bugs (admitted by yourself), and that it is starved of resources (essentially just you and not full time!).

I know from communication that it is widely used even in a clinical context. I'm also certain that most of the time we don't hear anything from its users, so I have little grounds to estimate the breadth.

Correct me if I'm wrong, but my what I understood from discussions with people implementing NGS pipelines, the FDA accreditation process seems to only care about documentation of process and demonstration of its effectiveness. For comparison, the GATK versions that are in current used are similarly unpublished and this seems to present no problem to their use. And there are a number of systems that such pipelines rely upon which aren't completely documented, including for example the sequencing and sample prep, which are fundamentally proprietary.

As for bugs, the zygosity mis-calling with the current defaults is concerning, but otherwise I am not aware of anything severe enough to prevent use in such a setting. Further, even here we are not talking about something fundamentally broken in freebayes, but default parameters which are not correct for particular applications. In this case, we see that the current defaults are optimal for low-coverage sequencing and genotype likelihood estimation, but that's not correct for high-coverage sequencing, which seems increasingly standard. It would seem that the validation processes required to set up clinical pipelines oriented towards detecting particular alleles will suss out these issues.

> Contacting you puts an amazing amount of pressure on, given that the results may have medical outcomes for real patients. Although it's an amazing source of "test data cases" it is just not sustainable.

I agree that free support for proprietary interests is unsustainable. If groups are willing to share test data, then there is not a problem and there are plenty of people who are willing to lend a hand.

> I would think some of your ideas around obsufcation would be sufficient, but often there is no scope for negotiation with human clinical samples.

This is similarly unsustainable, and I would like to do what I can to change the situation. As I've described, one solution would be to tax groups who refuse to support open science, but it is also a difficult situation for me because I don't want to withhold support that could improve an outcome for a patient. This is the pressure you refer to.

@tseemann thanks for your comments, hopefully others will chime in. I'm curious what the group thinks.

**Comment by chapmanb** [comment]
Erik and Torsten;
Thanks for the helpful discussion. I agree with Erik's approach. We need more organized, openly available test cases that exercise variant callers in difficult regions, but consent and privacy are huge barriers. I wonder if we could gain some traction by having these available on cloud resources under standard access agreements so the data is protected but available. The Cancer Genomics Cloud seems like a good model for this. This set of validation series from Nazneen Rahman's group (http://f1000research.com/articles/5-386/v1) is a nice example of having a set of organized test examples with truth sets. If it were available to a validation CI server and also for users to test methods in a lightweight way, that would be a big help to improving transparency and also serve as a framework for adding new cases.

The only way to have a useful discussion around improving clinical utility of variant calling tools is with these type of truth sets. As Erik mentions, the devil is in the details, and the more transparent and open we can be about discovering and improving the hard parts the more we can move forward. There are several good callers and I'd love to move the conversation around using these from publication status, which is a terrible metric for determining how a caller will do in your particular use case, to open and transparent validations.
