### ISSUE TITLE
IUPAC code Freebayes

### ISSUE THREAD

**Issue by robgilt** [freebayes/freebayes#275]
Hi,
 I am running FB with ploidy set for 4. I am using some reference sequence that has a lot of non ATGC characters like R, W, M, K,  S, Y etc which represent a combination of nucleotides (IUPAC code). For example R can be  A or G.  I am able to generate a BAM file index the reference through samtools. When it comes to finally running the Freebayes algorithm, it throws an error telling me that there are non atgc letters, asking me to further check my reference sequence. If I just replace one of these nucleotides (R) with A or G, then I am missing that SNP detection. Is it possible to add few lines to code, that would help Freebayes to recognize the IUPAC codes?

Thank you,
Rob.

**Comment by tseemann** [comment]
I am not the author of freebayes but my on first glance I would think this would be a lot more than a few lines of code. The model would utilise the reference base itself, and if you had ambiguous reference bases this would require a different type of model. But this is just a guess, i'll let @ekg chime in.

**Comment by ekg** [comment]
Actually it might only be a few lines. There is one spot where we check if
the reference is in ATGCN. However the simple fix will call all these sites
as SNPs, which may not be what you want. The right solution is to use a
graph reference system as in vg. Surely it is not only SNPs that occur, and
IUPAC codes provide no mechanism for representing any other kind of
polymorphism. VG provides a generic technique to deal with precisely this
issue.

**Comment by tseemann** [comment]
What about options like `-use-reference-allele` and `--min-alternate-fraction` ?

**Comment by ekg** [comment]
I believe it would just work. However, I can't stress enough that I am
working on precisely the answer to this problem in vg and do not think it
would be a good idea to fix here.

**Comment by robgilt** [comment]
@ ekg @tseemann , I do not know if VG you are mentioning here is an option of FB or sth else? I can try one of the options mentioned by @tseemann using --use-reference-allele and --min-alternate-fraction and --min-alternate-count, to see if the detection is appropriate. I am hoping this would be something like a user option whether to choose a degenerate reference sequence or a regular reference sequence. Thank you for your answers. Looking forward for a good solution. This could be a lot more useful if the reference sequence given can be opted as degenerate. 

Thank you,

**Comment by robgilt** [comment]
@ekg @tseemann : I tried with the option mentioned above: It does not work. The same error repeats. It does not have a problem with N, but with others it does. Here it is as follows: 
ERROR(freebayes): Found non-DNA character R at position 60 in Seq_chr1_10000-15000
. Is your reference compressed or corrupted? freebayes requires an uncompressed reference sequence.

**Comment by beechwood13** [comment]
I have no idea, how many lines of code would be needed, but it would really be nice, if a future version of FB could recognize and properly handle  ambiguity codes in the reference sequence.
Ambiguity ("IUPAC") codes in reference sequences often represent real situations (e.g. if the reference is a consensus sequence from  populations or heterozygotic lines) - and they indicate potentially variant positions.
The error mesage:

ERROR(freebayes): Found non-DNA character W at position 50 in chr1
. Is your reference compressed or corrupted? freebayes requires an uncompressed reference sequence.

is annoying. "W"  of course IS a DNA-character: It represents either "A" or "T"

One solution is to replace all ambiguity codes in the references by one of the constituent nucleotides.
Seqtk randbase can do this job.
E.g:

more test.fasta
>test
AGTCAACTWAMKSSMMMMMMMWWWWWWWWWWWSSSSSSSSSSSSSSSSS

seqtk randbase test.fasta
>test
AGTCAACTTACTGGCCCACCAAAATATTTAAACCGCCGCCGCCGGGGCC

A nice Python script for the same task can be found here:  
 https://genomicislands.wordpress.com/2014/06/27/converting-ambiguity-codes-in-fasta-files/

**Comment by lfaller** [comment]
Hi all,

I am new to FreeBayes and was trying to run it on a yeast strain where the reference contains a few non-ATGC characters.

Does anyone have a recommendation how to best treat this situation? 

Would you suggest to use the Variant Graph approach as opposed to FreeBayes?

Thanks for any insight!
~Lina

**Comment by beechwood13** [comment]
Hi Lina,
You can replace the ambiguity codes in your reference fasta file using the Python script  to be found at : 

https://github.com/markravinet/convert_ambiguity_codes

The original script named as "convert_ambiguity.py" only replaces two letter ambiguity codes (S,W,R,Y,K,M)
and leaves three letter ambiguity codes (B,D,V,H) unchanged. (FreeBayes will still complain about these ...)
There is a fork script on the same  github pages  named as "replace_ambiguity_codes.py" that converts ALL non-ATG codes.

Otherwise, FB does a good job.

**Comment by donutbrew** [comment]
So, what is the current (v1.3.1) expected behavior for IUPAC ambiguity bases in the reference? I'm coming in late, but what I've observed is that those positions are ignored by freebayes. Is this what I should be seeing?

 I suppose the most straightforward thing is still to modify the reference ahead of mapping, but I also wondered if there are plans to deal with this internally within freebayes. 

Keep up the good work!

**Comment by ekg** [comment]
Please remove ambiguity codes from the reference. Replace them with an
appropriate base character.

If you need to include variation in your reference, use vg. That's the
whole point of genome variation graphs. You can do read mapping and variant
calling against a reference with any kind of variation in it.
