### ISSUE TITLE
gVCF: invalid entries at start of the chromosome

### ISSUE THREAD

**Issue by pstawinski** [freebayes/freebayes#276]
I'm having a problem understanding the gVCF file format created by freebayes. I'm simply running freebayes like:
`freebayes --gvcf --fasta-reference (...)/hg19.fasta -b (...).bam`
It works like a charm, but strange entries appears at the chromosome "boundaries" in the gvcf file. To show an example:

```
chrM    16521   .       C       T       3743.35 .       AB=0;ABP=0;AC=2;AF=1;AN=2;AO=139;CIGAR=1X;DP=143;DPB=143;DPRA=0;EPP=5.65044;EPPR=3.73412;GTI=0;LEN=1;MEANALT=2;MQM=55.5827;MQMR=53.3333;NS=
chr1    16522   .       C       <*>     0       .       DP=106;END=16571;MIN=71 GQ:DP:MIN:QR:QA 173165:106:71:173255:90
chr1    10001   .       T       <*>     0       .       DP=2;END=10053;MIN=1    GQ:DP:MIN:QR:QA 4394:2:1:4554:160
```

Please notice, that first chr1 entry has position 16522, which is very close to the size of the chrM...

Same thing is on other chr boundaries:

```
chr1    249240217       .       GTA     GTTA    0.192919        .       AB=0.6;ABP=3.44459;AC=1;AF=0.5;AN=2;AO=3;CIGAR=1M1I2M;DP=5;DPB=6;DPRA=0;EPP=3.73412;EPPR=3.0103;GTI=0;LEN=1;MEANALT=1;MQM=1
chr2    249240220       .       .       <*>     0       .       DP=0;END=249250621;MIN=1        GQ:DP:MIN:QR:QA 27243.9:0:1:27663:419.086
chr2    10232   .       C       <*>     0       .       DP=1;END=10285;MIN=1    GQ:DP:MIN:QR:QA 2663:1:1:2663:-0
```

Please notice the chr2:249240220, which is actually bigger then the size of chr2 . It ENDs at 249250621, which is the size of chr1...

Is it an expected behaviour? 

My Freebayes version is:

```
$ /mnt/zgmvol/environment/software/freebayes/bin/freebayes --version
version:  v1.0.2-16-gd466dde
```

I can provide both bam and full gvcf file if needed.

**Comment by ekg** [comment]
This is not expected, but is a bug. I think the workaround is to run one
job per chromosome using --region chr1 for instance. If this happens every
time we don't do that, then it should be easy to debug.

**Comment by pstawinski** [comment]
>  If this happens every time we don't do that, then it should be easy to debug.

I've tried on about 4 samples, each time hitting this issue.

Thank you for your fast response. I'll implement the workaround by now.
