### ISSUE TITLE
Freebayes calling the same variant twice

### ISSUE THREAD

**Issue by lskrbnek** [freebayes/freebayes#279]
I have a case where Freebayes is calling both a deletion and a SNP in one call, and then again calling the SNP as a separate variant:
# CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  amplicon

17  30264425    .   GCCTCCTCCTCCTCCTCCG GCCTCCTCCTCCTCCG,GCCTCCTCCCCCTCCTCCG    0   .   AB=0,0;ABP=0,0;AC=0,0;AF=0,0;AN=2;AO=25,11;CIGAR=1M3D15M,9M1X9M;DP=432;DPB=429.789;DPRA=0,0;EPP=3.79203,3.20771;EPPR=3.82887;GTI=0;LEN=3,1;MEANALT=9,9;MQM=60,60;MQMR=60;NS=1;NUMALT=2;ODDS=179.831;PAIRED=1,1;PAIREDR=1;PAO=8,8;PQA=290.333,290.333;PQR=290.333;PRO=8;QA=844,410;QR=13635;RO=382;RPL=24,11;RPP=48.9587,26.8965;RPPR=764.481;RPR=1,0;RUN=1,1;SAF=13,6;SAP=3.09716,3.20771;SAR=12,5;SRF=189;SRP=3.10125;SRR=193;TYPE=del,snp;technology.illumina=1,1 GT:GQ:DP:RO:QR:AO:QA:GL 0/0:160.002:432:382:13635:25,11:844,410:0,-68.2855,-1150.61,-103.098,-1146.24,-1189.65
17  30264434    .   T   C   7.08785e-14 .   AB=0;ABP=0;AC=0;AF=0;AN=2;AO=11;CIGAR=1X;DP=453;DPB=453;DPRA=0;EPP=3.20771;EPPR=3.71775;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=243.435;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=410;QR=16078;RO=442;RPL=11;RPP=26.8965;RPPR=719.911;RPR=0;RUN=1;SAF=6;SAP=3.20771;SAR=5;SRF=219;SRP=3.08891;SRR=223;TYPE=snp;technology.illumina=1    GT:GQ:DP:RO:QR:AO:QA:GL 0/0:137.873:453:442:16078:11:410:0,-99.1178,-1409.26

(command:
freebayes-parallel regions.txt 8 -f hs37d5.fa amplicon.bam --haplotype-length 3 --min-mapping-quality 20 --min-base-quality 20 --mismatch-base-quality -threshold 20 --pooled-continuous --min-alternate-count 8 --min-alternate-fraction 0.01 --read-max-mismatch-fraction 0.05 --read-indel-limit 3 --genotype-qualities --min-repeat-entropy 1 --allele-balance-priors-off )

Once the top call is broken up into one line per variant, and then normalized, the SNP call is shown to be duplicated, although with a slightly different variant allele frequency (because of the different depth calculation at positions 30264425 and 30264434)

vcfbreakmulti amplicon.vcf | bcftools norm -f ../etc/hs37d5.fa -
# CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  amplicon

17  30264425    .   GCCT    G   0   .   AB=0;ABP=0;AC=0;AF=0;AN=2;AO=25;CIGAR=1M3D15M;DP=432;DPB=429.789;DPRA=0;EPP=3.79203;EPPR=3.82887;GTI=0;LEN=3;MEANALT=9;MQM=60;MQMR=60;NS=1;NUMALT=2;ODDS=179.831;PAIRED=1;PAIREDR=1;PAO=8;PQA=290.333;PQR=290.333;PRO=8;QA=844;QR=13635;RO=382;RPL=24;RPP=48.9587;RPPR=764.481;RPR=1;RUN=1;SAF=13;SAP=3.09716;SAR=12;SRF=189;SRP=3.10125;SRR=193;TYPE=del;technology.illumina=1 GT:GQ:DP:RO:QR:AO:QA:GL 0/0:160.002:432:382:13635:25:844:0,-68.2855,-1150.61
17  30264434    .   T   C   0   .   AB=0;ABP=0;AC=0;AF=0;AN=2;AO=11;CIGAR=9M1X9M;DP=432;DPB=429.789;DPRA=0;EPP=3.20771;EPPR=3.82887;GTI=0;LEN=1;MEANALT=9;MQM=60;MQMR=60;NS=1;NUMALT=2;ODDS=179.831;PAIRED=1;PAIREDR=1;PAO=8;PQA=290.333;PQR=290.333;PRO=8;QA=410;QR=13635;RO=382;RPL=11;RPP=26.8965;RPPR=764.481;RPR=0;RUN=1;SAF=6;SAP=3.20771;SAR=5;SRF=189;SRP=3.10125;SRR=193;TYPE=snp;technology.illumina=1    GT:GQ:DP:RO:QR:AO:QA:GL 0/0:160.002:432:382:13635:11:410:0,-103.098,-1189.65
17  30264434    .   T   C   7.08785e-14 .   AB=0;ABP=0;AC=0;AF=0;AN=2;AO=11;CIGAR=1X;DP=453;DPB=453;DPRA=0;EPP=3.20771;EPPR=3.71775;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=243.435;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=410;QR=16078;RO=442;RPL=11;RPP=26.8965;RPPR=719.911;RPR=0;RUN=1;SAF=6;SAP=3.20771;SAR=5;SRF=219;SRP=3.08891;SRR=223;TYPE=snp;technology.illumina=1    GT:GQ:DP:RO:QR:AO:QA:GL 0/0:137.873:453:442:16078:11:410:0,-99.1178,-1409.26
Lines total/modified/skipped:   3/2/0

The second SNP call is the more "correct", in terms of variant allele frequency, and the CIGAR is also more concise. Is there some way to tell Freebayes not to find the SNP call as part of the first variant?

**Comment by selkovjr** [comment]
This happens when a haplotype is truncated at read ends. 

![image](https://user-images.githubusercontent.com/465640/36686645-b697962a-1aec-11e8-8cc7-d772d716ed5a.png)

Strictly speaking, is not a freebayes problem. It is a feature of hybridization capture exacerbated by the shortcomings of common alignment algorithms. The same happens with long deletions. VAF estimation is only reliable (sort-of) for small variants. The higher the fraction of reads carrying an incomplete variant, the higher is the VAF error (and the VAF of spurious calls)

Freebayes just registers what it sees.
