### ISSUE TITLE
Allele Frequency from Freebayes is not matching with allele frequency observed in IGV and bamfile

### ISSUE THREAD

**Issue by BhaktiLimaye** [freebayes/freebayes#288]
Hello Dr. Erik,

I am using Freebayes (v1.0.2-16-gd466dde) for indel calling. 
trusight_myeloid panel. We have not done mark-duplicate step as we are dealing with amplicon panel. The aligner used in Novoalign.

I Have some questions regarding the observation about the indels which are called by freebayes.

I used following command for freebayes:

freebayes --use-duplicate-reads --min-alternate-count 10 --min-alternate-fraction 0.03 --min-coverage 10 --min-base-quality 20 --min-mapping-quality 30 --min-supporting-allele-qsum 20 --min-supporting-mapping-qsum 30 --min-alternate-qsum 40 -b main.bam -f hg19.fasta -v freebayes_raw.vcf

I got one variant which is of 52 bp deletion. But the VAF which I am getting is low as compared to IGV.

The VCF record for freebayes run:
chr19   13054564    .   AGCAGAGGCTTAAGGAGGAGGAAGAAGACAAGAAACGCAAAGAGGAGGAGGAGG  AG  0   .   AB=0;ABP=0;AC=0;AF=0;AN=2;AO=125;CIGAR=1M52D1M;DP=2648;DPB=2526.76;DPRA=0;EPP=274.444;EPPR=4725.98;GTI=0;LEN=52;MEANALT=138;MQM=70;MQMR=70;NS=1;NUMALT=1;ODDS=2377.57;PAIRED=1;PAIREDR=0.980302;PAO=0;PQA=0;PQR=0;PRO=0;QA=2914;QR=70597;RO=2183;RPL=0;RPP=274.444;RPPR=4725.98;RPR=125;RUN=1;SAF=125;SAP=274.444;SAR=0;SRF=2183;SRP=4743.33;SRR=0;TYPE=del;technology.illumina=1   GT:DP:RO:QR:AO:QA:GL    0/0:2648:2183:70597:125:2914:0,-432.548,-6091.33

So here VAF i.e varaint allele frequency is 125/2183+125 = 0.054159445 

But if I observe this variant in IGV, the VAF = 0.272363636
IGV results: Del: 749 , Total: 2750. Please also find attached snap shot.

Why there is a discrepancy in the VAF as compared to freebayes VCF record and IGV ?

I have also reviewed the base quality of supporting base position i.e. 13054564 and 13054617 using mpileup.  I have considered those read who have the above mentioned 52bp Deletion for mpileup run.
The count of reads which has 52bp Deletion and also having supporting base quality above 20, is near to 700 which is similar to IGV observation.

Further, I ran freebayes with lowering the value of parameter for --min-base-quality as 10.
The new run parameter is 
freebayes --use-duplicate-reads --min-alternate-count 10 --min-coverage 10 --min-base-quality 10 --min-mapping-quality 30 --min-supporting-allele-qsum 20 --min-supporting-mapping-qsum 30 --min-alternate-qsum 10 --min-alternate-fraction 0.03 -b main.bam -f hg19.fasta -v Trial17.vcf

Now, If I observe the VAF values for the same variant, then it is near to IGV observation.

chr19   13054564    .   AGCAGAGGCTTAAGGAGGAGGAAGAAGACAAGAAACGCAAAGAGGAGGAGGAGG  AG  2.20252e-12 .   AB=0.211522;ABP=2524.99;AC=1;AF=0.5;AN=2;AO=738;CIGAR=1M52D1M;DP=3489;DPB=2775;DPRA=0;EPP=1605.56;EPPR=4725.98;GTI=0;LEN=52;MEANALT=225;MQM=69.9919;MQMR=70;NS=1;NUMALT=1;ODDS=1559.43;PAIRED=0.98916;PAIREDR=0.980302;PAO=0;PQA=0;PQR=0;PRO=0;QA=11496;QR=70597;RO=2183;RPL=0;RPP=1605.56;RPPR=4725.98;RPR=738;RUN=1;SAF=738;SAP=1605.56;SAR=0;SRF=2183;SRP=4743.33;SRR=0;TYPE=del;technology.illumina=1   GT:DP:RO:QR:AO:QA:GL    0/1:3489:2183:70597:738:11496:-155.27,0,-5474.31

VAF = 738/2183+738 = 0.252653201.

I have tried one more run of execution considering the parameters --no-partial-observations
--min-repeat-entropy 1 but still getting same result. Only when I am lowring the --min_base_quality, then only I am getting VAF equals to IGV results.

As per my understanding, lowering the min_base_quality will add more false positive. 

Can you please provide your comments regarding the use of low value for --min-base-quality ? Will it affect results negatively ?

Can you please provide some suggestion on the above observation as why freebayes giving different VAF values ? 

Please let me know if you need more details.

The smiliar kind of observation was already mentioned on google freebayes forum where, IGV depth is not matching with freebayes output. (https://groups.google.com/forum/#!topic/freebayes/qaKxd8JyJQI)

 Thank you for your time,

Waiting for your reply,

Bhakti
Senior Bioinformatician
Pieriandx

**Comment by BhaktiLimaye** [comment]
IGV snapshot is attached. 
![chr19_13054564](https://cloud.githubusercontent.com/assets/15359246/15740314/03dbf908-28d2-11e6-91ce-ebff56b4802e.png)

**Comment by AlistairNWard** [comment]
You have the minimum mapping quality set at 30, so one thing to check in
IGV would be the mapping quality of the reads showing the deletion allele.


Alistair Ward, PhD
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by BhaktiLimaye** [comment]
Along with IGV analysis, I parsed bam file also for the variant position. There are more than 700 reads which shows 52bp Deletion having MAPQ > 70.  But in freebayes run, it is showing only 125 reads having 52 bp Deletion. 
I have also checked the supporting base quality of the deletion region from BAM file, there also base quality more than 20 for more than 700 reads.

**Comment by ekg** [comment]
I think that there may be a difference in the quality estimate in IGV and freebayes. I don't know how IGV works. Freebayes is estimating the deletion quality on the basis of the surrounding sequence.

It seems like removing all the filters (which are typically not necessary) resolves the discrepancy. Is this not the case?

**Comment by ekg** [comment]
This is critical:

> Further, I ran freebayes with lowering the value of parameter for --min-base-quality as 10.
The new run parameter is 
freebayes --use-duplicate-reads --min-alternate-count 10 --min-coverage 10 --min-base-quality 10 --min-mapping-quality 30 --min-supporting-allele-qsum 20 --min-supporting-mapping-qsum 30 --min-alternate-qsum 10 --min-alternate-fraction 0.03 -b main.bam -f hg19.fasta -v Trial17.vcf

> Now, If I observe the VAF values for the same variant, then it is near to IGV observation.

> chr19 13054564 . AGCAGAGGCTTAAGGAGGAGGAAGAAGACAAGAAACGCAAAGAGGAGGAGGAGG AG 2.20252e-12 . AB=0.211522;ABP=2524.99;AC=1;AF=0.5;AN=2;AO=738;CIGAR=1M52D1M;DP=3489;DPB=2775;DPRA=0;EPP=1605.56;EPPR=4725.98;GTI=0;LEN=52;MEANALT=225;MQM=69.9919;MQMR=70;NS=1;NUMALT=1;ODDS=1559.43;PAIRED=0.98916;PAIREDR=0.980302;PAO=0;PQA=0;PQR=0;PRO=0;QA=11496;QR=70597;RO=2183;RPL=0;RPP=1605.56;RPPR=4725.98;RPR=738;RUN=1;SAF=738;SAP=1605.56;SAR=0;SRF=2183;SRP=4743.33;SRR=0;TYPE=del;technology.illumina=1 GT:DP:RO:QR:AO:QA:GL 0/1:3489:2183:70597:738:11496:-155.27,0,-5474.31

Notice that removing this unnecessary filter resolves the discrepancy.

I suggest doing this:

```
freebayes --use-duplicate-reads --min-alternate-count 10 --min-coverage 10 --min-alternate-fraction 0.03 -b main.bam -f hg19.fasta -v Trial17.vcf
```

Is there a reason why this is problematic in your case?

**Comment by BhaktiLimaye** [comment]
Erik /Alistair  ,
Thanks
After running with above mentioned command by you. (freebayes --use-duplicate-reads --min-alternate-count 10 --min-coverage 10 --min-alternate-fraction 0.03 -b main.bam -f hg19.fasta -v Trial17.vcf)
I will definitely getting the value matching with IGV. This is true.
But as we are dealing with clinical dataset, I want to lower down the false positives. That is reason I am considering parameters which are related to quality. 

Can you please tell me how freebayes calculates the min-base-quality for a deletion ? From documentation, I understand this will be base quality of the base flanking the 52bp deletion region. Is it correct ?

**Comment by ekg** [comment]
If you want to lower false positives you should filter using the quality or
other features in the VCF. These are strongly correlated with error.
Filtering on the input can have nonlinear effects and I strongly urge you
not to do so.

We are working on a genotyper and classifier to filter the output of
freebayes and other variant callers, but it is not completely production
ready. See ekg/hhga

**Comment by BhaktiLimaye** [comment]
Thanx Erik
