### ISSUE TITLE
freebayes outputs wrong FMT/DPR for homozygous calls for the alternative allele

### ISSUE THREAD

**Issue by kaspernie** [freebayes/freebayes#293]
The FMT/DPR field (number of observation for each allele) generated by freebayes (v1.0.2-14-g9e98366) looks wrong for homozygous calls for the alternative allele (hom-alt). It should presumably report "DP(ref),DP(alt)" but sometimes (always?) reports "DP,DP" for hom-alt calls rather than the expected "0,DP". The hom-ref calls look as expected: "DP,0".
### Examples

Homozygous call for reference allele. DPR is correct:

```
GT=0/0
DP=21
DPR=21,0

```

Homozygous call for alternative allele. DPR is wrong (should have been 0,91):

```
GT=1/1
DP=91
DPR=91,91
```
### Notes

Judging from an uncomprehensive comparison to the output from "samtools mpileup + bcftools call -m", it looks like the call might be correct and that only DPR is wrong. (If the call is wrong, it might be related to #234 and #250.)

**Comment by wangyugui** [comment]
And the comment of VCF file(FMT/DPR Number=A)
should be changed to (FMT/DPR Number=R)
