### ISSUE TITLE
Problem when compiling freebayes

### ISSUE THREAD

**Issue by exepulveda** [freebayes/freebayes#294]
$ make
wget -q http://hypervolu.me/freebayes/build/v1.0.2-dirty &
cd src && make
make[1]: Entering directory `/home/a1634120/install/freebayes/src'
DETECTED_VERSION = v1.0.2-dirty
CURRENT_VERSION  = v1.0.2-dirty
g++ -O3 -D_FILE_OFFSET_BITS=64 -g -I../bamtools/src -I../ttmath -I../vcflib/src -I../vcflib/ freebayes.o BedReader.o CNV.o fastlz.o Fasta.o Parameters.o Allele.o Sample.o Result.o AlleleParser.o Utility.o Genotype.o DataLikelihood.o Multinomial.o Ewens.o ResultData.o Dirichlet.o Marginals.o split.o LeftAlign.o IndelAllele.o Bias.o Contamination.o NonCall.o SegfaultHandler.o ../vcflib/tabixpp/tabix.o ../vcflib/tabixpp/bgzf.o ../vcflib/smithwaterman/SmithWatermanGotoh.o ../vcflib/smithwaterman/disorder.c ../vcflib/smithwaterman/LeftAlign.o ../vcflib/smithwaterman/Repeats.o ../vcflib/smithwaterman/IndelAllele.o Variant.o ../bamtools/lib/libbamtools.a -o ../bin/freebayes -L./ -L../vcflib/tabixpp/ -L../bamtools/lib -ltabix -lz -lm
AlleleParser.cpp:590: error: undefined reference to 'BamTools::BamMultiReader::GetReferenceID(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
AlleleParser.cpp:2597: error: undefined reference to 'BamTools::BamMultiReader::GetErrorString[abi:cxx11]() const'
AlleleParser.cpp:46: error: undefined reference to 'BamTools::BamMultiReader::Open(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
AlleleParser.cpp:79: error: undefined reference to 'BamTools::BamMultiReader::GetHeaderText[abi:cxx11]() const'
AlleleParser.cpp:52: error: undefined reference to 'BamTools::BamMultiReader::Open(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
AlleleParser.cpp:59: error: undefined reference to 'BamTools::BamMultiReader::GetErrorString[abi:cxx11]() const'
AlleleParser.cpp:72: error: undefined reference to 'BamTools::BamMultiReader::GetErrorString[abi:cxx11]() const'
AlleleParser.cpp:54: error: undefined reference to 'BamTools::BamMultiReader::GetErrorString[abi:cxx11]() const'
AlleleParser.cpp:2332: error: undefined reference to 'BamTools::BamMultiReader::GetReferenceID(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
AlleleParser.cpp:2202: error: undefined reference to 'BamTools::BamMultiReader::GetReferenceID(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../bamtools/src/api/BamAlignment.h:517: error: undefined reference to 'BamTools::BamAlignment::FindTag(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char*&, unsigned int const&, unsigned int&) const'
../bamtools/src/api/BamAlignment.h:517: error: undefined reference to 'BamTools::BamAlignment::FindTag(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char*&, unsigned int const&, unsigned int&) const'
collect2: error: ld returned 1 exit status
make[1]: *** [../bin/freebayes] Error 1
make[1]: Leaving directory`/home/a1634120/install/freebayes/src'
make: **\* [all] Error 2

I'am using GCC 5.3.0

**Comment by ekg** [comment]
My immediate suspicion is that you cloned without --recursive.

**Comment by exepulveda** [comment]
I used --recursive. When I use GCC 4.9.3 it works, but GCC 5.3.0 does not
work.

/exequiel

2016-06-08 18:09 GMT+09:30 Erik Garrison <notifications@github.com>:

> My immediate suspicion is that you cloned without --recursive.
>
> On Wed, Jun 8, 2016, 03:06 exepulveda <notifications@github.com> wrote:
>
> > $ make
> > wget -q http://hypervolu.me/freebayes/build/v1.0.2-dirty &
> > cd src && make
> > make[1]: Entering directory /home/a1634120/install/freebayes/src'
> > DETECTED_VERSION = v1.0.2-dirty
> > CURRENT_VERSION = v1.0.2-dirty
> > g++ -O3 -D_FILE_OFFSET_BITS=64 -g -I../bamtools/src -I../ttmath
> > -I../vcflib/src -I../vcflib/ freebayes.o BedReader.o CNV.o fastlz.o
> Fasta.o
> > Parameters.o Allele.o Sample.o Result.o AlleleParser.o Utility.o
> Genotype.o
> > DataLikelihood.o Multinomial.o Ewens.o ResultData.o Dirichlet.o
> Marginals.o
> > split.o LeftAlign.o IndelAllele.o Bias.o Contamination.o NonCall.o
> > SegfaultHandler.o ../vcflib/tabixpp/tabix.o ../vcflib/tabixpp/bgzf.o
> > ../vcflib/smithwaterman/SmithWatermanGotoh.o
> > ../vcflib/smithwaterman/disorder.c ../vcflib/smithwaterman/LeftAlign.o
> > ../vcflib/smithwaterman/Repeats.o ../vcflib/smithwaterman/IndelAllele.o
> > Variant.o ../bamtools/lib/libbamtools.a -o ../bin/freebayes -L./
> > -L../vcflib/tabixpp/ -L../bamtools/lib -ltabix -lz -lm
> > AlleleParser.cpp:590: error: undefined reference to
> >
> 'BamTools::BamMultiReader::GetReferenceID(std::__cxx11::basic_string<char,
> > std::char_traits<char>, std::allocator<char> > const&) const'
> > AlleleParser.cpp:2597: error: undefined reference to
> > 'BamTools::BamMultiReader::GetErrorString[abi:cxx11]() const'
> > AlleleParser.cpp:46: error: undefined reference to
> >
> 'BamTools::BamMultiReader::Open(std::vector<std::__cxx11::basic_string<char,
> > std::char_traits<char>, std::allocator<char> >,
> > std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>,
> > std::allocator<char> > > > const&)'
> > AlleleParser.cpp:79: error: undefined reference to
> > 'BamTools::BamMultiReader::GetHeaderText[abi:cxx11]() const'
> > AlleleParser.cpp:52: error: undefined reference to
> >
> 'BamTools::BamMultiReader::Open(std::vector<std::__cxx11::basic_string<char,
> > std::char_traits<char>, std::allocator<char> >,
> > std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>,
> > std::allocator<char> > > > const&)'
> > AlleleParser.cpp:59: error: undefined reference to
> > 'BamTools::BamMultiReader::GetErrorString[abi:cxx11]() const'
> > AlleleParser.cpp:72: error: undefined reference to
> > 'BamTools::BamMultiReader::GetErrorString[abi:cxx11]() const'
> > AlleleParser.cpp:54: error: undefined reference to
> > 'BamTools::BamMultiReader::GetErrorString[abi:cxx11]() const'
> > AlleleParser.cpp:2332: error: undefined reference to
> >
> 'BamTools::BamMultiReader::GetReferenceID(std::__cxx11::basic_string<char,
> > std::char_traits<char>, std::allocator<char> > const&) const'
> > AlleleParser.cpp:2202: error: undefined reference to
> >
> 'BamTools::BamMultiReader::GetReferenceID(std::__cxx11::basic_string<char,
> > std::char_traits<char>, std::allocator<char> > const&) const'
> > ../bamtools/src/api/BamAlignment.h:517: error: undefined reference to
> > 'BamTools::BamAlignment::FindTag(std::__cxx11::basic_string<char,
> > std::char_traits<char>, std::allocator<char> > const&, char*&, unsigned
> int
> > const&, unsigned int&) const'
> > ../bamtools/src/api/BamAlignment.h:517: error: undefined reference to
> > 'BamTools::BamAlignment::FindTag(std::__cxx11::basic_string<char,
> > std::char_traits<char>, std::allocator<char> > const&, char*&, unsigned
> int
> > const&, unsigned int&) const'
> > collect2: error: ld returned 1 exit status
> > make[1]: *** [../bin/freebayes] Error 1
> > make[1]: Leaving directory/home/a1634120/install/freebayes/src'
> > make: *** [all] Error 2
> >
> > I'am using GCC 5.3.0
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/ekg/freebayes/issues/294>, or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAI4EfwHkLhmlMNiRwwT2S6_rk4Steafks5qJiOwgaJpZM4Iwh4_
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ekg/freebayes/issues/294#issuecomment-224525698>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AE32BFxpbId2kgqJdCq-SsAzIXTrsXJhks5qJn_fgaJpZM4Iwh4_>
> .
>



-- 
Exequiel Sepulveda

**Comment by isaacovercast** [comment]
Bump. I'm seeing this as well. GCC 5.1.0, any idea how to solve?

**Comment by walaj** [comment]
See https://github.com/jts/sga/issues/128

**Comment by mwhj** [comment]
Did anyone ever fix this?  I'm seeing the same problem trying to compile the newest version.  I'm running GCC 6.3.0.

....

'''
[ 95%] Linking CXX executable ../bin/freebayes
CMakeFiles/freebayes_OBJS.dir/src/AlleleParser.cpp.o: In function `AlleleParser::loadReferenceSequence(std::string&)':
/data/genomicsocorg/mwhj1/Programs/freebayes/src/AlleleParser.cpp:664: undefined reference to `SeqLib::BamHeader::Name2ID(std::string const&) const'
CMakeFiles/freebayes_OBJS.dir/src/AlleleParser.cpp.o: In function `AlleleParser::openBams()':
/data/genomicsocorg/mwhj1/Programs/freebayes/src/AlleleParser.cpp:78: undefined reference to `SeqLib::BamReader::Open(std::string const&)'
/data/genomicsocorg/mwhj1/Programs/freebayes/src/AlleleParser.cpp:122: undefined reference to `SeqLib::BamReader::HeaderConcat() const'
/data/genomicsocorg/mwhj1/Programs/freebayes/src/AlleleParser.cpp:71: undefined reference to `SeqLib::BamReader::Open(std::string const&)'
CMakeFiles/freebayes_OBJS.dir/src/AlleleParser.cpp.o: In function `AlleleParser::registerAlignment(SeqLib::BamRecord&, RegisteredAlignment&, std::string&, std::string&)':
/data/genomicsocorg/mwhj1/Programs/freebayes/src/AlleleParser.cpp:1318: undefined reference to `SeqLib::BamRecord::Sequence() const'
/data/genomicsocorg/mwhj1/Programs/freebayes/src/AlleleParser.cpp:1759: undefined reference to `SeqLib::BamRecord::Sequence() const'
CMakeFiles/freebayes_OBJS.dir/src/AlleleParser.cpp.o: In function `AlleleParser::updateAlignmentQueue(long, std::vector<Allele*, std::allocator<Allele*> >&, bool)':
/data/genomicsocorg/mwhj1/Programs/freebayes/src/AlleleParser.cpp:1944: undefined reference to `SeqLib::BamRecord::GetZTag(std::string const&, std::string&) const'
CMakeFiles/freebayes_OBJS.dir/src/AlleleParser.cpp.o: In function `RegisteredAlignment':
/data/genomicsocorg/mwhj1/Programs/freebayes/src/AlleleParser.h:71: undefined reference to `SeqLib::BamRecord::GetZTag(std::string const&, std::string&) const'
CMakeFiles/freebayes_OBJS.dir/src/AlleleParser.cpp.o: In function `AlleleParser::updateInputVariants(long, int)':
/data/genomicsocorg/mwhj1/Programs/freebayes/src/AlleleParser.cpp:2402: undefined reference to `SeqLib::BamHeader::Name2ID(std::string const&) const'
CMakeFiles/freebayes_OBJS.dir/src/AlleleParser.cpp.o: In function `AlleleParser::getInputVariantsInRegion(std::string&, long, long)':
/data/genomicsocorg/mwhj1/Programs/freebayes/src/AlleleParser.cpp:2272: undefined reference to `SeqLib::BamHeader::Name2ID(std::string const&) const'
CMakeFiles/freebayes_OBJS.dir/src/AlleleParser.cpp.o: In function `AlleleParser::toNextPosition()':
/data/genomicsocorg/mwhj1/Programs/freebayes/src/AlleleParser.cpp:2912: undefined reference to `SeqLib::BamHeader::Name2ID(std::string const&) const'
CMakeFiles/freebayes_OBJS.dir/src/LeftAlign.cpp.o: In function `countMismatches(SeqLib::BamRecord&, std::string)':
/data/genomicsocorg/mwhj1/Programs/freebayes/src/LeftAlign.cpp:345: undefined reference to `SeqLib::BamRecord::Sequence() const'
CMakeFiles/freebayes_OBJS.dir/src/LeftAlign.cpp.o: In function `leftAlign(SeqLib::BamRecord&, std::string&, bool)':
/data/genomicsocorg/mwhj1/Programs/freebayes/src/LeftAlign.cpp:26: undefined reference to `SeqLib::BamRecord::Sequence() const'
/data/genomicsocorg/mwhj1/Programs/freebayes/src/LeftAlign.cpp:27: undefined reference to `SeqLib::BamRecord::Sequence() const'
/data/genomicsocorg/mwhj1/Programs/freebayes/src/LeftAlign.cpp:272: undefined reference to `SeqLib::BamRecord::Sequence() const'
collect2: error: ld returned 1 exit status
gmake[3]: *** [../bin/freebayes] Error 1
gmake[3]: Leaving directory `/lustre/alice3/data/genomicsocorg/mwhj1/Programs/freebayes/build'
gmake[2]: *** [CMakeFiles/freebayes.dir/all] Error 2
gmake[2]: Leaving directory `/lustre/alice3/data/genomicsocorg/mwhj1/Programs/freebayes/build'
gmake[1]: *** [all] Error 2
gmake[1]: Leaving directory `/lustre/alice3/data/genomicsocorg/mwhj1/Programs/freebayes/build'
make: *** [freebayes] Error 2
'''

**Comment by mwhj** [comment]
Same behaviour with GCC 9.3.0
