### ISSUE TITLE
-l --only-use-input-alleles not working...

### ISSUE THREAD

**Issue by hamidhamzeiy** [freebayes/freebayes#296]
Hello,

I am able to use -@ but not -l --only-use-input-alleles.

Also work -l --only-use-input-alleles similar to the -l in samtools mpileup?

Thank you, Hamid

**Comment by ashbig** [comment]
I second this. I receive a "cannot open input bam" 

I got around this by intersecting with the vcf I input to freebayes, but I'd prefer a bug fix :)

**Comment by peterdfields** [comment]
@ashbig how did you get around this error with intersecting the vcf?

**Comment by ashbig** [comment]
@peterdfields You can just limit your bam file to the areas you wish to call by intersecting it prior to calling. You can do this through a bed/vcf or even another bam using bedtools/bed-ops. Should be functionally the same as --only-use-input-alleles

**Comment by peterdfields** [comment]
@ashbig do you have a sample command for doing this?
