### ISSUE TITLE
Some errors may occur when use parallel operation

### ISSUE THREAD

**Issue by yangwu91** [freebayes/freebayes#301]
**To use parallel operation, you should build vsflib first:**

> ```
>    $ cd /dir/to /freebayes/vcflib/
>    $ make
> ```

---

**Error:**

> ```
>    ../vcflib/bin/vcfstreamsort: error while loading shared libraries: libhts.so: cannot open shared object file: No such file or directory
> ```

**Solution:** 

> ```
>    $ export LD_LIBRARY_LIB=$LD_LIBRARY_LIB:/dir/to/samtools/htslib-1.x.x/
> ```

---

**Error:**

> ```
>    ./freebayes-parallel: line 38: parallel: command not found
> ```

**Solution (Ubuntu):**

> ```
>    $ sudo apt-get install parallel
> ```

---

**Error:**

> ```
>    ./freebayes-parallel: line 40: vcfuniq: command not found
> ```

**Solution:**
Modify Line 40 in /dir/to/freebayes/scripts/freebayes-parallel to this:

> ```
>     | ../vcflib/bin/vcfstreamsort -w 1000 | ../vcflib/bin/vcfuniq # remove duplicates at region edges
> ```

**Comment by rwhetten** [comment]
Modify the environment variable $LD_LIBRARY_PATH, not $LD_LIBRARY_LIB, to solve the problem with libhts.so.1
```
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/htslib-1.x.x
```

**Comment by SgmaOu** [comment]
Solution for errors on libhts.so.1:

`$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/**freebays**/htslib-1.x.x/`

The htslib is not in /samtools/ but from the sub-module of freebayes

**Comment by tseemann** [comment]
@yangwu91 you need to install `vcflib` too.

**Comment by jkreinz** [comment]
After correcting some of the errors mentioned on this thread, I keep getting the following message while attempting to run freebayes-parallel

File "../../vcflib/bin/vcfuniq", line 1
SyntaxError: Non-ASCII character '\xd2' in file ../../vcflib/bin/vcfuniq on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Any ideas?
