### ISSUE TITLE
Calling Compound Heterozygotes with Freebayes in Pooled, Targeted Sequencing

### ISSUE THREAD

**Issue by ricardoharripaul** [freebayes/freebayes#303]
Dear Erik,

I am trying to call variants in a pooled sequencing run with 32 individuals.  I have something like 15 000 X read depth in that area.  I am trying to call a 1 bp deletion that I know is there but I cannot find it in the vcf file and thus freebayes is not calling it.  I have been able to call 1 bp insertions in a similar fashion.  This variant is also a compound heterozygote disease-causing mutation.  I have attempted to call variants using duplicates but I still do not see the variants and we have validated that it is there by Sanger sequencing.  We are using this as a type of positive control for the sequencing technique.

Is there any way we can increase the sensitivity to detect this variant using freebayes?

Command being used currently: freebayes -f $REFERENCE -F 0.01 -C 32 --pooled-continuous BAM_FILE > out.vcf (adjusting for calling variants using duplicates)

Thank you,

Ricardo Harripaul

**Comment by ekg** [comment]
What is the frequency you expect to see this variant at?

**Comment by ricardoharripaul** [comment]
Hi Erik,

We are .looking for rare variants where MAF=0.005 or less.

Ricardo

**Comment by ekg** [comment]
Hi Ricardo,

In that case then the `-F 0.01 -C 32` settings are likely far too stringent.

What about setting `-F 0.0001 -C 5`... or an appropriate level for the -C setting based on your expectations.

The problem is that to detect things at 0.005 reliably, we will need to consider things that apparently have lower frequency.

**Comment by ricardoharripaul** [comment]
Thanks Erik.

**Comment by ricardoharripaul** [comment]
Hi Erik,

One more question.  In the sequencing pool, we spiked in a known mutation
as a control.  When calling the variant with freebayes it is listed as a
0/0 genotype implying it is not difference from the reference.  This is
strange because these variants are rare variants and known disease
variants.  I was not sure why it looked like this.  I was expecting a 1/1
genotype.

Thanks again,

Ricardo

**Comment by ekg** [comment]
Was this called as a single sample, and is the mutation at 100% frequency
in the pool? Also are the reads coming from both strands and are the reads
balanced across the allele?

**Comment by ricardoharripaul** [comment]
Hi Erik,

It is called as a single sample and the mutation is not at 100 %
frequency.  This particular mutation is homozygous so it would be balanced
on both alleles.

Thanks,

Ricardo

**Comment by ekg** [comment]
In that case it's unsurprising that this isn't a homozygous call. If it is
at low frequency then it will be likely to come back 0/0. If you are
calling in a pooled way, the idea is that you will work with the
observation frequencies downstream. The genotype call becomes meaningless.
