### ISSUE TITLE
Incorporate htslib

### ISSUE THREAD

**Issue by kyleabeauchamp** [freebayes/freebayes#304]
It was discussed in #222 that there might be performance gains (time + memory) by switching some freebayes internals to use htslib.  I didn't see an open issue on that topic, so I created one.

**Comment by kyleabeauchamp** [comment]
Perhaps if you can clearly enumerate your requirements, the HTSLib folks might be able to build additional features at the HTSLib level that streamlines things on the Freebayes side.

**Comment by ekg** [comment]
That would be amazing. In short, I'd like to replicate the BamTools API
usage patterns.

We need an object to represent an alignment, and methods to return the
ending position of the alignment.

I'll need a representation of the CIGAR string of an alingment.

Also, there should be one function to open a set of files, and one to set a
particular region.

Finally, an API feature that allows a `while (get next alignment)` kind of
loop is essential.

**Comment by kyleabeauchamp** [comment]
Are you familiar with pysam?  A lot of the key classes in pysam are actually implemented in cython, so they might be exposable in C++.

http://pysam.readthedocs.io/en/latest/api.html#pysam.AlignmentFile

http://pysam.readthedocs.io/en/latest/api.html#pysam.AlignedSegment

**Comment by ekg** [comment]
We really need them in native C/C++. I've done some wrapping of htslib in
vg, so maybe I could start from that.

**Comment by kyleabeauchamp** [comment]
Understood.   But if you can agree on a consistent API with pysam, then you have a pretty strong argument to abstract that layer out of pysam + Freebayes and upwards into htslib.

**Comment by jwalabroad** [comment]
I faced this same issue some time ago, and wrapping HTSlib into a BamTools C++ project isn't trivial. E.g. converting their 2-DNA-letters-per-byte seq representation into a more familiar std::string. I ended up making something called "[SnowTools](https://github.com/jwalabroad/SnowTools)" which is I think exactly what you are looking for. I ended up being able to switch everything out from BamTools with something in SnowTools. One nice feature is that all of the memory management headaches with C in HTSlib is handled internally using smart pointers in SnowTools. Another is you can interface with BWA-MEM entirely within C++.

The Broad also was developing something called Gamgee with similar intention, but this has been abandoned.
