### ISSUE TITLE
Compiling issue v1.0.2

### ISSUE THREAD

**Issue by wyleung** [freebayes/freebayes#307]
Dear developers,
I'm using a Linux based system (Ubuntu 14.04LTS) and i'm trying to compile Freebayes.

As per your instructions, i've made a checkout with  '--recursive' of freebayes.

Make ran till the following section:

```
wget -q http://hypervolu.me/freebayes/build/v1.0.2-dirty &
cd src && make
make[1]: Entering directory `/share/isilon/system/local/RESEARCH.LOCAL/sasc/programs/freebayes/freebayes-v1.0.2/src'
DETECTED_VERSION = v1.0.2-dirty
CURRENT_VERSION  = v1.0.2-dirty
g++ -O3 -D_FILE_OFFSET_BITS=64 -g -I../bamtools/src -I../ttmath -I../vcflib/src -I../vcflib/ -c freebayes.cpp
In file included from AlleleParser.h:31:0,
                 from freebayes.cpp:28:
../vcflib/src/Variant.h:18:21: fatal error: tabix.hpp: No such file or directory
 #include "tabix.hpp"
                     ^
compilation terminated.
make[1]: *** [freebayes.o] Error 1
make[1]: Leaving directory `/share/isilon/system/local/RESEARCH.LOCAL/sasc/programs/freebayes/freebayes-v1.0.2/src'
make: *** [all] Error 2

```

Perhaps the `vcflib` is updated and the gitmodules are out of sync for this particular version?

**Comment by lozybean** [comment]
Is there any solution?

**Comment by ekg** [comment]
Try to build from a fresh recursive clone. This usually is a problem if you
don't download all the submodules.

**Comment by drwhitehouse** [comment]
So I got the same error and found this issue.
However when I look:
Submodule path 'vcflib/tabixpp': checked out '80012f86dc22b13c75b73baf38195956db92473e'
Additionally:

$ find . -name tabix.hpp
./vcflib/include/tabix.hpp
./vcflib/tabixpp/tabix.hpp

I'm not sure that your suggested fix is going to work for me.

**Comment by tseemann** [comment]
@wyleung current version is 1.2.0 https://github.com/ekg/freebayes/releases
Recommend you use conda or brew to install.
