### ISSUE TITLE
big difference DP value between freebayes and samtools mpileup

### ISSUE THREAD

**Issue by microtsiu** [freebayes/freebayes#308]
when I call snv use freebayes lastest version, command is:  
freebayes -f human_g1k_v37.fasta -i -t target.bed -v output.vcf -m 60 -q 30 input.bam  
and samtools mpileup command is:  
samtools mpileup -B -f human_g1k_v37.fasta -l target.bed -d 2000000  -q 60 -Q 30 input.bam> mpileup.out  
the depth of each base between freebayes and samtools mpileup has big difference, such as:
freebayes result:
1   11168299    .   C   T   4.38166e-14 .   AB=0;ABP=0;AC=0;AF=0;AN=2;AO=6;CIGAR=1X;DP=21239;DPB=21239;DPRA=0;EPP=8.80089;EPPR=7.82785;GTI=0;LEN=1;MEANALT=3;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=29348;PAIRED=1;PAIREDR=0.998445;PAO=0;PQA=0;PQR=0;PRO=0;QA=216;QR=752648;RO=21225;RPL=0;RPP=16.0391;RPPR=164.147;RPR=6;RUN=1;SAF=1;SAP=8.80089;SAR=5;SRF=10531;SRP=5.7285;SRR=10694;TYPE=snp;technology.illumina=1   GT:DP:DPR:RO:QR:AO:QA:GL    0/0:21239:21239,6:21225:752648:6:216:0,-6371.73,-67688.6  
samtools mpileup result:
1   11168299    C   12861   .$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$...............  
but when i set Q 0 (q 0 ), the depth is similar  
Could you tell me why has it happened

**Comment by ekg** [comment]
The depth in freebayes is post-filter, and the -q filter is removing some
alignments which have very low quality at the site. Thus the resulting
depth is lower. The removed reads are probably not usable if their quality
is so low.

Maybe we need to add a pre-filter depth to rectify these concerns, which
come up continuously.
