### ISSUE TITLE
segfault with empty --variant-input

### ISSUE THREAD

**Issue by chapmanb** [freebayes/freebayes#310]
Hi all;
The current development version of freebayes segfaults if you pass an empty VCF (with a header, but no variants) as `--variant-input`. This works correctly (returning an empty VCF from FreeBayes) with 1.2.0 but seems to have broken with the latest updates. Here is a reproducible example:

https://s3.amazonaws.com/chapmanb/testcases/fb_empty_variantinput.tar.gz

Running:

```
freebayes -b Test1-sort.bam --variant-input needcall.vcf.gz  -f hg19.fa
```

gives a segfault during the setup of the VCF input:

```
Program received signal SIGSEGV, Segmentation fault.
Tabix::Tabix (this=0x8afb10, file=...) at tabix.cpp:53
53      tabix.cpp: No such file or directory.
(gdb) bt
#0  Tabix::Tabix (this=0x8afb10, file=...) at tabix.cpp:53
#1  0x0000000000447b14 in openTabix (filename=..., this=0x8824c8) at ../vcflib/src/Variant.h:106
#2  open (filename=..., this=0x8824c8) at ../vcflib/src/Variant.h:91
#3  AlleleParser::setupVCFInput (this=this@entry=0x881b60) at AlleleParser.cpp:508
#4  0x000000000045c773 in AlleleParser::AlleleParser (this=0x881b60, argc=<optimized out>, argv=<optimized out>)
    at AlleleParser.cpp:858
#5  0x0000000000407d8f in main (argc=7, argv=0x7fffffffd748) at freebayes.cpp:78
```

**Comment by ekg** [comment]
Thanks for the nice bug report. It should be easy enough to check and fix
appropriately. Should we throw a warning?

**Comment by chapmanb** [comment]
Erik;
Thanks for looking at this. I don't think we need a warning here -- it should just return an empty VCF (well, header only VCF) if it gets a VCF with no variants. Thanks again.
