### ISSUE TITLE
phased variant problem

### ISSUE THREAD

**Issue by rosema62** [freebayes/freebayes#317]
Hello 
I am having trouble getting freebayes to call phase variants.  To illustrate my problem (and avoid confidentiality issues with my company) I’ve created a simulated dataset (as shown below) which closely resembles my actual data except the two linked deletions in the simulation are homozygous instead of a mix of reads with 2 deletions and reads with none.  In brief my actual reads are stitched (merged) 250BP PE Illumina reads derived from a 374 bp amplicon.  Therefore the stitched reads cover the entire amplicon.

Creating simulated dataset:
wgsim -N 1000 -d 342 -s 0 -1 250 -2 250 -h  ampR.2dels.fa  read1.2dels.fq read2.2dels.fq

flash  -m 25 -M 300 -o test -t 1 read1.2dels.fq read2.2dels.fq |tee test.flash.log

bowtie2-build ampR.fa ampR.fa

bowtie2 --sensitive-local -p 4 -x ampR.fa -U test.extendedFrags.fastq  -S test.extendedFrags.fastq-vs-ampR.fa.sam 2>bowtie2.log

samtools view -Sb -o  test.extendedFrags.fastq-vs-ampR.fa.bam test.extendedFrags.fastq-vs-ampR.fa.sam
samtools sort test.extendedFrags.fastq-vs-ampR.fa.bam test.extendedFrags.fastq-vs-ampR.fa.sort
samtools index test.extendedFrags.fastq-vs-ampR.fa.sort.bam

I then ran freebayes
freebayes -f ampR.fa -F 0.1 -C 2 -K --haplotype-length 100 test.extendedFrags.fastq-vs-ampR.fa.sort.bam >test.extendedFrags.fastq-vs-ampR.fa.vcf 
which produces:
# CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  unknown

ampR    65      .       AACGGATGTAATGA  AA      5382.63 .       AB=0;ABP=0;AC=2;AF=1;AN=2;AO=859;CIGAR=1M12D1M;DP=873;DPB=124.714;DPRA=0;EPP=7.25971;EPPR=0;GTI=0;LEN=12;MEANALT=2;MQM=12.2154;MQMR=0;NS=1;NUMALT=1;ODDS=1192.79;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=14603;QR=0;RO=0;RPL=0;RPP=1868.31;RPPR=0;RPR=859;RUN=1;SAF=409;SAP=7.25971;SAR=450;SRF=0;SRP=0;SRR=0;TYPE=del        GT:DP:DPR:RO:QR:AO:QA:GL      1/1:873:873,859:0:0:859:14603:-800.827,-258.585,0
ampR    81      .       ACCCGCAGCTATCTCCCGCTTA  AA      5580.28 .       AB=0;ABP=0;AC=2;AF=1;AN=2;AO=896;CIGAR=1M20D1M;DP=896;DPB=81.4545;DPRA=0;EPP=7.28539;EPPR=0;GTI=0;LEN=20;MEANALT=1;MQM=12.269;MQMR=0;NS=1;NUMALT=1;ODDS=1244.09;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=15136;QR=0;RO=0;RPL=0;RPP=1948.65;RPPR=0;RPR=896;RUN=1;SAF=427;SAP=7.28539;SAR=469;SRF=0;SRP=0;SRR=0;TYPE=del GT:DP:DPR:RO:QR:AO:QA:GL      1/1:896:896,896:0:0:896:15136:-831.754,-269.723,0

Herein I see no indication that these two deletions are linked though 839 of the 1000 read pairs contain this partial cigar string: 12D4M20D.

Help would be much appreiciated.
Thanks
Mark

[simulated_data.zip](https://github.com/ekg/freebayes/files/466258/simulated_data.zip)

**Comment by robsyme** [comment]
Hi Mark

This post on the freebayes mailing list might help clarify the phasing in freebayes: https://groups.google.com/forum/#!topic/freebayes/fyhho8_H7J0

**Comment by rosema62** [comment]
Thanks for the suggestion but it appears that there is a problem with freebayes in handling the situation I described.  I sent a test set to Erik that reproduces the problem which he confirmed.  He said he would work on it but had no explanation for its failure.  He suggested another app (whatshap) but it didn't work either so I've had to roll my own solution to this particular problem

**Comment by rosema62** [comment]
Hi Robert

Thanks for the suggestion but it appears that there is a problem with freebayes in handling the situation I described. I sent a test set to Erik that reproduces the problem which he confirmed. He said he would work on it but had no explanation for its failure. He suggested another app (whatshap) but it didn't work either so I've had to roll my own solution to this particular problem

Mark
