### ISSUE TITLE
segfault from *bam with many contigs

### ISSUE THREAD

**Issue by abishara** [freebayes/freebayes#321]
Hi,

I get a segfault using freebayes on *bams that contain a large number of contigs (> 250k contigs).  I am interested in getting calls on only the ones that are of a certain size, but I can't seem to get it to run without crashing.  Any help would be greatly appreciated.  I included a small.fa and tmp.bam that produces this issue.

Thanks!

[issue.zip](https://github.com/ekg/freebayes/files/475548/issue.zip)

**Comment by ekg** [comment]
I'll check this out.

**Comment by claudiuskerth** [comment]
I can confirm this. 200k contigs still works fine, 250k leads to segfault. 

I guess one workaround for the moment is to concatenate those contigs into a pseudo scaffold and redo the mapping. Another one could be to reduce the number of "@SQ" BAM header lines to only those contigs that got reads mapped to. 

I would appreciate the removal of this limitation, since some of my post-mapping-pre-variant-estimation filters are easier to implement with separate contigs as compared to a pseudo scaffold.

claudius

**Comment by ekg** [comment]
I understand you cannot run one job for every e.g. 1000 contigs?

**Comment by claudiuskerth** [comment]
Hi Eric,

sorry, but I can't figure out what you mean. The read mapping has to be be done against the whole reference, of course, resulting in BAM files with headers that contain all contigs of the reference. Limiting `freebayes` to a target of only 1000 contigs through a BED file leads to the same segfault:

>freebayes -d -f Big_Data_ref.fa -t small.bed -T 0.01 -F 0 -C 0 -G 5 --min-coverage 3 --max-coverage 25 -V --use-mapping-quality par_34-9.sorted.bam 
loading fasta reference Big_Data_ref.fa
Opening BAM format alignment input file: par_34-9.sorted.bam ...
 done
Number of ref seqs: 583312
Making BedReader object for target file: small.bed ...
done
Number of target regions: 1000
no sample list file given, reading sample names from bam file
found 1 samples in BAM file
Segmentation fault (core dumped)

This is with version:  v1.0.2-58-g054b257. The BAM that I used for this test contains alignment records for reads mapping to 96,603 contigs in total, i. e. well below 250k. To me it looks like it's the number of ref seqs in the BAM header that is causing `freebayes` to segfault.

claudius

**Comment by ekg** [comment]
Do you get the same segfault with v1.1?

**Comment by claudiuskerth** [comment]
Hi Eric,

the segfault happens with `freebayes` from commit 39e5e4bcb (3 Nov) as well as.

claudius

**Comment by ekg** [comment]
Can you isolate the contig where the failure occurs? Are there any funny
features of this contig? For instance, depth being very high. Did you set
use-best-n-alleles?
