### ISSUE TITLE
FreeBayes cannot tell that a read group ID is missing if it appears in another BAM

### ISSUE THREAD

**Issue by sambrightman** [freebayes/freebayes#322]
If an alignment has an RG tag that does not occur in the header but does occur in another BAM's header, FreeBayes cannot currently detect this. I find that it proceeds but produces no sample information for the second BAM (a dot "." in every row for that sample column). It looks related to looking up sample names from read groups somehow, as would be expected.

I don't believe this is easily fixable given the way FreeBayes currently works but thought it worth filing anyway so that it's discoverable (I wasted some time on finding this - I re-headered a BAM without renaming the ID in the rest of the BAM). Potentially just close this immediately.

**Comment by ekg** [comment]
I'll blame the design of BAM for this, which has forced us to work with
hundred gigabyte files with headers. Headers are totally superfluous for
almost all uses, and split the presentation of data in a way that causes
exactly the kinds of issues you are running into. Each read should be
tagged with the read group and sample it comes from, without need to refer
to a global header. Why the designers of BAM couldn't trust compression to
handle redundancy is beyond my imagination. New formats (such as GFA)
continue to perpetuate the header anti-pattern. I wish it would stop.

We should at least try to improve handling of this kind of problem in
freebayes. Some of the issues with BAM handling lie in BamTools. As we will
move away from this shortly, maybe there is an opportunity to improve
things by using SeqLib, which being htslib based might handle things in a
more expected way.
