### ISSUE TITLE
Error message on passing test

### ISSUE THREAD

**Issue by sambrightman** [freebayes/freebayes#329]
Possibly related to merge of #316, I see this:

```
Failed to load index for -. Rebuild samtools index
ERROR(freebayes): Could not SetRegion to q:1..10000
ok 14 - freebayes handles region, stdin, and variant input
```

Somehow the test still passes (and I checked the output is correct). But:
- error message is not well-formatted (what is "-."? replace with "STDIN"? has it actually failed or not?)
- there should not be an error here, presumably

Maybe @walaj wants to take a look?

**Comment by walaj** [comment]
I think the issue is that you can't do random-access with SetRegion if you are passing via stdin, since you don't have an index file, and shouldn't expect one be available. So I think there should be an error.

Is this a new test?

I agree that "-" is not informative enough. I should replace this with STDIN as you suggest.

**Comment by sambrightman** [comment]
This is an old test, but it's not clear what has failed because the output is right. You couldn't do random-access with stdin previously, either... Seems like maybe random access is being done unnecessarily? Which would explain the result still working and lack of error before.

**Comment by walaj** [comment]
SeqLib will emit the error message, but doesn't actually throw an error. It just will return ``false`` for the SetRegion call, which is then up to freebayes on how it should handle this. I think in this case it should actually error and quit, since it can't do what is being asked.

**Comment by sambrightman** [comment]
Right, but again: this worked before and apparently still works now. Doesn't it sound like it is a spurious call, which isn't actually required in this case?

**Comment by tillea** [comment]
Hi,
I faced this issue when trying to build the Debian package for Version 1.3.1 of FreeBayes.  I think it makes sense to skip this test until the issue is cleared.
Kind regards, Andreas.
