### ISSUE TITLE
Can't install freebayes on Linux (ubuntu), make cmd fails.

### ISSUE THREAD

**Issue by serine** [freebayes/freebayes#335]
Hi there, 

I can't install freebayes. Here are my steps

```
git clone --recursive git://github.com/ekg/freebayes.git
cd freebayes
make
```

I get these messages at the very end and `bin/` directory is empty

```
make[4]: Leaving directory '/home/kirill/Downloads/freebayes/SeqLib/src'
make[4]: Entering directory '/home/kirill/Downloads/freebayes/SeqLib'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/kirill/Downloads/freebayes/SeqLib'
make[3]: Leaving directory '/home/kirill/Downloads/freebayes/SeqLib'
make[2]: Leaving directory '/home/kirill/Downloads/freebayes/SeqLib'
make[1]: Leaving directory '/home/kirill/Downloads/freebayes/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
```

Strange thing is if I run `make test`, test still fails, but `bin/` driectory is now populated with `freebayes` and `bamleftalign` executables that appear workable (haven't test them out appart from running `--help`, which works) 

```
Test Summary Report
-------------------
t/01_call_variants.t             (Wstat: 0 Tests: 19 Failed: 1)
  Failed test:  16
Files=4, Tests=40,  4 wallclock secs ( 0.02 usr  0.01 sys +  2.77 cusr  0.25 csys =  3.05 CPU)
Result: FAIL
Makefile:9: recipe for target 'test' failed
make[1]: *** [test] Error 1
make[1]: Leaving directory '/home/kirill/Downloads/freebayes/test'
Makefile:27: recipe for target 'test' failed
make: *** [test] Error 2
```

I fegure problem is in `Makefile`. Would be able to fix that? 

Thanks

**Comment by walaj** [comment]
It looks like it is doing fine with the ```src/Makefile``` piece, which actually builds the executable. Are you seeing ```freebayes``` in the ```src``` directory after the ```make```? Looks almost like the issue is in copying the executable to ```bin```

**Comment by serine** [comment]
right, if get into `src/` driectory in freshly cloned freebays  and run this `make` I don't get freebays in `src` but I do get it in `bin/`

**Comment by serine** [comment]
which bit gets into `src/` and initiates `make`?

```
all: vcflib/Makefile log
        cd src && $(MAKE)

log: src/version_git.h
        wget -q http://hypervolu.me/freebayes/build/$(shell cat src/version_git.h | grep v | cut -f 3 -d\  | sed s/\"//g) &

src/version_git.h:
        cd src && $(MAKE) autoversion
        touch src/version_git.h

vcflib/Makefile:
        @echo "To build freebayes you must use git to also download its submodules."
        @echo "Do so by downloading freebayes again using this command (note --recursive flag):"
        @echo "    git clone --recursive git://github.com/ekg/freebayes.git"
        @error

debug:
        cd src && $(MAKE) debug

install:
        cp bin/freebayes bin/bamleftalign /usr/local/bin/

uninstall:
        rm /usr/local/bin/freebayes /usr/local/bin/bamleftalign

test:
        cd test && make test

clean:
        cd src && $(MAKE) clean
        rm -fr bin/*

.PHONY: all install uninstall clean test
```

**Comment by mmokrejs** [comment]
`make: *** [all] Error 2`

You should scroll through the output back and look for the place where `Error 1 `appeared. That is the main problem.

**Comment by serine** [comment]
@mmokrejs 

I can't see other errors. My workflow shown below. I used to have no problem installing `freebays`.

```[biostation]:Downloads/check% ls
[biostation]:Downloads/check% git clone --recursive git://github.com/ekg/freebayes.git 1> /dev/null 2>&1
[biostation]:Downloads/check% ls
freebayes
[biostation]:Downloads/check% cd freebayes 
[biostation]:check/freebayes% ls
bamtools  bin  CONTRIBUTORS  examples  intervaltree  LICENSE  Makefile  paper  python  README.md  scripts  SeqLib  src  test  ttmath  vcflib
[biostation]:check/freebayes% ls bin 
[biostation]:check/freebayes% make -j 4 -f Makefile > log.txt 2>&1                                      
[biostation]:check/freebayes% ls bin 
[biostation]:check/freebayes% ls
bamtools  bin  CONTRIBUTORS  examples  intervaltree  LICENSE  log.txt  Makefile  paper  python  README.md  scripts  SeqLib  src  test  ttmath  vcflib
[biostation]:check/freebayes% grep -in error log.txt 
660:make: *** [all] Error 2
[biostation]:check/freebayes% tail log.txt 
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib libseqlib.a
make[4]: Leaving directory '/home/kirill/Downloads/check/freebayes/SeqLib/src'
make[4]: Entering directory '/home/kirill/Downloads/check/freebayes/SeqLib'
make[4]: Leaving directory '/home/kirill/Downloads/check/freebayes/SeqLib'
make[3]: Leaving directory '/home/kirill/Downloads/check/freebayes/SeqLib'
make[2]: Leaving directory '/home/kirill/Downloads/check/freebayes/SeqLib'
make[1]: Leaving directory '/home/kirill/Downloads/check/freebayes/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2```

Anyone else have any idea how to fix this problem?

**Comment by mmokrejs** [comment]
Dunno, but try `make -j 1` just in case ...

**Comment by serine** [comment]
Its prtty bizzar to me, but it works with just `make` or `make -j 1`. As soon as I give more threads, it breaks..

I guess issue can be closed.. but I wouldn't might having a bit more info as to why that is..? because when I compile `vcflib` it also breaks, but only sometimes, compare to `freebayes` - all the time :/ 

Cheers

**Comment by mmokrejs** [comment]
Often the dependence rules in Makefile are in wrong order. I am not a freebayes developer but you should attach the complete make outputs of a few unsuccessful attempts to this bug.
Indeed, freebayes should not re-package vcflib, htslib, bwa, fermi-lite, SeqLib, bamtools, intervaltree a bash-tap but instead, just depend on the to be installed.
I am not surprised your build attempts fail as you might be hitting a bug in someone's other code. 

Similarly, report the problem to vcflib developers.

**Comment by mmokrejs** [comment]
> which bit gets into src/ and initiates make?

The make all rule kicks in:

```
all: vcflib/Makefile log
        cd src && $(MAKE)
```

**Comment by DaniPaulo** [comment]
Hi,

I'm getting the same error but I was not able to fixed.
I made all the solutions described in this post but nothing works....
I'm also getting a first error:

ETECTED_VERSION = v1.1.0-6-gf069ec6-dirty
CURRENT_VERSION  = v1.1.0-6-gf069ec6
Updating version file.
g++ -O3 -D_FILE_OFFSET_BITS=64 -g -I../ttmath -I../bamtools/src/ -I../vcflib/src/ -I../vcflib/tabixpp/ -I../vcflib/smithwaterman/ -I../vcflib/multichoose/ -I../vcflib/filevercmp/ -I../vcflib/fastahack/ -I../vcflib/tabixpp/htslib -I../SeqLib -I../SeqLib/htslib -c ResultData.cpp
In file included from /usr/local/include/assert.h:5:0,
                 from Genotype.h:15,
                 from ResultData.h:7,
                 from ResultData.cpp:1:
ResultData.cpp: In member function ‘vcflib::Variant& Results::vcf(vcflib::Variant&, BigFloat, long double, Samples&, std::__cxx11::string, std::vector<Allele>&, std::map<std::__cxx11::basic_string<char>, int>, int, std::vector<std::__cxx11::basic_string<char> >&, int, GenotypeCombo&, std::map<std::__cxx11::basic_string<char>, std::vector<Allele*> >&, std::map<std::__cxx11::basic_string<char>, std::vector<Allele*> >&, std::map<Allele*, std::set<Allele*> >&, std::map<int, std::vector<Genotype> >&, std::vector<std::__cxx11::basic_string<char> >&, AlleleParser*)’:
ResultData.cpp:447:9: error: could not convert ‘& frame’ from ‘Except_Frame_T*’ to ‘Except_Frame_T’
         TRY { repeatstr = repeatstr.substr(0, repeatstr.size() - 1); } CATCH;
         ^
In file included from AlleleParser.h:25:0,
                 from ResultData.h:10,
                 from ResultData.cpp:1:
TryCatch.h:10:5: error: expected primary-expression before ‘catch’
     catch (std::out_of_range outOfRange) { \
     ^
ResultData.cpp:447:72: note: in expansion of macro ‘CATCH’
         TRY { repeatstr = repeatstr.substr(0, repeatstr.size() - 1); } CATCH;
                                                                        ^
ResultData.cpp:640:1: error: expected ‘while’ before ‘vcflib’
 vcflib::Variant& Results::gvcf(
 ^
ResultData.cpp:640:1: error: expected ‘(’ before ‘vcflib’
ResultData.cpp:640:16: error: expected primary-expression before ‘&’ token
 vcflib::Variant& Results::gvcf(
                ^
ResultData.cpp:641:20: error: expected primary-expression before ‘&’ token
     vcflib::Variant& var,
                    ^
ResultData.cpp:642:13: error: expected primary-expression before ‘&’ token
     NonCalls& nonCalls,
             ^
ResultData.cpp:642:15: error: ‘nonCalls’ was not declared in this scope
     NonCalls& nonCalls,
               ^
ResultData.cpp:643:17: error: expected primary-expression before ‘*’ token
     AlleleParser* parser) {
                 ^
ResultData.cpp:643:27: error: expected ‘)’ before ‘{’ token
     AlleleParser* parser) {
                           ^
ResultData.cpp:643:27: error: expected ‘;’ before ‘{’ token
ResultData.cpp:724:1: error: expected ‘}’ at end of input
 }
 ^
ResultData.cpp:724:1: error: expected ‘}’ at end of input
Makefile:161: recipe for target 'ResultData.o' failed
make: *** [ResultData.o] Error 1

**Comment by morningjasimine** [comment]
[ 93%] Linking CXX executable ../bin/freebayes
../SeqLib/lib/libseqlib.a(libseqlib_a-GenomicRegion.o)：在函数‘SeqLib::GenomicRegion::ChrName(SeqLib::BamHeader const&) const’中：
/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/GenomicRegion.cpp:54：对‘std::invalid_argument::invalid_argument(char const*)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-GenomicRegion.o)：在函数‘SeqLib::GenomicRegion::GenomicRegion(std::string const&, SeqLib::BamHeader const&)’中：
/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/GenomicRegion.cpp:135：对‘std::invalid_argument::invalid_argument(char const*)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-GenomicRegion.o)：在函数‘SeqLib::GenomicRegion::GenomicRegion(int, int, int, char)’中：
/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/GenomicRegion.cpp:174：对‘std::invalid_argument::invalid_argument(char const*)’未定义的引用
/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/GenomicRegion.cpp:177：对‘std::invalid_argument::invalid_argument(char const*)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamReader.o)：在函数‘std::vector<SeqLib::GenomicRegion, std::allocator<SeqLib::GenomicRegion> >::_M_range_check(unsigned long) const’中：
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/stl_vector.h:803：对‘std::__throw_out_of_range_fmt(char const*, ...)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamReader.o)：在函数‘std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::~_Sp_counted_base()’中：
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/shared_ptr_base.h:117：对‘operator delete(void*, unsigned long)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamReader.o)：在函数‘std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::~_Sp_counted_base()’中：
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/shared_ptr_base.h:117：对‘operator delete(void*, unsigned long)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamReader.o)：在函数‘std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<std::vector<SeqLib::GenomicRegion, std::allocator<SeqLib::GenomicRegion> >*>(std::vector<SeqLib::GenomicRegion, std::allocator<SeqLib::GenomicRegion> >*)’中：
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/shared_ptr_base.h:578：对‘operator delete(void*, unsigned long)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamReader.o)：在函数‘std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<std::unordered_map<int, SeqLib::TIntervalTree<int, unsigned long>, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<int const, SeqLib::TIntervalTree<int, unsigned long> > > >*>(std::unordered_map<int, SeqLib::TIntervalTree<int, unsigned long>, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<int const, SeqLib::TIntervalTree<int, unsigned long> > > >*)’中：
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/shared_ptr_base.h:578：对‘operator delete(void*, unsigned long)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamReader.o)：在函数‘SeqLib::TIntervalTree<int, unsigned long>::~TIntervalTree()’中：
/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/../SeqLib/IntervalTree.h:87：对‘operator delete(void*, unsigned long)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamReader.o):/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/../SeqLib/IntervalTree.h:89: 跟着更多未定义的参考到 operator delete(void*, unsigned long)
../SeqLib/lib/libseqlib.a(libseqlib_a-BamRecord.o)：在函数‘SeqLib::BamRecord::SetQualities(std::string const&, int)’中：
/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/BamRecord.cpp:330：对‘std::invalid_argument::invalid_argument(char const*)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamRecord.o)：在函数‘SeqLib::BamRecord::GetSmartStringTag(std::string const&) const’中：
/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/BamRecord.cpp:529：对‘std::basic_ios<char, std::char_traits<char> >::operator bool() const’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamRecord.o)：在函数‘SeqLib::BamRecord::GetSmartIntTag(std::string const&) const’中：
/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/BamRecord.cpp:554：对‘std::basic_ios<char, std::char_traits<char> >::operator bool() const’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamRecord.o)：在函数‘SeqLib::BamRecord::GetSmartDoubleTag(std::string const&) const’中：
/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/BamRecord.cpp:577：对‘std::basic_ios<char, std::char_traits<char> >::operator bool() const’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamRecord.o)：在函数‘SeqLib::BamRecord::BamRecord(std::string const&, std::string const&, SeqLib::GenomicRegion const*, SeqLib::Cigar const&)’中：
/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/BamRecord.cpp:592：对‘std::invalid_argument::invalid_argument(char const*)’未定义的引用
/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/BamRecord.cpp:596：对‘std::invalid_argument::invalid_argument(char const*)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamRecord.o)：在函数‘SeqLib::CigarField::CigarField(char, unsigned int)’中：
/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/BamRecord.cpp:655：对‘std::invalid_argument::invalid_argument(char const*)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamRecord.o)：在函数‘std::_Sp_counted_deleter<bam1_t*, SeqLib::free_delete, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::~_Sp_counted_deleter()’中：
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/shared_ptr_base.h:462：对‘operator delete(void*, unsigned long)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamRecord.o)：在函数‘std::_Sp_counted_deleter<bam1_t*, SeqLib::free_delete, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::~_Sp_counted_deleter()’中：
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/shared_ptr_base.h:462：对‘operator delete(void*, unsigned long)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamHeader.o)：在函数‘SeqLib::BamHeader::sam_hdr_read2(std::string const&) const’中：
/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/BamHeader.cpp:107：对‘std::basic_ios<char, std::char_traits<char> >::operator bool() const’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamHeader.o)：在函数‘SeqLib::BamHeader::IDtoName(int) const’中：
/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/BamHeader.cpp:160：对‘std::invalid_argument::invalid_argument(char const*)’未定义的引用
/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/BamHeader.cpp:163：对‘std::out_of_range::out_of_range(char const*)’未定义的引用
/nfs1/public2/User/lxf/soft/freebayes/SeqLib/src/BamHeader.cpp:166：对‘std::out_of_range::out_of_range(char const*)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamHeader.o)：在函数‘std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > >*>(std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > >*)’中：
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/shared_ptr_base.h:578：对‘operator delete(void*, unsigned long)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamHeader.o)：在函数‘std::_Sp_counted_ptr<std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > >*, (__gnu_cxx::_Lock_policy)2>::~_Sp_counted_ptr()’中：
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/shared_ptr_base.h:365：对‘operator delete(void*, unsigned long)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamHeader.o)：在函数‘std::_Sp_counted_ptr<std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > >*, (__gnu_cxx::_Lock_policy)2>::~_Sp_counted_ptr()’中：
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/shared_ptr_base.h:365：对‘operator delete(void*, unsigned long)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamHeader.o)：在函数‘std::_Sp_counted_deleter<bam_hdr_t*, bam_hdr_delete, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::~_Sp_counted_deleter()’中：
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/shared_ptr_base.h:462：对‘operator delete(void*, unsigned long)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamHeader.o)：在函数‘std::_Sp_counted_deleter<bam_hdr_t*, bam_hdr_delete, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::~_Sp_counted_deleter()’中：
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/shared_ptr_base.h:462：对‘operator delete(void*, unsigned long)’未定义的引用
../SeqLib/lib/libseqlib.a(libseqlib_a-BamHeader.o):/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/shared_ptr_base.h:374: 跟着更多未定义的参考到 operator delete(void*, unsigned long)
collect2: 错误：ld 返回 1
gmake[3]: *** [../bin/freebayes] 错误 1
gmake[3]: 离开目录“/nfs1/public2/User/lxf/soft/freebayes/build”
gmake[2]: *** [CMakeFiles/freebayes.dir/all] 错误 2
gmake[2]: 离开目录“/nfs1/public2/User/lxf/soft/freebayes/build”
gmake[1]: *** [all] 错误 2
gmake[1]: 离开目录“/nfs1/public2/User/lxf/soft/freebayes/build”
make: *** [freebayes] 错误 2

**Comment by ekg** [comment]
I'm sorry but I can't read the error messages here. What version of Ubuntu?
What version of gcc?

**Comment by tseemann** [comment]
@serine have you looked at the conda and brew packages for freebayes?  they contain patches to build freebayes still:

```    # make -j N results in: make: *** [all] Error 2
    # Reported 16 Jan 2017 https://github.com/ekg/freebayes/issues/356
    ENV.deparallelize

    # Works around ld: internal error: atom not found in symbolIndex
    # Reported 21 Jul 2014 https://github.com/ekg/freebayes/issues/83
    inreplace "vcflib/smithwaterman/Makefile", "-Wl,-s", "" if OS.mac?

    # Fixes bug ../vcflib/scripts/vcffirstheader: file not found
    # Reported 1 Apr 2017 https://github.com/ekg/freebayes/issues/376
    inreplace "scripts/freebayes-parallel" do |s|
      s.gsub! "../vcflib/scripts/vcffirstheader", "vcffirstheader"
      s.gsub! "../vcflib/bin/vcfstreamsort", "vcfstreamsort"
    end
```

**Comment by javanOkendo** [comment]
Hi all,

I am also getting the following error:
./scripts/update_version.sh ./
DETECTED_VERSION = v1.3.2-44-gfce9620
CURRENT_VERSION  = 
Updating version file.
wget -q http://hypervolu.me/freebayes/build/v1.3.2-44-gfce9620 &
cmake -H. -Bbuild && cmake --build build -- 
/bin/sh: cmake: command not found
make: *** [freebayes] Error 127

**Comment by ekg** [comment]
You'll need cmake. The build is run by cmake now.

**Comment by javanOkendo** [comment]
I have no permission to do that on our HPC server. Is there away I can do
this?

**Comment by ekg** [comment]
This is a very standard build tool on Linux. Please talk to your system
administrator about this.
