### ISSUE TITLE
Cannot set region 

### ISSUE THREAD

**Issue by bacms2** [freebayes/freebayes#342]
Hi Erik,

I am trying to run freebayes in parallel so generated the regions I wanted using bamtools and coverage_to_regions.py as described on the documentation. However when I try to run freebayes using the -r option followed by any of the intervals calculated on the step before I get the following error: 
$ freebayes -r 1:37016744-37108091 -f Oryza_indica.ASM465v1.dna.toplevel.fa indica_combined_samples.bam
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated.
Failed to load index for indica_combined_samples.bam. Rebuild samtools index
ERROR(freebayes): Could not SetRegion to 1:37016744..37108091

However the region exhibits in the fasta file and I don't have any problems running freebayes if I don't specify a region. 

Any idea what could be causing it?

**Comment by robsyme** [comment]
It looks to me as though your bam file is truncated and/or missing the index. Do you have both indica_combined_samples.bam and indica_combined_samples.bam.bai in the current directory?
