### ISSUE TITLE
Segfault with v1.1.0

### ISSUE THREAD

**Issue by TomaszSuchan** [freebayes/freebayes#344]
Hi Erik,
thanks for putting a lot of effort in updating freebayes! I'm getting some troubles running the newest version though.

With v1.1.0:
```
freebayes/bin/freebayes -b test-sorted.bam -f ../reference.fasta -v test2.vcf -d
Opening output file: test2.vcf ...
loading fasta reference ../reference.fasta
Opening BAM format alignment input file: test-sorted.bam ...
 done
Number of ref seqs: 720537
Number of target regions: 0
no sample list file given, reading sample names from bam file
found 1 samples in BAM file
Segmentation fault (core dumped)
```

Everything works well with v1.0.2:
```
freebayes -b test-sorted.bam -f ../reference.fasta -v test2.vcf -d
Opening output file: test2.vcf ...
loading fasta reference ../reference.fasta
Opening BAM fomat alignment input file: test-sorted.bam ...
 done
Number of ref seqs: 720537
Number of target regions: 0
no sample list file given, reading sample names from bam file
found 1 samples in BAM file
loading first target
to next target
processing position 8200 in sequence scaffold_10
alignment: 2_2205_3457_27131
[...]
```

Please let me know if I can help debugging this!

**Comment by walaj** [comment]
Hi Tomasz, can you run this in gdb and post the backtrace? Will be helpful in figuring this out.

**Comment by kyleabeauchamp** [comment]
FWIW, I also ran into an issue where a BAM worked in 1.02 and failed in 1.10.  My issue possibly had to due with ambiguous nucleotides and the traceback was generated by this line: https://github.com/ekg/freebayes/blob/25d07ae5541f276482b88c4880f7579ea77357ad/src/AlleleParser.cpp#L1015

**Comment by TomaszSuchan** [comment]
Hi Jeremiah,
it gives:
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004b50af in strcpy (
    __src=0x7fffef0f8010 "##fileformat=VCFv4.2\n##fileDate=20161124\n##source=freeBayes v1.1.0\n##reference=../reference.fasta\n##contig=<ID=scaffold_1,length=16909>\n##contig=<ID=scaffold_2,length=34426>\n##contig=<ID=scaffold_3,le"..., __dest=0x7ffffdd9b960 <error: Cannot access memory at address 0x7ffffdd9b960>)
    at /usr/include/x86_64-linux-gnu/bits/string3.h:110
110       return __builtin___strcpy_chk (__dest, __src, __bos (__dest));
```

My `reference.fasta` does not include IUPAC codes (except N).

**Comment by walaj** [comment]
@TomaszSuchan Hmm, still not sure where this is coming from. Any way to provide a more verbose backtrace or narrow it down to a minimal BAM that is producing this? 

For instance, I am wondering if you just trim your input to a single read, if it is still seqfaulting. Could be something unexpected in the header then.

**Comment by jgarbe256** [comment]
I'm also getting a segfault with 1.1.0 at the same point. The original poster's reference has a large number of reference contigs, as do I. I cut down my reference file to 50,000 contigs and freebayes was able to run without a problem. 

Opening BAM format alignment input file: bwa.bam ...
 done
Number of ref seqs: 507413
Number of target regions: 0
no sample list file given, reading sample names from bam file
found 1 samples in BAM file

Program received signal SIGSEGV, Segmentation fault.
0x0000000000494248 in split (s=<value optimized out>, delims="\n",
    elems=std::vector of length 0, capacity 0) at split.cpp:21
21	split.cpp: No such file or directory.
	in split.cpp

(gdb) bt
#0  0x0000000000494248 in split (s=<value optimized out>, delims="\n",
    elems=std::vector of length 0, capacity 0) at split.cpp:21
#1  0x0000000000494419 in split (s=<value optimized out>,
    delims=<value optimized out>) at split.cpp:32
#2  0x00000000004b7fba in vcflib::VariantCallFile::parseHeader (this=0x82dc60,
    hs=<value optimized out>) at ../vcflib/src/Variant.cpp:1182
#3  0x000000000044e2c0 in openForOutput (this=0x82d5e0,
    argc=<value optimized out>, argv=<value optimized out>)
    at ../vcflib/src/Variant.h:124
#4  setupVCFOutput (this=0x82d5e0, argc=<value optimized out>,
    argv=<value optimized out>) at AlleleParser.cpp:575
#5  AlleleParser::AlleleParser (this=0x82d5e0, argc=<value optimized out>,
    argv=<value optimized out>) at AlleleParser.cpp:925
#6  0x0000000000407a8f in main (argc=5, argv=0x7fffffffde58)
    at freebayes.cpp:78

**Comment by jgarbe256** [comment]
It looks like freebayes is creating a single string containing the entire vcf header, which gets quite big when the reference has a lot of contigs with long names, causing stack space depletion. Increasing the maximum stack size with "ulimit -s" seems to take care of the problem.
