### ISSUE TITLE
Out of bounds error with 1.10.4

### ISSUE THREAD

**Issue by kyleabeauchamp** [freebayes/freebayes#345]
I've noticed that some of my freebayes jobs are failing after the 1.10.4 upgrade with the following exception:  

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 0) >= this->size() (which is 0)
```

Things work fine after downgrading back to 1.0.2.9

**Comment by walaj** [comment]
Can you give us a traceback from gdb? Would help find the issue.
