### ISSUE TITLE
After bamleftaligning, result is an invalid BAM file

### ISSUE THREAD

**Issue by ihodes** [freebayes/freebayes#346]
It appears as though the header is dropped (both with -c option to BAM file, and without it to a SAM file). The alignments, in the SAM file, are there, just no header lines. Is there a suggested way to keep the header?

Hex inspection of BAM before `bamleftalign`:

```
00000000: 1f8b 0804 0000 0000 00ff 0600 4243 0200  ............BC..
00000010: ba07 ed59 5d88 5c57 1d3f d9b5 6966 2b45  ...Y].\W.?..if+E
```

and after
```
00000000: 1f8b 0804 0000 0000 00ff 0600 4243 0200  ............BC..
00000010: 7412 e59d 4b6f 23cb 75c7 39a2 9e0b 7597  t...Ko#.u.9...u.
```

Trying to `samtools view` the file gives me "[bam_header_read] invalid BAM binary header (this is not a BAM file).". 

I'm likely missing something very obvious here; would appreciate any pointers!

**Comment by ekg** [comment]
Just to be clear, how exactly are you running bamleftalign?

**Comment by ihodes** [comment]
`cat rna.bam | ./freebayes/bin/bamleftalign -c -f b37decoy.fasta > out.bam`

**Comment by ekg** [comment]
Well, that's exactly what happens to me too.

I think the update to seqlib may have broken it.

**Comment by walaj** [comment]
Quick thought - Would adding a "-" to the bamleftalign call fix this (i.e. Samtools-style piping)? I can't recall right now how this is wired up, but SeqLib uses the "-" as a keyword for reading from stdin.

**Comment by ekg** [comment]
@walaj that doesn't fix it for me :/

**Comment by walaj** [comment]
Nevermind, it looks like there may be a missing "writeheader" call in the SeqLib version. I can update my standing PR with this fix.

**Comment by ekg** [comment]
I'll be happy to merge that in!
