### ISSUE TITLE
How does bamleftalign realign complex indels?

### ISSUE THREAD

**Issue by ihodes** [freebayes/freebayes#349]
E.g. if the reference is

`AAAGTGGAAA` and the indel is `GTGG`, such that the indel in the BAM is as follows:

`AAAGTGG_GTGG_AAA`

Will bamleftalign be able to left-normalize it as below?

`AAA_GTGG_GTGGAAA`

**Comment by ekg** [comment]
I think it should be able to handle this. Have you seen what it does in
this case?

**Comment by ihodes** [comment]
Unfortunately, I'm blocked on this right now https://github.com/ekg/freebayes/issues/346
