### ISSUE TITLE
Do Freebayes work with bam from star(a RNA-seq aligner)?

### ISSUE THREAD

**Issue by jfmao** [freebayes/freebayes#350]
Dear freebayes friends,

Great to write to you.

We would like to call variant by freebayes from our bam files generated by STAR. But, we failed times. "Segmentation fault (core dumped)" is the only prompt we got from freebayes. Our RNA-seq data were prepared from haploid tissues.

We are wondering if Freebayes work with bam from STAR? Could you please provide us any helps? You know, Freebayes is the great tools for us to call variant for haploids. Freebayes is greatly important for us. By the way, samtools could work with our bam files.

More on STAR:
(1) the paper: http://bioinformatics.oxfordjournals.org/content/29/1/15
(2) the pages: https://github.com/alexdobin/STAR/releases

Thanks in advance. Looking forward to hearing from you.

Best wishes,

Jian-Feng

**Comment by winni2k** [comment]
I think this post may be relevant https://github.com/ekg/freebayes/issues/427

**Comment by winni2k** [comment]
According to this issue (https://github.com/ekg/freebayes/issues/58), I think the answer has been "Yes" since around 2016.
