### ISSUE TITLE
Error: VCF header contains multiple field declarations with the same ID=AC

### ISSUE THREAD

**Issue by Rehabahmed2015** [freebayes/freebayes#353]
Hi Erik,
I am trying to do stat on a  Freebayes VCF file using rtg tools and I got this:
Error: VCF header contains multiple field declarations with the same ID=AC
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Total number of alternate alleles in called genotypes">

Could you help?

**Comment by Rehabahmed2015** [comment]
As I separated the vcf into 2 vcfs, I think something went wrong. Now rtg stat is working.

**Comment by junhouhui** [comment]
hi, i have same problem. May i ask you how you solve this?
