### ISSUE TITLE
The GT and GL  are inconsistent e.g. 1/1:26:28:-80.014,0,-1.17865:950:74:2

### ISSUE THREAD

**Issue by GuyReeves** [freebayes/freebayes#354]
HI 

I have been running freebayes for a while but I have noticed that GT and GL  are not always consistent.
for instance based on GL the most likely GT =0/1  -  by eye I think it should be 0/0
 1/1:26:28:-80.014,0,-1.17865:950:74:2

I know this is not a fundamental flaw in the program, but I cannot figure out from pervious questions what is going on and what parameters I should change.

Thanks for any help 

Guy

I am running  freebayes in Galaxy (1.0.2.29--1).  This the command 
ln -s "/home/galaxy/galaxy/database/files/000/dataset_317.dat" "localref.fa" && samtools faidx "localref.fa" 2>&1 || echo "Error running samtools faidx for FreeBayes" >&2 && ln -s "/home/galaxy/galaxy/database/files/014/dataset_14251.dat" "localbam_0.bam" && ln -s "/home/galaxy/galaxy/database/files/_metadata_files/002/metadata_2147.dat" "localbam_0.bam.bai" && freebayes --bam "localbam_0.bam" --fasta-reference "localref.fa" --vcf "/home/galaxy/galaxy/database/files/014/dataset_14252.dat" -m "30" -q "20" -R "0" -Y "0" -e "1000" -F "0.2" -C "2" --min-alternate-qsum "0" -G "1" --min-coverage "10"

**Comment by zipho** [comment]
Was there any solution to this issue?
