### ISSUE TITLE
/bin/bash: freebayes: command not found

### ISSUE THREAD

**Issue by mhimanshu11** [freebayes/freebayes#360]
I am trying to use freebayes-parallel and all the other issues have been resolved apart from "/bin/bash: freebayes: command not found". 

freebayes is working fine and I am getting the output but unfortunately can't able to get anything from the freebayes-parallel.
Can you help in figuring out, what could be the possible error here?
Thank you,
Himanshu

**Comment by ekg** [comment]
You need to include freebayes in your path. Search for "Linux bash path" to
find relevant documentation.
