### ISSUE TITLE
New allele qualities not == in length to sequence (core dumped)

### ISSUE THREAD

**Issue by mrtnb** [freebayes/freebayes#361]
Freebayes crashes with error message:

> new allele qualities not == in length to sequence: Sx8drs-SAMPLE:C38WVACXX_1:8:2116:1266365:0:null:81:81:10267:-:NTNAACNCAAAACCNAATCCAACCCNTNCCCCTCCACNAANNNAANCCCTNCCCNAACCCNAACCCTANGCCNATTCCTAC:10267:81N:-6.4:-6.4
freebayes: AlleleParser.cpp:1016: void RegisteredAlignment::addAllele(Allele, bool, int, bool): Assertion `false' failed.
/bin/sh: line 1:  7542 Aborted                 (core dumped)

It seems to complain about a quality string in the alignment not having the same length as the read. Here is the relevant read pair from the alignment:

```
C38WVACXX_1:8:2116:1266365:0    99      1       10050   28      14M4D82M4S      =       10349   318     AACCCTAACCCTAAAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAAACCTACCCCTAACCCTCCC    <BBBFFFFFFFFFIIFIFIFFFIIIFIFBBFFIIFFFFIIFIFBFFFFFB<BFIIIIIIFFFFFBFFBBBFFBFB7<B<BBBBFBB'7BBBFBB<BB'77  NM:i:6  MD:Z:14^CCCT67C4A9      AS:i:76 XS:i:73 MC:Z:81S19M     MQ:i:28 RG:Z:SAMPLE.2
C38WVACXX_1:8:2116:1266365:0    147     1       10349   28      81S19M  =       10050   -318    NTNAACNCAAAACCNAATCCAACCCNTNCCCCTCCACNAANNNAANCCCTNCCCNAACCCNAACCCTANGCCNATTCCTACCCCTACCCTAACCCTAACC    !'!'00!'000'0'!'0''''0'00!0!'77'0'''0!00!!!'0!'0''!7''!77<<0!<077''0!'<0!0''<B0''''<'07<<700'7'<'777  NM:i:0  MD:Z:19 AS:i:19 XS:i:21 MC:Z:14M4D82M4S MQ:i:28 RG:Z:SAMPLE.2
```
Both read string and quality string are of length 100. Note that in the error message above freebayes only displays the first 81 bases from the second read and its CIGAR string starts with 81S.

Freebayes version:  v1.1.0-4-gb6041c6

**Comment by mrtnb** [comment]
Could this be related to #311?

**Comment by marcovth** [comment]
Same problem ...

new allele qualities not == in length to sequence: unknown:SRR4159313.104847930:null:125:125:1978665:-:NNNNNNNGGATTTANGANNNTNCNGTTCTANANNNCATTGGCCCAANACGGGTCCCACNGGGCTAAGTCAAGGTGTGGGCAGGGCTGNTTNCNCANGGAAGCCTNNNNGGAGAATCCATGNNNNN:1978665:125N:-6.4:-6.4
Assertion failed: (false), function addAllele, file AlleleParser.cpp, line 1016.
Abort trap: 6

**Comment by senaj** [comment]
Sam problem...
new allele qualities not == in length to sequence: unknown:m180111_022607_00125_c101401142550000001823302903141850_s1_X0/99843/ccs#CCCGAGGAAGAGTTTA:null:2:2:26:-:TA:26:2N:-13.8:-13.8
freebayes: AlleleParser.cpp:1016: void RegisteredAlignment::addAllele(Allele, bool, int, bool): Assertion `false' failed.

**Comment by ekg** [comment]
I guess we could change this to raise a warning and not exit. Would someone
with this problem please share a test case?

**Comment by senaj** [comment]
Hi ekg,
This seems to be an issue with version v1.1.0-4-gb6041c6 .
When I run freebayes version v1.0.0 freebayes will run.

**Comment by ekg** [comment]
Ok let me try to reproduce with the read listed above.
