### ISSUE TITLE
set different global ploidy for many samples

### ISSUE THREAD

**Issue by ekg** [freebayes/freebayes#363]
The `--cnv-map` parameter allows passing a file that sets the ploidy for each region and each sample, but in many cases we want to set the ploidy for a sample for the entire run.

So the map should be changed to allow this easily without extra scripting.

Maybe the name of the parameter should change or be extended? It is confusing.

**Comment by apfuentes** [comment]
Dear Erik,
Any idea when this function will be available for users?

Thanks

**Comment by ekg** [comment]
Hello! I had started to implement something but I need to finish it. The
basic functionality is just to set a global ploidy for samples. I guess the
easiest way is to modify the cnv-map input format so that this is easy to
do without listing the entire chromosome lengths and chromosomes for each
sample.

Sorry for the delay on this!

**Comment by apfuentes** [comment]
Ok, no problem. Thanks very much. Looking forward to use freebayes in my data :)
Hope all is going well.
Cheers
