### ISSUE TITLE
using --variant-input does not to report some variants

### ISSUE THREAD

**Issue by parlar** [freebayes/freebayes#368]
Hi!

I thought I'd use freebayes and to interrogate bams for the presence (and allele frequencies) of a specific sets of variants.
I'm running it like this: 
freebayes -@ $vcf --min-alternate-fraction 0 --only-use-input-alleles --pooled-continuous --report-monomorphic -t tmp.bed -f $hg19 $bam 
It would be quite handy to look manually at data this way, for certain somatic variants to see if there is any evidence at all there. However, I note that some variants present in the input vcf are not reported. This is rare but still an issue. 
Are you aware of this? The input vcf has been normalized and decomposed using vt, can this be causing the problem? I can supply test data if you want to look for bugs.

**Comment by ekg** [comment]
Test data would be very helpful. Please let me know if you can make a
smallish example.

**Comment by parlar** [comment]
Hi Erik, 

I'm enclosing some files here, zipped together.

16052301-ensemble.b.vcf.vep.vcf.gz
16052301-ensemble.a.vcf.vep.vcf.gz
16052301-ensemble.c.vcf.vep.vcf.gz
16052301-ensemble.c.vcf.vep.vcf.gz.tbi
16052301-ensemble.a.vcf.vep.vcf.gz.tbi
16052301-ensemble.b.vcf.vep.vcf.gz.tbi
tmp2.bed
16052301-ready.reg.bam
16052301-ready.reg.bam.bai

The examples are run like this:
freebayes -@ 16052301-ensemble.{a,b,c}.vcf.vep.vcf.gz --min-alternate-fraction 0 -l --only-use-input-alleles --pooled-continuous --report-monomorphic -t tmp2.bed -f /home/bcbio_root/share/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa 16052301-ready.reg.bam

There are two variants in the files that I want to recall:
1. chr5    112175614       .       AC      A
2. chr5    112175615       .       C       A

File "a" contains variant 1 only, file "b" contains variant 2 only, file "c" contains both variants (1+2).  

Both variants are called individually (example a,b), but not together (example c). The output from "c" only contains  variant 1 (chr5	112175614	.	ACC	AC).

This is an example with overlapping variants. I think I noticed "lost" variants also that were not part of such overlaps, I'll try to find more examples.

Kind regards, 

Pär












[files.zip](https://github.com/ekg/freebayes/files/820610/files.zip)

**Comment by parlar** [comment]
Should mention that I'm running freebayes v1.1.0-9-g09d4ecf .

I notice that most call gaps are of the form listed above, though I'm compiling a few other examples as well.
