### ISSUE TITLE
Sample output order inconsistency with 1.1.0 SeqLib development version 

### ISSUE THREAD

**Issue by chapmanb** [freebayes/freebayes#369]
We're running in bcbio with the lighterweight SeqLib PR from @walaj (PR #338), version 1.1.0-9 and running into an issue with sample ordering consistency for multi-BAM inputs. We split up calling into regions, call identically, then concatenate the outputs together. @phu5ion identified an issue where the output sample ordering in the VCF is inconsistent for the same version and command line inputs:

https://github.com/chapmanb/bcbio-nextgen/issues/1848#issuecomment-285222225

We have a workaround using `bcftools view -s` to force a consistent sample order, but thought this was an issue that might cause problems for other users as well. It would be helpful if the output was consistently sorted for the same BAM inputs.

**Comment by walaj** [comment]
@ekg - Can you direct me to where the order of the VCFs is being formed in the code? It sounds like this may be related to some differences between BamTools vs SeqLib in perhaps the order that reads are read from a "multi" reader? Or something different in the order of concatenating the headers?

I looked through a bit and saw the ``sampleList`` structure, but thought you might be able to quickly point me where to focus, or if this is the right structure to consider for this issue. I can then see how to address with SeqLib.

**Comment by lparsons** [comment]
@ekg Any update on this? It'd be nice to be able to pass in some list or something to force the order to be consistent. I'm probably going to implement a workaround similar to @chapmanb using `bcftools view -s`.
