### ISSUE TITLE
genotype quality with FreeBayes

### ISSUE THREAD

**Issue by Ana1335** [freebayes/freebayes#370]
Hi all, this is the first time that I am using FreeBayes. I have faced with a question, I would appreciate any help.
I have got a vcf file made by FreeBayes, genotype quality is missing. I want to filter out those below the cutoff value. Therefore I want to know how can I get (calculate) genotype quality from genotype likelihood?

**Comment by ekg** [comment]
You need to add a flag to the run. --genotype-qualities I believe.
