### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by SusanaFreitas** [freebayes/freebayes#375]
Dear all,
I have been trying to re-install FB, but I keep having the same error:

make[2]: Leaving directory `/home/bo1sdf/softwares/freebayes/vcflib/smithwaterman'
g++ -std=c++11 -O3 -D_FILE_OFFSET_BITS=64 -g -I../ttmath -I../bamtools/src/ -I../vcflib/src/ -I../vcflib/tabixpp/ -I../vcflib/smithwaterman/ -I../vcflib/multichoose/ -I../vcflib/filevercmp/ -I../vcflib/fastahack/ -I../vcflib/tabixpp/htslib -I../SeqLib -I../SeqLib/htslib -c ../vcflib/src/Variant.cpp
cc1plus: error: unrecognized command line option "-std=c++11"
make[1]: *** [Variant.o] Error 1
make[1]: Leaving directory `/home/bo1sdf/softwares/freebayes/src'
make: *** [all] Error 2

Does anyone know what is wrong? I searched online for the "cc1plus: error: unrecognized command line option "-std=c++11"" line, but I only found that I should update C++.
Thanks in advance,
Susana

**Comment by walaj** [comment]
You may need to update the compiler. What is the g++ version (gcc --version)?

**Comment by SusanaFreitas** [comment]
Hi, thanks for your answer!
4.4.7, is it still compatible? I am downloading freebayes in a server where I don't have sudo access...


$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE

**Comment by walaj** [comment]
It is not unfortunately, I recommend you have the sys admin install an updated version. This will be of much value, well outside of building this tool. They're already to GCC 5.3 now (at least) so an upgrade is due.

**Comment by SusanaFreitas** [comment]
The server has more recent versions of the GCC compiler available in modules, so I loaded the 5.3 version and the installation finally worked. I apologise I haven’t tried it sooner, I wasn't quite sure what the problem was (and how to fix it), so I didn't know what to look for.

Thanks for all the help!!
