### ISSUE TITLE
freebayes-parallel has hard-coded ../../vcflib/scripts/ for 2 of 3

### ISSUE THREAD

**Issue by tseemann** [freebayes/freebayes#376]
```
cat "$regionsfile" | parallel -k -j "$ncpus" "${command[@]}" --region {}
) | ../vcflib/scripts/vcffirstheader \
    | ../vcflib/bin/vcfstreamsort -w 1000 | vcfuniq # remove duplicates at region edges
```

This makes it unusable as a general installed script. 

It did not used to be like this - what happened?

Note that `vcfuniq` at the end does *not* have a path.

**Comment by virpatel524** [comment]
I had to change some of this script myself, but I agree, it shouldn't be hard-coded.

**Comment by crazyhottommy** [comment]
I had the same problem, could you please solve this?
Thanks!

**Comment by tseemann** [comment]
@crazyhottommy you just have to remove the `../vcflib/scripts/` parts.

**Comment by crazyhottommy** [comment]
@tseemann thanks! that's what I did...

**Comment by tseemann** [comment]
@crazyhottommy i've corrected it in Linuxbrew/Homebrew and it's patched in Bioconda.
