### ISSUE TITLE
Publication

### ISSUE THREAD

**Issue by aleferna** [freebayes/freebayes#377]
any news on the publication?

**Comment by ekg** [comment]
Freebayes has never been submitted for publication. I should update the
preprint to reflect the current model. I have been procrastinating on this
for several years. My primary focus now is genome variation graphs: vg.

The preprint serves for documentation and to have a DOI. About half of
papers using freebayes cite it using this reference. The ones that don't
tend to be in medicine. It is a bit frustrating when someone uses freebayes
to find a pathogenic variant and does not cite the method appropriately,
but I have given up asking for corrections as they can be nearly impossible
for the authors to obtain.
