### ISSUE TITLE
Compiling error: no matching function for call to '(make_pair...' while making bamtools_resolve.cpp.o

### ISSUE THREAD

**Issue by dburkhardt** [freebayes/freebayes#379]
I'm trying to build Freebayes for the first time and I'm running into a compiler error. Has anyone seen this before? Any suggestions about how to solve it? I'm running gcc v6.3.1.

```
/home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp: In member function ‘bool BamTools::ResolveTool::ReadNamesFileReader::Read(std::map<std::__cxx11::basic_string<char>, ReadGroupResolver>&)’:
/home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:415:74: error: no matching function for call to ‘make_pair(__gnu_cxx::__alloc_traits<std::allocator<std::__cxx11::basic_string<char> > >::value_type&, bool)’
         resolver.ReadNames.insert( make_pair<string,bool>(fields[1], true) ) ;
                                                                          ^
In file included from /usr/include/c++/6.3.1/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/6.3.1/bits/char_traits.h:39,
                 from /usr/include/c++/6.3.1/string:40,
                 from /home/dan/local/freebayes/bamtools/src/toolkit/bamtools_tool.h:14,
                 from /home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.h:13,
                 from /home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:10:
/usr/include/c++/6.3.1/bits/stl_pair.h:493:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^~~~~~~~~
/usr/include/c++/6.3.1/bits/stl_pair.h:493:5: note:   template argument deduction/substitution failed:
/home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:415:74: note:   cannot convert ‘fields.std::vector<_Tp, _Alloc>::operator[]<std::__cxx11::basic_string<char>, std::allocator<std::__cxx11::basic_string<char> > >(1ul)’ (type ‘__gnu_cxx::__alloc_traits<std::allocator<std::__cxx11::basic_string<char> > >::value_type {aka std::__cxx11::basic_string<char>}’) to type ‘std::__cxx11::basic_string<char>&&’
         resolver.ReadNames.insert( make_pair<string,bool>(fields[1], true) ) ;
                                                                          ^
/home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp: In member function ‘bool BamTools::ResolveTool::StatsFileReader::ParseReadGroupLine(const string&, std::map<std::__cxx11::basic_string<char>, ReadGroupResolver>&)’:
/home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:612:75: error: no matching function for call to ‘make_pair(const string&, ReadGroupResolver&)’
     readGroups.insert( make_pair<string, ReadGroupResolver>(name, resolver) );
                                                                           ^
In file included from /usr/include/c++/6.3.1/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/6.3.1/bits/char_traits.h:39,
                 from /usr/include/c++/6.3.1/string:40,
                 from /home/dan/local/freebayes/bamtools/src/toolkit/bamtools_tool.h:14,
                 from /home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.h:13,
                 from /home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:10:
/usr/include/c++/6.3.1/bits/stl_pair.h:493:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^~~~~~~~~
/usr/include/c++/6.3.1/bits/stl_pair.h:493:5: note:   template argument deduction/substitution failed:
/home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:612:61: note:   cannot convert ‘name’ (type ‘const string {aka const std::__cxx11::basic_string<char>}’) to type ‘std::__cxx11::basic_string<char>&&’
     readGroups.insert( make_pair<string, ReadGroupResolver>(name, resolver) );
                                                             ^~~~
/home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp: In member function ‘bool BamTools::ResolveTool::ResolveToolPrivate::MakeStats()’:
/home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:1019:93: error: no matching function for call to ‘make_pair(std::__cxx11::string&, const bool&)’
         else resolver.ReadNames.insert( make_pair<string, bool>(al.Name, isCurrentMateUnique) );
                                                                                             ^
In file included from /usr/include/c++/6.3.1/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/6.3.1/bits/char_traits.h:39,
                 from /usr/include/c++/6.3.1/string:40,
                 from /home/dan/local/freebayes/bamtools/src/toolkit/bamtools_tool.h:14,
                 from /home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.h:13,
                 from /home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:10:
/usr/include/c++/6.3.1/bits/stl_pair.h:493:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^~~~~~~~~
/usr/include/c++/6.3.1/bits/stl_pair.h:493:5: note:   template argument deduction/substitution failed:
/home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:1019:68: note:   cannot convert ‘al.BamTools::BamAlignment::Name’ (type ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’) to type ‘std::__cxx11::basic_string<char>&&’
         else resolver.ReadNames.insert( make_pair<string, bool>(al.Name, isCurrentMateUnique) );
                                                                 ~~~^~~~
/home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp: In member function ‘void BamTools::ResolveTool::ResolveToolPrivate::ParseHeader(const BamTools::SamHeader&)’:
/home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:1051:93: error: no matching function for call to ‘make_pair(const string&, ReadGroupResolver)’
         m_readGroups.insert( make_pair<string, ReadGroupResolver>(rg.ID, ReadGroupResolver()) );
                                                                                             ^
In file included from /usr/include/c++/6.3.1/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/6.3.1/bits/char_traits.h:39,
                 from /usr/include/c++/6.3.1/string:40,
                 from /home/dan/local/freebayes/bamtools/src/toolkit/bamtools_tool.h:14,
                 from /home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.h:13,
                 from /home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:10:
/usr/include/c++/6.3.1/bits/stl_pair.h:493:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^~~~~~~~~
/usr/include/c++/6.3.1/bits/stl_pair.h:493:5: note:   template argument deduction/substitution failed:
/home/dan/local/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:1051:70: note:   cannot convert ‘rg.BamTools::SamReadGroup::ID’ (type ‘const string {aka const std::__cxx11::basic_string<char>}’) to type ‘std::__cxx11::basic_string<char>&&’
         m_readGroups.insert( make_pair<string, ReadGroupResolver>(rg.ID, ReadGroupResolver()) );
                                                                   ~~~^~
make[4]: *** [src/toolkit/CMakeFiles/bamtools_cmd.dir/build.make:255: src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_resolve.cpp.o] Error 1
make[4]: Leaving directory '/home/dan/local/freebayes/bamtools/build'
make[3]: *** [CMakeFiles/Makefile2:521: src/toolkit/CMakeFiles/bamtools_cmd.dir/all] Error 2
make[3]: Leaving directory '/home/dan/local/freebayes/bamtools/build'
make[2]: *** [Makefile:128: all] Error 2
make[2]: Leaving directory '/home/dan/local/freebayes/bamtools/build'
make[1]: *** [Makefile:42: ../bamtools/lib/libbamtools.a] Error 2
make[1]: Leaving directory '/home/dan/local/freebayes/src'
make: *** [Makefile:2: all] Error 2
```

**Comment by ekg** [comment]
Are you even with the HEAD of master?

**Comment by JHereward** [comment]
I'm getting the same error on ubuntu 16.10 with gcc 6.2.0:

/home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp: In member function ‘bool BamTools::ResolveTool::ReadNamesFileReader::Read(std::map<std::__cxx11::basic_string<char>, ReadGroupResolver>&)’:
/home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:415:74: error: no matching function for call to ‘make_pair(__gnu_cxx::__alloc_traits<std::allocator<std::__cxx11::basic_string<char> > >::value_type&, bool)’
         resolver.ReadNames.insert( make_pair<string,bool>(fields[1], true) ) ;
                                                                          ^
In file included from /usr/include/c++/6/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/6/bits/char_traits.h:39,
                 from /usr/include/c++/6/string:40,
                 from /home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_tool.h:14,
                 from /home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.h:13,
                 from /home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:10:
/usr/include/c++/6/bits/stl_pair.h:493:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^~~~~~~~~
/usr/include/c++/6/bits/stl_pair.h:493:5: note:   template argument deduction/substitution failed:
/home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:415:74: note:   cannot convert ‘fields.std::vector<_Tp, _Alloc>::operator[]<std::__cxx11::basic_string<char>, std::allocator<std::__cxx11::basic_string<char> > >(1ul)’ (type ‘__gnu_cxx::__alloc_traits<std::allocator<std::__cxx11::basic_string<char> > >::value_type {aka std::__cxx11::basic_string<char>}’) to type ‘std::__cxx11::basic_string<char>&&’
         resolver.ReadNames.insert( make_pair<string,bool>(fields[1], true) ) ;
                                                                          ^
/home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp: In member function ‘bool BamTools::ResolveTool::StatsFileReader::ParseReadGroupLine(const string&, std::map<std::__cxx11::basic_string<char>, ReadGroupResolver>&)’:
/home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:612:75: error: no matching function for call to ‘make_pair(const string&, ReadGroupResolver&)’
     readGroups.insert( make_pair<string, ReadGroupResolver>(name, resolver) );
                                                                           ^
In file included from /usr/include/c++/6/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/6/bits/char_traits.h:39,
                 from /usr/include/c++/6/string:40,
                 from /home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_tool.h:14,
                 from /home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.h:13,
                 from /home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:10:
/usr/include/c++/6/bits/stl_pair.h:493:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^~~~~~~~~
/usr/include/c++/6/bits/stl_pair.h:493:5: note:   template argument deduction/substitution failed:
/home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:612:61: note:   cannot convert ‘name’ (type ‘const string {aka const std::__cxx11::basic_string<char>}’) to type ‘std::__cxx11::basic_string<char>&&’
     readGroups.insert( make_pair<string, ReadGroupResolver>(name, resolver) );
                                                             ^~~~
/home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp: In member function ‘bool BamTools::ResolveTool::ResolveToolPrivate::MakeStats()’:
/home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:1019:93: error: no matching function for call to ‘make_pair(std::__cxx11::string&, const bool&)’
         else resolver.ReadNames.insert( make_pair<string, bool>(al.Name, isCurrentMateUnique) );
                                                                                             ^
In file included from /usr/include/c++/6/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/6/bits/char_traits.h:39,
                 from /usr/include/c++/6/string:40,
                 from /home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_tool.h:14,
                 from /home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.h:13,
                 from /home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:10:
/usr/include/c++/6/bits/stl_pair.h:493:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^~~~~~~~~
/usr/include/c++/6/bits/stl_pair.h:493:5: note:   template argument deduction/substitution failed:
/home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:1019:68: note:   cannot convert ‘al.BamTools::BamAlignment::Name’ (type ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’) to type ‘std::__cxx11::basic_string<char>&&’
         else resolver.ReadNames.insert( make_pair<string, bool>(al.Name, isCurrentMateUnique) );
                                                                 ~~~^~~~
/home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp: In member function ‘void BamTools::ResolveTool::ResolveToolPrivate::ParseHeader(const BamTools::SamHeader&)’:
/home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:1051:93: error: no matching function for call to ‘make_pair(const string&, ReadGroupResolver)’
         m_readGroups.insert( make_pair<string, ReadGroupResolver>(rg.ID, ReadGroupResolver()) );
                                                                                             ^
In file included from /usr/include/c++/6/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/6/bits/char_traits.h:39,
                 from /usr/include/c++/6/string:40,
                 from /home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_tool.h:14,
                 from /home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.h:13,
                 from /home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:10:
/usr/include/c++/6/bits/stl_pair.h:493:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^~~~~~~~~
/usr/include/c++/6/bits/stl_pair.h:493:5: note:   template argument deduction/substitution failed:
/home/wfl/programs/freebayes/bamtools/src/toolkit/bamtools_resolve.cpp:1051:70: note:   cannot convert ‘rg.BamTools::SamReadGroup::ID’ (type ‘const string {aka const std::__cxx11::basic_string<char>}’) to type ‘std::__cxx11::basic_string<char>&&’
         m_readGroups.insert( make_pair<string, ReadGroupResolver>(rg.ID, ReadGroupResolver()) );
                                                                   ~~~^~
src/toolkit/CMakeFiles/bamtools_cmd.dir/build.make:254: recipe for target 'src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_resolve.cpp.o' failed
make[4]: *** [src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_resolve.cpp.o] Error 1
make[4]: Leaving directory '/home/wfl/programs/freebayes/bamtools/build'
CMakeFiles/Makefile2:520: recipe for target 'src/toolkit/CMakeFiles/bamtools_cmd.dir/all' failed
make[3]: *** [src/toolkit/CMakeFiles/bamtools_cmd.dir/all] Error 2
make[3]: Leaving directory '/home/wfl/programs/freebayes/bamtools/build'
Makefile:127: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/wfl/programs/freebayes/bamtools/build'
Makefile:42: recipe for target '../bamtools/lib/libbamtools.a' failed
make[1]: *** [../bamtools/lib/libbamtools.a] Error 2
make[1]: Leaving directory '/home/wfl/programs/freebayes/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lucidv01d** [comment]
I had a similar issue. Following the [travis-ci build script](https://travis-ci.org/ekg/freebayes/builds/205046518) for the latest commit helped. Specifically I had to switch my compiler to 4.8.1 and run `git submodule update --init --recursive`

**Comment by JHereward** [comment]
I actually managed to get around this by cloning freebayes, then deleting the bamtools folder, git clone bamtools within the freebayes folder, follow the instructions on the bamtools wiki to install using cmake etc then running make in the freebayes folder
