### ISSUE TITLE
Error running freebayes on Galaxy

### ISSUE THREAD

**Issue by bernuzzf** [freebayes/freebayes#380]
Hi,

I am working with prostate cancer  tissues that have undergone RNA-seq and want to identify SNP variants. Initially I runned FreeBayes on Galaxy by adding the output BAM file generated by HISAT2, but got the following error (error exit code 3()). I then re-tried re-running FreeBayes by adding the output BAM files generated by TopHat to see whether HISAT2 produced files that FreeBayes did not recognise, but still encountered the same problem (error exit code 4()). 
I was wondering whether anyone has already encountered this problem before and perhaps could help me solve the issues. 

Many thanks for the information provided

**Comment by ekg** [comment]
Would you please try to determine which read is causing the problem? You
can add --debug and you will be able to see the last processed position. By
making a window around that position it should be possible to pick up the
reads that do this.

Many times new cigar extensions have caused issues like this in RNAseq.

**Comment by bernuzzf** [comment]
Many thanks for the reply much appreciated. I shall look into it
