### ISSUE TITLE
installing problem 

### ISSUE THREAD

**Issue by jingjin0322** [freebayes/freebayes#381]
Hi All, 

I was trying to install freebayes, and this is what I got:

jing@jing-VirtualBox:~/Downloads/freebayes$ make
wget -q http://hypervolu.me/freebayes/build/v1.1.0-3-g961e5f3-dirty &
cd src && make
make[1]: Entering directory '/home/jing/Downloads/freebayes/src'
DETECTED_VERSION = v1.1.0-3-g961e5f3-dirty
CURRENT_VERSION  = v1.1.0-3-g961e5f3-dirty
make[1]: Leaving directory '/home/jing/Downloads/freebayes/src'
jing@jing-VirtualBox:~/Downloads/freebayes$ freebayes
freebayes: command not found

Hope someone can help me out. Will really appreciate it!

Thanks,
Jing

**Comment by ekg** [comment]
You need to put freebayes in your path for the bare command to work this
way.
