### ISSUE TITLE
Source release vs. git clone

### ISSUE THREAD

**Issue by samfux84** [freebayes/freebayes#385]
Hi all,

what is the point in having source code releases (for instance https://github.com/ekg/freebayes/archive/v1.1.0.tar.gz), if one can not build the software from it, because they do not contain the submodules that one can get with:

git clone --recursive git://github.com/ekg/freebayes.git

For me a source code release only makes sense if I can actually build a software from it.

Would it be possible to provide a source code release tarball that includes the submodules ? For doing a test installation, a checkout of the current master branch is fine. But I would like to install freebayes 1.1.0 as part of a central software stack, which contains mostly versioned software. In order to transparently document this, I would need an official release, such that I can create an environment module, which requires a version number.

Best regards

Sam

**Comment by tseemann** [comment]
@samfux84 I agree with you. But do you know how to make github do this?

**Comment by ekg** [comment]
This is a long standing problem with github's handling of source tarballs
that can be worked around by making a manual release.

**Comment by samfux84** [comment]
@tseemann According to https://stackoverflow.com/questions/34719785/how-to-add-submodule-files-to-a-github-release even github support claims that it is not possible to include submodules in a release.

On hpc cluster, we try to provide a transparent versioning of softwares to users, which also allows for reproducible builds of the software.

If a scientist needs to reference a software in a publication to properly document where his results come from, then he can not just write something like

On 8. May 2017 I was running a git clone --recursive command on this or that repo.

My PhD supervisor always emphasized that from the information given in a paper (eventually including supplementary information which can be uploaded for some journals) it should be possible to reproduce the published results. In order to make this possible, a user should have some information on what version of a software he is using. This is good scientific practice.

**Comment by ekg** [comment]
It is possible to do this, but it will require an appropriate checkout and
submodule update to do. `git clone ; git checkout <commit>; git submodule
update --init --recursive` if I remember correctly.
