### ISSUE TITLE
tag v1.1.0 does not build

### ISSUE THREAD

**Issue by samfux84** [freebayes/freebayes#386]
Hi,

I tried

- git clone --recursive git://github.com/ekg/freebayes.git
- cd freebayes
- git checkout v1.1.0
- make

Compilation terminated with

```
g++ -D_FILE_OFFSET_BITS=64 -g -O2 -fPIC -ftree-vectorize -march=corei7-avx -mavx -I../ttmath -I../bamtools/src/ -I../vcflib/src/ -I../vcflib/tabixpp/ -I../vcflib/smithwaterman/ -I../vcflib/multichoose/ -I../vcflib/filevercmp/ -I../vcflib/tabixpp/htslib -I../SeqLib -I../SeqLib/htslib -c freebayes.cpp
In file included from AlleleParser.h:31:0,
                 from freebayes.cpp:28:
../vcflib/src/Variant.h:26:19: fatal error: Fasta.h: No such file or directory
 #include "Fasta.h"
                   ^
compilation terminated.
```

The file is there:

```
[sfux@develop01 freebayes]$ find . -type f -name Fasta.h
./src/Fasta.h
./vcflib/fastahack/Fasta.h
[sfux@develop01 freebayes]$
```

It seems that a -I../vcflib/fastahack/ is missing.

Best regards

Sam

**Comment by samfux84** [comment]
Just noticed that the both Fasta.h files are not exactly the same. Any idea which of the two needs to be included ?

**Comment by samfux84** [comment]
Current master branch adds -I../vcflib/fastahack/:

g++ -std=c++11 -O3 -D_FILE_OFFSET_BITS=64 -g -I../ttmath -I../bamtools/src/ -I../vcflib/src/ -I../vcflib/tabixpp/ -I../vcflib/smithwaterman/ -I../vcflib/multichoose/ -I../vcflib/filevercmp/ **-I../vcflib/fastahack/** -I../vcflib/tabixpp/htslib -I../SeqLib -I../SeqLib/htslib -c ../vcflib/src/Variant.cpp

**Comment by samfux84** [comment]
Adding -I../vcflib/fastahack/ to the Makefile:

INCLUDE = -I../ttmath -I$(BAMTOOLS_ROOT)/src/ -I$(VCFLIB_ROOT)/src/ -I$(TABIX_ROOT)/ -I$(VCFLIB_ROOT)/smithwaterman/ -I$(VCFLIB_ROOT)/multichoose/ -I$(VCFLIB_ROOT)/filevercmp/ -**I$(VCFLIB_ROOT)/fastahack/** -I$(HTSLIB_ROOT) -I$(SEQLIB_ROOT) -I$(SEQLIB_ROOT)/htslib

results in:

```
g++ -D_FILE_OFFSET_BITS=64 -g -O2 -fPIC -ftree-vectorize -march=corei7-avx -mavx -I../ttmath -I../bamtools/src/ -I../vcflib/src/ -I../vcflib/tabixpp/ -I../vcflib/smithwaterman/ -I../vcflib/multichoose/ -I../vcflib/filevercmp/ -I../vcflib/fastahack/ -I../vcflib/tabixpp/htslib -I../SeqLib -I../SeqLib/htslib -c ../vcflib/src/Variant.cpp
../vcflib/src/Variant.cpp: In member function ‘bool vcflib::Variant::canonicalize_sv(FastaReference&, std::vector<FastaReference*>, int)’:
../vcflib/src/Variant.cpp:128:5: error: ‘function’ is not a member of ‘std’
     std::function<bool(const string&)> allATGC = [](const string& s){
     ^
../vcflib/src/Variant.cpp:128:19: error: expected primary-expression before ‘bool’
     std::function<bool(const string&)> allATGC = [](const string& s){
                   ^
../vcflib/src/Variant.cpp:128:19: error: expected ‘;’ before ‘bool’
../vcflib/src/Variant.cpp:2591:1: error: expected ‘}’ at end of input
 } // end namespace vcf
 ^
../vcflib/src/Variant.cpp: At global scope:
../vcflib/src/Variant.cpp:2591:1: error: expected ‘}’ at end of input
make[1]: *** [Variant.o] Error 1
make[1]: Leaving directory `/cluster/apps/gdc/freebayes/1.1.0/freebayes/src'
make: *** [all] Error 2
```
Please provide some help on how to install freebayes 1.1.0 (the release, and not 1.1.0-3-dirty)

**Comment by pescobar** [comment]
I am having exactly the same error when trying to build freebayes/1.1.0

Did you find any solution?

**Comment by samfux84** [comment]
Hi Pablo,

my solution in the end was to check out the current master branch. The checkout of the master branch of 8. May 2017 was building fine. I don't know which commits where included on 8. May and which ones were added later (this is the main reason why I prefer releases, then you know at least what you get, and you can tell somebody else how to reproduce what you did).

The hash of the last commit on 8. May starts with g961e5f3 but I did not save the full name of the hash.

If the current version of the master branch does not build, then it is because of some commits that were added between 8. May and today ;-)

Best regards

Sam

**Comment by pescobar** [comment]
hi @samfux84 

thanks for your help. I did something similar to workaround this issue. I was trying to reproduce a build that I have in my cluster inside a singularity container. Luckily I had saved a tarball with the freebayes/1.1.0 that I had previously installed in my cluster and built correctly so I have checked all the repositories to keep in sync with my previous build. I did this:

```
   cd /usr/local/src/
   git clone --recursive git://github.com/ekg/freebayes.git
   # the release system for freebayes does git --recursive which makes hard to reproduce the same installation
   # To workaround it I do some git checkout to use the same source code installed in the cluster
   cd /usr/local/src/freebayes/ && git checkout 39e5e4b # this is the git commit for freebayes release 1.1.0
   cd /usr/local/src/freebayes/SeqLib && git checkout cce1e410ef6d2ac64972f5cacd8a0f9b86cecdd8
   cd /usr/local/src/freebayes/SeqLib/bwa && git checkout fbd4dbc03904eccd71cdca8cac7aa48da749c19c
   cd /usr/local/src/freebayes/SeqLib/htslib && git checkout 0f298ce22c5c825c506129bf242348a31630c382
   cd /usr/local/src/freebayes/SeqLib/fermi-lite && git checkout 5bc90f8d70e2b66184eccbd223a3be714c914365
   cd /usr/local/src/freebayes/bamtools && git checkout e77a43f5097ea7eee432ee765049c6b246d49baa
   cd /usr/local/src/freebayes/intervaltree && git checkout dbb4c513d1ad3baac516fc1484c995daf9b42838
   cd /usr/local/src/freebayes/vcflib && git checkout 5e3ce04f758c6df16bc4d242b18a24d725d2e6e5
   cd /usr/local/src/freebayes/vcflib/fsom && git checkout a6ef318fbd347c53189384aef7f670c0e6ce89a3
   cd /usr/local/src/freebayes/vcflib/intervaltree && git checkout b704f195e9b51d44dad68e33c209b06e63ebb353
   cd /usr/local/src/freebayes/vcflib/smithwaterman && git checkout 84c08d7eae7211d87fbcb1871dae20e6c2041e96
   cd /usr/local/src/freebayes/vcflib/fastahack && git checkout c68cebb4f2e5d5d2b70cf08fbdf1944e9ab2c2dd
   cd /usr/local/src/freebayes/vcflib/filevercmp && git checkout 1a9b779b93d0b244040274794d402106907b71b7
   cd /usr/local/src/freebayes/vcflib/tabixpp/htslib/ && git checkout 0f298ce22c5c825c506129bf242348a31630c382
   cd /usr/local/src/freebayes/vcflib/tabixpp && git checkout 80012f86dc22b13c75b73baf38195956db92473e
   cd /usr/local/src/freebayes/vcflib/multichoose && git checkout 73d35daa18bf35729b9ba758041a9247a72484a5
   cd /usr/local/src/freebayes/vcflib/googletest/ && git checkout d225acc90bc3a8c420a9bcd1f033033c1ccd7fe0
```
with this version of the source code I could build the application and hopefully I can reproduce my previous installation
