### ISSUE TITLE
build/installation error on cluster

### ISSUE THREAD

**Issue by vincentmanz** [freebayes/freebayes#387]
Hi, 
I am trying to install on a cluster freebayes. 
I have loaded these modules: 
1) cmake/3.7.1          
2) perlmodules/5.10_2   
3) binutils/2.26        
4) gcc/6.1.0 
5) python/2.2713

I have got this error, how could I have a correct installation? Which version of the compiler do  you usually use? 

login-0-0@~/nobackup/freebayes$module rm intel/2015.3
login-0-0@~/nobackup/freebayes$make
wget -q http://hypervolu.me/freebayes/build/v1.1.0-3-g961e5f3-dirty &
cd src && make
make[1]: Entering directory `/cluster/home/vincem/nobackup/freebayes/src'
DETECTED_VERSION = v1.1.0-3-g961e5f3-dirty
CURRENT_VERSION  = v1.1.0-3-g961e5f3-dirty
g++ -O3 -D_FILE_OFFSET_BITS=64 -g -I../ttmath -I../bamtools/src/ -I../vcflib/src/ -I../vcflib/tabixpp/ -I../vcflib/smithwaterman/ -I../vcflib/multichoose/ -I../vcflib/filevercmp/ -I../vcflib/fastahack/ -I../vcflib/tabixpp/htslib -I../SeqLib -I../SeqLib/htslib freebayes.o BedReader.o CNV.o fastlz.o Fasta.o Parameters.o Allele.o Sample.o Result.o AlleleParser.o Utility.o Genotype.o DataLikelihood.o Multinomial.o Ewens.o ResultData.o Dirichlet.o Marginals.o split.o LeftAlign.o IndelAllele.o Bias.o Contamination.o NonCall.o SegfaultHandler.o ../vcflib/tabixpp/tabix.o ../vcflib/tabixpp/htslib/bgzf.o ../vcflib/smithwaterman/SmithWatermanGotoh.o ../vcflib/smithwaterman/disorder.cpp ../vcflib/smithwaterman/LeftAlign.o ../vcflib/smithwaterman/Repeats.o ../vcflib/smithwaterman/IndelAllele.o Variant.o ../bamtools/lib/libbamtools.a ../SeqLib/src/libseqlib.a ../SeqLib/bwa/libbwa.a ../SeqLib/fermi-lite/libfml.a ../SeqLib/htslib/libhts.a -o ../bin/freebayes -lz -lm -lpthread
Variant.o: In function `vcflib::VariantCallFile::getHeaderLinesFromFile[abi:cxx11]()':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1295: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1273: undefined reference to `Tabix::getHeader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1278: undefined reference to `Tabix::getNextLine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
Variant.o: In function `vcflib::VariantCallFile::setRegion(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1477: undefined reference to `Tabix::setRegion(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1478: undefined reference to `Tabix::getNextLine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
Variant.o: In function `vcflib::decomposePhasedGenotype(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1530: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Variant.o: In function `vcflib::Variant::canonicalize_sv(FastaReference&, std::vector<FastaReference*, std::allocator<FastaReference*> >, int)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:190: undefined reference to `FastaReference::getSubSequence(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:204: undefined reference to `FastaReference::getSubSequence(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:208: undefined reference to `FastaReference::getSequence(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:208: undefined reference to `FastaReference::getSubSequence(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:222: undefined reference to `FastaReference::getSubSequence(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:224: undefined reference to `FastaReference::getSubSequence(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:236: undefined reference to `FastaReference::getSubSequence(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:237: undefined reference to `FastaReference::getSubSequence(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int)'
Variant.o: In function `vcflib::decomposeGenotype(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1511: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Variant.o: In function `vcflib::Variant::parsedAlternates(bool, bool, bool, float, float, float, float, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1717: undefined reference to `CSmithWatermanGotoh::Align(unsigned int&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Variant.o: In function `vcflib::VariantCallFile::removeInfoHeaderLine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1235: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
Variant.o: In function `vcflib::VariantCallFile::removeGenoHeaderLine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1252: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
Variant.o: In function `vcflib::unionInfoHeaderLines(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:2053: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:2054: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Variant.o: In function `vcflib::VariantCallFile::updateSamples(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1145: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1146: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
Variant.o: In function `vcflib::VariantCallFile::headerWithSampleNames(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1159: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1160: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
Variant.o: In function `vcflib::VariantCallFile::parseHeader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1339: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1405: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1359: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Variant.o: In function `vcflib::VariantCallFile::parseHeader()':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1303: undefined reference to `Tabix::getHeader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1308: undefined reference to `Tabix::getNextLine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
Variant.o: In function `vcflib::Variant::parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:18: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:30: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:65: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:77: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:84: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:49: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:54: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:56: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)'
Variant.o: In function `vcflib::VariantCallFile::getNextVariant(vcflib::Variant&)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1437: undefined reference to `Tabix::getNextLine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
Variant.o: In function `vcflib::VariantCallFile::infoIds[abi:cxx11]()':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1198: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
Variant.o: In function `vcflib::VariantCallFile::formatIds[abi:cxx11]()':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1217: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
Variant.o: In function `vcflib::VariantCallFile::addHeaderLine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1177: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
Variant.o: In function `vcflib::Variant::removeAlt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1982: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.cpp:1991: undefined reference to `split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
AlleleParser.o: In function `vcflib::VariantCallFile::openForOutput(std::string&)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.h:127: undefined reference to `vcflib::VariantCallFile::parseHeader(std::string&)'
AlleleParser.o: In function `AlleleParser::openBams()':
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:97: undefined reference to `SeqLib::BamReader::Open(std::string const&)'
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:90: undefined reference to `SeqLib::BamReader::Open(std::string const&)'
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:141: undefined reference to `SeqLib::BamReader::HeaderConcat() const'
AlleleParser.o: In function `AlleleParser::updateHaplotypeBasisAlleles(long, int)':
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:1199: undefined reference to `vcflib::VariantCallFile::setRegion(std::string, long, long)'
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:1218: undefined reference to `vcflib::Variant::parsedAlternates(bool, bool, bool, float, float, float, float, float, std::string, std::string)'
AlleleParser.o: In function `AlleleParser::registerAlignment(SeqLib::BamRecord&, RegisteredAlignment&, std::string&, std::string&)':
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:1426: undefined reference to `SeqLib::BamRecord::Sequence() const'
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:1875: undefined reference to `SeqLib::BamRecord::Sequence() const'
AlleleParser.o: In function `AlleleParser::updateInputVariants(long, int)':
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:2355: undefined reference to `vcflib::VariantCallFile::setRegion(std::string, long, long)'
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:2372: undefined reference to `vcflib::Variant::parsedAlternates(bool, bool, bool, float, float, float, float, float, std::string, std::string)'
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:2453: undefined reference to `SeqLib::BamHeader::Name2ID(std::string const&) const'
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:2358: undefined reference to `vcflib::VariantCallFile::setRegion(std::string)'
AlleleParser.o: In function `AlleleParser::updateAlignmentQueue(long, std::vector<Allele*, std::allocator<Allele*> >&, bool)':
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:2043: undefined reference to `SeqLib::BamRecord::GetZTag(std::string const&) const'
AlleleParser.o: In function `RegisteredAlignment':
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.h:74: undefined reference to `SeqLib::BamRecord::GetZTag(std::string const&) const'
AlleleParser.o: In function `vcflib::VariantCallFile::openForOutput(std::string&)':
/usit/abel/u1/vincem/nobackup/freebayes/src/../vcflib/src/Variant.h:127: undefined reference to `vcflib::VariantCallFile::parseHeader(std::string&)'
AlleleParser.o: In function `AlleleParser::loadReferenceSequence(std::string&)':
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:683: undefined reference to `SeqLib::BamHeader::Name2ID(std::string const&) const'
AlleleParser.o: In function `AlleleParser::loadTarget(BedTarget*)':
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:2734: undefined reference to `vcflib::VariantCallFile::setRegion(std::string)'
AlleleParser.o: In function `AlleleParser::getInputVariantsInRegion(std::string&, long, long)':
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:2237: undefined reference to `vcflib::Variant::parsedAlternates(bool, bool, bool, float, float, float, float, float, std::string, std::string)'
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:2323: undefined reference to `SeqLib::BamHeader::Name2ID(std::string const&) const'
/usit/abel/u1/vincem/nobackup/freebayes/src/AlleleParser.cpp:2229: undefined reference to `vcflib::VariantCallFile::setRegion(std::string, long, long)'
LeftAlign.o: In function `countMismatches(SeqLib::BamRecord&, std::string)':
/usit/abel/u1/vincem/nobackup/freebayes/src/LeftAlign.cpp:345: undefined reference to `SeqLib::BamRecord::Sequence() const'
LeftAlign.o: In function `leftAlign(SeqLib::BamRecord&, std::string&, bool)':
/usit/abel/u1/vincem/nobackup/freebayes/src/LeftAlign.cpp:26: undefined reference to `SeqLib::BamRecord::Sequence() const'
/usit/abel/u1/vincem/nobackup/freebayes/src/LeftAlign.cpp:27: undefined reference to `SeqLib::BamRecord::Sequence() const'
/usit/abel/u1/vincem/nobackup/freebayes/src/LeftAlign.cpp:272: undefined reference to `SeqLib::BamRecord::Sequence() const'
collect2: error: ld returned 1 exit status
make[1]: *** [../bin/freebayes] Error 1
make[1]: Leaving directory `/cluster/home/vincem/nobackup/freebayes/src'
make: *** [all] Error 2

**Comment by vincentmanz** [comment]
anyone?

**Comment by wangyugui** [comment]
make clean
cd vcflib && make clean && make && cd ..
cd src && make clean && make && cd ..

it may work.

**Comment by dmiyagi** [comment]
FYI for those coming to this post later--had a similar error and @wangyugui 's suggestion worked. 
Error I had: 

`
CMakeFiles/freebayes_OBJS.dir/src/AlleleParser.cpp.o: In function `AlleleParser::loadReferenceSequence(std::string&)':
/home/{my_dir}/project/tools/freebayes/src/AlleleParser.cpp:664: undefined reference to `SeqLib::BamHeader::Name2ID(std::string const&) const'
CMakeFiles/freebayes_OBJS.dir/src/AlleleParser.cpp.o: In function `AlleleParser::openBams()':
/home/{my_dir}/project/tools/freebayes/src/AlleleParser.cpp:78: undefined reference to `SeqLib::BamReader::Open(std::string const&)'
/home/{my_dir}/project/tools/freebayes/src/AlleleParser.cpp:122: undefined reference to `SeqLib::BamReader::HeaderConcat() const'
/home/{my_dir}/project/tools/freebayes/src/AlleleParser.cpp:71: undefined reference to `SeqLib::BamReader::Open(std::string const&)'
CMakeFiles/freebayes_OBJS.dir/src/AlleleParser.cpp.o: In function `AlleleParser::registerAlignment(SeqLib::BamRecord&, RegisteredAlignment&, std::string&, std::string&)':
/home/{my_dir}/project/tools/freebayes/src/AlleleParser.cpp:1318: undefined reference to `SeqLib::BamRecord::Sequence() const'
/home/{my_dir}/project/tools/freebayes/src/AlleleParser.cpp:1759: undefined reference to `SeqLib::BamRecord::Sequence() const'
CMakeFiles/freebayes_OBJS.dir/src/AlleleParser.cpp.o: In function `AlleleParser::updateAlignmentQueue(long, std::vector<Allele*, std::allocator<Allele*> >&, bool)':
/home/{my_dir}/project/tools/freebayes/src/AlleleParser.cpp:1944: undefined reference to `SeqLib::BamRecord::GetZTag(std::string const&, std::string&) const'
CMakeFiles/freebayes_OBJS.dir/src/AlleleParser.cpp.o: In function `AlleleParser::updateAlignmentQueue(long, std::vector<Allele*, std::allocator<Allele*> >&, bool)':
/home/{my_dir}/project/tools/freebayes/src/AlleleParser.h:71: undefined reference to `SeqLib::BamRecord::GetZTag(std::string const&, std::string&) const'
CMakeFiles/freebayes_OBJS.dir/src/AlleleParser.cpp.o: In function `AlleleParser::updateInputVariants(long, int)':
/home/{my_dir}/project/tools/freebayes/src/AlleleParser.cpp:2402: undefined reference to `SeqLib::BamHeader::Name2ID(std::string const&) const'
CMakeFiles/freebayes_OBJS.dir/src/AlleleParser.cpp.o: In function `AlleleParser::getInputVariantsInRegion(std::string&, long, long)':
/home/{my_dir}/project/tools/freebayes/src/AlleleParser.cpp:2272: undefined reference to `SeqLib::BamHeader::Name2ID(std::string const&) const'
CMakeFiles/freebayes_OBJS.dir/src/AlleleParser.cpp.o: In function `AlleleParser::toNextPosition()':
/home/{my_dir}/project/tools/freebayes/src/AlleleParser.cpp:2912: undefined reference to `SeqLib::BamHeader::Name2ID(std::string const&) const'
CMakeFiles/freebayes_OBJS.dir/src/LeftAlign.cpp.o: In function `countMismatches(SeqLib::BamRecord&, std::string)':
/home/{my_dir}/project/tools/freebayes/src/LeftAlign.cpp:345: undefined reference to `SeqLib::BamRecord::Sequence() const'
CMakeFiles/freebayes_OBJS.dir/src/LeftAlign.cpp.o: In function `leftAlign(SeqLib::BamRecord&, std::string&, bool)':
/home/{my_dir}/project/tools/freebayes/src/LeftAlign.cpp:26: undefined reference to `SeqLib::BamRecord::Sequence() const'
/home/{my_dir}/project/tools/freebayes/src/LeftAlign.cpp:27: undefined reference to `SeqLib::BamRecord::Sequence() const'
/home/{my_dir}/project/tools/freebayes/src/LeftAlign.cpp:272: undefined reference to `SeqLib::BamRecord::Sequence() const'
collect2: error: ld returned 1 exit status
`

**Comment by pjotrp** [comment]
We have a new build system. Please try that. See README.
