### ISSUE TITLE
Somatic callig with (-allele-balance-priors-off)

### ISSUE THREAD

**Issue by Klux1rst** [freebayes/freebayes#391]
Hi @ekg ,

I am building a pipeline using freebayes to detect somatic mutation in tumor-only amplicon sequencing. I have been using -F 0.03 to detect variants with low-frequency. However, I have been facing some issues. For example, one my variant that have an Allele frequency of 14% in a well covered region (>1000x), is found by Freebayes with very low confidence (QUAL ~= 3-1274_S3). After looking at this thread https://github.com/ekg/freebayes/issues/272, I have re-run my analysis including the -a (-allele-balance-priors-off) parameter, and this allows me to find the same variant with a much higher quality (563).
My question is : What does this parameter do and how does it affect the quality of the variants?
Also if you have other parameters that you can advice according to my context, it would be great! 

Thank you very much for your time.

**Comment by ekg** [comment]
This parameter is weighting the quality by an allele balance metric that is
accumulated across all the samples in the analysis. For a single sample,
this is basically just over-weighting the effect of allele balance skews
that is typically included in the genotype likelihoods. See the
documentation in
https://github.com/ekg/freebayes/blob/master/paper/main.tex for
details (build it with "make"), as this is not described in the preprint
that is serving to give freebayes a DOI.
