### ISSUE TITLE
Calling SNPs on 10X Chromium single cell data

### ISSUE THREAD

**Issue by jeffr100** [freebayes/freebayes#393]
Hi Erik,

I am trying to call SNPs from 10X Chromium data.  As I mentioned, they use CB tags for each of the UMI groups rather than RG tags.  I was thinking there might be an easy way to make one of the tools such as bamaddrg work with these tags or have freebayes deal with them natively.  Each CB tag should be converted to an RG tag and then RGs with above a certain threshold of reads total and at a particular locus should be used for SNP calling.  Here are some lines from a sample BAM file:

7001034F:326:CARMMANXX:3:1114:15461:81435       272     1       10002   0       71M27S  *       0       0  AACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCATGTACTCTGCGTTGATACCACTGCTT   BBFB7B/B<FBF/BF/FFBFFBFFB<FFFFFBFBFFF<BFFFFFFFFFFFF<FFF/FFFFBFFFFFFFFFFFFFFF7</FBBB<</<FFFFF<<<7<<        NH:i:7  HI:i:7  AS:i:69 nM:i:0  NM:i:0  CR:Z:CACTCCAGTCAACCCT   CY:Z:BBBBBFFFFFFFFBFF   CB:Z:CACTCCAGTCATCCCT-1   UR:Z:AACCCTAACC UY:Z:FFFFFFFFBF UB:Z:AACCCTAACC BC:Z:GGACACGT   QT:Z:BBBBBFFF
7001034F:326:CARMMANXX:5:2101:4670:46449        256     1       10003   1       90M8S   *       0       0  ACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACACTANCACTANCACTANAACANAC   B/<//BFFFBB/FFF/<<BBBFF/<</<FBFBBFF<F/<BF/F///<//<<</FF/<F<B<//</<FF///<///<B<#<<//<#///7<#////#//        NH:i:3  HI:i:3  AS:i:80 nM:i:3  NM:i:5  CR:Z:CGAACATTCCCATTAT   CY:Z:/BBBBFFBFFF<BBFF   CB:Z:CGAACATTCCCATTAT-1   UR:Z:TTGACCTCAA UY:Z:B/FFFB<BFB UB:Z:TTGACCTCAA BC:Z:CCTGTGCG   QT:Z:BBBBBFFF
7001034F:326:CARMMANXX:3:1103:15996:18903       256     1       10003   1       97M1S   *       0       0  ACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAAAA   BBBBBFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF<<FBBF/FFFFFFFF</BFFBBBF/B///F/FF<//</<BB<F///</B/7BF/<B/        NH:i:3  HI:i:3  AS:i:93 nM:i:1  NM:i:1  CR:Z:CGGTTAAGTGTAACGG   CY:Z:/BBBBFFBBFFFBFFF   CB:Z:CGGTTAAGTGTAACGG-1   UR:Z:CCACTGCAGA UY:Z:FFFFFFFFFF UB:Z:CCACTGCAGA BC:Z:GGACACGT   QT:Z:BBBBBFFF
7001034F:326:CARMMANXX:4:1101:16789:77807       256     1       10003   3       98M     *       0       0  ACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACACTAACCCTAAC   BBBBBFFFFFFFFFFFFFFFFF<<BBBFB<BFFFFFBFFFFFFFFBB/FFFFFF<FFFFFFF</<BFB<BBFFFFFFFF/<<B</F//<//B/////7        NH:i:2  HI:i:2  AS:i:94 nM:i:1  NM:i:1  CR:Z:CGGTTAAGTGTAACGG   CY:Z:BBBBBFFFFFFFFFFF   CB:Z:CGGTTAAGTGTAACGG-1   UR:Z:CCACTGCAGA UY:Z:FFFFFFFFFF UB:Z:CCACTGCAGA BC:Z:GGACACGT   QT:Z:BBBBBFFF

**Comment by ekg** [comment]
You were able to get some traction on this. Is that correct?

**Comment by jeffr100** [comment]
I am able to get calls for some files, but I get this error:

Exception: Cannot read past the end of the alignment's sequence.
TCAGGTGACTACATTT-GGGCCACGCCTGCTTATGCAGCTATCTTGACCATTATGTGCTCAGCAATACCTCCCCATGTAC
TCTGCGTTGATACNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

**Comment by acwarren** [comment]
I am trying to do the same thing and I was wondering if you were able to get this to work? Do you have a script that you could share to convert the CB tags to RGs?

**Comment by jeffr100** [comment]
Let me look and see if I can find the script.  Basically you just need to switch out the UMI tags to being RG tags.

-Jeffrey

------------------------------------------------------
Jeffrey Rosenfeld, Ph. D

Manager of the Biomedical Informatics Shared Resource
Assistant Professor of Pathology and Laboratory Medicine
Rutgers Cancer Institute of New Jersey

jeffrey.rosenfeld@rutgers.edu<mailto:jeffrey.rosenfeld@rutgers.edu>
732-235-8918 (voice)





On May 18, 2018, at 10:59 AM, acwarren <notifications@github.com<mailto:notifications@github.com>> wrote:


I am trying to do the same thing and I was wondering if you were able to get this to work? Do you have a script that you could share to convert the CB tags to RGs?
