### ISSUE TITLE
Incorrect alleles reported in RNA-seq data (example provided)

### ISSUE THREAD

**Issue by zouden** [freebayes/freebayes#394]
Freebayes does not appear to work with RNA-seq data - it reports incorrect alleles, in our case it under-reports reference alleles.

I'm using Freebayes v1.1.0-9-g09d4ecf. 

Here is a small SAM file containing 4 SNPs. The latter two (20844609 and 20844617) should be approximately 33% alternate, but Freebayes reports them as 66% alternate. Is this fixable?

[testregion.danRer10.sam.txt](https://github.com/ekg/freebayes/files/1061777/testregion.danRer10.sam.txt)
[testregion.vcf.txt](https://github.com/ekg/freebayes/files/1061780/testregion.vcf.txt)

**Comment by ekg** [comment]
I am working on a fix. I ran into this as well.
