### ISSUE TITLE
make freebayes fails: make[1]: *** [../bamtools/lib/libbamtools.a] Error 127

### ISSUE THREAD

**Issue by HLAmolec** [freebayes/freebayes#395]
Hello,

I get error messages when running 'make' command and freebayes/bin contains only .keep 0 K file.
Please help to troubleshoot. 

Thanks,

Lena

Here is the entire output:
$make
cd src && make autoversion
make[1]: Entering directory `/data/Freebayes/freebayes/src'
DETECTED_VERSION = v1.1.0-3-g961e5f3
CURRENT_VERSION  =
Updating version file.
make[1]: Leaving directory `/data/Freebayes/freebayes/src'
touch src/version_git.h
wget -q http://hypervolu.me/freebayes/build/v1.1.0-3-g961e5f3 &
cd src && make
make[1]: Entering directory `/data/Freebayes/freebayes/src'
DETECTED_VERSION = v1.1.0-3-g961e5f3
CURRENT_VERSION  = v1.1.0-3-g961e5f3
cd ../vcflib/tabixpp/htslib && make
make[2]: Entering directory `/data/Freebayes/freebayes/vcflib/tabixpp/htslib'
echo '/* Empty config.h generated by Makefile */' > config.h
gcc -g -Wall -O2 -I.  -c -o kfunc.o kfunc.c
gcc -g -Wall -O2 -I.  -c -o knetfile.o knetfile.c
gcc -g -Wall -O2 -I.  -c -o kstring.o kstring.c
gcc -g -Wall -O2 -I.  -c -o bgzf.o bgzf.c
gcc -g -Wall -O2 -I.  -c -o faidx.o faidx.c
gcc -g -Wall -O2 -I.  -c -o hfile.o hfile.c
gcc -g -Wall -O2 -I.  -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.3.1"' > version.h
gcc -g -Wall -O2 -I.  -c -o hts.o hts.c
gcc -g -Wall -O2 -I.  -c -o md5.o md5.c
gcc -g -Wall -O2 -I.  -c -o regidx.o regidx.c
gcc -g -Wall -O2 -I.  -c -o sam.o sam.c
gcc -g -Wall -O2 -I.  -c -o synced_bcf_reader.o synced_bcf_reader.c
gcc -g -Wall -O2 -I.  -c -o vcf_sweep.o vcf_sweep.c
gcc -g -Wall -O2 -I.  -c -o tbx.o tbx.c
gcc -g -Wall -O2 -I.  -c -o vcf.o vcf.c
gcc -g -Wall -O2 -I.  -c -o vcfutils.o vcfutils.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_decode.o cram/cram_decode.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_encode.o cram/cram_encode.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_external.o cram/cram_external.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_index.o cram/cram_index.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_io.o cram/cram_io.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_samtools.o cram/cram_samtools.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_stats.o cram/cram_stats.c
gcc -g -Wall -O2 -I.  -c -o cram/files.o cram/files.c
gcc -g -Wall -O2 -I.  -c -o cram/mFILE.o cram/mFILE.c
gcc -g -Wall -O2 -I.  -c -o cram/open_trace_file.o cram/open_trace_file.c
gcc -g -Wall -O2 -I.  -c -o cram/pooled_alloc.o cram/pooled_alloc.c
gcc -g -Wall -O2 -I.  -c -o cram/rANS_static.o cram/rANS_static.c
gcc -g -Wall -O2 -I.  -c -o cram/sam_header.o cram/sam_header.c
gcc -g -Wall -O2 -I.  -c -o cram/string_alloc.o cram/string_alloc.c
gcc -g -Wall -O2 -I.  -c -o cram/thread_pool.o cram/thread_pool.c
gcc -g -Wall -O2 -I.  -c -o cram/vlen.o cram/vlen.c
gcc -g -Wall -O2 -I.  -c -o cram/zfio.o cram/zfio.c
ar -rc libhts.a kfunc.o knetfile.o kstring.o bgzf.o faidx.o hfile.o hfile_net.o hts.o md5.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram         _external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o cram/thread_pool.o          cram/vlen.o cram/zfio.o
ranlib libhts.a
gcc -g -Wall -O2 -I.  -fpic -c -o kfunc.pico kfunc.c
gcc -g -Wall -O2 -I.  -fpic -c -o knetfile.pico knetfile.c
gcc -g -Wall -O2 -I.  -fpic -c -o kstring.pico kstring.c
gcc -g -Wall -O2 -I.  -fpic -c -o bgzf.pico bgzf.c
gcc -g -Wall -O2 -I.  -fpic -c -o faidx.pico faidx.c
gcc -g -Wall -O2 -I.  -fpic -c -o hfile.pico hfile.c
gcc -g -Wall -O2 -I.  -fpic -c -o hfile_net.pico hfile_net.c
gcc -g -Wall -O2 -I.  -fpic -c -o hts.pico hts.c
gcc -g -Wall -O2 -I.  -fpic -c -o md5.pico md5.c
gcc -g -Wall -O2 -I.  -fpic -c -o regidx.pico regidx.c
gcc -g -Wall -O2 -I.  -fpic -c -o sam.pico sam.c
gcc -g -Wall -O2 -I.  -fpic -c -o synced_bcf_reader.pico synced_bcf_reader.c
gcc -g -Wall -O2 -I.  -fpic -c -o vcf_sweep.pico vcf_sweep.c
gcc -g -Wall -O2 -I.  -fpic -c -o tbx.pico tbx.c
gcc -g -Wall -O2 -I.  -fpic -c -o vcf.pico vcf.c
gcc -g -Wall -O2 -I.  -fpic -c -o vcfutils.pico vcfutils.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/cram_codecs.pico cram/cram_codecs.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/cram_decode.pico cram/cram_decode.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/cram_encode.pico cram/cram_encode.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/cram_external.pico cram/cram_external.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/cram_index.pico cram/cram_index.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/cram_io.pico cram/cram_io.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/cram_samtools.pico cram/cram_samtools.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/cram_stats.pico cram/cram_stats.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/files.pico cram/files.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/mFILE.pico cram/mFILE.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/open_trace_file.pico cram/open_trace_file.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/pooled_alloc.pico cram/pooled_alloc.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/rANS_static.pico cram/rANS_static.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/sam_header.pico cram/sam_header.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/string_alloc.pico cram/string_alloc.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/thread_pool.pico cram/thread_pool.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/vlen.pico cram/vlen.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/zfio.pico cram/zfio.c
gcc -shared -Wl,-soname,libhts.so.1 -pthread  -o libhts.so kfunc.pico knetfile.pico kstring.pico bgzf.pico faidx.pico hfile.pico hfile_net.pico hts.pico md5.pico regidx.pico sam.pico synced_bcf_reader.pico vcf_sweep.pico tbx.pic         o vcf.pico vcfutils.pico cram/cram_codecs.pico cram/cram_decode.pico cram/cram_encode.pico cram/cram_external.pico cram/cram_index.pico cram/cram_io.pico cram/cram_samtools.pico cram/cram_stats.pico cram/files.pico cram/mFILE.pi         co cram/open_trace_file.pico cram/pooled_alloc.pico cram/rANS_static.pico cram/sam_header.pico cram/string_alloc.pico cram/thread_pool.pico cram/vlen.pico cram/zfio.pico -lz -lm
ln -sf libhts.so libhts.so.1
gcc -g -Wall -O2 -I.  -c -o bgzip.o bgzip.c
gcc -pthread  -o bgzip bgzip.o libhts.a -lz
gcc -g -Wall -O2 -I.  -c -o htsfile.o htsfile.c
gcc -pthread  -o htsfile htsfile.o libhts.a -lz
gcc -g -Wall -O2 -I.  -c -o tabix.o tabix.c
gcc -pthread  -o tabix tabix.o libhts.a -lz
gcc -g -Wall -O2 -I.  -c -o test/fieldarith.o test/fieldarith.c
gcc -pthread  -o test/fieldarith test/fieldarith.o libhts.a -lz
gcc -g -Wall -O2 -I.  -c -o test/hfile.o test/hfile.c
gcc -pthread  -o test/hfile test/hfile.o libhts.a -lz
gcc -g -Wall -O2 -I.  -c -o test/sam.o test/sam.c
gcc -pthread  -o test/sam test/sam.o libhts.a -lz
gcc -g -Wall -O2 -I.  -c -o test/test-regidx.o test/test-regidx.c
gcc -pthread  -o test/test-regidx test/test-regidx.o libhts.a -lz
gcc -g -Wall -O2 -I.  -c -o test/test_view.o test/test_view.c
gcc -pthread  -o test/test_view test/test_view.o libhts.a -lz
gcc -g -Wall -O2 -I.  -c -o test/test-vcf-api.o test/test-vcf-api.c
gcc -pthread  -o test/test-vcf-api test/test-vcf-api.o libhts.a -lz
gcc -g -Wall -O2 -I.  -c -o test/test-vcf-sweep.o test/test-vcf-sweep.c
gcc -pthread  -o test/test-vcf-sweep test/test-vcf-sweep.o libhts.a -lz
make[2]: Leaving directory `/data/Freebayes/freebayes/vcflib/tabixpp/htslib'
cd ../bamtools && mkdir -p build && cd build && cmake .. && make
/bin/sh: cmake: command not found
**make[1]: *** [../bamtools/lib/libbamtools.a] Error 127**
make[1]: Leaving directory `/data/Freebayes/freebayes/src'
**make: *** [all] Error 2**

**Comment by kkleinoros** [comment]
No solution?

**Comment by walaj** [comment]
You need CMake, which your system cannot find, to build BamTools. Or you could build the version from PR #338 which doesn't require BamTools.
