### ISSUE TITLE
Freebayes starting with fasta files

### ISSUE THREAD

**Issue by veronneaupy** [freebayes/freebayes#399]
Hi,

Easy one for you. Can I use freebayes to call events on a .sam coming from : bowtie2 -f file.fasta -N1 -x ref_genome -S file.sam?

I did convert it to .bam, sort it, index it and it creates an empty .vcf file when I run freebayes like that :
 
freebayes --fasta-reference /home/mimeeb_group/genome/hgly/IOWA/genome738_IGV.fasta \
--ploidy 2 --pooled-continuous --use-best-n-alleles 4 \
--min-mapping-quality 30 --min-base-quality 30 --min-alternate-count 2 \
--min-alternate-fraction 0.05 --min-coverage 5 \
--use-mapping-quality --genotype-qualities \
--bam file_sort.bam > freebayes_TP.vcf

I often use fastq as input and bwa mem to align on my reference genome, but now it's different.

Thanks for your help!

PY

**Comment by ekg** [comment]
This should be possible. However I believe the SAM will need some quality
information, even if it is assigned. Freebayes assumes the base quality is
0 if no quality string is found. This could be resolved with a script to
add the qualities into the SAM or some coding in C++ to add a default
quality.

**Comment by veronneaupy** [comment]
Thanks! We do have a script to convert fasta to fastq. I'll try that.

PY

-----Message d'origine-----
De : Erik Garrison [mailto:notifications@github.com] 
Envoyé : 11 juillet 2017 08:15
À : ekg/freebayes
Cc : Véronneau, Pierre-Yves; Author
Objet : Re: [ekg/freebayes] Freebayes starting with fasta files (#399)

This should be possible. However I believe the SAM will need some quality information, even if it is assigned. Freebayes assumes the base quality is
0 if no quality string is found. This could be resolved with a script to add the qualities into the SAM or some coding in C++ to add a default quality.
