### ISSUE TITLE
Error: Could not SetRegion to

### ISSUE THREAD

**Issue by celinamg** [freebayes/freebayes#400]
I am attempting to run the following command:

freebayes --region 1:207782768-207782769 --gvcf --fasta-reference human_g1k_v37.fasta Sample.dedup.bam

And I get the vcf header with the following error message at the bottom:
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	unknown
Error: Failed to set region: -1:207,782,768-207,782,769(*)
ERROR(freebayes): Could not SetRegion to 1:207782768..207782769

Any ideas of what could be causing this?

**Comment by walaj** [comment]
Does your input BAM have a header with "1" (not "chr1") as one of the
chromosomes? It's not able to find the chromosome.
