### ISSUE TITLE
Problem when compiling freebayes with make

### ISSUE THREAD

**Issue by DaniPaulo** [freebayes/freebayes#401]
Hi everyone!

I'm trying to install freebayes, but gettingan error after "make" command.
I'm using Ubuntu 16.04.4 x64 and a gcc compiler v.5.4.0
Thank youso much!
The error is the following (I'm also receiving a lot of warnnings):

-----------------------------------------------

In file included from /usr/local/include/assert.h:5:0,
                 from Genotype.h:15,
                 from ResultData.h:7,
                 from ResultData.cpp:1:
ResultData.cpp: In member function ‘vcflib::Variant& Results::vcf(vcflib::Variant&, BigFloat, long double, Samples&, std::__cxx11::string, std::vector<Allele>&, std::map<std::__cxx11::basic_string<char>, int>, int, std::vector<std::__cxx11::basic_string<char> >&, int, GenotypeCombo&, std::map<std::__cxx11::basic_string<char>, std::vector<Allele*> >&, std::map<std::__cxx11::basic_string<char>, std::vector<Allele*> >&, std::map<Allele*, std::set<Allele*> >&, std::map<int, std::vector<Genotype> >&, std::vector<std::__cxx11::basic_string<char> >&, AlleleParser*)’:
ResultData.cpp:447:9: error: could not convert ‘& frame’ from ‘Except_Frame_T*’ to ‘Except_Frame_T’
         TRY { repeatstr = repeatstr.substr(0, repeatstr.size() - 1); } CATCH;
         ^
In file included from AlleleParser.h:25:0,
                 from ResultData.h:10,
                 from ResultData.cpp:1:
TryCatch.h:10:5: error: expected primary-expression before ‘catch’
     catch (std::out_of_range outOfRange) { \
     ^
ResultData.cpp:447:72: note: in expansion of macro ‘CATCH’
         TRY { repeatstr = repeatstr.substr(0, repeatstr.size() - 1); } CATCH;
                                                                        ^
ResultData.cpp:640:1: error: expected ‘while’ before ‘vcflib’
 vcflib::Variant& Results::gvcf(
 ^
ResultData.cpp:640:1: error: expected ‘(’ before ‘vcflib’
ResultData.cpp:640:16: error: expected primary-expression before ‘&’ token
 vcflib::Variant& Results::gvcf(
                ^
ResultData.cpp:641:20: error: expected primary-expression before ‘&’ token
     vcflib::Variant& var,
                    ^
ResultData.cpp:642:13: error: expected primary-expression before ‘&’ token
     NonCalls& nonCalls,
             ^
ResultData.cpp:642:15: error: ‘nonCalls’ was not declared in this scope
     NonCalls& nonCalls,
               ^
ResultData.cpp:643:17: error: expected primary-expression before ‘*’ token
     AlleleParser* parser) {
                 ^
ResultData.cpp:643:27: error: expected ‘)’ before ‘{’ token
     AlleleParser* parser) {
                           ^
ResultData.cpp:643:27: error: expected ‘;’ before ‘{’ token
ResultData.cpp:724:1: error: expected ‘}’ at end of input
 }
 ^
ResultData.cpp:724:1: error: expected ‘}’ at end of input
Makefile:161: recipe for target 'ResultData.o' failed
make[1]: *** [ResultData.o] Error 1
make[1]: Leaving directory '/home/danielpaulo/programs/freebayes/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ekg** [comment]
Would you please try with the current HEAD of master? I'm worried that enough has changed in the last week with the build that your problem will manifest in another way.

**Comment by wangyugui** [comment]
with the current HEAD of maste, 'make wbamtools' is OK, but 'make' have two error.

1,
```
../vcflib/src/Variant.h:18:21: fatal error: tabix.hpp: No such file or directory
 #include "tabix.hpp"
````

it can be fixed by 'export CPLUS_INCLUDE_PATH=/nfs/git/fixed/freebayes/vcflib/include'


2,
```
g++   -I../src -I../ttmath -I../vcflib/src/ -I../vcflib/smithwaterman/ -I../vcflib/multichoose/ -I../vcflib/filevercmp/ -I../vcflib/fastahack/ -I../SeqLib/htslib -I../SeqLib  freebayes.o BedReader.o CNV.o fastlz.o Fasta.o Parameters.o Allele.o Sample.o Result.o AlleleParser.o Utility.o Genotype.o DataLikelihood.o Multinomial.o Ewens.o ResultData.o Dirichlet.o Marginals.o split.o LeftAlign.o IndelAllele.o Bias.o Contamination.o NonCall.o SegfaultHandler.o ../vcflib/tabixpp/tabix.o ../vcflib/smithwaterman/SmithWatermanGotoh.o ../vcflib/smithwaterman/disorder.cpp ../vcflib/smithwaterman/LeftAlign.o ../vcflib/smithwaterman/Repeats.o ../vcflib/smithwaterman/IndelAllele.o Variant.o ../SeqLib/src/libseqlib.a ../SeqLib/bwa/libbwa.a ../SeqLib/fermi-lite/libfml.a ../SeqLib/htslib/libhts.a -o ../bin/freebayes -lz -llzma -lbz2 -lm -lpthread
AlleleParser.o: In function `AlleleParser::makeAllele(RegisteredAlignment&, AlleleType, long, int, int, int, std::string&, std::string&, SeqLib::BamRecord&, std::string&, long double, std::string&)':
AlleleParser.cpp:(.text+0x815a): undefined reference to `SeqLib::BamRecord::PositionEnd() const'
AlleleParser.o: In function `AlleleParser::registerAlignment(SeqLib::BamRecord&, RegisteredAlignment&, std::string&, std::string&)':
AlleleParser.cpp:(.text+0xa5a5): undefined reference to `SeqLib::BamRecord::PositionEnd() const'
```

**Comment by wangyugui** [comment]
and why we need 'log: src/version_git.h
        wget -q http://hypervolu.me/freebayes/build/$(shell cat src/version_git.h | grep v | cut -f 3 -d\  | sed s/\"//g) & '

can we put it in github?

I failed to access http://hypervolu.me maybe because of firewall.

**Comment by wangyugui** [comment]
There are two problems of  current HEAD of master in my case.

1, I failed to exec 'wget -q http://hypervolu.me/freebayes/build/' because of firewall?
   can we put it in github?

2, I can make 'src/Makfile' and 'vcflib/Makfile' without '-j 24' option.
but sometimes it will failed with make '-j 24' option.

**Comment by tseemann** [comment]
@wangyugui 
1. did you use a release.tgz ? if so, that does not include the git submodules and can't be compiled
2. parallel make is a known bug. compile only works with `make -j 1` aka `make`.

**Comment by wangyugui** [comment]
Thanks a lot.

I'm not using release.tgz.  I'm using git  HEAD of master which is newer than release.tgz.

Now I am using make 'src/Makfile' and make 'vcflib/Makfile' , so even with this problem, I can build it from the source.

**Comment by tseemann** [comment]
@wangyugui yes, you need to use  `git clone --recursive`
