### ISSUE TITLE
how many samples are needed for stable variant calling?

### ISSUE THREAD

**Issue by ieiwk** [freebayes/freebayes#407]
Dear ekg,

does one need to re-process all existing bam files every time new batch of sample data come to obtain the most reliable results? If not, what is the minimal recommended sample size?

Thanks a lot!

**Comment by ekg** [comment]
One sample is the minimum recommended size. Multiple will help with
sensitivity.

You can convert each sample into gVCF and merge post-hoc using another
tool. This preserves most of the information used by variant calling. This
is new territory, and I will be happy to support you by resolving any bugs
you find as this is a common use case.

**Comment by ieiwk** [comment]
I see. Thanks for the quick reply!

Without involving gVCF, I think the calling results of one sample is not so reliable as I experienced. For some sites, if I recall it correctly, calling on one bam together with that of the mother or with that of both parents resulted in the same and more reasonable genotypes. So I guess 2 or more samples are needed for stable and reasonable genotyping at some sites. But I am not sure how much benefit would be brought with more samples. Is it practically enough to process, say, 10 or 20 bams together?
