### ISSUE TITLE
what about MAPQ = 0 

### ISSUE THREAD

**Issue by dridk** [freebayes/freebayes#408]
Hi, 

In my BAM file , I have some reads with MAPQ = 0 . It means the read map elsewhere. ( white read on the screenshot). 
Freebayes detect a variant in this area ( see below ). 
Does Freebayes manage MapQ ? Does it use MAPQ to compute the variant QUAL score ?  How can interpret this variant ? 

![image](https://user-images.githubusercontent.com/1911063/28266159-b15d37fe-6af3-11e7-8e9b-b222fc6d8b03.png)

**Comment by wangyugui** [comment]
freebayes --help

```
   -m --min-mapping-quality Q
                   Exclude alignments from analysis if they have a mapping
                   quality less than Q.  default: 1
```

**Comment by tseemann** [comment]
@wangyugui is correct. Freebayes defaults need to be changed in most cases. I would go through the hole `freebayes -h` pages and read each option in full to make sure it is doing what you want. I personally don't understand *all* the options, but there are some common ones that are not set to values most people would want.
