### ISSUE TITLE
how come this varirant?

### ISSUE THREAD

**Issue by ieiwk** [freebayes/freebayes#410]
one SNV:
0/1:21:0:0:21:717:-62.3785,0,-3.4698

why 0/1 when all reads are from alternative allel?

fields are seperated by ":":
GT # Genotype
DP # Read Depth
RO # Reference allele observation count, with partial observations recorded fractionally
QR # Reference allele quality sum in phred
AO # Alternate allele observations, with partial observations recorded fractionally
QA # Alternate allele quality sum in phred
GL # Genotype Likelihood, log10-scaled likelihoods of the data given the called genotype for each possible genotype generated from the reference and alternate alleles given the sample ploidy

**Comment by ekg** [comment]
How many samples are there in the analysis?

What version of freebayes are you using?

Could you share the data at this locus so we can see what's happening?

**Comment by ieiwk** [comment]
Oh, I am very sorry. I made a wrong, as this variant is actually a deletion... Is it still interesting?
