### ISSUE TITLE
Freebayes terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by cdeanj** [freebayes/freebayes#413]
Running FreeBayes with vanilla parameters on an indexed reference genome and a sorted BAM file produces the following error (see title) for me. I am using FreeBayes version v1.1.0-44-gd784cf8 and have more than enough memory on my machine. Any ideas? I can provide the reference sequence and alignment file.

Best,
Chris

**Comment by wangyugui** [comment]
In most of cases, std::bad_alloc means not enough memory left.

```
/bin/time -f "real\t%e(%E)\nuser\t%U\nsys\t%S\nPeakRSS\t%M\n" freebayes xxxx
```
can output the max memory used.

**Comment by tseemann** [comment]
@cdeanj maybe try just running it on a small part of one chromosome using the `--region` option:
```
   -r --region <chrom>:<start_position>-<end_position>
                   Limit analysis to the specified region, 0-base coordinates,
                   end_position not included (same as BED format).
                   Either '-' or '..' maybe used as a separator.
```

**Comment by ekg** [comment]
@cdeanj if you're not finding the current HEAD resolves the problem, please send me the inputs that cause this failure and I'll see if it's more than a memory issue.

**Comment by ekg** [comment]
Depending on your experiment, some regions of the genome can have very deep alignments. Freebayes uses several gigabytes of RAM per million X read depth, but I haven't checked recently and it's possible things have degraded. If this is the problem then you can try to exclude these regions by running a coverage counter tool and then generating a set of targets to skip. You'll have to use tools in bedtools to do this and prepare the input target list for freebayes.
