### ISSUE TITLE
Low-frequency Variant not called in Tumor-Only

### ISSUE THREAD

**Issue by christianbioinf** [freebayes/freebayes#416]
I stumbled across a possible issue with freebayes (v1.1.0-44-gd784cf8) when using it on tumor-only targeted sequencing data. The variant (w/ frequency of ~5%) is detected and not filtered but the site is called as homozygous reference despite using the options `--pooled-continuous`, `--pooled-discrete`, `--min-alternate-fraction 0.01`, and `--allele-balance-priors-off`.

```
$ freebayes/bin/freebayes -d -f hg19.fa --pooled-continuous --pooled-discrete --min-alternate-fraction 0.01 --allele-balance-priors-off test.bam
found genotype alleles
filtering genotype alleles which are not supported by at least 2 observations comprising at least 0.01000 of the observations in a single individual
genotype allele: reference:1M:41231515:1:C qsum 371926
reference:1M:41231515:1:C has support of 9903 in individual 4759 (10447 obs) and fraction 0.94793
genotype allele: snp:1X:41231515:1:A qsum 55
genotype allele: snp:1X:41231515:1:G qsum 78
genotype allele: snp:1X:41231515:1:T qsum 20704
snp:1X:41231515:1:T has support of 540 in individual 4759 (10447 obs) and fraction 0.05169
filtered genotype alleles
adding allele to result alleles C
adding allele to result alleles S:41231515:1X:T
built haplotype alleles, now there are 2 genotype alleles
reference:1M:41231515:1:C|snp:1X:41231515:1:T
genotype alleles: reference:1M:41231515:1:C|snp:1X:41231515:1:T
searching genotype space
best combo: combo posterior prob: 0.00000
{"4759":["C/C",0.00000]}
chr17	41231516	.	C	T	2.90841e-12	.	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=540;CIGAR=1X;DP=10447;DPB=10447;DPRA=0;EPP=108.544;EPPR=1830.61;GTI=0;LEN=1;MEANALT=3;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=3386.34;PAIRED=1;PAIREDR=0.999192;PAO=0;PQA=0;PQR=0;PRO=0;QA=20704;QR=371926;RO=9903;RPL=540;RPP=1175.61;RPPR=21498.4;RPR=0;RUN=1;SAF=189;SAP=108.544;SAR=351;SRF=3507;SRP=1833.14;SRR=6396;TYPE=snp;technology.illumina=1	GT:DP:AD:RO:QR:AO:QA:GL	0/0:10447:9903,540:9903:371926:540:20704:0,-1281.79,-31587.3
```

This is the output when enabling the debug (`-d`) option which hints that the homozygous reference genotype is selected in the best-combo step. I have also tried to add the options `--genotype-qualities`, `--report-genotype-likelihood-max`, `--no-population-priors`, `--hwe-priors-off`, and `--binomial-obs-priors-off`, but without success.

I am wondering whether it is not possible to call variants with frequency below 10% since this seems to be the boundary below which I do not see any variants in any somatic dataset. I know that it is generally more sensible to do tumor/normal calling in such a case but I simply do not have normal/germline data.

**Comment by pmoulos** [comment]
Hi, I faced a similar problem. In my case (freebayes v1.0.2-16-gd466dde), just enabling ```--allele-balance-priors-off``` resolved the problem (also, the variant was not detected before).
