### ISSUE TITLE
Reads Supporting a Variant

### ISSUE THREAD

**Issue by cvniru** [freebayes/freebayes#418]
It's very useful to get the read names of the reads supporting the reference haplotype and all the alternate haplotypes. Currently this information is available in the debug output from the -d option. But this output is too verbose and the information is not readily parseable in an efficient way. It will be very helpful to add an output option that outputs this information in a structured file.

**Comment by ekg** [comment]
I would output this in the VCF, as it describes the variants directly and
any other structure file must do at least this.

**Comment by cvniru** [comment]
Perfect!
