### ISSUE TITLE
Missing Indel

### ISSUE THREAD

**Issue by cvniru** [freebayes/freebayes#422]
Freebayes seems to be missing a deletion that I see in my BAM file at chr4:55133936 CT > C.
I see other haplotypes called in the region around this shown below:
chr4	55133918	.	CTCTCTGCCCAAGTATGCC	CTCTCTGCCCAAGTATACT,CTCTCTGCCCAAGTATGCTT,ATCTCTGCCCAAGTATGCT,CTCTCTGCGCAAGTATGCT,CTCTCTGCCAAAGTATGCT,CTCTCTGCCCAAGTATGC,CTCTCTGCCCAAGTATGTT,CTCTCTGCCCAAGTATGAC,CTCTCTGCCCAAGTATGCT,GTCTCTGCCCAAGTATGCC,CTATCTGCCCAAGTATGCC,CTCTCTACCCAAGTATGCC,CTCTCTGACCAAGTATGCC,CTCTCTGTCCAAGTATGCC,CTCTCTGCACAAGTATGCC,CTCTCTGCCAAAGTATGCC 
chr4	55133937	.	TTTTTTTAGTGTGCATCAGAGGC	TTTTTTTAGTGTACATCAGAGGT,TTTTTTTAGTGTGTATCAGAGGT,TTTTTTTAGTATGCATCAGAGGC,TTTTTTTAGTGTACATCAGAGGC,TTTTTTTAGTGTGAATCAGAGGC,TTTTTTTAGTGTGTATCAGAGGC,TTTTTTTAGTGTGCATAAGAGGC,TTTTTTTAGTGTGCATCGGAGGC,CTTTTTTAGTGTGCATCAGAGGC,TTTTTTTAGTGTGCATCAGAAGC,TTTTTTTAGTGTGCATCAGAGGA,TTTTTTTAGTGTGCATCAGAGGT

Haplotype at 55133918 is of length 19 which means it ends at 55133937. The next Haplotype it looks at starts at position 55133937. Since the deletion I am looking at is the deletion of T at 55133937, perhaps it gets left out in the allele gathering step.

I changed a line in the AlleleParser::getNextAlleles() method from 
long int nextPosition = currentPosition + lastHaplotypeLength;
to
long int nextPosition = currentPosition + 1;
which forces it to look at every position.

I then get the following haplotypes which includes the deletion I am looking for:
chr4	55133934	.	GCC	ACT,GCTT,GC,GTT,GAC,GCT
chr4	55133936	.	CTTTTTTTA	CTTTTTTA,CTTTTTTTTA,TTTTTTTTA

I am attaching an IGV screenshot of the BAM file and can provide supporting files in an email.
![screen shot 2017-09-11 at 11 00 46 am](https://user-images.githubusercontent.com/850763/30281579-d0f29abe-96e0-11e7-8c22-a39da8073f9d.png)

I am running freebayes (version: v1.1.0-46-g8d2b3a0-dirty) with the command:
freebayes --fasta-reference ref.fa test.sorted.bam  -t target.bed --pooled-continuous --min-alternate-count 2 --min-alternate-fraction 0.0000001    --min-base-quality 30  --use-reference-allele  --haplotype-length 20  --use-duplicate-reads > test.vcf

**Comment by mmoisse** [comment]
See my comments in #433
