### ISSUE TITLE
FreeBayes in RNA-seq

### ISSUE THREAD

**Issue by annaquaglieri16** [freebayes/freebayes#427]
Hi, 
in a previous thread I noticed that FreeBayes does not to work well with RNA-Seq data. I am in the process of comparing different tools for RNA-Seq variant calling and I was wondering if it is now ok to use it and especially what type of pre-processing it requires (any from the GATK best practices?). 

Thanks, 

Anna

**Comment by annaquaglieri16** [comment]
In 

https://github.com/chapmanb/bcbio-nextgen/issues/389

it was claimed that

@mjafin and others, freebayes should now handle the spliced reads. If this isn't the case please ping me over on the freebayes repo. The only problem I remember was during left alignment of indels. I don't have the commit I'd handy but I believe it has been resolved.

Does it mean that it will handle correctly spliced reads without any pre-processing?

Thanks, 

Anna

**Comment by xgrau** [comment]
May I resurface this issue, in case the OP or the devs have any input on this?

I'm particularly interested in this last question:

> Does it mean that it will handle correctly spliced reads without any pre-processing?

Cheers

**Comment by for-giobbe** [comment]
I am interested as well!

**Comment by winni2k** [comment]
Me too.

**Comment by pjotrp** [comment]
freebayes is in maintenance mode. But if anyone wants to work on RNAseq code feel free to reopen this issue.

**Comment by winni2k** [comment]
Hi @pjotrp. I appreciate that freebayes is in maintenance mode. However I don't think this is an enhancement issue. This issue is merely a request for clarification. The functionality described in this issue may already exist. We would really just like to know if it does.

**Comment by winni2k** [comment]
> freebayes is in maintenance mode. But if anyone wants to work on RNAseq code feel free to reopen this issue.

How would I reopen this issue?

**Comment by sanjaynagi** [comment]
Id also be keen to know this @winni2k
