### ISSUE TITLE
Example pipeline

### ISSUE THREAD

**Issue by hzpc-joostk** [freebayes/freebayes#430]
Hey, 

I noticed an example pipeline in the `examples` folder. It is [five years old](https://github.com/ekg/freebayes/commit/9608597d12e127c847ae03aa03440ab63992fedf). How updated is it? Commands used in it are not reused in the README section [Calling variants: from fastq to VCF](https://github.com/ekg/freebayes#calling-variants-from-fastq-to-vcf). For example, left aligning alignments is done internally, as [explained in README](https://github.com/ekg/freebayes#indels) since 294c1f048791643fa49d1830efa68ebdbb4ec5a2.

Should it be removed to avoid confusion or replaced with something more practical? Including some parallel practices.

Thanks :)

**Comment by ekg** [comment]
Yes, I think it should be removed or updated. It's mostly confusing.

**Comment by cfc424** [comment]
Hi@ekg,
I met the similar problem and I can not run the parallel scripts, would you like to show me some examples? When I call SNPs from four Bam files at one time, the speed of freebayes is too slow. How could I deal with this? Choose another version??

My software version is:  v1.1.0-3-g961e5f3-dirty

Thanks a lot!
