### ISSUE TITLE
Variants in --variant-input wrongly parsed

### ISSUE THREAD

**Issue by mmoisse** [freebayes/freebayes#435]
When using the ``--variant-input`` options I noticed that the input vcf is sometimes wrongly parsed, especially in case of overlapping variants and insertions.

I believe that the base of the issue is the same as #368

In the example below ( [example.zip](https://github.com/ekg/freebayes/files/1519425/example.zip) ) you will find the following issues:
 

1. Wrongly parsed insertions for position chr5:73
2. If the variant false on a 'true' variant they are all lost chr5:83
3. If a SNV and indels do overlap, the SNV are turned into deletions chr5:87 and chr5:94

```
freebayes --variant-input inputVcf/test.complex.vcf.gz -f ref/test.fa test.bam
```
The input vcf looks like this
```
#CHROM  POS  ID  REF  ALT         QUAL    FILTER  INFO
chr5    66   .   A    AC          9174.8  PASS    .
chr5    73   .   .    C           9174.8  PASS    .
chr5    75   .   C    .           9174.8  PASS    .
chr5    78   .   CC   C           9174.8  PASS    .
chr5    83   .   A    A,T,C,G,AA  9174.8  PASS    .
chr5    87   .   C    A,T,C,G,CA  9174.8  PASS    .
chr5    94   .   C    A,T,C,G     9174.8  PASS    .
chr5    94   .   CA   C           9174.8  PASS    .
```

and the output like this:
```
#CHROM  POS  ID  REF  ALT        QUAL         FILTER  FORMAT                16052301
chr5    66   .   AG   ACG        0            .       GT:DP:RO:QR:AO:QA:GL  0/0:720:713:25759:0:0:0,-214.634,-2316.94
chr5    73   .   C    C          4.48417e-14  .       GT:DP:RO:QR:AO:QA:GL  0/0:720:717:26234:0:0:0,-215.838,-2359.52
chr5    75   .   C    .          1.32597e-14  .       GT:DP:RO:QR:AO:QA:GL  0/0:720:717:26138:0:0:0,-215.838,-2350.91
chr5    78   .   CCA  CA         4.85057e-13  .       GT:DP:RO:QR:AO:QA:GL  0/0:718:702:25299:0:0:0,-211.323,-2275.63
chr5    83   .   ACC  AC         2865.99      .       GT:DP:RO:QR:AO:QA:GL  0/1:719:415:14705:246:8009:-521.439,0,-1123.75
chr5    87   .   CC   CAC,A,G,T  0            .       GT:DP:RO:QR:AO:QA:GL  0/0:720:703:25590:0,0,0,0:0,0,0,0:0,-211.624,-2301.7,-211.624,-2301.7,-2301.7,-211.624,-2301.7,-2301.7,-2301.7,-211.624,-2301.7,-2301.7,-2301.7,-2301.7
chr5    94   .   CAG  CG,A,G,T   0            .       GT:DP:RO:QR:AO:QA:GL  0/0:720:678:24372:0,0,0,0:0,0,0,0:0,-204.098,-2192.13,-204.098,-2192.13,-2192.13,-204.098,-2192.13,-2192.13,-2192.13,-204.098,-2192.13,-2192.13,-2192.13,-2192.13
```

**Comment by ekg** [comment]
There are a lot of subtleties in how we handle variant input. To be perfectly honest, if genotyping known variants were important to me I would be using [`vg`](https://github.com/vgteam/vg), which is designed to deal with exactly this kind of problem from the level of alignment forward. I'm also the author, and this has been my primary focus for the past three years. I was motivated by exactly this kind of problem.
