### ISSUE TITLE
Freebayes parallel no output when using -t bedfile

### ISSUE THREAD

**Issue by cflsjt** [freebayes/freebayes#441]
Hi, I've been using Freebayes parallel and it's been working just fine. When I tried to use it with a target bedfile I get no output in the vcf file, just the header!

freebayes-parallel <(/software/bioinformatics/freebayes-1.1.0/scripts/fasta_generate_regions.py ${FAI} 1000000) 60 -f ${FASTA} -L ${BAMS} -t ${BED} -p 4 -C 5 -k --report-genotype-likelihood-max --min-mapping-quality 10 --genotype-qualities --use-mapping-quality --no-mnps --no-complex > $OUT/out.vcf

I've checked my bedfile and it's fine...is there an issue when using the parallel fragmentation with targets?...

**Comment by ekg** [comment]
There shouldn't be a problem. But the easiest thing tends to be to run in
parallel over the bed regions.
