### ISSUE TITLE
Freebayes on CRAM vs BAM

### ISSUE THREAD

**Issue by sarahmorton** [freebayes/freebayes#447]
We are using Freebayes to filter candidate de novo variants identified using GATK analysis of WGS data. In the first found, data were aligned to hg19 and input as bam files. We repeated the freebayes step now using data aligned to hg38 and piped from samtools as the data are now in cram format. 

Whereas previously the ~80 de novo snps per proband were reduced to ~60, now a far larger number of variants are not called by freebayes, resulting in ~25 variants per proband. 

We had previously used a Freebayes downloaded in October 2016, and are now using a version downloaded January 2018.  Both were version 1.1.0

Has anyone else seen a change in snp identification in freebayes?  A change within the version that we may not have accounted for?  Freebayes was important in improving our variant quality in the first WGS analysis and are anxious to determine the cause of the change. 

Thanks,
 sarah

**Comment by ekg** [comment]
You are running freebayes using the default parameters?

Could this be caused by the change in reference genome?

Today or tomorrow I will submit a PR that changes the default input thresholds to be more sensitive to candidate alleles. The major difference will be setting `--min-alternate-fraction 0.05`. This may affect your  issue here.

**Comment by sarahmorton** [comment]
Hi Erik,



Thank you for your quick reply.



We are using the default parameters for freebayes.  We were concerned that it might be caused by the change in the reference genome as well.  However it seems to be in this instance that there were somewhat random failures in the samtools reading of the input files, resulting in truncation of the genome at varied positions for each individual.



I really appreciate the change in sensitivity, and will can follow up with the new results after our samtools fix if that would be of interest.



Thanks again,

Sarah

________________________________

**Comment by ekg** [comment]
FYI I haven't yet pushed the update for the default min alternate fraction.

Thank you for explaining what problem you found. It is true also that the
change in reference sequence is going to have an effect, but if you have
randomly truncated inputs that might be minor in comparison.
