### ISSUE TITLE
Freebayes memory issue

### ISSUE THREAD

**Issue by tvdwbar** [freebayes/freebayes#451]
Hi, I am running into memory problems with a task that should be easily doable (I think). I'm running 1400 samples from a 100 amplicon sequencing experiment through freebayes for variant calling against reference genome. On average a sample has ~200 reads per amplicon. I have merged the bam files of all the samples into one merged.bam (~4 gb) while keeping the read group ID's. Used the recommended memory saving settings --use-best-n-alleles 2, --min-alternate-count 5. I'm using the target option to limit the caller to the amplicon regions and I am even feeding in the amplicon targets one at a time to avoid excessive memory usage. Each amplicon is appromixately 60 bp.
Server has 49 gb RAM available to process. Still for some amplicon targets the process gets killed by freebayes. I can see in the memory usage that available free RAM goes from 49gb to 0, process gets killed and then starts with the next target. For about 1/3 of my targets the process gets killed this way. I tried if this still is the case if I reduce the amount of samples and it still happens for some targets even with only 200 samples. I see other people in the comments that run 1000's of WGS samples with similar server RAM capacity, so shouldn't this be a very easy to process? Any idea's how to solve this?

**Comment by ekg** [comment]
This could be a bug. Or it could be that some amplicons have much higher
than average coverage. Is the latter a possibility?

**Comment by tvdwbar** [comment]
Hi Erik, I checked the coverage for these targets. Does not seem out of proportion. The multiplex was carefully optimized. We are now running with an extra 80gb RAM (total of 120 gb) and I split the 1400 samples into three batches. Now already running 2 hours on 1 amplicon, 1 batch, with current memory usage of 70 gb RAM (steady since 1,5 hour). Do you agree this is way to much memory usage for the described parameters?

**Comment by ekg** [comment]
Something is wrong. I can try to debug it but I will need a test case to
see what's happening.

**Comment by tvdwbar** [comment]
I can send you the files in a private message?

**Comment by ekg** [comment]
Yes that's fine!

**Comment by tvdwbar** [comment]
Sorry, new on github - Ive been searching for a private message button, but so far couldnt find one.

**Comment by PAMorin** [comment]
This sounds very similar to problems we have been seeing. Has the problem been resolved?
We are doing amplicon sequencing for ~100-400 amplicons (150bp), and up to ~500 samples so far. Depth of coverage is variable, but doesn't seem to get above a few thousand, and usually between 100 and 1000/sample/locus. Freebayes will run for some time (few-20 hrs), typically getting up to 10-15% of the memory capacity (and dropping back to 0), and then memory will clime until it maxes out our system (128 Gbytes RAM) and causes the system to crash. I was able to get it to run with one data set by using more options (see below) that reduce the number of SNPs, but it still crashes with other data sets. 
My full command line is:
nohup freebayes-parallel2 <(fasta_generate_regions.py ~/Ppho_GTseq/map/340_Ppho_GTseq_SNPs_LocNum_200218.fasta.fai 200) 1 -f ~/Ppho_GTseq/map/340_Ppho_GTseq_SNPs_LocNum_200218.fasta -L ./trimmed2_bamlist_largefiles.txt --haplotype-length 0 -kwVa --no-mnps --min-coverage 10 --no-complex --use-best-n-alleles 4 --min-alternate-count 5 --min-alternate-fraction 0.3 > Ppho_340loc_trimmed2_largefiles_noMNP_noComplex_minCov10_minAlt5_fract0.3.vcf &
Phil

**Comment by tvdwbar** [comment]
I think in my case it was a CPU issue, that too much of the workload was getting put into waiting (filling the RAM) with the CPU processing going to slowly. Another issue I had to resolve is to set the limit of the server to open many samples at the same time to a higher number (standard is limit at 1024), using code: ulimit -n 10000. Remember that for every file it opens the bam as well as the bam index file, so you will also pass 1000 files open quickly.
