### ISSUE TITLE
freebayes parallel crash: output not complete

### ISSUE THREAD

**Issue by charlesdavid** [freebayes/freebayes#454]
Hi, I am getting an error and crash using freebayes parallel.
The job runs for about 1 day and then crashes saying that the output is incomplete...
Also, says can't write to /tmp... is disk full?
The error suggests adding --tmpdir to specify a temp directory...
HOWEVER:
Adding `--tmpdir path/to/temp` throws an error saying that this is an invalid flag...

So, how do I correctly specify a temp directory?

Clearly the program can not run using the standard `/tmp` location.

**Please tell me that this is not hard coded, and the correct flag for passing the parameter **

Thanks

**Comment by tseemann** [comment]
I have never known there to be any `--tmpdir` or similar parameter to `freebayes`.
May I ask where you saw it?

Many `libc` system calls will honour the `$TMPDIR` variable if it is set. Does yours point to somewhere with enough disk space?

Did you run it with smaller input data set previously with success?

**Comment by charlesdavid** [comment]
@tseemann Have a look at the jobs log...

----------------------------------------------------------------------------------------------------------------
parallel: Error: Output is incomplete. Cannot append to buffer file in /tmp. Is the disk full?
parallel: Error: Change $TMPDIR with --tmpdir or use --compress.
------------------------------------------------------------
Sender: OpenLava System <openlava@aklppb34>
Subject: Job 141934: <FBPar> Exited

Job <FBPar> was submitted from host <aklppr31> by user <cflcyd>.
Job was executed on host(s) <86*aklppb34>, in queue <normal>, as user <cflcyd>.
</home/cflcyd> was used as the home directory.
</powerplant/workspace/cflcyd/git/Snapper> was used as the working directory.
Started at Thu Mar 29 15:05:54 2018
Results reported at Thu Mar 29 16:32:58 2018

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
#!/bin/bash
#BSUB -J FBPar
#BSUB -o /workspace/cflcyd/git/Snapper2/013.FB/logs/FB.out 
#BSUB -e /workspace/cflcyd/git/Snapper2/013.FB/logs/FB.err
#BSUB -n 86
#BSUB -m aklppb34

freebayes-parallel <(/software/bioinformatics/freebayes-1.1.0/scripts/fasta_generate_regions.py /workspace/cflcyd/git/Snapper2/000.raw/genome/Snapper_male_3000.fasta.fai 1000000) 86  -f /workspace/cflcyd/git/Snapper2/000.raw/genome/Snapper_male_3000.fasta  -L /workspace/cflcyd/git/Snapper2/010.IR/bamlist  --ploidy 2  --report-genotype-likelihood-max  --min-base-quality 10  --min-mapping-quality 10  --genotype-qualities  --use-mapping-quality  --no-mnps  --no-complex  --max-complex-gap 50  --min-alternate-fraction 0.1  --min-repeat-entropy 1  --no-partial-observations  --min-coverage 10  --max-coverage 500  --pooled-continuous  >/workspace/cflcyd/git/Snapper2/013.FB/80_Samples_FB.vcf

------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time   :  63760.93 sec.
    Max Memory :    114239 MB
    Max Swap   :    122625 MB

    Max Processes  :        96

The output (if any) is above this job summary.
---------------------------------------------------------------------------------------
**I just want to know the correct syntax for setting the temp directory in FB as the default is crashing!**

Thanks!

**Comment by tseemann** [comment]
This is not `freebayes-parallel` crashing.
It's `parallel` which is a separate tool, that it uses.
My default it uses `/tmp` but you don't have enough space there.
You will need to choose another folder on your disk which does have enough space.
Then add `export TMPDIR=/path/to/more/space` to your submission script.

**Comment by charlesdavid** [comment]
Great! Thanks for the clarification. For some reason I was thinking that FB needed to know the temp dir like in Picard Tools or GATK. Thanks.
