### ISSUE TITLE
Problems in hard filters when running freebayes

### ISSUE THREAD

**Issue by annaquaglieri16** [freebayes/freebayes#455]
Hi there, 

I am trying to compare the performance of freebayes on tumour RNA-Seq data with other callers and I am setting very loose threshold for total read depth and VAF:

freebayes --min-base-quality 20 --min-mapping-quality 20 --min-alternate-count 2 --min-coverage 10 --min-alternate-fraction 0.01

However, when I look at the results (compared to other callers where I set the same thresholds) it looks like freebayes is still using a pretty hard filter on VAF (0.2 as default). Here is a plot where each line is a mutation for a sample called at different starting library sizes (randomly downsampled). I obtain the VAF from each bamfile separately and the dot and lines are red if that variant is not called at that sequencing depth. Next to it is the same analysis but with Mutect2

The y-axis is the VAF. 

![screen shot 2018-03-30 at 11 18 06 am](https://user-images.githubusercontent.com/7087258/38119240-16cbf26a-340c-11e8-8ded-46a03b6cca77.png)

![screen shot 2018-03-30 at 11 20 49 am](https://user-images.githubusercontent.com/7087258/38119294-719654ec-340c-11e8-8da5-98c334b80797.png)

Am I missing something in terms of setting the right parameters? I ma running freebayes on a single sample mode even though it would be better run using all the samples at a time. 

Thanks for your help, 

Anna

**Comment by tseemann** [comment]
(I am not a freebayes expert, especially with diploid and population analyses)

Do the parameters you provide contradict each other?
`--min-alternate-count 2 --min-coverage 10` imples you'll accept VAF=0.2 
But `--min-alternate-fraction 0.01` says VAF=0.01?

I also recall @ekg saying that those parameters are only used to determine 'candidates' but are not hard cutoffs.

**Comment by ekg** [comment]
I believe that setting --min-alternate-count 2 and --min-coverage 10 shouldn't have this effect. Can I confirm that you're on the current HEAD of master here?

In general it's _very rare_ that setting hard filters (like --min-coverage 10 --min-base-quality 20 --min-mapping-quality 20) will improve your results. Of course this isn't a hard rule, but that's my impression based on numerous examples. It's always better to filter post-hoc if you have other models of what are going on than try to get freebayes to remove information pre-call.

**Comment by annaquaglieri16** [comment]
Thanks to both of you for your suggestion. I do agree that setting hard filters doesn't necessarily improve the results but I was trying to set some thresholds to make different callers comparable. 
However, I think at this stage I will stick with the default parameters for every caller.

I am using freebayes version:  v1.1.0-50-g61527c5 installed on the institute servers a few months ago. 

Is this correct to consider the following as Freebayes default for VAF? And,if so, isn't 20% quite a high threshold?

   -F --min-alternate-fraction N
                   Require at least this fraction of observations supporting
                   an alternate allele within a single individual in the
                   in order to evaluate the position.  default: 0.2

Thanks, 

Anna

**Comment by annaquaglieri16** [comment]
I will confirm with IT that they are running on the current HEAD of master. 

Cheers,
Anna

**Comment by annaquaglieri16** [comment]
I reckon my questions is answered by this comments in the README (If I got it right):

Observation thresholds
As a guard against spurious variation caused by sequencing artifacts, positions are skipped when no more than --min-alternate-count or --min-alternate-fraction non-clonal observations of an alternate are found in one sample. These default to 2 and 0.2 respectively. The default setting of --min-alternate-fraction 0.2 is suitable for diploid samples but should be changed for ploidy > 2.

With default settings Freebayes is not suitable for cancer variant calling where multiple clones can be present. 

Cheers, 

Anna

**Comment by wangyugui** [comment]
--min-alternate-fraction is used to filter allele. and it is not used in GT result?

The default GT policy is not good for tumor, but the AD info of all allele is good for tumor.

**Comment by ekg** [comment]
It is used on the input. The best thing is usually to call first with no
filters and then filter after. The only reason for input filters is for
performance tuning in very difficult contexts. In the vast majority of
cases I've seen prefiltering harm's performance by removing useful
information at an early stage. It is best to propagate probabilistic
information through to the later stages of analysis.

Does the OP still get the same discrepancy when running without any filters?
