### ISSUE TITLE
freebayes changes reference allele to N in the output vcf file

### ISSUE THREAD

**Issue by zpingfeng** [freebayes/freebayes#457]
Has anyone seen that the freebayes changes reference allele to N in the output vcf file? This causes problem when I try to write out fasta file using bcftools consensus -f reference.fa.

ERROR message:

The fasta sequence does not match the REF allele at cpl_Euc_Mauve_Alignment_extraction_ndhF:196:
   .vcf: [N]
   .vcf: [N] <- (ALT)
   .fa:  [M]GAGTTCGGTCACTTAATAGATCCACTTACTTCTATTATGTTAATATTAATTACTACTGTTGGAATTTTGGTTCTTTTTTATAGTGACAATTATATGTCTCATGATCAAGGATATTTGAGATTTTTTGCTTATATGAGTTTTTTCAATACTTCCATGTTGGGATTAGTTACTAGTTCGAATTTGATACAAATTTATATTTTTTGGGAATTAGTTGGAATGTGTTCTTATCTATTAATAGGTTTTTGGTTCACACGACCTAGTGCGGCGACTGCTTGTCAAAAAGCGTTTGTAACGAATCGTGTAGGCGATTTTGGTTTATTATTAGGAATTTTAGGTCTTTATTGGATAACCGGTAGTTTTGAATTTCGGGATTTGTTCCAAATATTGAATAACTTGATTTATAATAATGAGGTTCCTTTTTTATTTCTTACTTTGTGTGCCTTTCTTTTATTTGCAGGTGCAGTTGCGAAATCGGCACAATTCCCCCTTCATGTATGGTTACCTGATGCCATGGAAGGCCCTACTCCCATTTCGGCTCTTATACATGCCGCTACTATGGTAGCAGCGGGCATTTTTCTTGTAGCTCGACTTCTTCCTCTTTTTATAATCATACCTTACATAATGAATTTCATATCTTTAATAGGTATAATAACAGTATTATTAGGAGCTACTTTAGCTCTTGCTCAAAAAGATATTAAAAGAGGTTTAGCTTATTCTACAATGTCTCAATTGGGTTATATGATGTTAGCTCTAGGTATGGGGTCTTATCGAGCCGCTTTATTTCATTTGATTACTCATGCTTATTCAAAAGCATTGTTGTTTTTAGGATCCGGATCAATTATTCATTCAATGGAAGCTATTGTTGGATATTCTCCAGATAAAAGTCAGAATATGGTTCTTATGGGAGGTTTAAAAAAGCATGTACCAATTACAAAAACTGCTTTTTTAGTAGGTACACTTTCTCTTTGTGGTATTCCCCCCCTTGCTTGTTTTTGGTCCAAAGATGAAATTCTTAATGATAGTTGGTTGTATTCACCTATTTTCGCAATAATAGCTTGTTCCACAGCAGGATTAACCGCATTTTATATGTTTCGAATCTATTTMCTTACTTTTGAGGGACATTTCAATGTTCATTTTCAAAATTACAATGGTCAAAAAAGTAGTTCCTGCTATTCAATATCTCTATGGGGAAAAGAAGTGCCAAAAAYGATTAAAAATCATTTTTGTTTATTAAGTTTATTRACAATGAATAATAATGAAAGGRCTTCTTTTTTTTCGAATAARACATATCAAATTGATGGTAATGGAAAAAACAGGATACGYCCTTTTATTACTATTACTMATTTTGTCACTAAAAAWACTTTCTCTTATCCTCATGAATCGGACAATACCATGTTRTTTTCTATGGTTATATTAGTGYYATTTACTTTGTTTGTTGGGGTCGTAGGAATTCCCTTTGCTTTTAATCAAGAAGAAATTCATTTGGATATATTATCTAAATTGTTAAATCCGTCTATAAACCTTTTACATCCGAATTCAAATAATTCGGTGGATTGGTATGAATTTGTGACAAATGCAAGTTTTTCTGTCAGWATAGCTTTTTTCGGAATATTTATAGSGTCTTTTTTATATAASCCTATTTATTCATCTTTACAAAATTTGAACTTACTRAATTCGTTTTCTAAAAGAGGTYCTAATMGAATTTTAGGGGACAGAATAAGAAATGGGATATATGATTGGTCATATAATCGTGGTTACATAGATGCTTTTTATACAATAYCCTTAACTCAGGGTATAAGAGGACTAGCTGAACTAATTCATTTTTTGGATAGACGASTAATTGATGGAATTACGAATGGTYTCG

 
The vcf file looks like:
...
cpl_Euc_Mauve_Alignment_extraction_ndhF 196 . N A 1994.69 . AB=0;ABP=0;AC=2;AF=1;AN=2;AO=62;CIGAR=1X;DP=62;DPB=62;DPRA=0;EPP=3.15039;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=57.6452;MQMR=0;NS=1;NUMALT=1;ODDS=90.5554;PAIRED=0.967742;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=2291;QR=0;RO=0;RPL=19;RPP=23.184;RPPR=0;RPR=43;RUN=1;SAF=33;SAP=3.57068;SAR=29;SRF=0;SRP=0;SRR=0;TYPE=snp GT:DP:AD:RO:QR:AO:QA:GL 1/1:62:0,62:0:0:62:2291:-204.562,-18.6639,0
...
cpl_Euc_Mauve_Alignment_extraction_ndhF 1404 . N C 41.5189 . AB=0;ABP=0;AC=2;AF=1;AN=2;AO=3;CIGAR=1X;DP=3;DPB=3;DPRA=0;EPP=9.52472;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=25;MQMR=0;NS=1;NUMALT=1;ODDS=8.76405;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=110;QR=0;RO=0;RPL=3;RPP=9.52472;RPPR=0;RPR=0;RUN=1;SAF=0;SAP=9.52472;SAR=3;SRF=0;SRP=0;SRR=0;TYPE=snp GT:DP:AD:RO:QR:AO:QA:GL 1/1:3:0,3:0:0:3:110:-6.86106,-0.90309,0
cpl_Euc_Mauve_Alignment_extraction_ndhF 1889 . N C 5.93749 . AB=0;ABP=0;AC=2;AF=1;AN=2;AO=2;CIGAR=1X;DP=2;DPB=2;DPRA=0;EPP=7.35324;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=12;MQMR=0;NS=1;NUMALT=1;ODDS=1.07239;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=65;QR=0;RO=0;RPL=0;RPP=7.35324;RPPR=0;RPR=2;RUN=1;SAF=2;SAP=7.35324;SAR=0;SRF=0;SRP=0;SRR=0;TYPE=snp GT:DP:AD:RO:QR:AO:QA:GL 1/1:2:0,2:0:0:2:65:-2.27191,-0.60206,0
cpl_Euc_Mauve_Alignment_extraction_ndhF 1895 . N A 13.4169 . AB=0;ABP=0;AC=2;AF=1;AN=2;AO=3;CIGAR=1X;DP=3;DPB=3;DPRA=0;EPP=3.73412;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=11;MQMR=0;NS=1;NUMALT=1;ODDS=3.04259;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=111;QR=0;RO=0;RPL=0;RPP=9.52472;RPPR=0;RPR=3;RUN=1;SAF=2;SAP=3.73412;SAR=1;SRF=0;SRP=0;SRR=0;TYPE=snp GT:DP:AD:RO:QR:AO:QA:GL 1/1:3:0,3:0:0:3:111:-3.07641,-0.90309,0
cpl_Euc_Mauve_Alignment_extraction_ndhF 1911 . G A 144.576 . AB=0;ABP=0;AC=2;AF=1;AN=2;AO=9;CIGAR=1X;DP=9;DPB=9;DPRA=0;EPP=3.25157;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=25.5556;MQMR=0;NS=1;NUMALT=1;ODDS=17.0818;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=341;QR=0;RO=0;RPL=0;RPP=22.5536;RPPR=0;RPR=9;RUN=1;SAF=4;SAP=3.25157;SAR=5;SRF=0;SRP=0;SRR=0;TYPE=snp GT:DP:AD:RO:QR:AO:QA:GL 1/1:9:0,9:0:0:9:341:-18.3847,-2.70927,0
cpl_Euc_Mauve_Alignment_extraction_ndhF 1917 . G T 197.016 . AB=0;ABP=0;AC=2;AF=1;AN=2;AO=13;CIGAR=1X;DP=13;DPB=13;DPRA=0;EPP=3.17734;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=26;MQMR=0;NS=1;NUMALT=1;ODDS=22.627;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=475;QR=0;RO=0;RPL=0;RPP=31.2394;RPPR=0;RPR=13;RUN=1;SAF=6;SAP=3.17734;SAR=7;SRF=0;SRP=0;SRR=0;TYPE=snp GT:DP:AD:RO:QR:AO:QA:GL 1/1:13:0,13:0:0:13:475:-24.9727,-3.91339,0
cpl_Euc_Mauve_Alignment_extraction_ndhF 1923 . G T 417.729 . AB=0;ABP=0;AC=2;AF=1;AN=2;AO=21;CIGAR=1X;DP=21;DPB=21;DPRA=0;EPP=3.1137;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=31.2381;MQMR=0;NS=1;NUMALT=1;ODDS=33.7174;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=741;QR=0;RO=0;RPL=0;RPP=48.6112;RPPR=0;RPR=21;RUN=1;SAF=10;SAP=3.1137;SAR=11;SRF=0;SRP=0;SRR=0;TYPE=snp GT:DP:AD:RO:QR:AO:QA:GL 1/1:21:0,21:0:0:21:741:-49.6429,-6.32163,0
cpl_Euc_Mauve_Alignment_extraction_ndhF 1950 . G C 786.84 . AB=0;ABP=0;AC=2;AF=1;AN=2;AO=35;CIGAR=1X;DP=35;DPB=35;DPRA=0;EPP=3.07234;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=34.9143;MQMR=0;NS=1;NUMALT=1;ODDS=53.1255;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=1290;QR=0;RO=0;RPL=0;RPP=79.0118;RPPR=0;RPR=35;RUN=1;SAF=17;SAP=3.07234;SAR=18;SRF=0;SRP=0;SRR=0;TYPE=snp GT:DP:AD:RO:QR:AO:QA:GL 1/1:35:0,35:0:0:35:1290:-90.9785,-10.5361,0
...
cpl_Euc_Mauve_Alignment_extraction_ndhF 2033 . N G 802.419 . AB=0;ABP=0;AC=2;AF=1;AN=2;AO=35;CIGAR=1X;DP=35;DPB=35;DPRA=0;EPP=3.07234;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=34.9143;MQMR=0;NS=1;NUMALT=1;ODDS=53.1255;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=1298;QR=0;RO=0;RPL=35;RPP=79.0118;RPPR=0;RPR=0;RUN=1;SAF=17;SAP=3.07234;SAR=18;SRF=0;SRP=0;SRR=0;TYPE=snp GT:DP:AD:RO:QR:AO:QA:GL 1/1:35:0,35:0:0:35:1298:-92.5365,-10.5361,0
cpl_Euc_Mauve_Alignment_extraction_ndhF 2039 . G A 537.808 . AB=0;ABP=0;AC=2;AF=1;AN=2;AO=22;CIGAR=1X;DP=22;DPB=22;DPRA=0;EPP=3.40511;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=36.6818;MQMR=0;NS=1;NUMALT=1;ODDS=35.1036;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=836;QR=0;RO=0;RPL=22;RPP=50.7827;RPPR=0;RPR=0;RUN=1;SAF=10;SAP=3.40511;SAR=12;SRF=0;SRP=0;SRR=0;TYPE=snp GT:DP:AD:RO:QR:AO:QA:GL 1/1:22:0,22:0:0:22:836:-62.0275,-6.62266,0
cpl_Euc_Mauve_Alignment_extraction_ndhF 2057 . N T 48.3554 . AB=0;ABP=0;AC=2;AF=1;AN=2;AO=2;CIGAR=1X;DP=2;DPB=2;DPRA=0;EPP=3.0103;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=33;MQMR=0;NS=1;NUMALT=1;ODDS=7.37776;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=76;QR=0;RO=0;RPL=2;RPP=7.35324;RPPR=0;RPR=0;RUN=1;SAF=1;SAP=3.0103;SAR=1;SRF=0;SRP=0;SRR=0;TYPE=snp GT:DP:AD:RO:QR:AO:QA:GL 1/1:2:0,2:0:0:2:76:-6.03938,-0.60206,0
...

run command:
freebayes   -b $bamf -f $ref -i -X -u -F 0.3 > $odir/$outf.vcf

**Comment by Buuntu** [comment]
I am getting very similar results.  I get lots of alleles as "N" in the reference that I don't get with bcftools for example.  Running freebayes-parallel with `--pooled-continuous -F 0.2 -C 5 -ploidy 1` I am doing aligntment with minimap2 and then generating the bam file with samtools.

**Comment by ekg** [comment]
Would you please look at the reference file where the Ns are given? What do
you see at the place where you see an N?

Is the file in unix format (use tofrodos if not) and is the FASTA index
(.fai) up to date?
