### ISSUE TITLE
Filtering by QUAL

### ISSUE THREAD

**Issue by helloeoh001** [freebayes/freebayes#462]
The filter, QUAL>1, excludes one of the most important variant KRAS G12X in cancer genomics.

The QUAL value of KRAS G12X is always very low such as 1.96241e-13.

Mapping quality, and base quality are all very very good.

Could you explain? and how to calculate QUAL by freebayes?

chr12   25398284        rs121913529     C       A       1.96241e-13     .       NS=1;DP=831;DPB=831.0;AC=1;AN=2;AF=0.5;RO=716;AO=115;PRO=0.0;PAO=0.0;QR=23495;QA=3591;PQR=0.0;PQA=0.0;SRF=354;SRR=362;SAF=57;SAR=58;SRP=3.2044;SAP=3.02918;AB=0.138387;ABP=946.859;RUN=1;RPP=8.4673;RPPR=117.152;RPL=66.0;RPR=49.0;EPP=3.02918;EPPR=5.06046;DPRA=0.0;ODDS=87.2282;GTI=0;TYPE=snp;CIGAR=1X;NUMALT=1;MEANALT=1.0;LEN=1;MQM=60.0;MQMR=60.0;PAIRED=1.0;PAIREDR=0.997207;technology.il
lumina=1.0;ANN=A|missense_variant|MODERATE|KRAS|KRAS|transcript|NM_033360|protein_coding|2/6|c.35G>T|p.Gly12Val

**Comment by ekg** [comment]
QUAL is assuming you have a diploid (or whatever ploidy you set), so it
doesn't seem like it's going to do what you want if you are looking at
somatic variation. I wouldn't filter using it if you have this kind of
application. Instead, I would apply something like hhga:
https://github.com/ekg/hhga.

If you are interested in how QUAL is calculated please see the preprint or
updated draft in the repo (cd paper && make).
