### ISSUE TITLE
Compliation problems

### ISSUE THREAD

**Issue by xapple** [freebayes/freebayes#47]
A strange error occured when I typed `make`. Maybe you can help me ?

```
xapple@cluster freebayes ((03cb231...)) $ make
cd src && make
make[1]: Entering directory `~/test/freebayes/src'
cd ../bamtools && mkdir -p build && cd build && cmake .. && make
-- The C compiler identification is unknown
-- The CXX compiler identification is GNU
-- Check for working C compiler: /bubo/sw/comp/gcc/4.6.3_kalkyl/bin/g++
-- Check for working C compiler: /bubo/sw/comp/gcc/4.6.3_kalkyl/bin/g++ -- broken
CMake Error at /usr/share/cmake/Modules/CMakeTestCCompiler.cmake:32 (MESSAGE):
  The C compiler "/bubo/sw/comp/gcc/4.6.3_kalkyl/bin/g++" is not able to
  compile a simple test program.

  It fails with the following output:

   Change Dir: ~/test/freebayes/bamtools/build/CMakeFiles/CMakeTmp



  Run Build Command:/usr/bin/gmake "cmTryCompileExec/fast"

  gmake[2]: Entering directory
  `~/test/freebayes/bamtools/build/CMakeFiles/CMakeTmp'

  /usr/bin/gmake -f CMakeFiles/cmTryCompileExec.dir/build.make
  CMakeFiles/cmTryCompileExec.dir/build

  gmake[3]: Entering directory
  `~/test/freebayes/bamtools/build/CMakeFiles/CMakeTmp'

  /usr/bin/cmake -E cmake_progress_report
  ~/test/freebayes/bamtools/build/CMakeFiles/CMakeTmp/CMakeFiles
  1

  Building C object CMakeFiles/cmTryCompileExec.dir/testCCompiler.c.o

  /bubo/sw/comp/gcc/4.6.3_kalkyl/bin/g++ -o
  CMakeFiles/cmTryCompileExec.dir/testCCompiler.c.o -c
  ~/test/freebayes/bamtools/build/CMakeFiles/CMakeTmp/testCCompiler.c



  ~/test/freebayes/bamtools/build/CMakeFiles/CMakeTmp/testCCompiler.c:2:3:
  error: #error "The CMAKE_C_COMPILER is set to a C++ compiler"

  gmake[3]: *** [CMakeFiles/cmTryCompileExec.dir/testCCompiler.c.o] Error 1

  gmake[3]: Leaving directory
  `~/test/freebayes/bamtools/build/CMakeFiles/CMakeTmp'

  gmake[2]: *** [cmTryCompileExec/fast] Error 2

  gmake[2]: Leaving directory
  `~/test/freebayes/bamtools/build/CMakeFiles/CMakeTmp'





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:9 (project)


-- Configuring incomplete, errors occurred!
make[1]: *** [../bamtools/lib/libbamtools.a] Error 1
make[1]: Leaving directory `~/test/freebayes/src'
make: *** [all] Error 2
```

**Comment by rockeet** [comment]
CMake is bullshit

**Comment by nextkitt** [comment]
> Any update? Similar issue for current head:
> 
> make
> cd src && make
> make[1]: Entering directory `/work2/UQ/Science/SCMB/Beatson/bin/freebayes/freebayes/src'
> DETECTED_VERSION = v9.9.2-12-gc3e485d-dirty
> CURRENT_VERSION = v9.9.2-12-gc3e485d-dirty
> cd ../bamtools && mkdir -p build && cd build && cmake .. && make
> -- The C compiler identification is unknown
> -- The CXX compiler identification is GNU
> -- Check for working C compiler: /sw/gcc/4.5.2/bin/g++
> -- Check for working C compiler: /sw/gcc/4.5.2/bin/g++ -- broken
> CMake Error at /sw/CMake/2.8.5/local/gcc-4.5.2/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:52 (MESSAGE):
> The C compiler "/sw/gcc/4.5.2/bin/g++" is not able to compile a simple test
> program.
> 
> It fails with the following output:
> 
> Change Dir: /home/uqmstan1/Beatson_shared/bin/freebayes/freebayes/bamtools/build/CMakeFiles/CMakeTmp
> 
> Run Build Command:/usr/bin/gmake "cmTryCompileExec/fast"
> 
> gmake[2]: Entering directory
> `/work2/UQ/Science/SCMB/Beatson/bin/freebayes/freebayes/bamtools/build/CMakeFiles/CMakeTmp'
> 
> /usr/bin/gmake -f CMakeFiles/cmTryCompileExec.dir/build.make
> CMakeFiles/cmTryCompileExec.dir/build
> 
> gmake[3]: Entering directory
> `/work2/UQ/Science/SCMB/Beatson/bin/freebayes/freebayes/bamtools/build/CMakeFiles/CMakeTmp'
> 
> /sw/CMake/2.8.5/local/gcc-4.5.2/bin/cmake -E cmake_progress_report
> /home/uqmstan1/Beatson_shared/bin/freebayes/freebayes/bamtools/build/CMakeFiles/CMakeTmp/CMakeFiles
> 1
> 
> Building C object CMakeFiles/cmTryCompileExec.dir/testCCompiler.c.o
> 
> /sw/gcc/4.5.2/bin/g++ -o CMakeFiles/cmTryCompileExec.dir/testCCompiler.c.o
> -c
> /home/uqmstan1/Beatson_shared/bin/freebayes/freebayes/bamtools/build/CMakeFiles/CMakeTmp/testCCompiler.c
> 
> /home/uqmstan1/Beatson_shared/bin/freebayes/freebayes/bamtools/build/CMakeFiles/CMakeTmp/testCCompiler.c:2:3:
> error: #error "The CMAKE_C_COMPILER is set to a C++ compiler"
> 
> gmake[3]: Leaving directory
> `/work2/UQ/Science/SCMB/Beatson/bin/freebayes/freebayes/bamtools/build/CMakeFiles/CMakeTmp'
> 
> gmake[3]: *** [CMakeFiles/cmTryCompileExec.dir/testCCompiler.c.o] Error 1
> 
> gmake[2]: Leaving directory
> `/work2/UQ/Science/SCMB/Beatson/bin/freebayes/freebayes/bamtools/build/CMakeFiles/CMakeTmp'
> 
> gmake[2]: *** [cmTryCompileExec/fast] Error 2
> 
> CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
> CMakeLists.txt:9 (project)
> 
> -- Configuring incomplete, errors occurred!
> make[1]: *** [../bamtools/lib/libbamtools.a] Error 1
> make[1]: Leaving directory `/work2/UQ/Science/SCMB/Beatson/bin/freebayes/freebayes/src'
> make: *** [all] Error 2

Please check your env：

```
env | grep -i 'CC='
```

if `CC=/xxx/bin/g++`, change `CC=/xxx/bin/gcc`.

**Comment by ekg** [comment]
I think you might want to update your freebayes version using git. I
suggest cloning a new repository and starting from scratch:

git clone --recursive ...
