### ISSUE TITLE
Sample name is "unknown" and can't be specified

### ISSUE THREAD

**Issue by adamnovak** [freebayes/freebayes#471]
Freebayse has a `-s --samples FILE` option, but that takes a filename and restricts calling to certain samples, where the sample info is pulled from the BAM file.

I have a (simulated) single-sample BAM with no sample annotations in it, and I want Freebayes to call on it and output calls with a particular sample name. Freebayse insists on naming the output sample "unknown" and I am not sure how to make it call it something else.

**Comment by ekg** [comment]
Use bamaddrg or some tool in Picard to add a sample name and read group for
the sample. That's how you specify sample names.

**Comment by adamnovak** [comment]
The workaround I'm using right now in toil-vg is to modify the output VCF,
which toil-vg already has to touch to apply an offset. That seems to work.
But I guess we should be adding sample information when we convert from GAM
to BAM in that pipeline, or when we generate the GAM to begin with.
