### ISSUE TITLE
Conflict of packages for v1.2.0 on bioconda

### ISSUE THREAD

**Issue by kmgibson** [freebayes/freebayes#472]
Hi,
I am trying to install the latest version (1.2.0) from bioconda, with `condo install freebayes=1.2.0`.

However, this version is incompatible with `yarl`, as well as `snakemake` and `idna_ssl`. However, version 1.1.0 or called `v1.1.0-dirty` in the documentation seems to install and work just fine.

Upon looking further into the dependencies for v1.2.0 vs v1.1.0, there is an option for 1.1.0 to have python >3 whereas v1.2.0 has python v2.7 hard wired. Will this be changed in the future to be like v1.1.0, where there are multiple python versions that work with freebayes v1.2.0?

Best,
Keylie

**Comment by tseemann** [comment]
@kmgibson Erik is not in charge or responsible for the Bioconda packages.

@slugger70 - can you advise on what @kmgibson should do here?

**Comment by Slugger70** [comment]
I've asked this question on the bioconda gitter channel. If you don't hear back @kmgibson, try asking on the Bioconda git repo issues page.

**Comment by tseemann** [comment]
@npavlovikj wow i didn't know bioconda attempted the `2to3` step. that could be risky. does it check the return code of to see if it ever fails?

**Comment by kmgibson** [comment]
@tseemann, I'm sorry. I didn't know whose job it was. I should have left it general.

@Slugger70, I thought I checked Bioconda's page for this, but couldn't find it. I'll see what happens and may ask there. 

I'll use the older version (1.1.0) for now. I was just curious if it was going to be updated. Thanks!
