### ISSUE TITLE
genotyping inconsistency for combined populations

### ISSUE THREAD

**Issue by mx52** [freebayes/freebayes#476]
Hi,

I have two selective introgression lines (line 1, n = 385, line 2, n = 166) where I expect SNPs closely linked to a genetic marker to be shared between the lines, and SNPs outside this region should be largely unique within each line. For one downstream analysis, I need the genotype at those unique sites in other other family that are absent in this family (i.e., genotype in line 1 at SNP sites that are unique in line 2). I have two questions regarding this:

1. I recently discovered the option of forcing SNP call using a vcf input. I'm wondering if this is the best way to get genotype data I need. Specifically, I would call SNPs in each line separately, obtain a list of unique SNPs, and force call at these sites in the other family.

2. Before I became aware of the option above, I obtained the genotypes I need by combining the two lines in the SNP call. In this SNP call, I used exactly the same criteria as used in the SNP call in each line separately. This did get me the data I needed, but I expected genotypes from separately calls to be the same as in the combined calls. But when I compared denotyoes from the two runs of SNP calls, I found a low level (but not so low that I can simply ignore) of differences. For line 1, I found 67 differences out of 27,886 genotypes (0.24%). All these cases occur when there was allele imbalance, and H is called in one run but not the other. Specifically, in 43 cases, H is called in the combined run but not the separate run, and in the rest 24 cases, H is called in the separate call run but not in the combined run. In addition, 65 out of 67 genotyping differences occur at sites that have very different allele frequency in line 2. 

Based on this observation, I'm worried that (1) because the combined lines is not really a Hardy-Weinberg population, the hwe prior may be causing a problem in genotype call, and (2) the family in which the site is not segregating is biasing the allele frequency observation, and in turn, bias genotype call in the family where the SNP is actually segregating, and this is aggravated when there is allele imbalance. Because of these concerns, I'm wondering if combining two independent introgression lines is a good practice at all and if there is any option to deal with this issue in Freebayes. The bioinfo facility at my university suggested me to turn off the hwe prior in the combined call. Do you think it would help?

Thank you very much for your input!

**Comment by ekg** [comment]
I would suggest running the samples together. If you're worried the model will cause bias you can separate the calculations for genotyping by giving a --populations file that describes which sample is in which population. This will ensure the allele representation is consistent but the genotyping is unaffected by population structure.

**Comment by mx52** [comment]
Hi Erik,

Many thanks for the suggestion! I'll try using the --populations option right away!

**Comment by mx52** [comment]
Hi Erik,

I tried what you suggested and it decreased inconsistent genotype from 67 to 20 out of 27,886 genotype. 

In the meanwhile, I am calling SNPs in each line separately using the SNP sites from the other family as an input vcf file and use --min-alternate-count 0 and --use-only-input-alleles. It's going very slow though. By doing this, does Freebayes still considers all other sites that are not in the input file (because as I understand, --use-only-input-alleles is for allele filtering, not for sites, right?)? I do not need genotypes from sites that are not in the input files. Is there a way to ask Freebayes to only consider sites in the input file and so I can speed up the SNP calling?

Many thanks!

**Comment by ekg** [comment]
It should call only those sites that are given. Still it has to process the
entire set. It will not be much faster than the non targeted process.

The number of inconsistent genotypes would seem to be in the typical range
for raw genotyping error.
