### ISSUE TITLE
sensitivity in a large cohort

### ISSUE THREAD

**Issue by ju-cheng** [freebayes/freebayes#477]
I have a large cohort with over 6000 samples. When I tried variant calling with the individual samples, one bam file for each of the samples, seven of them were mutated with strong evidence. But when I used a bam file with all the 6000 samples, the variant didn't show up in the vcf file. Is there anyway to keep the sensitivity across a large cohort?

**Comment by ekg** [comment]
This seems extremely strange to me. If the variant is reported in a single
sample it will be reported in a larger cohort. This is because the
reporting is based on the count of alternate allele observations and the
fraction these have in a single individual. The quality may go up or down
but that is secondary. Is another variant reported nearby in place of the
ones you see? You see the 6000 samples in the header of the VCF (there
could be a problem with read group and sample annotations on the alignments
clashing leading to this effect).

**Comment by ju-cheng** [comment]
thanks @ekg 
Yes I did see another variant nearby. The other variant was correctly called in a cohort of over 6000 samples.

**Comment by nclowell** [comment]
I have a similar issue. I compared a subset of my data (~50 individuals) to the full data set (400 individuals). Of the loci that are genotyped across the majority of individuals in the subset, only 1.5% of these are genotyped at all in the full data set. 

@ju-cheng Did you happen to learn why this happened in your data?

**Comment by ekg** [comment]
Could you have a collision in your sample or read group IDs?

**Comment by nclowell** [comment]
I don't think so - I just double-checked that the sample names are unique.

**Comment by ekg** [comment]
That's amazing. Is there any way you could share one site, both the full
set and also one where it calls the expected genotypes?

This is after filtering at some quality threshold?

**Comment by nclowell** [comment]
For my subset of data, I filtered the vcf file for many things, including minimum quality score of 20. This produced the ~4000 SNPs, of which very few are in the unfiltered vcf file for the entire data set.

I'm attaching a text file with the first three variants shared between my quality filtered subset and my unfiltered full data set. From my eyeballing, they look very similar re: genotypes, missing data, read depth, etc.
[shared_vars.txt](https://github.com/ekg/freebayes/files/3375135/shared_vars.txt)

I should mention I'm using the dDocent pipeline, which calls freebayes for genotype calling. So I'm not calling freebayes directly! But it appears dDocent names all intermediate files with the original file names, so there still shouldn't be any redundancies.

Can there be collisions with other objects other than sample names?

Thank you!

**Comment by ekg** [comment]
I suggest that you open an issue on dDocent. Please CC me there with @ekg.
