### ISSUE TITLE
QUAL score of '.'

### ISSUE THREAD

**Issue by jgbaum** [freebayes/freebayes#478]
Hi,

We've been using Freebayes indirectly as part of Speedseq for quite some time and a question recently arose as to the meaning of QUAL scores that are a period (.).  For example:

```
5	157481885	.	C	T	.	PASS	SSC=28.913;TYPE=snp	GT:GQ:DP:RO:QR:AO:QA:GL	0/0:99:279:279:9865:0:0:0,-83.9874,-887.737	0/0:99:410:388:13804:22:756:0,-55.0744,-1173.72
```

Any information would be appreciated, including guidance on whether these should be filtered from downstream analysis.  As an FYI, we use this version (2cb0fb8adb9fa9c429da81b211d39050ed368fdc) from Jun 20, 2016.

Thanks and happy to provide more information, if necessary.

-Jason

**Comment by ekg** [comment]
I suggest you make this query in the speedseq issues page:
https://github.com/hall-lab/speedseq

freebayes always writes a QUAL so this has been modified somehow downstream
of it.

**Comment by jgbaum** [comment]
Thank, much.  I've posted and issue there (https://github.com/hall-lab/speedseq/issues/128).

Also, I realized I put the SHA-1 hash of speedseq in the original issue...apologies.  We are using version 0.9.21 of Freebayes (1635a15917a444bb6aed9cba457b6a192f1f4962)
