### ISSUE TITLE
freebayes aborted with .vcf partially generated

### ISSUE THREAD

**Issue by jon-xu** [freebayes/freebayes#480]
Dear Friends,

Who could give a hand on this?

I ran freebayes on my reads against hg19, and it aborted half way generating vcf file (I can see some SNVs called).

Not sure what's happening here...

Any advice would be helpful!

Cheers,
Jon

**Comment by ekg** [comment]
Did you run out of memory or was the time limit of the job exceeded?

**Comment by jon-xu** [comment]
Hi Erik,

Thanks for the reply!

No it hasn’t run out of memory nor time limit of the job exceeded.

It just stopped at some reads, as I can figure out which reads if I take away from the sam/bam file, the freebayes can work well.

And that’s why freebayes stopped half way.

But I just cannot tell the difference of these reads from others…

Cheers,
Jon



On 11 07 2018, at 18:55, Erik Garrison <notifications@github.com<mailto:notifications@github.com>> wrote:

Did you run out of memory or was the time limit of the job exceeded?

**Comment by ekg** [comment]
If you can share the specific subset of reads that contain the problematic
one (say 1000 reads) then we can figure out what's going on.

**Comment by jon-xu** [comment]
Hi Erik,

Here I have attached 6 files:
1.sam, 1.bam are the ones leading to error when running freebayes, although 1.vcf can be generated (till before the problematic read).

And if you remove the very last read (NB500915:123:HMWCMBGXX:1:21109:16107:13834)from 1.sam, to become 2.sam and 2.bam, freebayes can generate 2.vcf without error.

The freebayes version is 1.1.0, and the reference genome is hg19 (I changed the chr21 to 21 for example to adapt to the sam file information).

And here below is the error message:

*** glibc detected *** freebayes: free(): invalid pointer: 0x000000000082b6c4 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x75dee)[0x7f6004a25dee]
/lib64/libc.so.6(+0x78c3d)[0x7f6004a28c3d]
/usr/lib64/libstdc++.so.6(_ZNSsD1Ev+0x39)[0x7f600527b4c9]
freebayes[0x454649]
freebayes[0x455bda]
freebayes[0x453450]
freebayes[0x453b29]
freebayes[0x408242]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x7f60049ced1d]
freebayes[0x407929]
======= Memory map: ========
00400000-00567000 r-xp 00000000 d7f:3e8ec 144115242450857568             /opt/Modules/freebayes/1.1.0/bin/freebayes
00766000-0082b000 rw-p 00166000 d7f:3e8ec 144115242450857568             /opt/Modules/freebayes/1.1.0/bin/freebayes
0082b000-0082d000 rw-p 00000000 00:00 0
00de9000-00e62000 rw-p 00000000 00:00 0                                  [heap]
7f5ff8000000-7f5ff8021000 rw-p 00000000 00:00 0
7f5ff8021000-7f5ffc000000 ---p 00000000 00:00 0
7f5ffe4f7000-7f60016de000 rw-p 00000000 00:00 0
7f60045b0000-7f60049b0000 rw-p 00000000 00:00 0
7f60049b0000-7f6004b3a000 r-xp 00000000 80a:bc76c 144115562711214773     /lib64/libc-2.12.so
7f6004b3a000-7f6004d3a000 ---p 0018a000 80a:bc76c 144115562711214773     /lib64/libc-2.12.so
7f6004d3a000-7f6004d3e000 r--p 0018a000 80a:bc76c 144115562711214773     /lib64/libc-2.12.so
7f6004d3e000-7f6004d40000 rw-p 0018e000 80a:bc76c 144115562711214773     /lib64/libc-2.12.so
7f6004d40000-7f6004d44000 rw-p 00000000 00:00 0
7f6004d44000-7f6004d5a000 r-xp 00000000 80a:bc76c 144115562711214801     /lib64/libgcc_s-4.4.7-20120601.so.1
7f6004d5a000-7f6004f59000 ---p 00016000 80a:bc76c 144115562711214801     /lib64/libgcc_s-4.4.7-20120601.so.1
7f6004f59000-7f6004f5a000 rw-p 00015000 80a:bc76c 144115562711214801     /lib64/libgcc_s-4.4.7-20120601.so.1
7f6004f5a000-7f6004fdd000 r-xp 00000000 80a:bc76c 144115562711214831     /lib64/libm-2.12.so
7f6004fdd000-7f60051dc000 ---p 00083000 80a:bc76c 144115562711214831     /lib64/libm-2.12.so
7f60051dc000-7f60051dd000 r--p 00082000 80a:bc76c 144115562711214831     /lib64/libm-2.12.so
7f60051dd000-7f60051de000 rw-p 00083000 80a:bc76c 144115562711214831     /lib64/libm-2.12.so
7f60051de000-7f60052c6000 r-xp 00000000 80a:bc76c 144115562744660314     /usr/lib64/libstdc++.so.6.0.13
7f60052c6000-7f60054c6000 ---p 000e8000 80a:bc76c 144115562744660314     /usr/lib64/libstdc++.so.6.0.13
7f60054c6000-7f60054cd000 r--p 000e8000 80a:bc76c 144115562744660314     /usr/lib64/libstdc++.so.6.0.13
7f60054cd000-7f60054cf000 rw-p 000ef000 80a:bc76c 144115562744660314     /usr/lib64/libstdc++.so.6.0.13
7f60054cf000-7f60054e4000 rw-p 00000000 00:00 0
7f60054e4000-7f60054fb000 r-xp 00000000 80a:bc76c 144115562711214863     /lib64/libpthread-2.12.so
7f60054fb000-7f60056fb000 ---p 00017000 80a:bc76c 144115562711214863     /lib64/libpthread-2.12.so
7f60056fb000-7f60056fc000 r--p 00017000 80a:bc76c 144115562711214863     /lib64/libpthread-2.12.so
7f60056fc000-7f60056fd000 rw-p 00018000 80a:bc76c 144115562711214863     /lib64/libpthread-2.12.so
7f60056fd000-7f6005701000 rw-p 00000000 00:00 0
7f6005701000-7f6005716000 r-xp 00000000 80a:bc76c 144115562711214881     /lib64/libz.so.1.2.3
7f6005716000-7f6005915000 ---p 00015000 80a:bc76c 144115562711214881     /lib64/libz.so.1.2.3
7f6005915000-7f6005916000 r--p 00014000 80a:bc76c 144115562711214881     /lib64/libz.so.1.2.3
7f6005916000-7f6005917000 rw-p 00015000 80a:bc76c 144115562711214881     /lib64/libz.so.1.2.3
7f6005917000-7f6005937000 r-xp 00000000 80a:bc76c 144115562711214760     /lib64/ld-2.12.so
7f6005b19000-7f6005b1f000 rw-p 00000000 00:00 0
7f6005b34000-7f6005b36000 rw-p 00000000 00:00 0
7f6005b36000-7f6005b38000 r--p 0001f000 80a:bc76c 144115562711214760     /lib64/ld-2.12.so
7f6005b38000-7f6005b39000 rw-p 00021000 80a:bc76c 144115562711214760     /lib64/ld-2.12.so
7f6005b39000-7f6005b3a000 rw-p 00000000 00:00 0
7ffca858a000-7ffca859f000 rw-p 00000000 00:00 0                          [stack]
7ffca85bd000-7ffca85be000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted

Thanks,
Jon




On 11 07 2018, at 19:19, Erik Garrison <notifications@github.com<mailto:notifications@github.com>> wrote:

If you can share the specific subset of reads that contain the problematic
one (say 1000 reads) then we can figure out what's going on.

**Comment by ekg** [comment]
I don't seem to be getting the attachments. Would you send them to my email address?

**Comment by jon-xu** [comment]
Hi Erik,

Please find them here.



Thanks!
Jon



On 11 07 2018, at 20:12, Erik Garrison <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't seem to be getting the attachments. Would you send them to my email address?

**Comment by ekg** [comment]
This still isn't working. Try sending them to erik dot garrison at gmail.

**Comment by jon-xu** [comment]
Hi Erikson,

Not sure whether the email I sent to gmail reached you?

Cheers,

Jun


Erik Garrison <notifications@github.com<mailto:notifications@github.com>> 於 2018年7月11日 20:21 寫道：

This still isn't working. Try sending them to erik dot garrison at gmail.
