### ISSUE TITLE
freebayes-parallel works for v0.9.20, but not 1.2.0

### ISSUE THREAD

**Issue by hurchu** [freebayes/freebayes#495]
Hi, 
I tried to run freebayes parallel. 
In same machine, same bam file, same reference fa, same command line:
v0.9.20, it finished in about 12 mins.
v1.2.0, it took much longer than v0.9.20. I checked the cpu by "top", it showed
20761 root      20   0  264964 240820   2660 R 100.0  1.6   0:32.40 freebayes                                    
20762 root      20   0  505748 481272   2440 R 100.0  3.2   0:21.10 freebayes                                    
20763 root      20   0  505748 481268   2440 R  99.7  3.2   0:21.08 freebayes                                    
20782 root      20   0  505748 481272   2440 R  99.7  3.2   0:16.05 freebayes       

My command: 
./freebayes-parallel <(./fasta_generate_regions.py hg19.fasta.fai 3000000) 4 --use-duplicate-reads --min-alternate-count 10 --min-alternate-fraction 0.03 --min-coverage 10 --min-base-quality 20 --min-mapping-quality 30 --min-supporting-allele-qsum 20 --min-supporting-mapping-qsum 30 --min-alternate-qsum 40 -f hg19_GRCh37_p13_full.fasta main.bam > main.freebayes.raw.vcf   

Thanks!

**Comment by hurchu** [comment]
I think I found the reason. In 1.2.0, by default, --min-alternate-fraction parameter=0.05, --min-repeat-entropy=1.
I will check and report later.

**Comment by tseemann** [comment]
Version 0.9.20 is from 12 Dec 2014 - nearly 4 years ago, and there have been >400 commits since then,
It may be faster, but it may also be wrong.
*Caveat empor*
