### ISSUE TITLE
GT (0/0) and DP, RO mismatch

### ISSUE THREAD

**Issue by gaosong0329** [freebayes/freebayes#496]
Hi all,

I am currently using Freebayes in my project to detect somatic variants. But I run into a question to understand GT and RO, DP. The details are as follows:

In the VCF file produced by Freebayes, I observed one line: 

12	22063251	.	CAAAAAAAAAAAAAAGAGTAC	CAAAAAAAAAAAAAGAGTAC,CAAAAAAAAAAAAGAGTAC,CAAAAAAAAAAAGAGTAC,CAAAAAAAAAAAAAAAGAGTAC	0	.	AB=0,0,0,0;ABP=0,0,0,0;AC=0,0,0,0;AF=0,0,0,0;AN=2;AO=124,35,8,12;CIGAR=1M1D19M,1M2D18M,1M3D17M,1M1I20M;DP=328;DPB=401.762;DPRA=0,0,0,0;EPP=11.486,3.56868,7.35324,3.0103;EPPR=3.26577;GTI=0;LEN=1,2,3,1;MEANALT=12,12,12,12;MQM=59.8226,60,60,60;MQMR=59.4706;NS=1;NUMALT=4;ODDS=81.4118;PAIRED=0.967742,1,1,1;PAIREDR=0.911765;PAO=39.7833,34.45,31.2,46.7833;PQA=1168.98,999.65,900.4,1387.98;PQR=1950.98;PRO=64.7833;QA=3597,1048,238,282;QR=4411;RO=136;RPL=79,19,6,6;RPP=23.254,3.56868,7.35324,3.0103;RPPR=3.5851;RPR=45,16,2,6;RUN=1,1,1,1;SAF=6,0,0,0;SAP=222.679,79.0118,20.3821,29.068;SAR=118,35,8,12;SRF=1;SRP=289.709;SRR=135;TYPE=del,del,del,ins;technology.ILLUMINA=1,1,1,1	**GT**:**DP**:AD:**RO**:QR:AO:QA:GL	**0/0**:**328**:136,124,35,8,12:**136**:4411:124,35,8,12:3597,1048,238,282:0,-33.3567,-122.293,-235.928,-340.766,-336.344,-300.686,-405.52,-578.33,-383.758,-297.932,-412.044,-614.602,-679.358,-421.417

In this line, since GT is 0/0, I would expect RO (136) to be as close as possible with DP (328). However, RO is only less than half of DP. So why is GT 0/0 in this case? 

The command to generate this vcf is: 

freebayes --bam <my_input_bam> --fasta-reference human_g1k_v37_decoy.fasta --targets <target_bed_file> --vcf <output_vcf_file> --pooled-continuous --haplotype-length 0 --hwe-priors-off --binomial-obs-priors-off --allele-balance-priors-off --min-alternate-fraction 0.01 --min-alternate-count 5 --min-mapping-quality 20 --min-base-quality 20 --read-max-mismatch-fraction 0.05 --reference-quality 60,40 --use-best-n-alleles 6 --min-alternate-qsum 110 --min-supporting-mapping-qsum 110 --strict-vcf

Could anyone give me some hints to understand this scenario, please? Thank you very much!

**Comment by ekg** [comment]
There is moderately strong support for three alleles here. Note that the
quality is 0. This means the call isn't to be trusted. Look at the locus in
an alignment viewer and this should be clear.

**Comment by tseemann** [comment]
@gaosong0329 inspect it with
```
samtools tview -p 12:22063251 <my_input_bam> human_g1k_v37_decoy.fasta
```
