### ISSUE TITLE
Runtime of version 1.2.0 in multi-sample mode

### ISSUE THREAD

**Issue by marc-sturm** [freebayes/freebayes#497]
Hi Eric,

we just updated from version 1.1.0 to version 1.2.0 and noticed that the runtime in multi-sample mode increased dramatically (40min to 120min for 3 samples), while the runtime in single-sample mode stayed the same.

Is this known and intended this way, or is this a bug?

These are the parameters I used:
.../freebayes-1.2.0/bin/freebayes -b [BAMs] -f .../GRCh37.fa -t .../target.bed --min-alternate-fraction 0.1 --min-mapping-quality 20 --min-base-quality 10 --min-alternate-qsum 90

Best,
  Marc

**Comment by tseemann** [comment]
My guess is the new default  `--min-repeat-entropy 1.0`

It improves calls in low complexity regions, but if too high it will keep extending the haplotype window forever.

Try setting it to 0.5 and see what happens.

**Comment by marc-sturm** [comment]
Hi, I already tested with `--min-repeat-entropy 0.0` and the runtime stayed the same.

**Comment by tseemann** [comment]
Hmmm. I'm out of ideas then.

**Comment by ekg** [comment]
Other default settings changed. We now require only 0.05 (5%) of the reads
in one sample to consider an alternate allele. This really helps
sensitivity. In my experience the increased runtime is less important than
the increase in sensitivity. But you may have different constraints, and
you can use -F to adjust this parameter. The repeat extension thing doesn't
seem to be causing much change in runtime.

**Comment by marc-sturm** [comment]
I used `--min-alternate-fraction 0.1 ` both before and after the the update, so that cannot be the reason for the runtime change.

**Comment by marc-sturm** [comment]
I just benchmarked the singe-sample case again with more data and it also shows a massive runtime increase:
For an exome dataset version 1.1.0 took 2h 45m and version 1.2.0 took 7h 15m.

Here the commands I used:

v1.1.0:
	/mnt/share/opt/freebayes-1.1.0/bin/freebayes -b /mnt/projects/diagnostic/Exome_Diagnostik/Sample_DX184664_01//DX184664_01.bam -f /tmp/local_ngs_data//GRCh37.fa -t /mnt/share/data/enrichment/ssHAEv6_2017_01_05.bed --min-alternate-fraction 0.15 --min-mapping-quality 1 --min-base-quality 10 --min-alternate-qsum 90 > 1.vcf 2> 1.log

v1.2.0:
	/mnt/share/opt/freebayes-1.2.0/bin/freebayes -b /mnt/projects/diagnostic/Exome_Diagnostik/Sample_DX184664_01//DX184664_01.bam -f /tmp/local_ngs_data//GRCh37.fa -t /mnt/share/data/enrichment/ssHAEv6_2017_01_05.bed --min-alternate-fraction 0.15 --min-mapping-quality 1 --min-base-quality 10 --min-alternate-qsum 90 > 2.vcf 2> 2.log  

Can you replicate the problem like that?

Best,
  Marc

**Comment by ekg** [comment]
Which one of the versions provides more accurate results for you?
Correctness is more important than speed.

**Comment by marc-sturm** [comment]
Hi Eric,

the results are 95% identical, but version 1.2.0 seems to be much better at genotyping difficult indels.
However three times the runtime is a lot since there is no built-in parallelization.

I was just wondering if this is a bug or indended this way.
The changelog only mentions that parameters changed and when I turn the parameters back the runtime stays the same. So it looked like a bug to me.

Best,
  Marc

**Comment by ekg** [comment]
This seems to be an unfortunate side effect of improving genotyping
accuracy and sensitivity.

I hear you. Freebayes should be natively parallel. This is a simple enough
project but would take care to do correctly. In most pipelines people apply
their own parallelization to freebayes over target regions. This works both
locally and on a cluster, and because of this I never was motivated to
fully solve this and implement native parallelism.
