### ISSUE TITLE
Error 127, cmake installed

### ISSUE THREAD

**Issue by GBeattie** [freebayes/freebayes#499]
Hey!

Getting this message after make command:

To build freebayes you must use git to also download its submodules.
Do so by downloading freebayes again using this command (note --recursive flag):
    git clone --recursive git://github.com/ekg/freebayes.git
make: error: Command not found
make: *** [vcflib/Makefile] Error 127

Command used to download freebayes:

git clone --recursive git://github.com/ekg/freebayes.git  

After seeing that others have resolved this by installing cmake, I checked cmake was installed, which it was, then re-installed it. Still no luck!

Any ideas?

All the best,

Gordon

**Comment by tseemann** [comment]
Install via Bioconda or Homebrew ?

**Comment by GBeattie** [comment]
Bioconda seems to have circumvented the issue, thanks!
