### ISSUE TITLE
Freebayes output does not match given input

### ISSUE THREAD

**Issue by fpbarthel** [freebayes/freebayes#504]
I am using `freebayes` to query a given list of variants (provided using `-@` and with `-l` switched on as well). Both the input VCF and the freebayes output VCF were processed using `bcftools norm` and `vt` to left-align, remove multi-allelics, convert MNPs to SNPs and remove any duplicate variant.

I am now running into the issue that a very small number of events output by freebayes are not exactly the same variants provided at input. Here is just a few of them. Any thoughts on what this could be? For all example, the top given is the freebayes output and the bottom is the input variant provided with `-@`.

Insertion event that seems to have shifted by one nucleotide? Even though the reference at g.27 and g.28 is both a T, these seem like different events?

```
< 1 535327 . T TTTG (freebayes output)
---
> 1 535328 . T TTG (freebayes -@ input)
```

Insertion showing a similar problem. These slightly shifted insertions seem to be somewhat common.

```
< 1 1180290 . C CTT
---
> 1 1180290 . C CT
```

Even more common are deletions that became an insertion?

```
< 1 1200961 . G GT
---
> 1 1200961 . GTGTGTGTGTGTTTTCTCTCCAT G
```

Another deletion that became an insertion?

```
< 1 1585304 . A AC
---
> 1 1585305 . CACACACACACAA C
```

Same but smaller

```
< 1 18232726 . T TG
---
> 1 18232726 . TG T
```

**Comment by fpbarthel** [comment]
Also, freebayes doesn't always call a variant even if it is supplied in the input VCF. Initially I suspected this was just a coverage issue, and perhaps freebayes doesn't report if there is zero coverage.  But then I noticed that some variants never appear in the output file, regardless of coverage. For example this variant:

```
"2 "	"209113113"	"209113113"	"G"	"C"
```

Never appeared in output in several dozen files, even if given in input and is sufficiently covered across all samples. Look like a freebayes issue?

**Comment by tseemann** [comment]
something like `bedtools merge -s -d 0` ?

**Comment by ekg** [comment]
Would you please share a test case that reproduces this?

**Comment by fpbarthel** [comment]
Thanks for looking into this. I wrote a test case using b37-aligned `NA12878` BAM files provided by BI (chr 6 only). See also the description [here](https://gatkforums.broadinstitute.org/gatk/discussion/1292/which-datasets-should-i-use-for-reviewing-or-benchmarking-purposes) and the BAM file and index can be found here: `ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/working/20120117_ceu_trio_b37_decoy`. Look for the file called: `CEUTrio.HiSeq.WGS.jaffe.b37_decoy.NA12878.chr6.clean.dedup.recal.20120117.bam` and associated index.

I used the following `input.vcf.gz` file (compressed using `bgzip input.vcf` and indexed using `tabix input.vcf.gz`):

```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=6,length=171115067>
#CHROM	POS	ID	 REF	ALT	QUAL	FILTER	INFO
6	6053838	.	G	T	.	PASS	.
6	6053839	.	A	T	.	PASS	.
6	6089128	.	AG	 A	.	PASS	.
6	6089129	.	GAC	G	.	PASS	.
6	6272040	.	G	A	.	PASS	.
6	6272041	.	CA	C	.	PASS	.
6	7376695	.	GC	G	.	PASS	.
6	7376696	.	C	T	.	PASS	.
6	21676793	.	T	TA	.	PASS	.
6	21676794	.	AG	A	.	PASS	.
6	22443608	.	A	ATT	.	PASS	.
6	22443609	.	A	T	.	PASS	.
6	24077761	.	A	AC	.	PASS	.
6	24077762	.	A	ACACACACACAC	.	PASS	.
6	25239714	.	GC	G	.	PASS	.
6	25239715	.	C	CA	.	PASS	.
6	157517161	.	T	C	.	PASS	.
6	157517162	.	T	TCC	.	PASS	.
```

I designed this file to contain sequential variants of all possible variant combinations (SNP|SNP,SNP|DEL,SNP|INS, etc).

Also, I used the following `targets.bed` file (created using `bcftools view input.vcf.gz | vcf2bed | bedtools merge`):

```
6	6053837	6053839
6	6089127	6089129
6	6272039	6272041
6	7376694	7376696
6	21676792	21676794
6	22443607	22443609
6	24077760	24077762
6	25239713	25239715
6	157517160	157517162
```

Then I run freebayes using as follows:
```
freebayes -f human_g1k_v37_decoy.fasta -t targets.bed -l -@ input.vcf.gz CEUTrio.HiSeq.WGS.jaffe.b37_decoy.NA12878.chr6.clean.dedup.recal.20120117.bam > output.vcf
```

The output VCF looks like this:

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NA12878
6       6053838 .       G       T       2.83695e-15     .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=0;CIGAR=1X;DP=155;DPB=155;DPRA=0;EPP=0;EPPR=3.69677;GTI=0;LEN=1;MEANALT=0;MQM=0;MQMR=55.4581;NS=1;NUMALT=1;ODDS=219.481;PAIRED=0;PAIREDR=0.838
6       6089128 .       A               2.81812e-15     .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=0;CIGAR=1X;DP=103;DPB=103;DPRA=0;EPP=0;EPPR=4.04333;GTI=0;LEN=1;MEANALT=0;MQM=0;MQMR=39.1359;NS=1;NUMALT=1;ODDS=147.393;PAIRED=0;PAIREDR=0.922
6       6089129 .       G       A       1.04873e-14     .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=0;CIGAR=1X;DP=102;DPB=102;DPRA=0;EPP=0;EPPR=3.38795;GTI=0;LEN=1;MEANALT=0;MQM=0;MQMR=38.8696;NS=1;NUMALT=1;ODDS=132.144;PAIRED=0;PAIREDR=0.945
6       6272040 .       G       A       1.75185e-15     .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=0;CIGAR=1X;DP=114;DPB=114;DPRA=0;EPP=0;EPPR=3.08649;GTI=0;LEN=1;MEANALT=0;MQM=0;MQMR=55.8947;NS=1;NUMALT=1;ODDS=162.643;PAIRED=0;PAIREDR=0.833
6       7376695 .       GCT     GT      1.02462e-14     .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=0;CIGAR=1M1D1M;DP=104;DPB=104;DPRA=0;EPP=0;EPPR=5.56125;GTI=0;LEN=1;MEANALT=0;MQM=0;MQMR=54.932;NS=1;NUMALT=1;ODDS=147.393;PAIRED=0;PAIREDR=0.
6       21676793        .       TA      TAA     0       .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=4;CIGAR=1M1I1M;DP=118;DPB=120.5;DPRA=0;EPP=11.6962;EPPR=5.75321;GTI=0;LEN=1;MEANALT=1;MQM=46.5;MQMR=53.0702;NS=1;NUMALT=1;ODDS=131.495;PAIRED=
6       22443608        .       AA      ATTA    3.69957e-15     .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=0;CIGAR=1M2I1M;DP=153;DPB=153;DPRA=0;EPP=0;EPPR=24.5973;GTI=0;LEN=2;MEANALT=0;MQM=0;MQMR=56.3268;NS=1;NUMALT=1;ODDS=216.708;PAIRED=0;P
6       24077761        .       AA      ACA     2.77291e-15     .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=0;CIGAR=1M1I1M;DP=112;DPB=112;DPRA=0;EPP=0;EPPR=3.02986;GTI=0;LEN=1;MEANALT=0;MQM=0;MQMR=56.6306;NS=1;NUMALT=1;ODDS=158.484;PAIRED=0;P
6       25239714        .       GCC     GC      3.69557e-15     .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=0;CIGAR=1M1D1M;DP=117;DPB=117;DPRA=0;EPP=0;EPPR=12.9991;GTI=0;LEN=1;MEANALT=0;MQM=0;MQMR=55.7478;NS=1;NUMALT=1;ODDS=164.029;PAIRED=0;P
6       157517161       .       T       C       0       .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=0;CIGAR=1X;DP=145;DPB=145;DPRA=0;EPP=0;EPPR=3.74411;GTI=0;LEN=1;MEANALT=0;MQM=0;MQMR=54.1655;NS=1;NUMALT=1;ODDS=205.618;PAIRED=0;PAIREDR=0.848
```

As you can see, except for `6:6089129` (no idea why) none of the connected variants are reported in the output.

Interested to see what you can find.

If it makes things easier, here are dropbox download links for:
- [input.vcf.gz](https://www.dropbox.com/s/ynrc2sgx94iqei5/input.vcf.gz?dl=0)
- [input.vcf.gz.tbi](https://www.dropbox.com/s/0mmx9mmhonsqk46/input.vcf.gz.tbi?dl=0)
- [targets.bed](https://www.dropbox.com/s/da99z8u5qk7lisv/targets.bed?dl=0)

**Comment by fpbarthel** [comment]
Just to add, if there are three variants in sequence provided in the input VCF, eg.

```
6 | 7751425 | A | C
6 | 7751426 | A | C
6 | 7751427 | A | C
```

Only `6:7751425` returns anything

**Comment by FrankFeng** [comment]
> Also, freebayes doesn't always call a variant even if it is supplied in the input VCF. Initially I suspected this was just a coverage issue, and perhaps freebayes doesn't report if there is zero coverage. But then I noticed that some variants never appear in the output file, regardless of coverage. For example this variant:
> 
> ```
> "2 "	"209113113"	"209113113"	"G"	"C"
> ```
> Never appeared in output in several dozen files, even if given in input and is sufficiently covered across all samples. Look like a freebayes issue?
> 
> Could this be related to my targets file, which has separate entries for adjavent events? In this case my targets bed (zero-based) looks like
> 
> ```
> 2       209113111       209113112       C/T     +
> 2       209113112       209113113       G/A     +
> ```
> And inputs.vcf (`-@`):
> 
> ```
> 2       209113112       .       C       T  
> 2       209113113       .       G       A 
> ```
> Would it make a difference if I joined adjavent regions in the targets bed file?

This is a bug of Freebayes. In the input VCF file, if two variants are overlapping and at least one of them is an INDEL, then only the larger INDEL will be outputted. 

The work-around is separating the SNPs and INDELs, and further for the INDELs, grouping the non-overlapping ones. In the end, there are one VCF file for SNPs and several VCF files for non-overlapping INDELs, which are then used as input VCF separately for the -@ option of Freebayes. The last step is merging all resulting output VCF files.

**Comment by budach** [comment]
Hi, I am also running this bug.

Overlapping indels and indels fully located within larger indels are not being called. Is somebody working on this or can point me to the portion of the code that most likely needs to be changed? I can then potentially implement a fix for this.
