### ISSUE TITLE
position of variant in query read or alignment length

### ISSUE THREAD

**Issue by anwarMZ** [freebayes/freebayes#510]
Hi, 

I am trying freebayes to align my DNA reads against the E.coli genome Assembly using BWA MEM exactly as mentioned in your tutorial (which btw is very helpful, thanks !) https://github.com/ekg/alignment-and-variant-calling-tutorial 
But my main question is that i want to know the positions of a variant in the query reads that support the alternative allele or reference. I want to look from read's perspective that where does this variant happens. Can i do that using freebayes or any other alternative?

Thanks, 
Zohaib

**Comment by ekg** [comment]
Hi @anwarMZ,

What exactly do you need this for?

> But my main question is that i want to know the positions of a variant in the query reads that support the alternative allele or reference. I want to look from read's perspective that where does this variant happens. 

You already have metrics in the output that show the average placement of the read relative to the variant (whether the average position is to the left or right). You want this for every read? You may want to write your own code to do this.

**Comment by anwarMZ** [comment]
I need this to model my data to see the probability of a variant at each position in the reads.

Can you please explain this a bit more. I think you are pointing to EPP, EPPR, RPP and RPPR? 

> You already have metrics in the output that show the average placement of the read relative to the variant (whether the average position is to the left or right). You want this for every read? 

Thank you for helping with this

**Comment by ekg** [comment]
> I need this to model my data to see the probability of a variant at each position in the reads.

Yes, it could be extracted. But you need to write a patch to freebayes to do it. The output format wouldn't exactly be VCF-like.

> Can you please explain this a bit more. I think you are pointing to EPP, EPPR, RPP and RPPR?

That's right. It does sound like you're interested in something a little different.

I would write a tool that takes a VCF file and builds up the model you're describing by passing over a set of reads and checking if each one has a variant in the VCF file while recording its read-relative position. Then you wouldn't be limited to only using freebayes.

**Comment by anwarMZ** [comment]
> I would write a tool that takes a VCF file and builds up the model you're describing by passing over a set of reads and checking if each one has a variant in the VCF file while recording its read-relative position. Then you wouldn't be limited to only using freebayes.

Exactly, I was hoping that i can use the  vcf output and extract for example a position say nth where the variant is called and then possibly take the names of those reads that support the alt allele? is that possible or i have to write the code my self for this? It would be computationally expensive to check the variant for say 10m reads at the nth position even when only 5K reads support that allele.

**Comment by anwarMZ** [comment]
Sorry i missed one thing, the reason to get the names of the reads is so that i can filter reads with a certain alignment length threshold from corresponding alignment file. Since the relative position is on aligned read part (if i am not wrong) i guess i would want to take only the alignment with a say 80% length of total read length
