### ISSUE TITLE
The bamtools merge API is time- and memory-consumed for a large number of bam files

### ISSUE THREAD

**Issue by zhangrengang** [freebayes/freebayes#511]
I have ~800 samples and bam files. If I use freebayes directly, it costed ~50G memory and ~2 days to call a 1M region. However, if I use samtools to merge these bam files and then use freebayes to call the variants, totally it only costed a few hours and < 1G memory. I tested the bamtools merge command and it realy is largely time- and memory-consumed. Thus, it might be better to replace the bam merge API from bamtools to samtools.

The samtools + freebayes pipeline that I have tested:
```
samtools merge merged.bam \
-R chr1:0-1000000 \
in1.bam    .....  in800.bam
samtools index merged.bam
freebayes -f ref.fa merged.bam -r chr1:0-1000000 > chr1:0-1000000.vcf
```

**Comment by ekg** [comment]
This is very true. Unfortunately, the best solution is to rebase around another library. This will take a small hackathon to complete. For now you can merge with a better tool, like sambamba.

**Comment by ekg** [comment]
You can also merge with sambamba or similar and pipe directly into freebayes, but if you're going to iterate the analysis and you have the space, you can also use the same process to make a region-merged BAM for the sample set.
