### ISSUE TITLE
RPL filter 

### ISSUE THREAD

**Issue by xiucz** [freebayes/freebayes#513]
Hi @ekg ,
I get a variant, but it fails with RPL filter, and the igv snapshot shows below:
![d8b10a07e8fc025057c6bb46f84c1507](https://user-images.githubusercontent.com/12706146/51170343-3197f680-18e9-11e9-8942-c9f3192c62b6.jpg)

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	AG179-1
chr19	33792731	.	GGCGGGTGCGGGTGCGGGTG	GGCGGGTGCGGGTGCGGGTGCGGGTG	70.2077	.	AB=0.444444;ABP=3.25157;AC=1;AF=0.5;AN=2;AO=4;CIGAR=1M6I19M;DP=9;DPB=10.2;DPRA=0;EPP=5.18177;EPPR=3.44459;GTI=0;LEN=6;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=16.1659;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=137;QR=182;RO=5;RPL=1;RPP=5.18177;RPPR=13.8677;RPR=3;RUN=1;SAF=2;SAP=3.0103;SAR=2;SRF=3;SRP=3.44459;SRR=2;TYPE=ins;technology.ILLUMINA=1	GT:DP:AD:RO:QR:AO:QA:GL	0/1:9:5,4:5:182:4:137:-9.95872,0,-14.0258
```
I am a little confused how do you define reads places left or right of the variant?

Thank you and waiting response/suggestions from you. 
Xiucz

**Comment by ekg** [comment]
Is it failing the filter? It just has one read placed left. The meaning of
the filter is how many reads have the variant in the right or left end
(measuring from the middle). It looks ok to me.

**Comment by xiucz** [comment]
> Is it failing the filter? It just has one read placed left. The meaning of the filter is how many reads have the variant in the right or left end (measuring from the middle). It looks ok to me.
> […](#)

Sorry,  you said one read placed left, there are nine reads from top to bottom, the first and the seventh , the eighth and the ninth read  has INS variants, which one do you refers to?  The DELs are all in the middle of the reads. Do I misunderstand  something?
