### ISSUE TITLE
bug in SNP genotype calling? 0/0 instead of 0/1

### ISSUE THREAD

**Issue by rgiannico** [freebayes/freebayes#517]
Hi, 
Is there a reason why freebayes reports this SNP position as homo instead of hetero? 
It has 3406 T and 3025 C , no quality or strand-bias problems (or so it seems to me), it is reported as a variant inside the vcf  but with a 0/0 genotype instead of 0/1 ! 

```
$ freebayes --bam Sample1.bam   --fasta-reference hg19.fa   --region chr22:23802169-23802173  > Sample1.vcf
$ cat Sample1.vcf | grep -v "^#"
chr22   23802171        .       T       C       0       .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=3025;CIGAR=1X;DP=6443;DPB=6443;DPRA=0;EPP=180.324;EPPR=174.078;GTI=0;LEN=1;MEANALT=3;MQM=3.87041;MQMR=11.4818;NS=1;NUMALT=1;ODDS=4262.71;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=78052;QR=88518;RO=3406;RPL=3025;RPP=6571.71;RPPR=7321.08;RPR=0;RUN=1;SAF=1761;SAP=180.324;SAR=1264;SRF=1955;SRP=164.956;SRR=1451;TYPE=snp;technology.IONTORRENT=1   GT:DP:AD:RO:QR:AO:QA:GL 0/0:6443:3406,3025:3406:88518:3025:78052:0,-892.463,-2146.62
```

Looking at the bam in IGV I can see it's clearly hetero. 
Freebayes notices it's a variant somehow (it appears in the vcf after all) but oddly fails to call the genotype!

I can provide a small bam file to reproduce the issue if needed. 
I'm using freebayes v1.2.0

**Comment by ekg** [comment]
I don't know if this is a bug, but the results are confusing. The mapping qualities are very low for the reads supporting the alternate. They would indicate that there is a 50% chance that the reads mapping to the alternate should be mapped elsewhere. That said, mapping quality isn't being used in the algorithm by default.

You could try turning off all observation-based prior shaping: `freebayes -wVa`.

There isn't a single reference supporting read mapped to the right fo the locus. Is that expected?

**Comment by rgiannico** [comment]
Thank you for you answer, 

I tried with `freebayes -wVa` but it's still the same, 
the only changes are "ODDS=2059.58" instead of "ODDS=4262.71" and "QUAL" column 2.01545e-13 instead of 0

I'm not sure what you mean with your last sentence, it's an amplicon sequencing, and this position is ~20bp before the amplicon's edge, does it answer your question? 
This is an IGV screenshot, hope this helps
![image](https://user-images.githubusercontent.com/2571713/52577786-1b675280-2e23-11e9-81df-c5e14603df13.png)

This behaviour is quite confusing (meaning unespected) for me too, 
I also have to add it's an IonTorrent BAM file, so I also tried to run the torrent variant caller from the torrent suite and it's correctly called as hetero in it. Maybe for some reason Freebayes does not (or not yet) fully support bam files generated with IonTorrent technology?

**Comment by ekg** [comment]
That would be weird because freebayes runs inside the iontorrent machine.
But it is an older version. If you don't mind sharing this data I will take
a look. Send me an email when you can.

**Comment by ekg** [comment]
Maybe the depth is causing confusion. I'll see what I can figure out.

**Comment by ekg** [comment]
At the moment, you can work around this by providing `--legacy-gls`. I'll try to figure out exactly what's causing this problem. It could be some kind of underflow, judging by the fact that you have such high read depth here.

    freebayes -f ~/ref/hs37d5.fa --legacy-gls -r chr22:23802050-23802200 slice.bam

```txt
22      23802171        .       T       C       60590.6 .       AB=0.469502;ABP=55.064;AC=1;AF=0.5;AN=2;AO=3025;CIGAR=1X;DP=6443;DPB=6443;DPRA=0;EPP=180.324;EPPR=174.078;GTI=0;LEN=1;MEANALT=3;MQM=3.87041;MQMR=11.4818;NS=1;NUMALT=1;ODDS=13951.5;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=78052;QR=88518;RO=3406;RPL=3025;RPP=6571.71;RPPR=7321.08;RPR=0;RUN=1;SAF=1761;SAP=180.324;SAR=1264;SRF=1955;SRP=164.956;SRR=1451;TYPE=snp;technology.IONTORRENT=1 GT:DP:AD:RO:QR:AO:QA:GL 0/1:6443:3406,3025:3406:88518:3025:78052:-7017.87,0,-7959.81
```

**Comment by rgiannico** [comment]
Thank you!
using  `--legacy-gls`  actually works, do you think I could use it by default in any case scenario or could cause some other problem sometime? 
Please keep me updated if you find out exactly what's the problem anyway, I'm curious :P

**Comment by ekg** [comment]
For the moment, I'd just use it. The model can't handle contamination or
allele imbalance parameters, but if those don't matter then you should be
fine.
