### ISSUE TITLE
About free bayes info field 

### ISSUE THREAD

**Issue by guffrann** [freebayes/freebayes#523]
I have been working with somatic variant callers. I was using mutect2 but I stopped using it because of the false positives. I personally love Freebayes and thanks all the community. 
    The problem is I want to apply filters to my vcf file by a few values. Those values are QA, PQA, QR, PQR MQM, MQMR. When I observed the values I only saw some values such as 60 for all of them. 
    How can I fix this. Is it because I run freebayes with some filters that those values are not calculated ?

    Thanks in advance

**Comment by Nheyer** [comment]
could you show the command and a vcf line?
