### ISSUE TITLE
A question about genotypes

### ISSUE THREAD

**Issue by xiaoqiwang19** [freebayes/freebayes#526]
Hi,
I used two different methods to do base quality  correction for the sequenced data, and the depth information was consistent. The results of QR and QA were a little different, but the genotypes of the results detected with freebayes were different.The genotype from method 1 result  is 0/1, while the genotype from  method 2 result is 0/0. I would like to know, does the software model genotype calculation  use the allele quality ?I don't understand what makes the difference .Looking forward to  your reply. thank you!
Method 1)
chr7	116423470	.	TGG	TGGG	7.12059E-12	.	AB=0.0938694;ABP=23629.1;AC=1;AF=0.5;AN=2;AO=1548;CIGAR=1M1I2M;DP=16491;DPB=17007.7;DPRA=0;EPP=3364.45;EPPR=334.831;GTI=0;LEN=1;MEANALT=2;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=9108.11;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=57178;QR=545914;RO=14941;RPL=1548;RPP=3364.45;RPPR=32447;RPR=0;RUN=1;SAF=1548;SAP=3364.45;SAR=0;SRF=8226;SRP=334.831;SRR=6715;TYPE=ins;technology.Iontorrent=1	GT:DP:AD:RO:QR:AO:QA:GL	0/1:16491:14941,1548:14941:545914:1548:57178:-179.415,0,-44131.7
Method 2)
chr7	116423470	.	TGG	TGGG	7.39061E-12	.	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=1548;CIGAR=1M1I2M;DP=16491;DPB=17007.7;DPRA=0;EPP=3364.45;EPPR=334.831;GTI=0;LEN=1;MEANALT=2;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=9717.83;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=54224;QR=540116;RO=14941;RPL=1548;RPP=3364.45;RPPR=32447;RPR=0;RUN=1;SAF=1548;SAP=3364.45;SAR=0;SRF=8226;SRP=334.831;SRR=6715;TYPE=ins;technology.Iontorrent=1	GT:DP:AD:RO:QR:AO:QA:GL	0/0:16491:14941,1548:14941:540116:1548:54224:0,-85.3834,-43696.1

The parameters of the software I used are as follows:
freebayes -f hg19.fa -t lib.bed  -4 -F 0.01 -C 5 --min-coverage 30 --haplotype-length 20 --pooled-continuous sample.bam  --vcf  sample.vcf
version：freebayes-v1.1.0-3

**Comment by ekg** [comment]
Yes, the software uses the quality information in the Bayesian model that
is used to develop a genotype call and genotype and site quality estimates.

**Comment by xiaoqiwang19** [comment]
Ok, I see.Thank you very much for your quick reply.
