### ISSUE TITLE
ultra high depth makes freebayes run indefinitely

### ISSUE THREAD

**Issue by aurelielaugraud** [freebayes/freebayes#529]
Hello, 
we're using freebayes on sheep GBS data.  on a particular part of chr9 seems to get freebayes stuck, it runs indefinitely but doesn't write anything. a bit of research shows this part of Chr9 contains a extra subcentromeric chromatin , it leads to very high coverage ( 1000 per individual, 500000 for the population )... any idea which parameter in freebayes would allow us to make it finish ? my other option is to split chr9 in 2 parts : before and after the problem but I was hoping There would be a "proper" way to make freebayes stop thinking about that part and move on to the rest of the chromosome. thank you

**Comment by jgarbe256** [comment]
You should be able to use the max-coverage option to ignore high coverage regions:
--max-coverage N
                   Do not process sites with greater than this coverage. default: no limit

However, in my experience it didn't work. Looking at the source code it looks like that option sets a per-sample maximum coverage, and if coverage at a site is over the maximum the reads are down-sampled to the maximum. 
But based on the source code the --min-coverage option does work the way the it says it should: sites with total (across all samples) coverage less than the minimum are ignored.

**Comment by ekg** [comment]
You will want to use a coverage map of yout BAMs to build a set of target
regions that contain approximately the same number of reads and then run in
parallel over those. You can also exclude the really deep regions this way.

There are scripts and documentation floating around. But I'm not
remembering exactly where. I should probably drop them into the README and
the help text.

**Comment by jgarbe256** [comment]
This issue describes generating regions of equal reads:
https://github.com/ekg/freebayes/issues/479

**Comment by ekg** [comment]
OK! I think this would be the way to do it:

samtools depth aln.bam | python2.7 ./coverage_to_regions.py ref.fa.fai 10000 >targets.bed
awk '{ print $1":"$2"-"$3 }' targets.bed >targets.regions

Now use this region list to run. You will tend to get similar runtime for each region. If you still run into a problem, you can exclude really short regions from this computation. A collapse of some repeat in the assembly will not yield a sequence that you can reliably do variant calling on.

**Comment by sagitaninta** [comment]
Hi, I would like to know if anyone can call variants based on coverage because I've tried this command by @ekg 
`samtools depth aln.bam | python2.7 ./coverage_to_regions.py ref.fa.fai 10000 >targets.bed
`
And it does not work because the python script cannot read the stdin.
