### ISSUE TITLE
Lots of "N" in reference allele

### ISSUE THREAD

**Issue by Buuntu** [freebayes/freebayes#531]
I am getting lots of "N" in the reference allele column of the vcf when running freebayes on my own data set.  When using samtools I don't get these "N" variants on the same data.  This is kind of a unique experiment in that we are sequencing populations of bacteria with an unknown number of samples (extremely high).

After trimming raw fastq reads (with fastp), mapping (with minimap2), and sorting the bam files (with bcftools), I am running the command:
```
freebayes-parallel <(fasta_generate_regions.py reference.fasta.fai 100000) 16 \
        -f reference.fasta \
        -C 10 \
        -F 0.2 \
        --pooled-continuous \
        --ploidy=1 \
        sorted.bam > variants.vcf
```

Any idea why this might be?  I have tried changing the parameters, not running freebayes-parallel, not using --pooled-continuous, and all give me the same result.  I don't think using grep to filter out variants with "N" in them is the right decision either as these are probably real variants that are just getting marked as "N" allele for whatever reason.

**Comment by tseemann** [comment]
@Buuntu I would not use `--ploidy=1` even though you have haploid bacteria. The reason is that when you have contamination or missed mapping (due to different copy number repeats in the reference genome) you get false positive SNP calls. Best to use higher ploidy and post-filter.

**Comment by ekg** [comment]
I would use the expected ploidy and mutation prior (--theta). Based on my
experience, setting up the model this wah it leads to more easily
interpretable results and more correct calls. You can always filter out
errors or things that look polymorphic. You will see all the alleles that
get considered for the call in the output VCF. If you see cases where there
are many alleles with high coverage, that would be the time to filter.

Or you can just use the frequencies and do a kind of pangenomic variant
calling. The interpretation will change then.

Torsten, you definitely have a different perspective. What kind of ploidy
would you set? Did you write up this approach?

**Comment by ekg** [comment]
And to be clear, the Ns are in your reference. You may have non ATGC
characters in the reference. That's what I would check.

**Comment by Buuntu** [comment]
@ekg you are right, there are N's in the reference!  Is there any way to tell freebayes to ignore these instead of marking them as SNPs/Indels?  Unfortunately some of the references are de novo assemblies from short reads and hence not the most accurate.

**Comment by Buuntu** [comment]
Are the `-F 0.2` and `-C 10` arguments essentially the same as
`vcftools --max-missing 0.2 -minDP 10`? And what effect would setting vs not setting `--ploidy=1` have?  What would be the filtering I would need to do if I don't set `--ploidy==1`?

The post-filtering I am planning to do right now is just
`vcftools --minQ 20` (Qual > 20)

**Comment by ekg** [comment]
They are not the same. These limit the input to freebayes. This changes the
calculations that the algorithm does and the resulting called alleles and
assigned genotypes. The vcftools options filter the output. It is better to
provide full information the algorithm and filter afterwards.

**Comment by IanCodes** [comment]
> @ekg you are right, there are N's in the reference! Is there any way to tell freebayes to ignore these instead of marking them as SNPs/Indels? Unfortunately some of the references are de novo assemblies from short reads and hence not the most accurate.

I am interested in knowing the answer to @Buuntu 's question.  I am using the BALB/cJ reference genome and have noticed many of the variants have 'N' for REF.  Is there a way to tell Freebayes to not call variants against unknown reference sequence?

**Comment by ekg** [comment]
I don't think there is any way to force this. You could just filter these
sites out of the VCF.
