### ISSUE TITLE
Broken pipe of freebayes-parallel 

### ISSUE THREAD

**Issue by vagabond12** [freebayes/freebayes#534]
[root@whmx ~]# /home/soft/freebayes/scripts/freebayes-parallel <(/home/soft/freebayes/scripts/fasta_generate_regions.py  /home/Macaca_fascicularis_5.0.fna.fai 100000) 36  -f  /home/Macaca_fascicularis_5.0.fna   MFI111.merged.bam  >  out.vcf
/home/soft/freebayes/scripts/freebayes-parallel: line 40: ../vcflib/scripts/vcffirstheader: No such file or directory
/home/soft/freebayes/scripts/freebayes-parallel: line 38: parallel: command not found
/home/soft/freebayes/scripts/freebayes-parallel: line 40: ../vcflib/bin/vcfstreamsort: No such file or directory
/home/soft/freebayes/scripts/freebayes-parallel: line 40: vcfuniq: command not found
Traceback (most recent call last):
  File "/home/soft/freebayes/scripts/fasta_generate_regions.py", line 32, in <module>
    print chrom_name + ":" + str(region_start) + "-" + str(end)
IOError: [Errno 32] Broken pipe
[root@whmx ~]# 

why? Anyone help me?

**Comment by ekg** [comment]
You need to put the executables and scripts from vcflib in your path. This
is the first error. You don't have vcffirstheader available.
