### ISSUE TITLE
--ploidy 1 not working from v1.1 to v1.2

### ISSUE THREAD

**Issue by gf777** [freebayes/freebayes#540]
Hi,

I have realized that the current release does not seem to support ploidy 1 any longer. The software runs but the output includes also alternate alleles under diploidy assumption. Testing the same dataset on v.1.1 solved the issue.

**Comment by ekg** [comment]
Are the genotypes diploid? That's not good.

**Comment by ekg** [comment]
Do you have any more details about this?

**Comment by GiulioF1** [comment]
Hi Erik, I can share an example with you if you wish. Basically, it does seem to simply ignore it. I had run it once on a mitogenome. Reverting to the previous version did work.
