### ISSUE TITLE
Inconsistent ALT and GT fields 

### ISSUE THREAD

**Issue by gormleymp** [freebayes/freebayes#556]
I have some odd VCFs where the GTs appear to be all triallelic but these do not seem to match the REF and ALT fields.  I have VCFs only and do not have much information on how variants were called.   Is this expected behavior? 

REF = A 
ALT = G 
TUMOR GT = 0/0/1
NORMAL GT = 0/0/1 

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  TUMOR   NORMAL
1       63643   1:63643_A/G     A       G       16927.1 .       NS=2;DP=1710;DPB=1710;AC=2;AN=6;AF=0.333333;RO=1097;AO=613;PRO=0;PAO=0;QR=44389;QA=24928;PQR=0;PQA=0;SRF=599;SRR=498;SAF=357;SAR=256;SRP=23.2028;SAP=39.146;AB=0.35848;ABP=300.484;RUN=1;RPP=163.724;RPPR=209.526;RPL=200;RPR=413;EPP=60.1452;EPPR=4.24747;DPRA=0;ODDS=116.368;GTI=0;TYPE=snp;CIGAR=1X;NUMALT=1;MEANALT=1;LEN=1;MQM=56.3605;MQMR=50.3263;PAIRED=0.998369;PAIREDR=0.999088;technology.ILLUMINA=1;ANN=G|intergenic_region|MODIFIER|FAM138A-OR4F5|FAM138A.2-OR4F5|intergenic_region|FAM138A.2-OR4F5|||n.63643A>G||||||     GT:GQ:DP:AD:RO:QR:AO:QA:SRF:SRR:SAF:SAR 0/0/1:160.002:242:156,86:156:6366:86:3518:80:76:45:41   0/0/1:160.002:1468:941,527:941:38023:527:21410:519:422:312:215

**Comment by ekg** [comment]
What were you expecting to see?

**Comment by gormleymp** [comment]
Naiively, I was expecting to see multiple alleles in either the ALT or REF position for these alleles.  Rather, I suppose this data is stating that this is a triploid genome and, in this instance, both the normal and tumor sample have one copy of the alternate allele and two copies of the reference allele.   Is this the correct interpretation?   Is it standard practice to call somatic variants from the human genome with an assumption of a triploid genome in Freebayes?
