### ISSUE TITLE
Invalid GVCFs: floating point number in integer QA field

### ISSUE THREAD

**Issue by leecbaker** [freebayes/freebayes#557]
Freebayes is generating invalid VCFs by mislabeling the type of the QA field. For example, here are some excerpts from a VCF that I'm working on. This VCF was generated by `version:  v1.1.0-dirty`, which is the latest from macports.

The header describes the QA field as an integer:
`##FORMAT=<ID=QA,Number=A,Type=Integer,Description="Sum of quality of the alternate observations">`

While the field has floating point values:
`chrY    2649791 .       A       <*>     0       .       DP=10;END=2649801;MIN_DP=9      GQ:DP:MIN_DP:QR:QA      3972.86:10:9:3970:-2.86202`

This causes crashes in pysam (based on htslib):
```[E::vcf_parse_format] Invalid character '.' in 'QA' FORMAT field at chrY:2649791
Traceback (most recent call last):
  File "scripts/abc.py", line 215, in <module>
    <details omitted>
  File "pysam/libcbcf.pyx", line 3926, in pysam.libcbcf.TabixIterator.__next__
ValueError: error in vcf_parse
```

Running vcf validator points this issue out as well, on a huge percentage of the VCF file:
`column 01 at chrY:2649791 .. Could not validate the int [-1.23088]`

Can we change this field's description from `Integer` to `Float`? The relevant code appears to be here: https://github.com/ekg/freebayes/blob/b4dd47844c2e836d9ef9d1f08f577d9ad7adce0c/src/AlleleParser.cpp#L436

**Comment by ekg** [comment]
Ok, is this also happening in v1.3.1?

Please share an example that causes this.

**Comment by ekg** [comment]
I see you shared the VCF fragment.

**Comment by leecbaker** [comment]
I just noticed that PR #549 is a potential solution to this problem.

**Comment by leecbaker** [comment]
@ekg Yes, this is happening on the current master version.

Unfortunately I can't share the data that I'm calling; however, this seems to occur when calling with `--gvcf` and with high depth data.

What seems to be happening is when an integer has more than 6 digits, it's printed in scientific notation rather than as a normal integer.

Here's some more data exhibiting this:
```
chrM    504     .       T       A       0       .       AB=0;ABP=0;AC=0;AF=0;AN=1;AO=887;CIGAR=1X;DP=17658;DPB=17658;DPRA=0;EPP=1158.44;EPPR=388.208;GTI=0;LEN=1;MEANALT=3;MQM=59.8489;MQMR=59.9
284;NS=1;NUMALT=1;ODDS=108981;PAIRED=0.939121;PAIREDR=0.94522;PAO=0;PQA=0;PQR=0;PRO=0;QA=14901;QR=536448;RO=16484;RPL=787;RPP=1158.44;RPPR=95.0774;RPR=100;RUN=1;SAF=883;SAP=1894.52;SAR=4;SRF=7
681;SRP=168.846;SRR=8803;TYPE=snp;technology.NOVASEQ=1  GT:DP:AD:RO:QR:AO:QA:GL 0:17658:16484,887:16484:536448:887:14901:0,-46879
chrM    505     .       C       <*>     0       .       DP=17370;END=506;MIN_DP=17007   GQ:DP:MIN_DP:QR:RO:QA:AO        1.18374e+06:17370:17007:1.19842e+06:17000:14683:370
chrM    507     .       T       <*>     0       .       DP=17213;END=508;MIN_DP=16912   GQ:DP:MIN_DP:QR:RO:QA:AO        1.12047e+06:17213:16912:1.12768e+06:16931:7211:282
chrM    509     .       C       <*>     0       .       DP=17691;END=510;MIN_DP=17668   GQ:DP:MIN_DP:QR:RO:QA:AO        1.22722e+06:17691:17668:1.22977e+06:17626:2549:65
```

**Comment by tseemann** [comment]
In this case it is the `QR` and `GQ` fields, `1.18374e+06` and `1.19842e+06`
I assume this can be fixed by the correct `printf` style formatting for long integers?

**Comment by leecbaker** [comment]
@tseemann That sounds right to me. I took a quick look at it though, and it seems like the printing system is a bit more complicated than you might think. Conversion of an integer / float to string is done separately from actually printing that string in the VCF, and I think it's usually done in this function: https://github.com/ekg/freebayes/blob/aa2ace881f4af22d8409809f396ec7cba93f1128/src/convert.h#L15-L20

A question I had- can't that function be replaced with `std::to_string` in most cases, at least for integers?

**Comment by leecbaker** [comment]
This issue is still present- is this project still active? Seems like the pull requests have not seen any attention.

**Comment by pjotrp** [comment]
@leecbaker fill me in. What PR are you referring to?

**Comment by pjotrp** [comment]
#549 was merged 3 days ago.
