### ISSUE TITLE
Invalid GVCFs: floating point number in integer field QR

### ISSUE THREAD

**Issue by leecbaker** [freebayes/freebayes#558]
This is very similar to #557.

Lines like the following fail to parse with common tools, including vcf-validator. The reason is that there is a number in floating point format in the QR field.

`chrY	58980526	.	A	<*>	0	.	DP=1657;END=58980545;MIN_DP=1533	GQ:DP:MIN_DP:QR:QA	1.07189e+06:1657:1533:1.11571e+06:43824.5`

According to the header, an integer should be expected in this field:
`##FORMAT=<ID=QR,Number=1,Type=Integer,Description="Sum of quality of the reference observations">`

Changing this to label the field as a floating point value fixes the issue, and the VCF will validate. It looks like the fix is simply to change the header that freebayes generates here: https://github.com/ekg/freebayes/blob/b4dd47844c2e836d9ef9d1f08f577d9ad7adce0c/src/AlleleParser.cpp#L435

**Comment by leecbaker** [comment]
#549 is a potential solution to this problem.

**Comment by finswimmer** [comment]
I observe the same problem today. Any plans when the fix will be merged?

Thanks a lot!

**Comment by leecbaker** [comment]
Is this project abandoned? It seems like the original author has largely disappeared.

**Comment by pjotrp** [comment]
No, not abandoned. Though most of it is in maintenance mode for now.

**Comment by pjotrp** [comment]
A patch would be appreciated.

**Comment by leecbaker** [comment]
@pjotrp A PR is linked earlier in this thread #549. It's already been merged.
