### ISSUE TITLE
Different output with same input

### ISSUE THREAD

**Issue by marc-sturm** [freebayes/freebayes#560]
Hi Erik,

we updated from freebayes 1.2.0 to 1.3.1 and noticed changing output in out nightly tests without any changes to that data.
When I tried to create a minimal test case, I noitced that the variant calls vary when I copy the data to different folders.

Here the output of the attached example data:
[example.zip](https://github.com/ekg/freebayes/files/3500120/example.zip)

* Call on NA12878 data:
> rm -rf subdir *.vcf
> /mnt/share/opt/freebayes-1.3.1/bin/freebayes -t **roi.bed** --min-alternate-fraction 0.1 --min-mapping-quality 1 --min-base-quality 15 --min-alternate-qsum 90 -f /tmp/local_ngs_data/GRCh37.fa -b **NA12878_03.bam** -v **vc1.vcf**

* Copy the data to 'subdir' and call again:

> mkdir subdir
> **cp NA12878_03.bam NA12878_03.bam.bai roi.bed subdir/**
> /mnt/share/opt/freebayes-1.3.1/bin/freebayes -t **subdir/roi.bed** --min-alternate-fraction 0.1 --min-mapping-quality 1 --min-base-quality 15 --min-alternate-qsum 90 -f /tmp/local_ngs_data/GRCh37.fa -b **subdir/NA12878_03.bam** -v **vc2.vcf**

* now there are differences in the calls:

> diff vc1.vcf vc2.vcf
> &gt; chr11 94189450        .       C       A       4.60471e-14     .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=73;CIGAR=1X;DP=580;DPB=580;DPRA=0;EPP=161.528;EPPR=618.222;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=455.681;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=1389;QR=15889;RO=507;RPL=73;RPP=161.528;RPPR=489.424;RPR=0;RUN=1;SAF=0;SAP=161.528;SAR=73;SRF=49;SRP=719.472;SRR=458;TYPE=snp;technology.ILLUMINA=1     GT:DP:AD:RO:QR:AO:QA:GL 0/0:580:507,73:507:15889:73:1389:0,-49.4014,-1304.64
> < chr11 94189450        .       C       A       4.6288e-14      .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=73;CIGAR=1X;DP=580;DPB=580;DPRA=0;EPP=161.528;EPPR=618.222;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=455.681;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=1389;QR=15889;RO=507;RPL=73;RPP=161.528;RPPR=489.424;RPR=0;RUN=1;SAF=0;SAP=161.528;SAR=73;SRF=49;SRP=719.472;SRR=458;TYPE=snp;technology.ILLUMINA=1     GT:DP:AD:RO:QR:AO:QA:GL 0/0:580:507,73:507:15889:73:1389:0,-49.4014,-1304.64
159c159
> &gt; chr11 108119615       .       CAAAAAAAAAAAAAAGAAAAAAGTGGATT   CAAAAAAAAAAAAAGAAAAAAGTGGATT    0.166228        .       AB=0.157895;ABP=22.325;AC=1;AF=0.5;AN=2;AO=3;CIGAR=1M1D27M;DP=19;DPB=18.4828;DPRA=0;EPP=9.52472;EPPR=19.0002;GTI=0;LEN=1;MEANALT=4;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=3.24375;PAIRED=1;PAIREDR=1;PAO=1;PQA=37.5;PQR=37.5;PRO=1;QA=102;QR=414;RO=11;RPL=3;RPP=9.52472;RPPR=19.0002;RPR=0;RUN=1;SAF=0;SAP=9.52472;SAR=3;SRF=0;SRP=26.8965;SRR=11;TYPE=del;technology.ILLUMINA=1     GT:DP:AD:RO:QR:AO:QA:GL 0/1:19:11,3:11:414:3:102:-4.95384,0,-33.0304
> < chr11 108119615       .       CAAAAAAAAAAAAAAGAAAAAA  CAAAAAAAAAAAAAGAAAAAA   11.1671 .       AB=0.15625;ABP=35.8538;AC=1;AF=0.5;AN=2;AO=5;CIGAR=1M1D20M;DP=32;DPB=30.9545;DPRA=0;EPP=3.44459;EPPR=3.0103;GTI=0;LEN=1;MEANALT=5;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=2.49181;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=177;QR=737;RO=20;RPL=5;RPP=13.8677;RPPR=38.1882;RPR=0;RUN=1;SAF=2;SAP=3.44459;SAR=3;SRF=9;SRP=3.44459;SRR=11;TYPE=del;technology.ILLUMINA=1 GT:DP:AD:RO:QR:AO:QA:GL    0/1:32:20,5:20:737:5:177:-8.39804,0,-58.779

I hope you can find the bug quickly with the information I providid.

Best,
  Marc

P.S.: I also noticed a significant speedup of multi-sample calling (~70% less run time). Is that intended? It's not in the release notes, so I was wondering...

**Comment by ekg** [comment]
The speedup is intended. The change in behavior is a little strange, but
I'm not sure that it's actually a bug. It looks like the range of the
haplotype call is changed.

**Comment by marc-sturm** [comment]
It might not be a severe bug, but for us it's not really acceptable to get different results for exactly the same data. We need the results to be reproducible.

Most of the time the differences are low-quality variants, but once an additional quality 200 variant popped up in our test cases. That's not really acceptable in diagnostics...

Best,
  Marc

**Comment by ekg** [comment]
It is important that we fix errors. It will be the case that some erroneous
calls are removed through the process of improvement. That this will change
your pipelines is natural. It is good you are trying to understand the
change.

However, the issue is slightly different here. The calls that you have
shared are not semantically different. They assert the same alleles over a
different range of the reference. This is not a problem. Apply
normalization routines in vt, samtools, bcftools, vcflib, or vcf-tools to
remove the additional reference matching sequence when doing your
comparison. If you find significant differences that you can validate to be
incorrect in the new version then I will be happy to look into it.

**Comment by marc-sturm** [comment]
Hi Erik,

the extra bases are not the problem in the case of the variant at chr11:108119615.
As you say, they are taken care of by variant normalization.
We use [VcfLeftNormalize](https://github.com/imgag/ngs-bits/blob/master/doc/tools/VcfLeftNormalize.md) for normalization.

However that quality is very different as well. One time it is 0.16 and one time 11.16.
This leads to variants that randomly appear and disappear when we apply quality filters (e.g. min quality 10).

Best,
  Marc

**Comment by ekg** [comment]
Ok, I understand your concern. Would you be able to show some cases where
this is introducing an error that you validate with another method?

In this case, I am somewhat skeptical of the call because it's in a
homopolymer. On the other hand, if the reads don't have systematic indel
errors then it isn't unreasonable to see 5 alternate and 20 reference
observations.

The change in quality is because more alignments fully overlap the shorter
window, and are thus considered together.

The window size has changed because I resolved a bug in the entropy
dependent haplotype window determination.

**Comment by marc-sturm** [comment]
Hi Erik,

no, we did not validate the variants and I agree that they are mostly in in bad quality regions.

However, both calls were performed with the same version of freebayes (1.3.1), so the same results should be reported. The only difference was the location of the BAM/BED files, so the variant calls are not deterministic with version 1.3.1. We did not see this kind of behavior with version 1.2.0.

Best,
  Marc

**Comment by ekg** [comment]
Ok now I understand. Sorry to be confused.

This is incredibly strange. The file location should be irrelevant. I
didn't touch anything related to it, and I've never seen a problem like
this before.

**Comment by ekg** [comment]
I'll need this file to reproduce your tests:

tmp/local_ngs_data/GRCh37.fa

**Comment by marc-sturm** [comment]
Sorry, I was not really clear either.
I should have made my point of the last comment clearly in the initial issue :)

You can download the genome from:
https://download.imgag.de/ahsturm1/GRCh37.fa
https://download.imgag.de/ahsturm1/GRCh37.fa.fai

Here some additional info about OS, compiler, etc:
![grafik](https://user-images.githubusercontent.com/5638144/63020224-cd98d900-be9d-11e9-9271-66bef8447c5d.png)
