### ISSUE TITLE
GVCF output coordinate bug(s)

### ISSUE THREAD

**Issue by bredeson** [freebayes/freebayes#561]
Hey,
First, thank you for FreeBayes! I love how light-weight and fast it is. I am currently using v1.3.1-17-gaa2ace8 to call variants on a large vertebrate genome and I have encountered errors (also observed using v1.1.0-54-g49413aa) in the output when using `--targets` and `--gvcf` flags together:

In the following three lines, `Scaffold16:219949881-233828960` is the first interval traversed with `--targets`, but when FreeBayes begins traversing `Scaffold19.1:1-13305`, the `CHROM` field for the last non-variant GVCF block is inappropriately written as `Scaffold19.1`:
```
Scaffold16    233828404  .  GAA  GAAA  331.659  .  AB=0;ABP=0;AC=2;AF=1...
Scaffold19.1  233828407  .  .    <*>   0        .  DP=28;END=233828960;MIN_DP=4
Scaffold19.1  1          .  G    <*>   0        .  DP=4;END=410;MIN_DP=0
```

When there are no variants called (say, on small contigs with poor read coverage), the flowing lines with duplicate starting coordinates and out-of-range FORMAT sub-field values may be reported:
```
Scaffold19.36  2169  .  C    <*>   0       .  DP=26;END=2552;MIN_DP=13  GQ:DP:MIN_DP:QR:RO:QA:AO    389007:26:13:389751:26:744:0
Scaffold19.36  2553  .  ACC  ACCC  624.86  .  AB=0.916667...            GT:GQ:DP:AD:RO:QR:AO:QA:GL  0/1:0:24:2,22:2:82:22:808:-64.6346,0,-0.22393
Scaffold19.37  2556  .  .    <*>   0       .  DP=23;END=2998;MIN_DP=5   GQ:DP:MIN_DP:QR:RO:QA:AO    405084:23:5:405592:23:508:0
Scaffold19.38  1     .  T    <*>   0       .  DP=0;END=998;MIN_DP=0     GQ:DP:MIN_DP:QR:RO:QA:AO    -0:0:0:-0:0:-0:0
Scaffold19.38  1     .  T    <*>   0       .  DP=12;END=82;MIN_DP=0     GQ:DP:MIN_DP:QR:RO:QA:AO    38803:12:0:38840:12:37:0
```

My full command line was: 
```
freebayes \
  --genotype-qualities \
  --use-mapping-quality \
  --report-genotype-likelihood-max \
  --min-base-quality 20 \
  --min-mapping-quality 30 \
  --haplotype-length 2 \
  -F 0.2 --min-repeat-entropy 0 \
  --use-best-n-alleles 4 \
  --strict-vcf \
  --gvcf \
  --bam my.bam \
  --fasta-reference my.fasta \
  --targets my.bed \
>my.vcf
```

Best,
Jessen

**Comment by bredeson** [comment]
This is still an issue in v1.3.1-17-gaa2ace8, by the way.

**Comment by ekg** [comment]
Thanks for noting this. It sounds like uninitialized memory / left over
from the last block.

**Comment by bredeson** [comment]
Hi, I'd like to re-open this issue. I'm still observing this bug in the v1.3.6 release static binary.
