### ISSUE TITLE
Negative correlation between number of variants and mapped reads

### ISSUE THREAD

**Issue by mullerbsf** [freebayes/freebayes#564]
Dear Erik, 

I have whole genome sequencing pooled data from haploid organism that I used  Freebayes to detect variants using pooled continuous and diploid options.

The steps used were: 
Illumina raw data (2x150bp) --> Trimmomatic --> BWA-mem --> Picard MarkDuplicates --> GATK v.3.8.1 IndelRealigner --> FreeBayes v.1.2.0 with pooled_continuous and ploidy=2 options.

To QC the results, I plotted the number of reads vs. number of variants and I obtained an unexpected negative correlation (plots attached). The number of variants appears to reach a plateau around 20K. The two dots with low variants are control strains. The pools with lower mapped reads (low mean depth) are the ones that FreeBayes detects more variants.

Do you know what could be causing this unexpected behavior using FreeBayes?

I appreciate your help!
Barbara.
![Ploidy2](https://user-images.githubusercontent.com/43009904/63553631-0c1b3d00-c509-11e9-8272-086a1a65806f.png)
![Pooled_continuous](https://user-images.githubusercontent.com/43009904/63553632-0c1b3d00-c509-11e9-8611-40dce69f3b58.png)

**Comment by ekg** [comment]
Could it be that it's easier to map reads to regions of your reference that
are common among the samples that you are analyzing? The intuition is that
lower coverage would correlate with sequence diversity that itself
frustrates the alignment.

**Comment by mullerbsf** [comment]
Dear Erik, 

I do not believe that sequence diversity justifies these results. The samples are very close to each other and the reference (<1% divergence). I still suspect something in FreeBayes might be creating this bias, where the pool with lower depth had more polymorphic SNPs (using the pooled continuous or ploidy as 2). It looks like FreeBayes is not able to distinguish sequencing errors from a true rare variant.

I ran LoFreq and CRISP for this experiment and those variant callers designed for pooled sequencing data gave me a positive correlation between number of variants and mapped reads.

![Screen Shot 2019-10-07 at 2 28 24 PM](https://user-images.githubusercontent.com/43009904/66338440-1f466880-e90f-11e9-9f80-fd295fa65c71.png)

![Screen Shot 2019-10-07 at 2 28 39 PM](https://user-images.githubusercontent.com/43009904/66338450-23728600-e90f-11e9-99cb-8ab92352bf17.png)

Also, I extracted the variants that were common between FreeBayes and CRISP, and plotted using the FreeBayes calls. I did not observe a positive correlation, suggesting the presence of bias.

![Screen Shot 2019-10-07 at 2 28 50 PM](https://user-images.githubusercontent.com/43009904/66338486-34bb9280-e90f-11e9-9c5a-cf01202c88b4.png)

I would be interested to know if you have any suggestion to improve this behavior on Freebayes.

Thank you!
Barbara.

**Comment by tseemann** [comment]
(I just note that you used `freebayes 1.2.0` and current is `1.3.1` but not sure if that affects this particular issue)

**Comment by mullerbsf** [comment]
Dear Erik, 

Thank you for your answer.

My experiment is composed of pooled sequences from different unicellular cells of _Chlamydomonas reinhardtii_, which is haploid (n=1) organism. This project uses WGS of mutagenized algae pool population from selection experiments. Then, each library is a pool-seq from different unicellular cells that are expected to be continuous data.

I ran CRISP as a pooled discrete with poolsize=5, since my dataset has low depth. Now, I am planning to run FreeBayes using CRISP positions as target regions. 

Do you recommend me to use **--pooled-discrete** together with **--pooled-continuous**?
I did not find this recommendation in your tutorial, that FreeBayes needs both options to be a true pooled called. I am confused about that. In my interpretation, it needs to be one or another option.

I was planning to rerun FreeBayes with the following parameters. Can you check and recommend the best way to run it?

freebayes \
          --fasta-reference         ${FASTAREF} \
          --bam-list                ${LIST_OF_BAMS} \
          **--target**s                 ${TARGETS} \
          **--variant-input**			${VCF} \
          **--only-use-input-alleles** \
          **--use-best-n-alleles 4** \
          **--pooled-continuous \ # or --pooled-discrete \**
          --max-complex-gap         1 \
          --theta                   0.01 \
          --min-alternate-fraction  0.2 \
          --min-alternate-count     2 \
          --min-coverage            5 \
          --min-mapping-quality     1 \
          --min-base-quality        10 \
          --report-genotype-likelihood-max \
          > ${VCFPATH}/${FILE_CODE}_snps_and_indels_pt${SLURM_ARRAY_TASK_ID}.vcf 

Dear Torsten Seemann, I don't believe it is a version issue. I will try to run in the freebayes/1.3.1 version at this time. Thanks! 

I appreciate your attention.
Best regards,

Barbara.

**Comment by ekg** [comment]
I would suggest using both --pooled-discreet and --pooled-continuous.

They are probably misnamed, but it's hard to fix that now that there are
lots of documents referencing them.

--pooled-discrete enables pooled calling with the number of copies in the
pool defined by --ploidy.

--pooled-continuous only changes the alleles that are reported. All alleles
that pass the input thresholds are reported. Genotypes that are called
would reflect the genotyping model based on --ploidy, --cnv-map, and
--pooled-discrete

**Comment by tseemann** [comment]
@mullerbsf did you forget to increase `--ploidy 100` as @ekg suggested?
