### ISSUE TITLE
freebayes-parallel tmpdir parameter

### ISSUE THREAD

**Issue by daynefiler** [freebayes/freebayes#565]
Hi,

It would be really helpful to add a tempdir parameter to the freebayes-parallel script (to be passed to parallel). This would make using the script easier and no longer require users to change their system environment variables. (related to #454)

**Comment by tseemann** [comment]
`parallel` should honour the standard Unix `$TMPDIR` variable?
If you want to change it, then just run this?
```
TMPDIR=/scratch/daynefiler freebayes-parallel ....
```
