### ISSUE TITLE
question about --skip-coverage option

### ISSUE THREAD

**Issue by freemao** [freebayes/freebayes#566]
Dear Erik,

Thanks for adding the -g option to the new version. I am wondering the coverage cutoff specified by this option is for the total read depth by adding all the samples or just for each of them? For example, if I am calling variants using 500 samples and the average coverage is 1 for each of them, which kind of value I should specify for the -g option?

Thanks, 
Chenyong

**Comment by SichongP** [comment]
In case anyone is wondering, according to [this thread](https://github.com/ekg/freebayes/issues/582#issuecomment-573430835) it appears to be total coverage among all samples.
