### ISSUE TITLE
Github release tarball/zip missing submodules 

### ISSUE THREAD

**Issue by colinsauze** [freebayes/freebayes#568]
The github source code releases  from https://github.com/ekg/freebayes/releases are missing the submodules and aren't buildable. There's no .git inside the release file either, so doing a submodule update doesn't work. I've tested this on both v1.3.1 and v1.3.0. 

Steps to recreate/error output:

$ wget https://github.com/ekg/freebayes/archive/v1.3.0.zip
$ unzip v1.3.0.zip
$ cd freebayes-1.3.0
$ make
To build freebayes you must use git to also download its submodules.
Do so by downloading freebayes again using this command (note --recursive flag):
    git clone --recursive git://github.com/ekg/freebayes.git
make: error: Command not found
make: *** [vcflib/Makefile] Error 127

**Comment by tseemann** [comment]
Annoyingly github does not provide a way to make release tarballs that include submodules.
Conda and brew both use `git clone --recursive` with a the correct release tag.
