### ISSUE TITLE
Please port to Python3

### ISSUE THREAD

**Issue by tillea** [freebayes/freebayes#569]
Hello,
the Debian Med team is maintaining freebayes for official Debian. The recently released Debian 10 was the last Debian release featuring Python2 since this programming language is EOL. If you are interested that we continue to maintain freebayes in official Debian (and that users of other modern distributions will have no problems to install freebayes on their systems) I'd recommend you port your code to Python3. The 2to3 tool might be of great help here. I have seen some commits about Python3 compatibility.  It would be great if you could tag a new release if the conversion might be finished.
Kind regards, Andreas.

**Comment by ekg** [comment]
Hi Andreas,

Thanks for you work on supporting freebayes in Debian. I thought that we
have a patch in that does port freebayes (it's supporting scripts at least)
to python3. I should check that this is completed. It should be easy enough
to use 2to3 if there is anything left to clean up. I can tag a new release
then.

**Comment by tseemann** [comment]
WE fixed it in `vcflib` but I don't have access to `freebayes`.


CURRENT
```
==> /home/linuxbrew/.linuxbrew/Cellar/freebayes/1.3.1/bin/fasta_generate_regions.py <==
==> /home/linuxbrew/.linuxbrew/Cellar/freebayes/1.3.1/bin/coverage_to_regions.py <==
#!/usr/bin/env python
```

needs to be changed to:

```
#!/usr/bin/env python3
```
AND the code moved to py3

**Comment by tseemann** [comment]
UPDATE: https://github.com/ekg/freebayes/compare/v1.3.1...master
It has already been done.
You need to make a new release @ekg !

**Comment by ekg** [comment]
I'll do this today.

**Comment by tseemann** [comment]
Ping @ekg

**Comment by tillea** [comment]
On Sat, Sep 14, 2019 at 11:04:51PM -0700, Torsten Seemann wrote:
> Ping @ekg 
Ping again. ;-)

**Comment by tillea** [comment]
Is there any problem to simply tag a release if the code is fixed in principle?  1.1.2020 is really comming soon and we are keen on cleaning up Python2 bugs right now.

**Comment by ekg** [comment]
I have tagged a new release, v1.3.2.

Thank you for your support and patience!

**Comment by tillea** [comment]
@ekg Thanks for tagging.
I've downloaded the new version and spottet some remaining things 2to3 liked to fix.  Here is the [patch](https://salsa.debian.org/med-team/freebayes/blob/master/debian/patches/2to3.patch) for your comfort and critical inspection.
Unfortunately I had build issues which I will report in a separate issue since its not related to the Python3 migration.
Kind regards, Andreas.

**Comment by tillea** [comment]
> @ekg Thanks for tagging.
> I've downloaded the new version and spottet some remaining things 2to3 liked to fix. Here is the [patch](https://salsa.debian.org/med-team/freebayes/blob/master/debian/patches/2to3.patch) for your comfort and critical inspection.
> Unfortunately I had build issues which I will report in a separate issue since its not related to the Python3 migration.
> Kind regards, Andreas.

Is there anything more I can do than linking to the patch that is used in Debian?

**Comment by pjotrp** [comment]
Thanks @tillea, it will go in.
