### ISSUE TITLE
allele lost during re-genotyping?

### ISSUE THREAD

**Issue by tomSimonet** [freebayes/freebayes#570]
Hi,

I may have encountered some pb during a re-genotyping process, failing to get the original input alleles;
sorry by advance if this is not relevant;

In a somatic calling diagnosis context, I'm combining variants from all the samples of the run, then re-genotyping these samples individually for the pool of variants, in order to get allelic frequencies in each sample, and discard alleles considered as noise based on this inter-indiviual comparison (I'm not performing a joint calling due to the very high depth of our sequencing, which makes freebayes very slow and often exceeding our memory capacity).
the pb is I'm confused about the variants I get after the re-genotyping step, which seems to be incorrect.

To simplify, here I call and re-genotype the same sample:
Calling:
```
./freebayes-v1.3.1 -f hg19.fa -q 10 -m 20 --use-duplicate-reads -b S1_sort.bam -r chr1:117057400-117057500 -F 0.01 -C 3 > S1.vcf
cat S1.vcf | grep -P '^chr1\t1170574[456].\t' | cut -f1-2,4-5

chr1	117057448	CAAAAAAAAATCATAT	CAAAAAAAATCATAT,CAAAAAAAAAATCATAT,CAAAAAAAAATAATAT
```
Re-genotyping:
```
./freebayes-v1.3.1 -f hg19.fa --variant-input S1.vcf.gz --only-use-input-alleles -q 10 -m 20 --use-duplicate-reads -b S1_sort.bam -r chr1:117057400-117057500 > S1_reGen.vcf
cat S1_reGen.vcf | grep -P '^chr1\t1170574[456].\t' | cut -f1-2,4-5

chr1    117057448       .       CAA     CA,CAA
chr1    117057459       .       C       A
```

-> one allele is the ref, and the CA->CAA is missing

If I normalize before re-genotyping, it is becoming even more confusing to me:

```
./vt normalize -r hg19.fa S1.vcf.gz > S1_norm.vcf
cat S1_norm.vcf| grep -P '^chr1\t1170574[456].\t' | cut -f1,2-4,5

chr1  117057457       .       ATC     TC,AATC,ATA
```

```
./freebayes-v1.3.1 -f hg19.fa --variant-input S1_norm.vcf.gz --only-use-input-alleles -q 10 -m 20 --use-duplicate-reads -b S1_sort.bam -r chr1:117057400-117057500 > S1_norm_reGen.vcf
cat S1_norm_reGen.vcf | grep -P '^chr1\t1170574[456].\t' | cut -f1-2,4-5

chr1    117057457       .       ATC     AC,AAT,T
```

So is it just something expected?
Am I doing wrong and is it something I can change by modifying the parameters?
many thanks !
thomas

**Comment by ekg** [comment]
It does look like something strange is going on, but without seeing the
alignments it's a little hard to know what's causing it. Would you be able
to share them for this one locus, ideally publicly?

This re-calling mode has difficulty in regions of low complexity. I think
it may be necessary to turn off some haplotype-calling related features.
Try running the re-genotyping with --haplotype-basis-alleles rather than
--variant-input. Also, when using --variant-input, try running with
--haplotype-length 0. These are the first things I'd try.

Getting this perfectly correct will require a major update to freebayes, so
that it uses a graph model internally for genotyping, realigning the reads
to that. It's a long game to get this in place, and I'm trying to organize
a project to do so now.

**Comment by tomSimonet** [comment]
thanks for replying so quickly!!

attached file is a sam centered on the locus that reproduces the result. [19SC07130_S32_min.sam.gz](https://github.com/ekg/freebayes/files/3657897/19SC07130_S32_min.sam.gz)


I tested with the --haplotype-basis-alleles mode with --haplotype-length 0, but only 1 allele is retained:

```
./freebayes-v1.3.1 -f hg19_min.fa --haplotype-basis-alleles S1_raw.vcf.gz --haplotype-length 0 -q 10 -m 20 --use-duplicate-reads -b S1_min.bam -r chr1:117057400-117057500 > S1_reHapl.vcf

chr1	117057448	CAAAAAAAAATCA	CAAAAAAAATCA
```


I also tested another normalization, with your vcflib tool, which seems to output a more understandable set of alleles than vt:
```
cat S1_raw.vcf | ./vcflib/bin/vcfallelicprimitives -kg | grep -P '^chr1\t1170574[456].\t' | cut -f1,2-4,5

chr1	117057448	CA	CAA,C
chr1	117057459	C	A
```

but again the re-genotyping gives me the same result:
```
./freebayes-v1.3.1 -f hg19_min.fa --variant-input S1_vcflibNorm.vcf.gz --only-use-input-alleles -q 10 -m 20 --use-duplicate-reads -b S1_min.bam -r chr1:117057400-117057500 > S1_vcflibNorm_reGen.vcf

chr1	117057448	CAA	CA,CAA
chr1	117057459	C	A
```

I then try to decompose multiallelic variants:
```
./vcflib/bin/vcfbreakmulti S1_vcflibNorm.vcf > S1_vcflibNorm-decomp.vcf

chr1117057448	CA	CAA
chr1117057448	CA	C
chr1117057459	C	A
```

and again same re-genotyping result:
```
./freebayes-v1.3.1 -f hg19_min.fa --variant-input S1_vcflibNorm-decomp.vcf.gz --only-use-input-alleles -q 10 -m 20 --use-duplicate-reads -b S1_min.bam -r chr1:117057400-117057500 > S1_vcflibNorm-decomp_reGen.vcf

chr1	117057448	CAA	CA,CAA
chr1	117057459	C	A
```

so finally I split multiallelic sites in different vcfs, and re-genotype separately on each, and this time I could get my alleles :
```
cat S1_vcflibNorm-decomp_1.vcf | grep -P '^chr1\t1170574[456].\t' | cut -f1,2-4,5

chr1	117057448	CA	C
chr1	117057459	C	A

./freebayes-v1.3.1 -f hg19_min.fa --variant-input S1_vcflibNorm-decomp_1.vcf.gz --only-use-input-alleles -q 10 -m 20 --use-duplicate-reads -b S1_min.bam -r chr1:117057400-117057500 > S1_vcflibNorm-decomp-1_reGen.vcf

chr1	117057448	CAA	CA
chr1	117057459	C	A
```

```
cat S1_vcflibNorm-decomp_2.vcf | grep -P '^chr1\t1170574[456].\t' | cut -f1,2-4,5

chr1	117057448	CA	CAA

./freebayes-v1.3.1 -f hg19_min.fa --variant-input S1_vcflibNorm-decomp_2.vcf.gz --only-use-input-alleles -q 10 -m 20 --use-duplicate-reads -b S1_min.bam -r chr1:117057400-117057500 > S1_vcflibNorm-decomp-2_reGen.vcf

chr1	117057448	CA	CAA
```

don't know if it can help...

**Comment by ekg** [comment]
I'm a little confused. It looks like the case where you used vcflib
normalization produces the same set of alleles. The representation changes
in freebayes, where it is adding an extra base to the calls. This is normal
though, because it always calls over the two bases flanking an indel. Does
that make sense?

**Comment by tomSimonet** [comment]
well may be I was not clear with all these tests ;
when I regenotyped normalized alleles, without having splitting them, I got
chr1	117057448	CAA	CA,CAA
with an alt that is the ref; whereas I expected
chr1	117057448	CAA	CA,CAAA
or
chr1	117057448	CA	C,CAA;
then  if the multiallelic site was splitted in 2 distinct vcfs, used separately to recall the genotype, I could get the expected ones, in 2  final regenotyped vcfs:
vcf1 : chr1	117057448	CAA	CA
vcf2 : chr1	117057448	CA	CAA

It may sound stupid, because here I'm trying to get the genotypes for the same alleles as in the original vcf, which is pointless; but it's only for simplicity, in the real process, I'm also trying to get genotypes for alleles found in other patients.
