### ISSUE TITLE
Dyld broken pipe

### ISSUE THREAD

**Issue by feardley** [freebayes/freebayes#573]
Hi,
I am using freebayes as part of snippy and am getting a piping error due to dyld (see log file below). I installed freebayes using brew and have also tried uninstalling and reinstalling manually (not with brew) but get the same error. When installing with brew I receive the warning  
'brewsci/bio/freebayes dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.' I think this might be related?

Cheers

[freebayes.log](https://github.com/ekg/freebayes/files/3745645/freebayes.log)

**Comment by feardley** [comment]
Realised that I attached the wrong .log file, have now updated it.

**Comment by tseemann** [comment]
@feardley please run this:
```
brew update
brew upgrade
brew doctor      # this will tell you broken things
```

Then once you fix that:
```
brew reinstall freebayes
```
