### ISSUE TITLE
Segfault when using -@ option

### ISSUE THREAD

**Issue by cursorially** [freebayes/freebayes#575]
Hello hello,

I'm consistently getting a segfault when I try to run freebayes with a set of input alleles. 

`freebayes -f test.fa -@ test.inputs.vcf.gz test.aln.bam > test.out.vcf`

Just using the `.fa` and `.bam` inputs on their own works fine.

`freebayes -f test.fa test.aln.bam > test.out.vcf`

Above code produces the desired output, except that I do need to use the input alleles for this project. I can't seem to find any documentation on this specific issue.

Attached is files for a test case ([test.case.gz](https://github.com/ekg/freebayes/files/3770560/test.case.gz)), as well as the output from `-d` ([segfault.debug.output.txt](https://github.com/ekg/freebayes/files/3770561/segfault.debug.output.txt)) in case it doesn't reproduce on another machine.

Ollie

**Comment by tseemann** [comment]
My guess would be that the `-@` option does not accept `.gz` input.

**Comment by cursorially** [comment]
The readme says that the `-@` option requires `.gz` input.

**Comment by tseemann** [comment]
Hmm you are right, the top of the help says:
```
    freebayes -f ref.fa -@ in.vcf.gz aln.bam >var.vcf
```
but later it only says
```
   -@ VCF
                   Use variants reported in VCF file as input to the algorithm.
                   Variants in this file will included in the output even if
                   there is not enough support in the data to pass input filters.
```

Does uncompressed VCF fail too?
Did you try ` --variant-input ` instead of `-@` ?

**Comment by ekg** [comment]
I'll check out the test case, thanks!

**Comment by tseemann** [comment]
Something seems to be wrong the `test.case.gz` file
```
% file test.case.gz
test.case.gz: gzip compressed data, extra field, original size modulo 2^32 0
```

**Comment by cursorially** [comment]
Thanks for picking up on that. Rezipped files attached.

[test.case.tar.gz](https://github.com/ekg/freebayes/files/3776470/test.case.tar.gz)

**Comment by cursorially** [comment]
Thanks for picking that up.

`--input-alleles` works but `-@` doesn't somehow. Linked is a (hopefully) fixed test case in case you still wanted to check it out @ekg 

https://www.dropbox.com/sh/i30iwvq78b7bkng/AAAxF7DMkw012l621zlSKfH7a?dl=0

**Comment by cursorially** [comment]
And now it's not working again, so I'm going to assume that the working case was a mistake on my part.

**Comment by Nheyer** [comment]
@cursorially  Your test files appear to work running on my end, just making sure, have you tryed re-indexing test.inputs.vcf.gz with bcftools ?

**Comment by cursorially** [comment]
@Nheyer just gave that a shot, same result as before

**Comment by Nheyer** [comment]
I used:
bwa index test.ref.fa
Then ran : 
freebayes -f test.ref.fa -@ test.inputs.vcf.gz test.bam

**Comment by cursorially** [comment]
Just tried that, there's no change. In any case, the version of freebayes I'm using (v1.2.0-17-ga78ffc0) uses a reference indexed by `samtools faidx` and remakes the .fai file if it doesn't exist. Can you confirm that the .vcf output you're getting is contains the positions from the input .vcf file?

**Comment by Nheyer** [comment]
I will be able to tomorrow  around 7am PST

**Comment by Nheyer** [comment]
hmm it looks like due to an update with  vcftools you do need to use tabix now,  and I do not see all 870 variants that were in the input file. But I am not seeing the segfaults
