### ISSUE TITLE
AF has only three values of 0, 0.5 and 1

### ISSUE THREAD

**Issue by wangxuedong930227** [freebayes/freebayes#576]
I use the simplest operation of freebayes, the AF in the vcf has only three values of 0, 0.5 and 1，
like this:
chr1    131265  .       A       C       0.000115218     .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=2;CIGAR=1X;D
P=8;DPB=8;DPRA=0;EPP=7.35324;EPPR=16.0391;GTI=0;LEN=1;MEANALT=1;MQM=8;MQMR=21;NS=1;NUMALT=1;ODDS=10.5374;
PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=142;QR=422;RO=6;RPL=1;RPP=3.0103;RPPR=3.0103;RPR=1;RUN=1;SA
F=1;SAP=3.0103;SAR=1;SRF=3;SRP=3.0103;SRR=3;TYPE=snp;technology.illumina=1   GT:DP:AD:RO:QR:AO:QA:GL 0/0:
8:6,2:6:422:2:142:0,-0.88824,-10.03
chr1    131552  .       G       T       0.00154399      .       AB=0.238095;ABP=15.5221;AC=1;AF=0.5;AN=2;
AO=5;CIGAR=1X;DP=21;DPB=21;DPRA=0;EPP=3.44459;EPPR=5.18177;GTI=0;LEN=1;MEANALT=1;MQM=19.4;MQMR=19.125;NS=
1;NUMALT=1;ODDS=7.94176;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=350;QR=1072;RO=16;RPL=3;RPP=3.44459
;RPPR=5.18177;RPR=2;RUN=1;SAF=0;SAP=13.8677;SAR=5;SRF=0;SRP=37.7539;SRR=16;TYPE=snp;technology.illumina=1
    GT:DP:AD:RO:QR:AO:QA:GL 0/1:21:16,5:16:1072:5:350:-2.60235,0,-21.4087

**Comment by ekg** [comment]
Do you have only one diploid sample?

If so, what would that do to the allele frequency spectrum?

**Comment by tseemann** [comment]
```
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated allele frequency in the range (0,1]">
```

**Comment by ekg** [comment]
That should be updated to indicate that 0 is expected in no-call cases.
