### ISSUE TITLE
Build issues for version 1.3.2

### ISSUE THREAD

**Issue by tillea** [freebayes/freebayes#579]
Hi,
when trying to build freebayes 1.3.2 I get:

        make -j1 "INSTALL=install --strip-program=true"
    make[1]: Entering directory '/build/freebayes-1.3.2'
    cd src && make
    make[2]: Entering directory '/build/freebayes-1.3.2/src'
    DETECTED_VERSION = v1.0.0
    CURRENT_VERSION  =
    Updating version file.
    g++ -O3 -D_FILE_OFFSET_BITS=64 -g -ggdb -O3 -D_FILE_OFFSET_BITS=64 -g -ggdb -I../ttmath  -I/usr/include/bamtools `pkg-config --cflags libvcflib` `pkg-config --cflags libseqlib` `pkg-config --cflags htslib`   `pkg-config --cflags jsoncpp` -c freebayes.cpp
    In file included from AlleleParser.h:19,
                     from freebayes.cpp:30:
    BedReader.h:41:40: error: wrong number of template arguments (1, should be 2)
       41 |     map<string, IntervalTree<BedTarget*> > intervals; // intervals by reference sequence
          |                                        ^
    In file included from BedReader.h:12,
                     from AlleleParser.h:19,
                     from freebayes.cpp:30:
    /usr/include/bamtools/../intervaltree/IntervalTree.h:40:7: note: provided for 'template<class Scalar, class Value> class IntervalTree'
       40 | class IntervalTree {
          |       ^~~~~~~~~~~~
    In file included from AlleleParser.h:19,
                     from freebayes.cpp:30:
    BedReader.h:41:42: error: template argument 2 is invalid
       41 |     map<string, IntervalTree<BedTarget*> > intervals; // intervals by reference sequence
          |                                          ^
    BedReader.h:41:42: error: template argument 4 is invalid
    BedReader.h: In member function 'void BedReader::buildIntervals()':
    BedReader.h:63:47: error: wrong number of template arguments (1, should be 2)
       63 |         map<string, vector<Interval<BedTarget*> > > intervalsBySeq;
          |                                               ^
    In file included from BedReader.h:12,
                     from AlleleParser.h:19,
                     from freebayes.cpp:30:
    /usr/include/bamtools/../intervaltree/IntervalTree.h:11:7: note: provided for 'template<class Scalar, class Value> class Interval'
       11 | class Interval {
          |       ^~~~~~~~
    In file included from AlleleParser.h:19,
                     from freebayes.cpp:30:
    BedReader.h:63:49: error: template argument 1 is invalid
       63 |         map<string, vector<Interval<BedTarget*> > > intervalsBySeq;
          |                                                 ^
    BedReader.h:63:49: error: template argument 2 is invalid
    BedReader.h:63:51: error: template argument 2 is invalid
       63 |         map<string, vector<Interval<BedTarget*> > > intervalsBySeq;
          |                                                   ^
    BedReader.h:63:51: error: template argument 4 is invalid
    BedReader.h:65:27: error: no match for 'operator[]' (operand types are 'int' and 'std::string' {aka 'std::__cxx11::basic_string<char>'})
       65 |             intervalsBySeq[t->seq].push_back(Interval<BedTarget*>(t->left, t->right, &*t));
          |                           ^
    BedReader.h:65:65: error: wrong number of template arguments (1, should be 2)
       65 |             intervalsBySeq[t->seq].push_back(Interval<BedTarget*>(t->left, t->right, &*t));
          |                                                                 ^
    In file included from BedReader.h:12,
                     from AlleleParser.h:19,
                     from freebayes.cpp:30:
    /usr/include/bamtools/../intervaltree/IntervalTree.h:11:7: note: provided for 'template<class Scalar, class Value> class Interval'
       11 | class Interval {
          |       ^~~~~~~~
    In file included from AlleleParser.h:19,
                     from freebayes.cpp:30:
    BedReader.h:67:52: error: wrong number of template arguments (1, should be 2)
       67 |         for (map<string, vector<Interval<BedTarget*> > >::iterator s = intervalsBySeq.begin(); s != intervalsBySeq.end(); ++s) {
          |                                                    ^
    In file included from BedReader.h:12,
                     from AlleleParser.h:19,
                     from freebayes.cpp:30:
    /usr/include/bamtools/../intervaltree/IntervalTree.h:11:7: note: provided for 'template<class Scalar, class Value> class Interval'
       11 | class Interval {
          |       ^~~~~~~~
    In file included from AlleleParser.h:19,
                     from freebayes.cpp:30:
    BedReader.h:67:54: error: template argument 1 is invalid
       67 |         for (map<string, vector<Interval<BedTarget*> > >::iterator s = intervalsBySeq.begin(); s != intervalsBySeq.end(); ++s) {
          |                                                      ^
    BedReader.h:67:54: error: template argument 2 is invalid
    BedReader.h:67:56: error: template argument 2 is invalid
       67 |         for (map<string, vector<Interval<BedTarget*> > >::iterator s = intervalsBySeq.begin(); s != intervalsBySeq.end(); ++s) {
          |                                                        ^
    BedReader.h:67:56: error: template argument 4 is invalid
    BedReader.h:67:67: error: expected ';' before 's'
       67 |         for (map<string, vector<Interval<BedTarget*> > >::iterator s = intervalsBySeq.begin(); s != intervalsBySeq.end(); ++s) {
          |                                                                   ^~
          |                                                                   ;
    BedReader.h:67:68: error: 's' was not declared in this scope
       67 |         for (map<string, vector<Interval<BedTarget*> > >::iterator s = intervalsBySeq.begin(); s != intervalsBySeq.end(); ++s) {
          |                                                                    ^
    BedReader.h:67:87: error: request for member 'begin' in 'intervalsBySeq', which is of non-class type 'int'
       67 |         for (map<string, vector<Interval<BedTarget*> > >::iterator s = intervalsBySeq.begin(); s != intervalsBySeq.end(); ++s) {
          |                                                                                       ^~~~~
    BedReader.h:67:116: error: request for member 'end' in 'intervalsBySeq', which is of non-class type 'int'
       67 |         for (map<string, vector<Interval<BedTarget*> > >::iterator s = intervalsBySeq.begin(); s != intervalsBySeq.end(); ++s) {
          |                                                                                                                    ^~~
    BedReader.h:67:121: error: expected ')' before ';' token
       67 |         for (map<string, vector<Interval<BedTarget*> > >::iterator s = intervalsBySeq.begin(); s != intervalsBySeq.end(); ++s) {
          |             ~                                                                                                           ^
          |                                                                                                                         )
    BedReader.h:67:125: error: 's' was not declared in this scope
       67 |         for (map<string, vector<Interval<BedTarget*> > >::iterator s = intervalsBySeq.begin(); s != intervalsBySeq.end(); ++s) {
          |                                                                                                                             ^
    In file included from /usr/include/htslib/cram/cram.h:48,
                     from /usr/include/SeqLib/BamWalker.h:15,
                     from /usr/include/SeqLib/BamReader.h:6,
                     from LeftAlign.h:99,
                     from AlleleParser.h:30,
                     from freebayes.cpp:30:
    /usr/include/htslib/cram/cram_io.h: In function 'int block_resize_exact(cram_block*, size_t)':
    /usr/include/htslib/cram/cram_io.h:511:33: error: invalid conversion from 'void*' to 'unsigned char*' [-fpermissive]
      511 |     unsigned char *tmp = realloc(b->data, len);
          |                          ~~~~~~~^~~~~~~~~~~~~~
          |                                 |
          |                                 void*
    make[2]: *** [Makefile:100: freebayes.o] Error 1

Please note: I'm using the Debian packaged versions of some popular libs in their latest version - so this might conflict with your code.  If you think this is the case here I'll try to sort this out with Debian C++ experts and let you know.
Kind regards, Andreas.

**Comment by ekg** [comment]
Thanks, Andreas! Please let me know what they say.

I was thinking about moving the whole build over to cmake. Would that be easier to deal with? I would probably use the ExternalProject interface to add in the dependencies--- would that specifically be a problem for packaging?

**Comment by tillea** [comment]
On Tue, Dec 17, 2019 at 06:35:35AM -0800, Erik Garrison wrote:
> Thanks, Andreas! Please let me know what they say.
Yes.
 
> I was thinking about moving the whole build over to cmake. Would that be easier to deal with? I would probably use the ExternalProject interface to add in the dependencies--- would that specifically be a problem for packaging?
Usually it simplifies packaging if the build system checks for system installed libraries and uses the code copies only if the system is lacking the needed requirements.
Kind regards, Andreas.

**Comment by ekg** [comment]
> Usually it simplifies packaging if the build system checks for system installed libraries and uses the code copies only if the system is lacking the needed requirements.

I'm typically pegging things to particular git commits. I know this isn't ideal, because it means that we've got to download the source from the particular target when doing the build. 

Is there a way to be sure of what commit a given system library derives from?

**Comment by mr-c** [comment]
@ekg Well, your vcflib submodule is 4 years old, so that's probably a big part of the issue :-P

Building is done disconnected from the internet. If upstream is recording git commit IDs as part of their release then maybe we could give that to you, but they don't. Maybe you could record the range of acceptable version numbers as part of your CMakefile

**Comment by tillea** [comment]
On Tue, Dec 17, 2019 at 08:20:31AM -0800, Michael R. Crusoe wrote:
> Building is done disconnected from the internet. If upstream is recording git commit IDs as part of their release then maybe we could give that to you, but they don't. Maybe you could record the range of acceptable version numbers as part of your CMakefile
Since git became popular it became a habit to just point to specific commits.  I think that's not a good idea for several reasons.  It is better to use the good old habit to do a "release" (which in Git can be done by a tag).  This flags a certain state of "release quality" for distributors.  For libraries its a good idea to use SOVERSIONs to specify ABI compatibility.  In you build system you can just check library >=version which I consider more reliable than some Git tags (with potential security issues, ABI breaks, whatever).
Hope these hints might be helpful, Andreas.

**Comment by jmarshall** [comment]
> I was thinking about moving the whole build over to cmake. Would that be easier to deal with?

It is hard to imagine anything being made easier by a move to cmake.

**Comment by jmarshall** [comment]
```
In file included from /usr/include/htslib/cram/cram.h:48,
                 from /usr/include/SeqLib/BamWalker.h:15,
                 from /usr/include/SeqLib/BamReader.h:6,
                 from LeftAlign.h:99,
                 from AlleleParser.h:30,
                 from freebayes.cpp:30:
/usr/include/htslib/cram/cram_io.h: In function 'int block_resize_exact(cram_block*, size_t)':
/usr/include/htslib/cram/cram_io.h:511:33: error: invalid conversion from 'void*' to 'unsigned char*' [-fpermissive]
```

This one is a SeqLib issue that would be fixed by walaj/SeqLib#53 / [Debian bug #946924](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946924).

**Comment by tillea** [comment]
> This one is a SeqLib issue that would be fixed by [walaj/SeqLib#53](https://github.com/walaj/SeqLib/pull/53) / [Debian bug #946924](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946924).

I confirm that this specific issue is gone when applying the suggested patch.  Unfortunately the other issues are remaining.  Any hint how to fix this?

**Comment by ekg** [comment]
The top issue looks like a mistmatch in the intervaltree library. There must be two differing versions in scope.

**Comment by tillea** [comment]
On Wed, Dec 18, 2019 at 06:22:48AM -0800, Erik Garrison wrote:
> The top issue looks like a mistmatch in the intervaltree library. There must be two differing versions in scope. 
Debian ships with the latest release of libvcflib (= version 1.0.1) which was updated by Michael Crusoe recently (Wed, 11 Dec 2019).  May be this is the reason for the new interface.  Hmmm, perhaps we should have bumped SOVERSION due to this change?  Would you mind trying to build freebayes against libvcflib 1.0.1?
Kind regards, Andreas.

**Comment by jmarshall** [comment]
It is a bit astonishing that there are two complete copies of both intervaltree and htslib in freebayes's (recursive) list of submodules, but nonetheless the two intervaltrees are substantially the same.

The problem is that the code in _freebayes/src/*_ would need to be updated to account for the interface changes due to PR ekg/intervaltree#20.

**Comment by ekg** [comment]
Yep, it's a horrible build design.

I'll take a look at a fix tomorrow.

**Comment by ekg** [comment]
I've reproduced this by updating the intervaltree module in freebayes.

**Comment by ekg** [comment]
@tillea would you please check to see if the update resolves the issue? If so, I'll cut a new point release. CC @mr-c

**Comment by tillea** [comment]
On Thu, Dec 19, 2019 at 06:13:11AM -0800, Erik Garrison wrote:
> @tillea would you please check to see if the update resolves the issue? If so, I'll cut a new point release. CC @mr-c 
I was able to build and the build time tests are working.  We should write some CI test to be really sure but that's a task for later, thought.

**Comment by mr-c** [comment]
@ekg Great, thank you! Maybe squash & merge https://github.com/ekg/freebayes/pull/580 to switch to upstream's bamtools from your fork and update seqlib to something recent?
