### ISSUE TITLE
freebayes not using provided reference for decoding of cram

### ISSUE THREAD

**Issue by SebastianHollizeck** [freebayes/freebayes#592]
Hey,

I am currently working on a fully portable pipeline and one of the streps is docker/singularity.

I built a docker container with the precompiled binary and it starts (the help can be requested through docker, but then when I run it on my data, the binary in the docker fails. 

```
MA45136:freebayes hollizecksebastian$ docker run  -v /Volumes:/Volumes shollizeck/freebayes:1.3.1  -d -b /Volumes/dawson_genomics/Projects/CASCADE/cromwell-execution/FreeBayesSomaticWorkflow/a3f17912-6be4-4b5e-a594-31e8ecf7fd06/call-callVariants/shard-0/inputs/-1080333418/CA82-13_rmd.cram -f /Volumes//dawson_genomics/Projects/CASCADE/cromwell-execution/FreeBayesSomaticWorkflow/a3f17912-6be4-4b5e-a594-31e8ecf7fd06/call-callVariants/shard-0/inputs/236811012/GCA_000001405.15_GRCh38_full_analysis_set.fna -v test.vcf  -d -r chr7
Opening output file: test.vcf ...
loading fasta reference /Volumes//dawson_genomics/Projects/CASCADE/cromwell-execution/FreeBayesSomaticWorkflow/a3f17912-6be4-4b5e-a594-31e8ecf7fd06/call-callVariants/shard-0/inputs/236811012/GCA_000001405.15_GRCh38_full_analysis_set.fna
Opening BAM format alignment input file: /Volumes/dawson_genomics/Projects/CASCADE/cromwell-execution/FreeBayesSomaticWorkflow/a3f17912-6be4-4b5e-a594-31e8ecf7fd06/call-callVariants/shard-0/inputs/-1080333418/CA82-13_rmd.cram ...
 done
Number of ref seqs: 456
will process reference sequence chr7:0..159345973
Number of target regions: 1
no sample list file given, reading sample names from bam file
found 1 samples in BAM file
loading first target
to next target
processing target  chr7 0 159345973
[E::socket_connect] Can't resolve www.ebi.ac.uk:80: System error
Failed to populate reference for id 6
Unable to fetch reference #6 9996..21882
Failure to decode slice
Could not find any mapped reads in target region chr7:0..159345973
total sites: 1
processed sites: 0
ratio: 0

```

I found the cause of this problem is that freebayes does not provide the reference when reading from cram, which makes htslib read from the UR tag of the cram (https://github.com/samtools/htslib/issues/639#issuecomment-355341716)
which in term will not work, in a container, if the path is different.

I can workaround by binding the reference the same way into the container as it was when the cram got created, but that is not a very nice way.

Could you (I would love to provide a pull request, but I am really not good at c++) maybe fix this?
freebayes already has the fasta reference, so it doesn't change any requirements.

Cheers,
Sebastian

**Comment by ekg** [comment]
The error says that you can't connect to the web. I assume this is
something that seqLib is doing to conform to the CRAM spec. Anyone have any
ideas for a workaround that's simpler than hacking up seqLib?

[E::socket_connect] Can't resolve www.ebi.ac.uk:80:

**Comment by SebastianHollizeck** [comment]
The error message is also present if it works though.
I assume it tries different access points to get the reference from and reports which ones failed.

**Comment by SebastianHollizeck** [comment]
@ekg Sorry to bother you, but I did some reading on this issue (because I really want to use freebayes for my analysis)
And it seems there are two general possibilities
either 1) freebayes does not set the reference of the cram
or 2) seqlib does not pass it to htslib underneath (https://github.com/walaj/SeqLib/pull/38 and https://github.com/walaj/SeqLib/issues/34)

Can you maybe point me into the right direction, so i can rule out 1, so i can instead open an issue with seqlib (and maybe fix this)

I can also say, that its not just the precompiled binary, because i thought maybe the latest changes to seqlib might have solved this, but my self compiled version exits with the same error.

**Comment by alxsimon** [comment]
Hi, has this issue been solved ? I am in the process of deciding if my preprocessing pipeline should output BAM or CRAM.

**Comment by SebastianHollizeck** [comment]
I did create a fix in a pull request, which fixes the issue, but it fails the test, because it crashes with a corrupted reference instead of gracefully shutting down. Sadly I am not smart enough to figure out why my changes affects that

**Comment by alxsimon** [comment]
@SebastianHollizeck Thanks for the answer. I think I will stick with bams for now then.
Unfortunately I don't have the skills or time to solve this either.

**Comment by pjotrp** [comment]
If anyone wants to work on this feel free to reopen. Personally I don't see the point of running CRAM in pipelines. CRAM is OK for storage. But if anyone wants to work on fixing CRAM issues, feel free to contribute.
