### ISSUE TITLE
How to call somatic SNVs from scRNA-seq data

### ISSUE THREAD

**Issue by ziyangliu93** [freebayes/freebayes#599]
I try to use freebayes to call somatic mutations from 10X single cell RNA-seq data. Unfortunately, I only have one tumor sample. My question is that, shall I run freebayes on the matched normal control of the same patient so that I can exclude all polymorphic sites (gremline mutations) and retain qualified somatic mutations? If so, should I run the pipeline on them separately or do joint calling?

**Comment by winni2k** [comment]
Hi! I would like to do the same thing. @ziyangliu93, what freebayes arguments did you use, and did the results look sensible?

Regarding your question on germline filtering: My (limited) reading of the tumor-normal calling literature and some hands-on work suggests that filtering out germline variants from hard calls in a normal sample is not very sensitive/effective. Tumor-normal variant callers tend to work with read evidence directly. I have found this script helpful for post-hoc filtering of germline SNVs in a VCF https://github.com/Genomon-Project/EBFilter. This script applies the statistical model of EBCall, but allows you to perform variant calling with a tool other than EBCall first.
