### ISSUE TITLE
unable to find fasta index entry

### ISSUE THREAD

**Issue by dlema82** [freebayes/freebayes#602]
Hello,

I am having an issue similar to #185 and #159 
I have a mitochondrial genome reference fasta that I used to map my reads with bwa mem | samtools view | samtools sort | adna-ldup | picard AddOrReplaceReadGroups
Then when I try to run freebayes with the command: 
freebayes -f Ppardus_mtgenome_li_etal_plateau.fa -p 1 -m 10 -q 4 --min-coverage 1 -v freebayes_variants.vcf.gz A34746_mtgenome.mapped.bam A52028_mtgenome.mapped.bam A52039_mtgenome.mapped.bam A52047_mtgenome.mapped.bam A81302_mtgenome.mapped.bam A81845_mtgenome.mapped.bam A87236_mtgenome.mapped.bam A161733_mtgenome.mapped.bam A164151_mtgenome.mapped.bam A186944_mtgenome.mapped.bam A208770_mtgenome.mapped.bam A213648_mtgenome.mapped.bam A238222_mtgenome.mapped.bam F1444_mtgenome.mapped.bam F27279_mtgenome.mapped.bam F30779_mtgenome.mapped.bam F89917_mtgenome.mapped.bam 

I get the error:
unable to find FASTA index entry for 'KP202265.1_Panthera_pardus'

It is the same reference I have used for the entirety of the pipeline. I have used both bwa index and samtools faidx to index the ref. I've tried changing the header of the reference. I've tried adjusting /path/to/ref and /path/to/bams
This same reference has worked in another set of data, and freebayes ran using it without a hitch, and I have not changed anything this time except the names of the .bam files

I can't seem to find any solutions elsewhere.

Please advise.
Regards,
Danielle

**Comment by ekg** [comment]
There is a mismatch, somehow, between your FASTA file and the BAM you are
giving to freebayes.

Can you share some lines of the BAM (in SAM) and the corresponding FASTA
sequence names?

**Comment by dlema82** [comment]
Here is the beginning of the .sam for sample A34746
`@SQ     SN:KP202265.1_Panthera_pardus   LN:24654
@PG     ID:bwa  PN:bwa  VN:0.7.17-r1198-dirty   CL:bwa mem -t 8 Ppardus_mtgenome_li_etal_plateau.fa /array/dlema/A34746_skewer-trimmed-pair1.fastq.gz /array/dlema/A34746_skewer-trimmed-pair2.fastq.gz
E00526:56:HTMVHCCXY:2:1101:6867:1889    77      *       0       0       *       *       0       0       CGCATCGATCTGTAAAGAGGTTAATATGATGGAAGGGTACTGTTAAACAATTTGTATAATTAACTGCGCTATGATTCCGCGGATGCTGGCCTCAAGCGTCACCGGGGCCTTTTCTAATCCATAGTACTGGGCTGCGCGGTCACGCAAGTC  AAAFFFAFJJJJJJJJJFJFJFAJJJJFAFFJA<AFJFJJJJJ7FFJJJJAJFFJFJJJFJFJJJJJJJJJA<FJJF7AAJ7JJJJJJJJJJFJFJJJJJJFJJJJJFJFJ-FJJJJJJFJ7JJJJJ<AFFAJFJJJFFAAFFJJJJJ<F  AS:i:0  XS:i:0 `

The corresponding fasta does not have sequence names, it is not annotated, just a nucleotide sequence of the whole mitogenome, with the header ">KP202265.1_Panthera_pardus"

I have attached it here
[Ppardus_mtgenome_li_etal_plateau.fa.zip](https://github.com/ekg/freebayes/files/4269188/Ppardus_mtgenome_li_etal_plateau.fa.zip)

Thank you.
Danielle

**Comment by tseemann** [comment]
```
0000000   >   K   P   2   0   2   2   6   5   .   1   _   P   a   n   t
0000020   h   e   r   a   _   p   a   r   d   u   s  cr  nl   C   G   A
```
i notice the .fa file has Windows/DOS line endings (cr + nl)
Try running `dos2unix` on it, and rebuilding the index?
