### ISSUE TITLE
Cannot build Freebayes

### ISSUE THREAD

**Issue by NTNguyen13** [freebayes/freebayes#603]
Hi, I have tried to install Freebayes by using

```
git clone --recursive git://github.com/ekg/freebayes.git
sudo make install
```

but I got this error 

```
cp bin/freebayes bin/bamleftalign /usr/local/bin/
cp: cannot stat 'bin/freebayes': No such file or directory
cp: cannot stat 'bin/bamleftalign': No such file or directory
Makefile:27: recipe for target 'install' failed
```

What have gone wrong in my case? I have gcc installed

I have also tried to download the tar file of 1.3.2 and 1.3.1 but still got the same problem

**Comment by ekg** [comment]
You haven't completely downloaded the repository and submodules. Maybe
there is a problem with GitHub. Check the log of the clone.

**Comment by mdtorohernando** [comment]
It is the same for me. I think something happens with the repository

**Comment by mdtorohernando** [comment]
Solution: 
git clone --recursive git://github.com/ekg/freebayes.git
cmake -H. -Bbuild && cmake --build build -- -j4

**Comment by ekg** [comment]
Excuse me, do we still have a makefile in the repo? I should probably
remove that.

**Comment by tseemann** [comment]
i don't think freebayes compiled with `-j 4` properly.

**Comment by ekg** [comment]
Use cmake. It will then compile with -j 4 properly. I'm removing the
makefile now.

**Comment by tseemann** [comment]
Please don't hard-code `-j 4` - it will break CIRCLE and TRAVIS on brew and conda etc.

**Comment by ekg** [comment]
How should parallelism be exposed?

**Comment by tseemann** [comment]
The Make jobserver accepts the global `-j` provided by the user, and recursive makes should use `$(MAKE)` so they inherit the global hobserver.  CIRCLE etc can use $MAKEFLAGS
