### ISSUE TITLE
freebayes terminates after the message "...is out of order! expected after..."

### ISSUE THREAD

**Issue by Ramya1000** [freebayes/freebayes#608]
Hello,

I have alignments in bam format from which I removed duplicates using picard MarkDuplicates tool followed by resolving overlapping paired end reads using BamUtil:clipOverlap command. Since many of my reads were overlapping, the resulting bam has reads which are heavily soft clipped. 
Now when I was joint calling the variants using freebayes-v1.3.1, the program terminated with the following error message:

> NS500422:689:HWHKYBGX5:3:22609:25455:3523 at chr17:85769 is out of order! expected after 85777

> NS500422:689:HWHKYBGX5:2:22201:26351:9847 at chr17:85777 is out of order! expected after 85781

I think this has something to do with excessive soft clipping but am unable to think of a way to fix it. Can you please help me with it.

Thank you,
Ramya
The alignments corresponding to these read ids are listed below:

> NS500422:689:HWHKYBGX5:2:22201:26351:9847	99	chr17	85628	60	150M	=	85778	152	GGAGTGAGGGACGCCTCCCTAAGGGGAGGGGGACCGAACCCCTTTTTAAGAAGGAGTCCATATATATATATTAATAAAAAAAAGTAATATATATATATATATTGGAATAGATATATTATTATACAGAAATAAGCTTAATTATAATATAAT	AAA/AEEAEEAE/EAEAEAEA66E/EEEEEEEE/EE//EEEAEE/AEEEA/A/EEE/E/EEE/EEEEEEE/EEE6EEEEEEEE//EE/EEE/EEEEEEE/EEE//EA/EE/<EEE/AE/EE/EAA/<EEEE////<<<//A<EEAE<AE/	MC:Z:151M	MD:Z:12C9T87T20T18	PG:Z:MarkDuplicates	RG:Z:HWHKYBGX5_L2_S125	NM:i:4	AS:i:130	XS:i:50

> NS500422:689:HWHKYBGX5:2:22201:26351:9847	147	chr17	85778	60	149S2M	=	85628	-152	GAGTGTGGGACCCCTCCCTAATTGGAGGGGGACCGAACCCCTTTTTAAGAAGGAGTCCATATATATATATTAATAAAAAAAAGTAATATATATATATATATTGGAATAGTTATATTATTATACAGAAATATGCTTAATTATAATATAATAT	6//EA/A/6/////E</<EEAA/<A/6///<E/AEEA</66/EEAA////</EEEEA/EEEE/AEEEEEEE/AEEEEEE/E</A/EEEE/EEEEEEEEEEAE6AEEEEEEEEEEEEEEEEEEEEEE/AEEEEEEEE6EEEEA6EEE//AAA	AS:i:141	MC:Z:150M	MD:Z:5A16G128	NM:i:2	PG:Z:MarkDuplicates	RG:Z:HWHKYBGX5_L2_S125	XS:i:22

>NS500422:689:HWHKYBGX5:3:22609:25455:3523	99	chr17	85619	60	151M	=	85770	156	GACCCCGAAGGAGTGAGGGACCCCTCCCTAATGGGAGGGGGACCGAACCCCTTTTTAAGAAGGAGTCCATATATATATATTAATAAAAAAAAGTAATATATATATATATATTGGAATAGTTATATTATTATACAGAAATATGCTTAATTAT AAAAAEEEEEEEEEEEEEEEAAAEEEEEEEEEAEEEEEEEEAEEAEEAEAA/EEEEEEEEEEEEEEE6EAEEEEEEEEEEEEEEEEEEEEEE<EEE/AEE<EEEEEEAE/AE//EA///<AEEEE<</E</E/E/E<E/<E//E/<//AA/	MC:Z:151M	MD:Z:151	PG:Z:MarkDuplicates	RG:Z:HWHKYBGX5_L3_S430	NM:i:0	AS:i:151	XS:i:69

> NS500422:689:HWHKYBGX5:3:22609:25455:3523	147	chr17	85770	60	146S5M	=	85619	-156	CGAAGGAGTGAGGGACCCCTCCCTAATGTGAGGGGGACCGAACCCCTTTTTAAGAATGAGTCCATATATATATATTAATAAAAAAAAGTAATATATATATATATATTGGAATAGTTATATTATTATACAGAAATATGCTTAATTATAATAT	6//////66</A/EE///AE<//E<AA6/6/6/6/E<///E///AAEEEEA/E6A//AEAE//EEEEEEEEEAEAE<EEE/EEEEEE6</AEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA	AS:i:141	MC:Z:151M	MD:Z:28G27G94	NM:i:2	PG:Z:MarkDuplicates	RG:Z:HWHKYBGX5_L3_S430	XS:i:54

**Comment by ekg** [comment]
Please try sorting your BAM file again. The soft clipping changes the read
start position and can disorder the alignments.

**Comment by Ramya1000** [comment]
Thank you Erik for the suggestion. I just re-ran freebayes after sorting the bam files (samtools -o sort.bam input.bam). However, the error remains unchanged. On Googling the error, the only page I could find a mention of it is 

> https://git-r3lab.uni.lu/R3/legacy/freebayes/commit/3e07445a9949ce0e8926bf99cafdfe38ae0f9f27 

I will try to create smaller sized bams which replicate this error to isolate the problem.

**Comment by tseemann** [comment]
@ekg i never knew that soft clipping required re-sorting. it sort of makes sense, but the coordinates are not changed, only the CIGAR string?

**Comment by tseemann** [comment]
Try phyloviz? http://www.phyloviz.net/
Or Geoburst? http://www.phyloviz.net/goeburst/

If you use `mlst --legacy --scheme campylobacter` it will give you what you need?

**Comment by Ramya1000** [comment]
I figured out few more points about the specific problem: Both the read pairs which are giving the problem map towards the terminal end of mitochondrial chromosome. Since, mt is circular in reality but treated as linear for mapping, maybe that is creating some problems. I am attaching an IGV shot which shows the read pairs (in red with black outline) in their respective bam files. I am wiped out at the moment but will investigate this more closely tomorrow and write back.

Till then,
Ramya :)

<img width="1337" alt="Screen Shot 2020-03-24 at 10 03 01 PM" src="https://user-images.githubusercontent.com/43824050/77476668-43ddc080-6e1b-11ea-873a-b87972fd0fdc.png">

**Comment by Ramya1000** [comment]
I further investigated the issue: the warning is related to the soft clipping of reads because running freebayes with bams prior to soft-clipping does not give the message. Further, re-sorting the bam file after soft clipping does not solve the problem [@tseemann: Soft-clipping does change the starting coordinates of the read along with the CIGAR string]. I manually verified that soft clipping was done accurately and is not the problem. Running freebayes with just the bams containing the reported reads does not replicate the warning. And the warning is always concerning the heavily soft-clipped reads mapping towards the terminal end of a chromosome (un-related to the chromosome being mitochondrial as suggested in an earlier post by me). For my specific case, I will ignore the warning since it leads to freebayes ignoring certain reads in a high coverage region and is not an error.

Hope someone finds this helpful in case they run across something similar :)

Have a great day!
Ramya :)

**Comment by Ramya1000** [comment]
Sorry, I forgot to mention: Freebayes does not terminate after this message. This message is a warning and not an error. I had misunderstood the situation initially and thus, the subject of this thread is incorrect - Ramya
