### ISSUE TITLE
QUAL = 0 for most SNPs in Freebayes VCF

### ISSUE THREAD

**Issue by foala** [freebayes/freebayes#611]
Hello,
I have ran Freebayes on 43 samples, and have been getting QUAL = 0 for the vast amjority of the discovered SNPs.
When I run bcftools stats, I get:

SN      0       number of SNPs: 1994548

# QUAL, Stats by quality:
# QUAL  [2]id   [3]Quality      [4]number of SNPs 
QUAL    0       0       1780263 454478  1279701 5674
QUAL    0       1       144     63      37      26
QUAL    0       2       91      37      20      28
QUAL    0       3       62      38      16      13
QUAL    0       4       43      26      15      9
QUAL    0       5       45      21      20      12
QUAL    0       6       46      19      17      12
QUAL    0       7       40      27      7       11
QUAL    0       8       29      17      10      13
QUAL    0       9       32      18      9       14
QUAL    0       10      32      19      9       10

##fileformat=VCFv4.2
##fileDate=20200331
##source=freeBayes v1.3.2-dirty

Please advise as to how to interpret that score, and how to proceed with the vast majority of SNPs?

Thank you

**Comment by tseemann** [comment]
Please provide the full command line you used to run freebayes.

**Comment by ekg** [comment]
This is normal. Freebayes is writing every site that it attempts a call in the output VCF.

In general, this reduces confusion by showing exactly what happened during the operation of the method. Although, some users do expect the tool to just provide a single answer, so for them this temporarily increases confusion. On balance, it's easier to explain that it's verbose than have it miss things.

Just remove the variants with QUAL=0. These are cases where there was enough evidence to consider the possibility of a variant, but there was definitely not enough evidence to think that the allele was found in one of the samples.

**Comment by foala** [comment]
> This is normal. Freebayes is writing every site that it attempts a call in the output VCF.
> 
> In general, this reduces confusion by showing exactly what happened during the operation of the method. Although, some users do expect the tool to just provide a single answer, so for them this temporarily increases confusion. On balance, it's easier to explain that it's verbose than have it miss things.
> 
> Just remove the variants with QUAL=0. These are cases where there was enough evidence to consider the possibility of a variant, but there was definitely not enough evidence to think that the allele was found in one of the samples.

Dear Erik,
Thank you for your detailed reply.
Now it is very clear.
Is there a way to turn that off, in order to save storage space? and If I do, would that help accelerate the variant calling process?
Currently it is relatively slow (I have a 1.2 Gbp genome, and 43 samples (30x)). I split the genome into different scaffolds, but it has taken more than 7 days now..

Thank you again and stay safe.

**Comment by ekg** [comment]
You can split the genome into more smaller pieces. If you need to filter
out these QUAL=0 calls, just pipe through a tool that does that for you.
vcffilter -f 'QUAL > 0' will. As will similar methods in bcftools and
vcf-tools.
