### ISSUE TITLE
How to get the same depth value freebayes/samtools

### ISSUE THREAD

**Issue by gbbio** [freebayes/freebayes#619]
As I understand, the depth from freebayes is post-filter. Which filter steps are applied and is it possible to apply this on a bam or pileup file so the dept from samtools is the same as freebayes?

Sometimes the difference is only about 10 reads but sometimes more then 60.

**Comment by Nheyer** [comment]
you will need the following flags 
`--use-duplicate-reads   
--pooled-continuous OR
--report-all-haplotype-alleles
`
This will make freebayes not disregard what it suspects are technical duplicates,
it will not discard a base form depth if it passes initial filter, regardless of the result of wither or not the output would be incorrect for the given expected ploidiy

This  will not throw out any reads based on the huristic that if it is not a valid SNP then  this is an error and should not go in our depth 


in the end freebayes will always be a little different from that of samtools as it dose a bit of realigning

**Comment by gbbio** [comment]
Thanks for your reply, I will check it out.

**Comment by Nheyer** [comment]
If the depth is over 1000x at a given base 60 reads or so is likely due to the local remapping, ifyou are seeing output of less then 1000 that is a bigger issue as the `--min-coverage  1000`  should be limiting the input to freebayes to sites with at least 1000x coverage.
