### ISSUE TITLE
Missing some SNPs in vcf , freebayes-parallel  with parameter --variant-input 

### ISSUE THREAD

**Issue by liwg123** [freebayes/freebayes#625]
I'm attempting run signal thread freebayes AND  multiple threads freebayes-parallel WITH parameter --variant-input VCF , in my VCF file i have 11578 SNPs. In signal thread mode freebayes output all of the 11578 SNPs AS i expected, but in multiple threads freebayes-parallel mode, the output vcf file have only 9665 SNPs of the 11578 SNPs. my commands is below.

signal thread mode:
freebayes --no-indel --no-mnps --no-complex -m 0 -q 20 -R 0 -S 0 -n 2 \
-f /dellfcsan/data/public/genome/maize/Zea_mays.AGPv3.22.fasta -L maize_12K_8sample.list  \
--variant-input /fcsan/projects/callsnp_mGPS_512/panel/maize_11578SNP_NA.vcf.gz  \
> maize_12K_8samples_freebys_VCF_SNP_n2_strin_NA_MQ0.vcf

multiple threads:
freebayes-parallel \
/dellfcsan/data/public/genome/maize/Zea_mays.AGPv3.22.100kbp.regions 36  \
--no-indel --no-mnps --no-complex -m 0 -q 20 -R 0 -S 0 -n 2 -f /dellfcsan/data/public/genome/maize/Zea_mays.AGPv3.22.fasta -L maize_12K_8sample.list \
--variant-input /fcsan/projects/callsnp_mGPS_512/panel/maize_11578SNP_NA.vcf.gz  \
> maize_12K_8samples_freebys_VCF_SNP_n2_strin_NA_MQ0_36threads.vcf

in multiple threads mode, I got the WARNING messeges as below.
WARNING(freebayes): Could not set the region of the variants input file to 1:0..100000
WARNING(freebayes): Could not set the region of the variants input file to 1:100000..200000
WARNING(freebayes): Could not set the region of the variants input file to 1:200000..300000
WARNING(freebayes): Could not set the region of the variants input file to 1:300000..400000

I exptect to get all of the 11578 SNPs in multiple threads mode as in  signal thread mode, but the output vcf file include 9665 SNPs only.

Thank you very much for explanation.
Best

**Comment by Nheyer** [comment]
this looks like a malformed .regions file, can you attach your Zea_mays.AGPv3.22.100kbp.regions  file

**Comment by liwg123** [comment]
[Zea_mays.AGPv3.22.100kbp.regions.txt](https://github.com/freebayes/freebayes/files/5685980/Zea_mays.AGPv3.22.100kbp.regions.txt)

@Nheyer  the Zea_mays.AGPv3.22.100kbp.regions file has attached，thanks.

**Comment by pjotrp** [comment]
The regions file contains over 20K small connected regions for 10K SNPs:

```
1:3000000-3100000
1:3100000-3200000
1:3200000-3300000
1:3300000-3400000
1:3400000-3500000
1:3500000-3600000
etc
```

why would you want to do that? The parallel script chunks small regions this way and you are probably missing out on SNPs that are exactly on the border of a region. Not that that should happen, but it is pushing your luck ;). 

Increase the chunk size so you get about 4x the chunks for the number of cores you want to use and see what happens.
