### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by sylee623** [freebayes/freebayes#633]
Hello, I have problem with installation.

You can see the whole logfile here --> [install_freebayes.log](https://github.com/ekg/freebayes/files/5072271/install_freebayes.log)

This part is where the error occurred.

../SeqLib/lib/libseqlib.a(libseqlib_a-ssw_cpp.o): In function `StripedSmithWaterman::Aligner::CleanReferenceSequence()':
/home/sylee/freebayes/SeqLib/src/../SeqLib/ssw_cpp.h:213: undefined reference to `operator delete(void*, unsigned long)'
collect2: error: ld returned 1 exit status
gmake[3]: *** [../bin/freebayes] Error 1
gmake[3]: Leaving directory `/lustre/export/home/sylee/freebayes/build'
gmake[2]: *** [CMakeFiles/freebayes.dir/all] Error 2
gmake[2]: Leaving directory `/lustre/export/home/sylee/freebayes/build'
gmake[1]: *** [all] Error 2
gmake[1]: Leaving directory `/lustre/export/home/sylee/freebayes/build'
make: *** [freebayes] Error 2

how can I solve this problem?

**Comment by ekg** [comment]
Looks like you might glibc?

**Comment by sylee0623** [comment]
gcc 5.4.0 and gcc 7.2.0 (first time I failed to install, so I updated to gcc7 but same error was occured)

**Comment by Nheyer** [comment]
can you run the following:
`make clean`
`cmake CMakeLists.txt 2> cmake_stderr.txt > cmake_stdout.txt`
`make 2> make_stderr.txt > make_stdout.txt` 
and then attack those 4 files ? 
@sylee623
