### ISSUE TITLE
freebayes-parallel bgzf_read error

### ISSUE THREAD

**Issue by sylvia-science** [freebayes/freebayes#634]
I'm trying to run my freebayes on my bam files in parallel, but it's throwing this error, which I haven't been able to find a solution for:

[E::bgzf_read] Read block operation failed with error -1 after 0 of 4 bytes
terminate called after throwing an instance of 'std::runtime_error'

This is the command I'm running
freebayes-parallel <(fasta_generate_regions.py /disk2/Projects/EloRD/Data/ReferenceData/refdata-cellranger-GRCh38-1.2.0.fasta.fai  100000) 12 -f /disk2/Projects/EloRD/Data/ReferenceData/refdata-cellranger-GRCh38-1.2.0.fasta GL1024BM.bam >GL1024BM.vcf

The fasta_generate_regions.py runs fine individually. Running freebayes -f /disk2/Projects/EloRD/Data/ReferenceData/refdata-cellranger-GRCh38-1.2.0.fasta GL1024BM.bam >GL1024BM.vcf also works, it just takes over a day to run.

**Comment by Nheyer** [comment]
based on some other issues that have been poping up, I think something has broken freebayes-parallel, or the fasta_generate_regions.py. I would recommend for now  just manually creating one line bed files that split up your genome into the number of threads you wish to use, then call freebayes in the background on each in a loop, then concatenate the files together using bcftools concatenate.
