### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Bioinfohelp** [freebayes/freebayes#638]
Hi,

When I try to install freebayes using git clone --recursive git://github.com/ekg/freebayes.git and the make -j4, I end up with an error. I get the error if I try to run the Makefile in bin or from vcflib. I checked the Makefile in vcflib to make sure that it matches the current Makefile for vcflib, which it does. I can't really tell what the problem is and the error prevents the program from running. This is what I get:

[ 37%] Building CXX object CMakeFiles/vcflib.dir/src/Variant.cpp.o
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp: In function ‘std::string vcflib::reverse_complement(const std::string&)’:
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp:21: error: expected primary-expression before ‘[’ token
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp:21: error: expected primary-expression before ‘]’ token
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp:21: error: expected primary-expression before ‘char’
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp:21: error: expected unqualified-id before ‘char’
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp: In function ‘std::string vcflib::toUpper(const std::string&)’:
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp:45: error: expected primary-expression before ‘[’ token
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp:45: error: expected primary-expression before ‘]’ token
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp:45: error: expected primary-expression before ‘char’
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp:45: error: expected unqualified-id before ‘char’
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp: In member function ‘bool vcflib::Variant::isSymbolicSV() const’:
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp:202: error: expected initializer before ‘:’ token
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp:3014: error: expected primary-expression at end of input
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp:3014: error: expected ‘;’ at end of input
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp:3014: error: expected primary-expression at end of input
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp:3014: error: expected ‘)’ at end of input
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp:3014: error: expected statement at end of input
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp:3014: error: expected ‘}’ at end of input
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp: At global scope:
/home/asrix/bin/freebayes/vcflib/src/Variant.cpp:3014: error: expected ‘}’ at end of input
gmake[6]: *** [CMakeFiles/vcflib.dir/src/Variant.cpp.o] Error 1
gmake[6]: Leaving directory `/import/home/asrix/bin/freebayes/build/vcflib-prefix/src/vcflib-build'
gmake[5]: *** [CMakeFiles/vcflib.dir/all] Error 2
gmake[5]: Leaving directory `/import/home/asrix/bin/freebayes/build/vcflib-prefix/src/vcflib-build'
gmake[4]: *** [all] Error 2
gmake[4]: Leaving directory `/import/home/asrix/bin/freebayes/build/vcflib-prefix/src/vcflib-build'
gmake[3]: *** [vcflib-prefix/src/vcflib-stamp/vcflib-build] Error 2
gmake[3]: Leaving directory `/import/home/asrix/bin/freebayes/build'
gmake[2]: *** [CMakeFiles/vcflib.dir/all] Error 2
gmake[2]: Leaving directory `/import/home/asrix/bin/freebayes/build'
gmake[1]: *** [all] Error 2
gmake[1]: Leaving directory `/import/home/asrix/bin/freebayes/build'
make: *** [freebayes] Error 2

Any help would be appreciated.

Thanks!

**Comment by woaishiye** [comment]
have you solved this problem?? i meet with the same problem

**Comment by pjotrp** [comment]
Use the new meson build system.
