### ISSUE TITLE
Freebayes genereted gvcf files contains errors

### ISSUE THREAD

**Issue by yganwork** [freebayes/freebayes#639]
Hi,

First I want to thank you for freebayes, it's a great tool!

I am generating gvcf files for over a 100 samples using a reference genome of about 10^9 bp.  I call variants using the folowing command line:
**freebayes --genotype-qualities --strict-vcf --ploidy 2 -f {refGenome} --gvcf --gvcf-dont-use-chunk true --vcf {variantFile} {dedupBamFile}**

Variant calling does not fail, but downstream splitting into SNP and INDEL using **gatk SelectVariant** does fail on several samples with the same error (except for the line number):
**The provided VCF file is malformed at approximately line number 973642001: empty alleles are not permitted in VCF records**

When investigating the gvcf generated by freebayes (relevant parts only shown below, escaped some stars to avoid markdown issues) I noticed that those empty alleles are part of a chunk in the next contig with coordinates of the previous contig. In the example given, I get a chunk in contig SWJQ01000002.1 for the range 8013061 - 8013090. This should be in contig SWJQ01000001.1 and it should not be as a chunk (see command line above). The same type of error happens for the next scaffolds (only 2 more shown in excerpt, many more in the gvcf).  About 20% of my samples produce a gvcf with this type of errors, all were analyzed using the same reference genome and freebayes command line. Unless I missed something, this looks like a bug?

##fileformat=VCFv4.2
##fileDate=20200820
##source=freeBayes v1.3.2-46-g2c1e395
##reference=XXX
##contig=<ID=SWJQ01000001.1,length=**8013090**>
##contig=<ID=**SWJQ01000002.1**,length=5190156>
##contig=<ID=SWJQ01000003.1,length=2769777>
##contig=<ID=SWJQ01000004.1,length=397823>
...
SWJQ01000001.1  8013059 .       T       <\*>     0       .       DP=0;END=8013059;MIN_DP=0       GQ:DP:MIN_DP:QR:RO:QA:AO        -0:0:0:-0:0:-0:0
SWJQ01000001.1  8013060 .       G       <\*>     0       .       DP=0;END=8013060;MIN_DP=0       GQ:DP:MIN_DP:QR:RO:QA:AO        -0:0:0:-0:0:-0:0
**SWJQ01000002.1**  **8013061** .       .       <\*>     0       .       DP=0;END=8013090;MIN_DP=0       GQ:DP:MIN_DP:QR:RO:QA:AO        -0:0:0:-0:0:-0:0
SWJQ01000002.1  1       .       T       <\*>     0       .       DP=0;END=1;MIN_DP=0     GQ:DP:MIN_DP:QR:RO:QA:AO        -0:0:0:-0:0:-0:0
SWJQ01000002.1  2       .       A       <\*>     0       .       DP=10;END=2;MIN_DP=10   GQ:DP:MIN_DP:QR:RO:QA:AO        370:10:10:370:10:-0:0
...
SWJQ01000003.1  5190107 .       .       <\*>     0       .       DP=0;END=5190156;MIN_DP=0       GQ:DP:MIN_DP:QR:RO:QA:AO        -0:0:0:-0:0:-0:0
...
SWJQ01000004.1  2769587 .       .       <\*>     0       .       DP=0;END=2769777;MIN_DP=0       GQ:DP:MIN_DP:QR:RO:QA:AO        -0:0:0:-0:0:-0:0
...

Yannick

**Comment by yganwork** [comment]
I am affraid I cannot share data from this project at this time and mainly wanted to report the issue. I currently don't have time to build and try a smaller subset resulting in this error as I am on a deadline for this work. For now, I am just removing those lines from the vcf so I can proceed with my analysis.

If you manage to fix it, I am willing to do some tests using my data to give you feedback. Just let me know.

**Comment by yganwork** [comment]
**More strange things in the same gvcf output.**

After removing the chunk lines above, splitting SNPs and INDELS with gatk SelectVariant still fails with the same error as before.  This time I could identify the error related to the error message: the ALT allele is empty (i.e. the tabs from previous and next column have nothing between them) for a deletion (see below). I am using --strict-vcf with freebayes and if I am interpreting the VCF specification document correctly, this is indeed not allowed:

5.  ALT — alternate base(s):  Comma-separated list of alternate non-reference alleles.  These alleles do not have to be called in any of the samples.  Options are base Strings made up of the bases A,C,G,T,N (case insensitive)or  the  ‘*’  symbol  (allele  missing  due  to  overlapping  deletion)  or  a  MISSING  value  ‘.’   (no  variant)  or  an angle-bracketed ID String (“<ID>”) or a breakend replacement string as described in Section 5.4.  If there are no alternative alleles,  then the MISSING value must be used.  In other words,  the ALT field must be a symbolic allele, or a breakend replacement string, or match the regular expression ^([ACGTNacgtn]+|\*|\.)$. Tools processing VCF files are not required to preserve case in the allele String, except for IDs, which are casesensitive.  (String; no whitespace, commas, or angle-brackets are permitted in the ID String itself)

...
SWJQ01000668.1	272340	.	C	<\*>	0	.	**DP=2**;END=272340;MIN_DP=2	GQ:DP:MIN_DP:QR:RO:QA:AO	74:2:2:74:2:-0:0
SWJQ01000668.1	272341	.	G	<\*>	0	.	**DP=2;**END=272341;MIN_DP=2	GQ:DP:MIN_DP:QR:RO:QA:AO	74:2:2:74:2:-0:0
SWJQ01000668.1	272342	.	**CTCA		22.2017**	.	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=2;CIGAR=4D;**DP=2**;DPB=0;DPRA=0;EPP=7.35324;EPPR=0;GTI=0;LEN=4;MEANALT=1;MQM=28.5;MQMR=0;NS=1;NUMALT=1;ODDS=5.10485;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=48;QR=0;RO=0;RPL=2;RPP=7.35324;RPPR=0;RPR=0;RUN=1;SAF=0;SAP=7.35324;SAR=2;SRF=0;SRP=0;SRR=0;TYPE=del;technology.ILLUMINA=1	GT:GQ:DP:AD:RO:QR:AO:QA:GL	1/1:21:2:0,2:0:0:2:48:-4.02319,-0.60206,0
SWJQ01000668.1	272346	.	G	<\*>	0	.	**DP=13**;END=272346;MIN_DP=13	GQ:DP:MIN_DP:QR:RO:QA:AO	481:13:13:481:13:-0:0
SWJQ01000668.1	272347	.	C	<\*>	0	.	**DP=14**;END=272347;MIN_DP=14	GQ:DP:MIN_DP:QR:RO:QA:AO	518:14:14:518:14:-0:0
...

Yannick

**Comment by pjotrp** [comment]
We can not fix what we can't reproduce.
