### ISSUE TITLE
Unable to open fna and BAM files using freebayes. 

### ISSUE THREAD

**Issue by sahh04** [freebayes/freebayes#644]
Hi, 
I installed freebayes version 1.3.2 through conda and I am running it through the linux command line on a WSL. When I enter the simplest operation: 
`freebayes -f GCF.fna possorted.bam > test.vcf`
I get the error: 
`could not open GCF.fna` 
Why did I get this and how can I open the file?

**Comment by ekg** [comment]
This makes it seem like GCF.fna isn't accessible from where you are running the script. Try` head -c 1000 GCF.fna` instead of the freebayes command.

**Comment by sahh04** [comment]
It seems like I was able to open the files and run the command after moving them to a different folder and using the cd command. However, running the files is taking a long time. How long should I expect a 2 GB FASTA and 9 GB BAM file to take using the standard command? I have 24 gigs of RAM and an 8 core Ryzen 2700x on my system.

**Comment by ekg** [comment]
You should run in parallel over the contigs or chromosomes in your FASTA
using something like gnu parallel.
