### ISSUE TITLE
Error in using slurm array for freebayes

### ISSUE THREAD

**Issue by anna176577** [freebayes/freebayes#645]
Hello,

I am using freebayes to call the SNPs from multiple bam files. I have created the bam files and their indexes. Then I created a text file from genome.fasta using:
`fasta_generate_regions.py genome.fasta.fai 100000 > test.txt`
I split the test.txt file using split and created 40 subset files. Then I used SLURM array for freebayes:
```
RUN=${SLURM_ARRAY_TASK_ID}
INPUT=$(ls path/*.txt | sed -n ${RUN}p)
SAMPLE=$(basename "$INPUT" .txt)

freebayes -f genome.fasta \
          -L list_of_bam.txt \
          -r /path/test${RUN}.txt  > {SAMPLE}.vcf
```
          
However, it gives the error:
`unable to find FASTA index entry for test01.txt`

I want to use freebayes for SNP calling by a SLURM array so that it can be done efficiently. I am not sure what is going with code. I will appreciate any help! Thank you.

**Comment by ekg** [comment]
It looks like the -r flag isn't used right. I believe this is a specific
region string. You'll want to convert the region list to BED and use a BED
targets input rather then the --region input.

Hope this helps.

**Comment by ekg** [comment]
I believe the regions should contain their length. chr:0-100 for instance.
Do you not see this?

**Comment by anna176577** [comment]
I generated the regions file for genome.fasta using fasta_generate_regions.py. The regions file I got looks like this:

gene1:0-189
gene2:0-189
gene3:0-522

It shows genes and their length. Then I further divided this regions file to subsets to use it in an array. Each subset format is the same as above.

**Comment by ekg** [comment]
Bed format goes:

region start end

With tabs between.

Use a script to convert this into BED format. You can probably write one in
python or awk. Then split the file and provide it as --targets to your
freebayes jobs.

**Comment by anna176577** [comment]
I have converted the txt file to bed file which looks like:
```
gene1 0 189
gene2 0 189
gene3 0 522
```
I used this file as --targets but got the error "bed targets file is not open".

**Comment by anna176577** [comment]
Hi Erik, 

So the bed file worked and I have used SLURM array. However, the job complaints for memory assigned. I have used 15 gb total memory. That was the whole idea to make targets file so that it does not require more memory. Can you please suggest what is the optimum memory requirement for an array job with one node. Thank you!

**Comment by ekg** [comment]
It depends on how many samples you give, their depth, ploidy, and
diversity. But, 15G is dramatically more than I would expect in most cases.

**Comment by anna176577** [comment]
Thank you! I am using 200 bam files, diploid and diverse accessions. The job gave an error even after assigning 40G total memory.

`Some of your processes may have been killed by the cgroup out-of-memory handler.`

I am suspecting if it is even using different target bed regions that I have assigned using --targets:
```
freebayes -f genome.fasta  \
          -L list_of_bam.txtt \
          --targets ${INPUT}\
          --max-complex-gap         1 \
          --theta                   0.01 \
          --ploidy                  2 \
          --min-alternate-fraction  0.2 \
          --min-alternate-count     2 \
          --min-coverage            3 \
          --min-mapping-quality     1 \
          --min-base-quality        20 \
          --report-genotype-likelihood-max \
          --throw-away-complex-obs \
          --throw-away-mnps-obs \
          --throw-away-indel-obs > ${SAMPLE}.vcf
```
Thank you for your help!

**Comment by ekg** [comment]
Add

--use-best-n-alleles 4

**Comment by anna176577** [comment]
I got the same error for memory after a few minutes of run for one target file. I assigned 8G mem and it used more than that. However, the vcf prepared meanwhile was quite similar to what I got earlier with other arguments.
