### ISSUE TITLE
make problem of freebayes

### ISSUE THREAD

**Issue by woaishiye** [freebayes/freebayes#646]
when i use the command line "cmake -H. -Bbuild && cmake --build build -- -j4" ,i got the following mistake,and i dont know where is the problem?
-- Configuring done
-- Generating done
-- Build files have been written to: /ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/build
[  2%] Generating ../src/version_git.txt
[  4%] Performing build step for 'vcflib'
DETECTED_VERSION = v1.0.0
CURRENT_VERSION  = v1.0.0
[  4%] Built target SetVersion
[  6%] Performing build step for 'seqlib'
Making all in bwa
Making all in htslib
[ 33%] Built target htslib-build
[ 37%] Building CXX object CMakeFiles/vcflib.dir/src/Variant.cpp.o
[ 41%] Building CXX object CMakeFiles/vcflib.dir/smithwaterman/Repeats.cpp.o
[ 45%] Building CXX object CMakeFiles/vcflib.dir/smithwaterman/IndelAllele.cpp.o
Making all in fermi-lite
Making all in src
cc1plus: error: unrecognized command line option "-std=c++14"
gmake[5]: *** [libseqlib_a-FastqReader.o] Error 1
gmake[4]: *** [all-recursive] Error 1
gmake[3]: *** [all] Error 2
gmake[2]: *** [seqlib-prefix/src/seqlib-stamp/seqlib-build] Error 2
gmake[1]: *** [CMakeFiles/seqlib.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 50%] Building CXX object CMakeFiles/vcflib.dir/smithwaterman/disorder.cpp.o
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp: In function ‘std::string vcflib::reverse_complement(const std::string&)’:
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp:21: error: expected primary-expression before ‘[’ token
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp:21: error: expected primary-expression before ‘]’ token
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp:21: error: expected primary-expression before ‘char’
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp:21: error: expected unqualified-id before ‘char’
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp: In function ‘std::string vcflib::toUpper(const std::string&)’:
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp:45: error: expected primary-expression before ‘[’ token
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp:45: error: expected primary-expression before ‘]’ token
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp:45: error: expected primary-expression before ‘char’
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp:45: error: expected unqualified-id before ‘char’
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp: In member function ‘bool vcflib::Variant::isSymbolicSV() const’:
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp:202: error: expected initializer before ‘:’ token
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp:3014: error: expected primary-expression at end of input
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp:3014: error: expected ‘;’ at end of input
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp:3014: error: expected primary-expression at end of input
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp:3014: error: expected ‘)’ at end of input
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp:3014: error: expected statement at end of input
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp:3014: error: expected ‘}’ at end of input
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp: At global scope:
/ldfssz3/ComP1/NJAU/haoxiaoshuai/software/freebayes/freebayes-master/vcflib/src/Variant.cpp:3014: error: expected ‘}’ at end of input
gmake[5]: *** [CMakeFiles/vcflib.dir/src/Variant.cpp.o] Error 1
gmake[5]: *** Waiting for unfinished jobs....
gmake[4]: *** [CMakeFiles/vcflib.dir/all] Error 2
gmake[3]: *** [all] Error 2
gmake[2]: *** [vcflib-prefix/src/vcflib-stamp/vcflib-build] Error 2
gmake[1]: *** [CMakeFiles/vcflib.dir/all] Error 2
gmake: *** [all] Error 2

any help will be appreciated!!!

**Comment by pjotrp** [comment]
Try the meson/ninja build at https://github.com/pjotrp/freebayes

**Comment by pjotrp** [comment]
Please use the new meson build system.
