### ISSUE TITLE
How to use multiple .bam files of different genotypes/strains

### ISSUE THREAD

**Issue by shanmugavadivelps** [freebayes/freebayes#649]
Sir,
I have 200 different strain's .bam file and i want to generate single VCF with SNP call data for all 200 strains. How to proceed for this?.

pls suggest me an option and command?

with thanks

**Comment by ekg** [comment]
Make sure the read groups and sample names in the files are unique across
the full set. Then you can supply all the BAM files at once to freebayes.
It's probably necessary to run over regions or contigs of your reference.
