### ISSUE TITLE
Build 1.3.2, test cases for binaries, installation instructions?

### ISSUE THREAD

**Issue by mathog** [freebayes/freebayes#650]
Greetings,

I just built 1.3.2 like this:

```
  pversion=1.3.2
  package=freebayes
  cd /usr/common/src
  git clone --recursive git://github.com/ekg/freebayes.git
  mv freebayes ${package}-${pversion}
  cd ${package}-${pversion}
  mkdir build
  cd build
  cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON .. \
    2>&1 | tee cmake_2020_10_01.log
  make 2>&1 | tee build_2020_10_01.log

```

When it completed in the "bin" directory there were two programs:  freebayes and bamleftalign.  They both run with just "-help" and ldd does not show any unresolved library links.  However, there is no "make test", nor could I find a test case for either, so I do not know if they actually work properly.  Is there somewhere a set of tests one could run on these to demonstrate that the build is valid (at least more or less so)?

Also, I could not find any installation instructions.  Are those two binaries standalone or are there files somewhere in the large source tree which must be in particular locations for these to access?

Thank you.

**Comment by ekg** [comment]
Yes, in the test directory there is a test suite.

**Comment by mathog** [comment]
Hmm.  When I ran "make test" in the "build" subdirectory (see above) nothing happened.  There is a makefile in the top level, maybe it only works there?

```
cd /usr/common/src/${package}-${pversion}
make 2>&1 | tee build_2020_10_02.log
#seems to have rebuilt pretty much everything, then 
#failed early on in tests with some of these:
#  t/00_region_and_target_handling.t: line 29: samtools: command not found
#so it needs samtools.
module load samtools
make test 2>&1 | tee  tee test_2020_10_02B.log
#mutiple failures in tests, including:
ok
Random access with SetRegion not available for STDIN reading (no index file)
ERROR(freebayes): Could not SetRegion to q:1..10000
../scripts/freebayes-parallel: line 38: parallel: command not found
#looks like it needs gnu parallel. install that and try again.
make test 2>&1 | tee  tee test_2020_10_02C.log
#ends with:
All tests successful.
Files=4, Tests=46, 11 wallclock secs ( 0.04 usr  0.02 sys +  9.26 cusr  2.58 csys = 11.90 CPU)
Result: PASS
#despite this section:
ok 11 - region outside of bounds error
ok
Random access with SetRegion not available for STDIN reading (no index file)
ERROR(freebayes): Could not SetRegion to q:1..10000
t/01_call_variants.t ............... 
1..25
```

So it seems to work now (except for maybe that one stdin related issue).  The "samtools" and "parallel" dependencies should probably be checked explicitly in the scripts and a more user friendly error message emitted.  Better yet, have the make test for them.

Anyway, good to go now.  Thanks.
