### ISSUE TITLE
getting error in freebayes-parallel

### ISSUE THREAD

**Issue by shanmugavadivelps** [freebayes/freebayes#651]
sir,

I installed freebayes through conda in python2 environment and i ran command

freebayes-parallel <(fasta_generate_regions.py F_lycopersi.fna.fai 100000) 3 -f F_lycopersi.fna -X -u -F 0.75 -C 8 FLR.bam > Freebpara.vcf
 getting an error as below

/home/shanmu/anaconda3/envs/py2/bin/freebayes-parallel: line 40: vcffirstheader: command not found
/home/shanmu/anaconda3/envs/py2/bin/freebayes-parallel: line 40: vcfstreamsort: command not found
/home/shanmu/anaconda3/envs/py2/bin/freebayes-parallel: line 38: parallel: command not found
/home/shanmu/anaconda3/envs/py2/bin/freebayes-parallel: line 40: vcfuniq: command not found
(py2) shanmu@shanmu-ASUSPRO-P1440FA-P1440FA:/media/shanmu/shanmu_hdd/SNP_calling$ close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
pls help me to solve

**Comment by pjotrp** [comment]
You need vcflib tools.
