### ISSUE TITLE
Freebayes regroup MNV of the son and the snp in the father into one single line in the vcf

### ISSUE THREAD

**Issue by MelanieBroutin** [freebayes/freebayes#654]
Hi, 

I currently working with MNV (multiple nucleotide variant) in germline exome family and I have noticed a problem with the calling of freebayes. 

If the son has a MNV and the father has a SNV at the same position, freebayes will give me a single line in the vcf. 
Example: I want this :
```
1 10 AG TC  son
1 10 A T father
```
but I have that:
 `1 10 AG TC  son;father`

Real example:
Example:
![image](https://user-images.githubusercontent.com/53903734/96426372-7149eb80-11fd-11eb-9a38-beacb21bfb3d.png)
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	c23cc581-bca2-484f-a23a-f9fa5df7c61c	e3678e3d-11c7-4380-b29e-3cb2e9ad5fb2
3	37089130	.	AA	GC	2320.25	.	AB=0.375451;ABP=40.333;AC=1;AF=0.25;AN=4;AO=104;CIGAR=2X;DP=849;DPB=852;DPRA=0.484266;EPP=6.01695;EPPR=11.2212;GTI=0;LEN=2;MEANALT=6;MQM=60;MQMR=60;NS=2;NUMALT=1;ODDS=381.984;PAIRED=0.990385;PAIREDR=0.996094;PAO=3.5;PQA=86;PQR=0;PRO=0;QA=3647;QR=18851;RO=512;RPL=61;RPP=9.77527;RPPR=74.6859;RPR=43;RUN=1;SAF=33;SAP=33.1604;SAR=71;SRF=165;SRP=143.494;SRR=347;TYPE=mnp;technology.protocol=1	GT:GQ:DP:AD:RO:QR:AO:QA:GL	0/0:138.594:572:346,0:346:12862:0:0:0,-106.565,-1158.17	0/1:138.594:277:166,104:166:5989:104:3647:-248.037,0,-455.427
```
I checked all options of freebayes but I did not find any options that can correct my problem. 
Do you have a solution for this issue ?
Thanks

**Comment by ekg** [comment]
You should put the data together when you do the calling. Then they should
be called together as you prefer.

**Comment by MelanieBroutin** [comment]
Thank you for your quick answer. 

But I am not sure to understand what you say. I put RG in bam for each sample and I tried to merged bam but I have the same result.
`freebayes -b merged.bam -f GRCh37.fa --targets manifest > merge.vcf`
I have tried to called like that too, but it is the same.
`freebayes -b bam1.bam bam2.bam -f GRCh37.fa --targets manifest > output.vcf`

Thanks.
