### ISSUE TITLE
Segmentation fault on precompiled and self built instances

### ISSUE THREAD

**Issue by 7PintsOfCherryGarcia** [freebayes/freebayes#655]
Title says it all, 

valgrind error log on precompiled static version(1.3.1) :  [valgrinderrPreComp1.3.1.txt](https://github.com/ekg/freebayes/files/5415134/valgrinderrPreComp1.3.1.txt)

Same happens with 1.3.0, no static binaries available for 1.2. Release tarballs of 1.2.X do not include submodules so not built from source. 

valgrind error log on compiled from source version(1.3.1):  [valgrinderr1.3.1.txt](https://github.com/ekg/freebayes/files/5415173/valgrinderr1.3.1.txt)

make -v:

     GNU Make 4.2.1

cmake --version:

    cmake version 3.16.3

gcc --version:

    gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

ldd bin/freebayes:

    linux-vdso.so.1 (0x00007ffe267da000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff89098d000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff890971000)
    liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007ff890948000)
    libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007ff890935000)
    libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff890754000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff890605000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff8905e8000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff8903f6000)
    /lib64/ld-linux-x86-64.so.2 (0x00007ff890d41000)

OS:

    istributor ID:	Ubuntu
    Description:	Ubuntu 20.04.1 LTS
    Release:	20.04
    Codename:	focal

uname -a:

    Linux bicu 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

lscpu:

    Architecture:                    x86_64
    CPU op-mode(s):                  32-bit, 64-bit
    Byte Order:                      Little Endian
    Address sizes:                   43 bits physical, 48 bits virtual
    CPU(s):                          16
    On-line CPU(s) list:             0-15
    Thread(s) per core:              2
    Core(s) per socket:              8
    Socket(s):                       1
    NUMA node(s):                    1
    Vendor ID:                       AuthenticAMD
    CPU family:                      23
    Model:                           113
    Model name:                      AMD Ryzen 7 3700X 8-Core Processor
    Stepping:                        0
    Frequency boost:                 enabled
    CPU MHz:                         4049.081
    CPU max MHz:                     4050,0000
    CPU min MHz:                     2200,0000
    BogoMIPS:                        8099.31
    Virtualization:                  AMD-V
    L1d cache:                       256 KiB
    L1i cache:                       256 KiB
    L2 cache:                        4 MiB
    L3 cache:                        32 MiB
    NUMA node0 CPU(s):               0-15
    Vulnerability Itlb multihit:     Not affected
    Vulnerability L1tf:              Not affected
    Vulnerability Mds:               Not affected
    Vulnerability Meltdown:          Not affected
    Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
    Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
    Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional, STIBP conditional, RSB filling
    Vulnerability Srbds:             Not affected
    Vulnerability Tsx async abort:   Not affected
    Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonst
                                 op_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a 
                                 misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibpb stibp vmmcall fsgsbas
                                 e bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr w
                                 bnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter  pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca
'''

**Comment by pjotrp** [comment]
You may want to try my new meson/ninja build at https://github.com/pjotrp/freebayes
