### ISSUE TITLE
Compilation error: emmintrin.h No such file or directory

### ISSUE THREAD

**Issue by R-obert** [freebayes/freebayes#658]
I'm trying to compile Freebayes on a ppc64 machine (I know ... don't ask). I have git cloned it onto the machine, then:

```
cd freebayes
make -j4
```
At **performing build step for 'seqlib'** I get:

`ksw.c:29:23: fatal error: emmintrin.h: No such file or directory`

I think this is related to the architecture (due to [not-cross-pre-compiled components](https://github.com/broadinstitute/gatk/issues/1870)?), but how can I still compile Freebayes on the ppc64 machine that I'm unfortunately tied to?

**Comment by R-obert** [comment]
I found out that @walaj [has introduced](https://github.com/ekg/freebayes/pull/316) SeqLib to Freebayes in version 1.1, can you comment on why SeqLib doesn't compile on ppc64? Right before the emmintrin.h error message it says `make[6]: Entering directory '/home/user/freebayes/SeqLib/bwa'`.

**Comment by pjotrp** [comment]
Try my branch on https://github.com/pjotrp/freebayes. I made it work on ARM64 which also uses emmintrin.h

**Comment by pjotrp** [comment]
This should be fix with the upcoming release.
