### ISSUE TITLE
Travis build failing because of vclib tools in tests

### ISSUE THREAD

**Issue by pjotrp** [freebayes/freebayes#668]
**Only bug reports!**

Tests currently fail. And vcflib is not in Debian/Ubuntu (perhaps unsurprisingly). They are in GNU Guix, however.

See https://travis-ci.org/github/pjotrp/freebayes/jobs/749997265

**Comment by jnumm** [comment]
I guess you have to add `libvcflib-tools` to the apt packages that travis installs.

vcflib is indeed packaged in Debian and Ubuntu, these are a couple of links to see that: https://tracker.debian.org/pkg/libvcflib, https://packages.ubuntu.com/search?keywords=vcflib

**Comment by pjotrp** [comment]
I just added them!

**Comment by jnumm** [comment]
Ok, now I see that you added them.

Lines 31 and 47 in .travis.yml only contain os: linux, I suggest you to remove those lines.
That explains the problems with an unprepared linux image that does not have the build tools: https://travis-ci.com/github/freebayes/freebayes/jobs/473452874

Then there was something weird happening with ARM64 build. There was no explanation in the log, maybe run out of memory  `c++: fatal error: Killed signal terminated program cc1plus` https://travis-ci.com/github/freebayes/freebayes/jobs/473452873

**Comment by pjotrp** [comment]
The Guix build is fixed and Debian should be fine too. ARM travis builds... will have to fix some day. Closing this issue because vcflib dependency is fixed.
