### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [freebayes/freebayes#67]
I would like to point out that identifiers like "[`_ALLELE_H`](https://github.com/ekg/freebayes/blob/8a98f117c36cb5c64e319428cf059b512dbf2916/src/Allele.h#L1)" and "[`__SAMPLE_H`](https://github.com/ekg/freebayes/blob/9ed353ce647740cf231c1882479dc6e71ac80849/src/Sample.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
Would you like to achieve standard compliance anyhow?

**Comment by pjotrp** [comment]
> Would you like to achieve standard compliance anyhow?

Yes, we should fix this.

**Comment by ekg** [comment]
Could we use to `#pragma once` rather than these?

AFAIK it's supported by all major compilers.

**Comment by pjotrp** [comment]
HI @jnumm, do you think we can close this issue?

**Comment by jnumm** [comment]
@pjotrp Yes, I think we can close this.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/freebayes/freebayes/commit/3b72737db2576f4172b48461facc9ec1d5ba392e "Avoid C++ reserved identifiers").
