### ISSUE TITLE
Makefile is missing

### ISSUE THREAD

**Issue by samfux84** [freebayes/freebayes#676]
Freebayes 1.3.1 contained a Makefile in the top-level directory to build the software with GNU Make. In 1.3.3 this Makefile is missing.

The changelog for 1.3.3 mentions

`Added Meson+Ninja build system for faster builds`

But it does not mention that possibility to build freebayes with GNU Make using the provided Makefile has been removed. Is it still possible to build freebayes with GNU Make? Can one copy the Makefile from version 1.3.1 or 1.3.2? Should this work?

It does not take a lot of time to build freebayes with GNU Make and it is a well established build system. There is no need to add additional complexity.

If it is not possible to build freebayes with GNU Make, what about CMake? Is Meson+Ninja the only possible way to build freebayes from source?

**Comment by pjotrp** [comment]
GNU Make is no longer supported. The previous one simply invoked cmake, it was not a proper make file anyway. Follow the instruction in the README.
