### ISSUE TITLE
freebayes-parallel error from fasta_generate_regions.py - /usr/bin/env: 'python3': No such file or directory

### ISSUE THREAD

**Issue by moldach** [freebayes/freebayes#679]
I'm getting the following error when trying to run `freebayes-parallel`:

> /usr/bin/env: 'python3': No such file or directory

Despite the fact that `python3` is available at `/usr/bin/python3`:

```
$ which python3
/usr/bin/python3
```

### Submission Script

```
#!/bin/bash

#SBATCH --job-name=freebayes-parallel-test
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=1000
#SBATCH --time=00:15:00
#SBATCH --mail-user=moldach@ucalgary.ca
#SBATCH --mail-type=END
#SBATCH --output=freebayes_4CPU_bench.out
#SBATCH --error=freebayes_4CPU_bench.err

umask -S u=rwx,g=rwx,o=

# freebayes
date;
echo "proband freebayes running...";

/project/M-mtgraovac182840/tools/freebayes-master/scripts/freebayes-parallel \
    <(python /project/M-mtgraovac182840/tools/freebayes-master/scripts/fasta_generate_regions.py /project/M-mtgraovac182840/indexes/GRCh37/Homo_sapiens.GRCh37.dna.toplevel.fa.fai 100000) 4 \
    --min-coverage 5 \
    --min-base-quality 30 \
    --min-mapping-quality 30 \
    --min-alternate-count 5 \
    -f /project/M-mtgraovac182840/indexes/GRCh37/Homo_sapiens.GRCh37.dna.toplevel.fa \
    /project/M-mtgraovac182840/matthew/tool-testing/MTG_human_genomics_pipeline-master/alignment/bwa/proband_bwaMEM_sort_dedupped.bam >var.vcf

date
```

### Error

```
/usr/bin/env: 'python3': No such file or directory
Traceback (most recent call last):
  File "/project/M-mtgraovac182840/tools/freebayes-master/scripts/fasta_generate_regions.py", line 28, in <module>
```

**Comment by jnumm** [comment]
I know nothing of slurm and such, but looks like there might be no python3 executable on the system where the execution is actually happening. So add the word `python` before the first .py file, (just like there already is `python` before the other script filename as well).

```diff
-/project/M-mtgraovac182840/tools/freebayes-master/scripts/freebayes-parallel \
+python /project/M-mtgraovac182840/tools/freebayes-master/scripts/freebayes-parallel \
```

**Comment by pjotrp** [comment]
I am adding a patch to locate python3 through /usr/bin/env. As it should be :)

**Comment by moldach** [comment]
@pjotrp i just tried the must recent patch (with `--recursive`) and I'm getting the same error.

**Comment by pjotrp** [comment]
Please paste output here including the command. What does '/usr/bin/env python3' say?

**Comment by moldach** [comment]
> 
> 
> Please paste output here including the command. What does `/usr/bin/env python3` say?


```
[moldach@marc MTG_oldPipeScript]$ /usr/bin/env python3
Python 3.6.8 (default, Apr 16 2020, 01:36:27)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

`python3` executable is on the system.

This is the command and output I got from https://github.com/freebayes/freebayes/commit/6584f39804f30cacf14b02d752ba81cefa5d55f2


## Command:

```
/project/M-mtgraovac182840/tools/freebayes/scripts/freebayes-parallel \
    <(python /project/M-mtgraovac182840/tools/freebayes/scripts/fasta_generate_regions.py /project/M-mtgraovac182840/indexes/GRCh37/Homo_sapiens.GRCh37.dna.toplevel.fa.fai 100000) 4 \
    --min-coverage 5 \
    --min-base-quality 30 \
    --min-mapping-quality 30 \
    --min-alternate-count 5 \
    -f /project/M-mtgraovac182840/indexes/GRCh37/Homo_sapiens.GRCh37.dna.toplevel.fa \
    /project/M-mtgraovac182840/matthew/tool-testing/MTG_human_genomics_pipeline-master/alignment/bwa/proband_bwaMEM_sort_dedupped.bam >var.vcf
```

## Output/Error

```
/usr/bin/env: 'python3': No such file or directory
Traceback (most recent call last):
  File "/project/M-mtgraovac182840/tools/freebayes-legacy/scripts/fasta_generate_regions.py", line 28, in <module>
    print(chrom_name + ":" + str(region_start) + "-" + str(end))
IOError: [Errno 32] Broken pipe
```

**Comment by pjotrp** [comment]
Well, it looks like python3 is not visible at that point in the pipeline.

**Comment by moldach** [comment]
> Well, it looks like python3 is not visible at that point in the pipeline.

The question is _why_? Any suggestions for testing or making `python3` available. 

Like can I use an `export PATH` or `source ~/.bashrc` within a script to allow it to find?

I've heard that `/usr/bin/env` as the SHEBANG can cause problems because it's looking for the first place in the PATH (however, it's odd in this case as it's not found anywhere).

Ultimately, I'm working on a secure linux environment where outbound internet connections are not allowed due to security concerns. 

The `python3` available on at `/usr/bin/python3` was one installed by the Sys.Admins and does not have python modules available, nor can I install them. Thus we have settled on a method of creating `conda` environments on a computer with internet and transferring them to the secure linux env. There, we've been successful `source ~/.bashrc` and then `conda activate <envName>`, which makes this `python3` available.

```
[moldach@marc MTG_oldPipeScript]$ which python3
/usr/bin/python3
[moldach@marc MTG_oldPipeScript]$ source ~/.bashrc
(base) [moldach@marc MTG_oldPipeScript]$ conda activate expansionHunterDeNovo
(expansionHunterDeNovo) [moldach@marc MTG_oldPipeScript]$ which python3
/project/M-mtgraovac182840/miniconda3/envs/expansionHunterDeNovo/bin/python3
```

**Comment by sagitaninta** [comment]
I got the same exact error with @moldach and wondering if there is a solution for that?
