### ISSUE TITLE
Build issues for version 1.3.4 under Debian

### ISSUE THREAD

**Issue by tillea** [freebayes/freebayes#683]
**Describe the bug**

I wanted to update the Debian package of freebayes to version 1.3.4.  Unfortunately I get

    c++ -Ilibfreebayes_common.a.p -I. -I.. -I../src -I../ttmath -I/usr/include/vcflib -I/usr/include/smithwaterman -I/usr/include/fastahack -I/usr/include/SeqLib -I/usr/include/jsoncpp -fdiagnostics-color=always -  pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -g -O2 -fdebug-prefix-map=/build/freebayes-1.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -               D_FORTIFY_SOURCE=2 -fPIC -pthread -fpermissive -Wno-reorder -Wno-sign-compare -Wno-unused-variable -Wno-unused-but-set-variable -MD -MQ libfreebayes_common.a.p/src_DataLikelihood.cpp.o -MF libfreebayes_common.a.p/  src_DataLikelihood.cpp.o.d -o libfreebayes_common.a.p/src_DataLikelihood.cpp.o -c ../src/DataLikelihood.cpp
    In file included from /usr/include/vcflib/Variant.h:34,
                     from ../src/AlleleParser.h:32,
                     from ../src/DataLikelihood.h:20,
                     from ../src/DataLikelihood.cpp:1:
    /usr/include/fastahack/Fasta.h:30:7: error: redefinition of ‘class FastaIndexEntry’
       30 | class FastaIndexEntry {
          |       ^~~~~~~~~~~~~~~
    In file included from ../src/AlleleParser.h:25,
                     from ../src/DataLikelihood.h:20,
                     from ../src/DataLikelihood.cpp:1:
    ../src/Fasta.h:29:7: note: previous definition of ‘class FastaIndexEntry’
       29 | class FastaIndexEntry {
          |       ^~~~~~~~~~~~~~~
    In file included from /usr/include/vcflib/Variant.h:34,
                     from ../src/AlleleParser.h:32,
                     from ../src/DataLikelihood.h:20,
                     from ../src/DataLikelihood.cpp:1:
    /usr/include/fastahack/Fasta.h:44:7: error: redefinition of ‘class FastaIndex’
       44 | class FastaIndex : public map<string, FastaIndexEntry> {
          |       ^~~~~~~~~~
    In file included from ../src/AlleleParser.h:25,
                     from ../src/DataLikelihood.h:20,
                     from ../src/DataLikelihood.cpp:1:
    ../src/Fasta.h:43:7: note: previous definition of ‘class FastaIndex’
       43 | class FastaIndex : public map<string, FastaIndexEntry> {
          |       ^~~~~~~~~~
    In file included from /usr/include/vcflib/Variant.h:34,
                     from ../src/AlleleParser.h:32,
                     from ../src/DataLikelihood.h:20,
                     f[8/27] c++ -Ilibfreebayes_common.a.p -I. -I.. -I../src -I../ttmath -I/usr/include/vcflib -I/usr/include/smithwaterman -I/usr/include/fastahack -I/usr/include/SeqLib -I/usr/include/jsoncpp -    fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -g -O2 -fdebug-prefix-map=/build/freebayes-1.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -pthread -fpermissive -Wn[9/27] c++ -Ilibfreebayes_common.a.p -I. -I.. -I../src -I../ttmath -I/usr/include/vcflib -I/usr/include/smithwaterman -I/usr/include/fastahack -I/usr/   include/SeqLib -I/usr/include/jsoncpp -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -g -O2 -fdebug-prefix-map=/build/freebayes-1.3.4=. -fstack-protector-  strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -pthread -fpermissive -Wno-reorder -Wno-sign-compare -Wno-unused-variable -Wno-unused-but-set-variable -MD -MQ libfreebayes_common.a.p/  src_Multinomial.cpp.o -MF libfreebayes_common.a.p/src_Multinomial.cpp.o.d -o libfreebayes_common.a.p/src_Multinomial.cpp.o -c ../src/Multinomial.cpp
    [10/27] c++ -Ilibfreebayes_common.a.p -I. -I.. -I../src -I../ttmath -I/usr/include/vcflib -I/usr/include/smithwaterman -I/usr/include/fastahack -I/usr/include/SeqLib -I/usr/include/jsoncpp -fdiagnostics-        color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -g -O2 -fdebug-prefix-map=/build/freebayes-1.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time - D_FORTIFY_SOURCE=2 -fPIC -pthread -fpermissive -Wno-reorder -Wno-sign-compare -Wno-unused-variable -Wno-unused-but-set-variable -MD -MQ libfreebayes_common.a.p/src_Fasta.cpp.o -MF libfreebayes_common.a.p/src_Fasta. cpp.o.d -o libfreebayes_common.a.p/src_Fasta.cpp.o -c ../src/Fasta.cpp
    [11/27] c++ -Ilibfreebayes_common.a.p -I. -I.. -I../src -I../ttmath -I/usr/include/vcflib -I/usr/include/smithwaterman -I/usr/include/fastahack -I/usr/include/SeqLib -I/usr/include/jsoncpp -fdiagnostics-        color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -g -O2 -fdebug-prefix-map=/build/freebayes-1.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time - D_FORTIFY_SOURCE=2 -fPIC -pthread -fpermissive -Wno-reorder -Wno-sign-compare -Wno-unused-variable -Wno-unused-but-set-variable -MD -MQ libfreebayes_common.a.p/src_AlleleParser.cpp.o -MF libfreebayes_common.a.p/    src_AlleleParser.cpp.o.d -o libfreebayes_common.a.p/src_AlleleParser.cpp.o -c ../src/AlleleParser.cpp
    FAILED: libfreebayes_common.a.p/src_AlleleParser.cpp.o
    c++ -Ilibfreebayes_common.a.p -I. -I.. -I../src -I../ttmath -I/usr/include/vcflib -I/usr/include/smithwaterman -I/usr/include/fastahack -I/usr/include/SeqLib -I/usr/include/jsoncpp -fdiagnostics-color=always -  pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -g -O2 -fdebug-prefix-map=/build/freebayes-1.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -               D_FORTIFY_SOURCE=2 -fPIC -pthread -fpermissive -Wno-reorder -Wno-sign-compare -Wno-unused-variable -Wno-unused-but-set-variable -MD -MQ libfreebayes_common.a.p/src_AlleleParser.cpp.o -MF libfreebayes_common.a.p/    src_AlleleParser.cpp.o.d -o libfreebayes_common.a.p/src_AlleleParser.cpp.o -c ../src/AlleleParser.cpp
    In file included from /usr/include/vcflib/Variant.h:34,
                     from ../src/AlleleParser.h:32,
                     from ../src/AlleleParser.cpp:1:
    /usr/include/fastahack/Fasta.h:30:7: error: redefinition of ‘class FastaIndexEntry’
       30 | class FastaIndexEntry {
          |       ^~~~~~~~~~~~~~~
    In file included from ../src/AlleleParser.h:25,
                     from ../src/AlleleParser.cpp:1:
    ../src/Fasta.h:29:7: note: previous definition of ‘class FastaIndexEntry’
       29 | class FastaIndexEntry {
          |       ^~~~~~~~~~~~~~~
    In file included from /usr/include/vcflib/Variant.h:34,
                     from ../src/AlleleParser.h:32,
                     from ../src/AlleleParser.cpp:1:
    ...

The build for version 1.3.3 went fine.

Kind regards, Andreas.

**Comment by tillea** [comment]
On Sat, Feb 06, 2021 at 07:05:08AM -0800, Pjotr Prins wrote:
> Closed #683 via 00594a1db84855f99c9fe2c23305b86fa542dff2.
Would you mind tagging a release? Andreas.

**Comment by pjotrp** [comment]
@tillea done!
