### ISSUE TITLE
meson installation issue

### ISSUE THREAD

**Issue by ehenrion** [freebayes/freebayes#687]
Hi, I'm having trouble installing freebayes with meson...

I'm on Ubuntu 16.04, have successfully installed `meson` and `ninja-build` with `apt` but I'm still unable to install freebayes v1.3.4...
I also want to mention I've never used `meson` before... 

Here is the error I have : 
```
root@beluga2:/cvmfs/soft.mugqic/CentOS6/software/freebayes/tmp/freebayes# meson build/ --buildtype debug
The Meson build system
Version: 0.29.0
Source dir: /cvmfs/soft.mugqic/CentOS6/software/freebayes/tmp/freebayes
Build dir: /cvmfs/soft.mugqic/CentOS6/software/freebayes/tmp/freebayes/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: freebayes
Native cpp compiler: c++ (gcc 5.3.1-14ubuntu2)
Native c compiler: cc (gcc 5.3.1-14ubuntu2)
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency zlib found: YES 1.2.8
Native dependency liblzma found: YES 5.1.0alpha
Dependency threads found: YES
Native dependency htslib found: YES 1.11-86-gd9890a9

Meson encountered an error in file meson.build, line 20, column 0:
Unknown method "find_library" in object.
```

Any help would be greatly appreciated.

And please, don't mind the `CentOS6` part in the path of the `Source` and `Build` directories, this is just some legacy in the naming...

Thanks in advance,
Best.

**Comment by pjotrp** [comment]
Your meson is way too old.

**Comment by ehenrion** [comment]
Oh... Thanks...
Did I miss any specifications regarding the version of meson to use in order to install free bayes ?
Does that also means that the apt repositories are also "way too" old on Ubuntu16.04 ?
Do you know if there is any specific development repo I could use to have an up-to-date version of meson ?
Thanks a lot

**Comment by ehenrion** [comment]
Ok I got it... Installing meson through pip3 resolved the version issue...
Thanks again !
