### ISSUE TITLE
Add install to build including scripts? (bioconda)

### ISSUE THREAD

**Issue by jpuritz** [freebayes/freebayes#693]
Would be nice to have the ability to install compiled executable and scripts with meson.  Bioconda build is patching this now: (https://github.com/bioconda/bioconda-recipes/pull/27011)

**Comment by jpuritz** [comment]
Actually it's not building properly on OS X for reasons that can't seem to figure out...

**Comment by pjotrp** [comment]
Hi @jpuritz, what is the latest status of the conda builds?

**Comment by jpuritz** [comment]
They are a bit of a patchwork mess, but functional and the python 3.9 pinning is no longer an issue.

**Comment by pjotrp** [comment]
v1.3.5 is in conda.
