### ISSUE TITLE
bioconda

### ISSUE THREAD

**Issue by jpn2021** [freebayes/freebayes#694]
bioconda pull is requiring Python 3.9 but that conflicts with many other things. As it is not required for freebayes can you please remove that requirement.

**Comment by jnumm** [comment]
FYI, there is another PR discussion where the strict python 3.9 dependency was brought up too.  https://github.com/bioconda/bioconda-recipes/pull/27011#issuecomment-789884849

**Comment by pjotrp** [comment]
See also #693
