### ISSUE TITLE
Read depth in format field of a VCF file (i.e. AD)

### ISSUE THREAD

**Issue by ZenoFan** [freebayes/freebayes#697]
Hi,

First, I want to thank you for creating the nice pipeline for SNP calling. My question is really just confirming the results from freebayes. In my case, I want to calculate allele frequencies myself and call SNPs based on various prior distributions. However, I want to know if the read depth in 'AD' field are faithful read depth from observed alleles. It looks like only the called alleles had read depth data in the 'AD' field. Is a third allele's data discarded if not called? This would affect how I process the data in downstream analyses. Please advice.

Thanks,
Zeno

**Comment by ekg** [comment]
I believe these are the filtered data that are given to the caller.

**Comment by ZenoFan** [comment]
Hi Erik,

So that means 'AD' records read depth for all observed alleles. The ones
not observed were just 0 in read depth, but not present in 'AD' field?

Thanks,
Zeno
