### ISSUE TITLE
cannot install the latest version freebayes by conda 

### ISSUE THREAD

**Issue by BowenXiao123** [freebayes/freebayes#698]
code
`conda install -c bioconda freebayes`
`freebayes --version `
version:  v0.9.21
`conda update -c bioconda freebayes`
`freebayes --version `
version:  v0.9.21

**Comment by jpn2021** [comment]
Is there a workaround or a fix?

**Comment by pjotrp** [comment]
You need to contact the conda folks.

**Comment by pjotrp** [comment]
Duplicate of #694
