### ISSUE TITLE
Allele balance (AB) field

### ISSUE THREAD

**Issue by YannDussert** [freebayes/freebayes#700]
Hi,

The AB is described in the VCF header as "a number between 0 and 1 representing the ratio of reads showing the **reference** allele to all reads". However, looking at read coverage for individual sites, it seems it should be "the ratio of reads showing the **alternate** allele to all reads".

Here is two examples of SNPs called in a single individual (I discarded non-relevant INFO and FORMAT fields for clarity):

>NC_050105.1     16919   .       G       A       55.3226 .       AB=0.714286   GT:DP:AD 0/1:7:2,5
>NC_050105.1     16928   .       C       T       36.8228 .       AB=0.4   GT:DP:AD 0/1:10:6,4

I apologize if I missed or misunderstood something.

Best regards,
Yann

**Comment by asp8200** [comment]
It seems to me that there is still a mismatch between the stated definition of AB in the header of the VCF-file produced by freebayes and the actual reported value for AB in the VCF-file. 

Here is an example where AB is reported to be 0.561894 while REF=C,  ALT=T,  #C = 6685, #T = 8579 and depth=15268. In this case,  AB should be #REF / depth = 0.4378, however, the reported value of AB is identical to #ALT/depth.


```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT
chr7    117540230       .       C       T       158917  .       AB=0.561894;ABP=511.048;AC=1;AF=0.5;...
```
