### ISSUE TITLE
Two closeby SNPs are called as 'complex'

### ISSUE THREAD

**Issue by yliueagle** [freebayes/freebayes#702]
(I found this was nicely explained in the manual using _freebayes ... | vcfallelicprimitives -kg >calls.vcf_

I found in some cases, two SNPs close to each other will be called as a single variant as 'complex', see the example below.
Is there a way to avoid this? I.e., to call them as two separated SNPs? Thanks

**(Two SNPs C and A was called as: CATA)**
![image](https://user-images.githubusercontent.com/7893315/115882178-ce448980-a44c-11eb-96d9-9e495527e97a.png)

**IGV view:**

![image](https://user-images.githubusercontent.com/7893315/115882016-9fc6ae80-a44c-11eb-91d3-713e0b611035.png)

**Comment by yliueagle** [comment]
This 'issue' has been solved

**Comment by ekg** [comment]
This is a feature not a bug.

**Comment by cherryamme** [comment]
> This 'issue' has been solved

@yliueagle I mmet the same question. How did you solve it？
