### ISSUE TITLE
Some indels seems to be called incorrectly when reads are realigned by abra2.

### ISSUE THREAD

**Issue by sib0** [freebayes/freebayes#705]
Hello,

I am running Freebayes on BAM files generated by ```minimap2```, with duplicates removed from BAM files with ```picard```, then realigned with ```abra2``` and finally softclipped with ```ivar```.

I am using current last release installed with conda, ```freebayes-1.3.5```.

I tried different options but I cannot get ```freebayes``` to call correctly several indels, it seems it only concern regions realigned by ```abra2``` although i'm not sure.

Removing all tags added by ```abra2``` did not change the result.
It seems that the coverage is wrongly reported in the VCF : only the reads supporting variant alleles are considered.
```
MN908947|wg    10497    .    TTGGTTTTAACATAGATTATGACTGTGTCTCTTTTTGTTACATGCACCATATGGAATTACCAACTGGAGTTCAT    TT    935.34    .    AB=0;ABP=0;AC=1;AF=1;AN=1;AO=44;CIGAR=1M72D1M;DP=45;DPB=72.9324;DPRA=0;EPP=47.4268;EPPR=0;GTI=0;LEN=72;MEANALT=2;MQM=41.8636;MQMR=0;NS=1;NUMALT=1;ODDS=215.37;PAIRED=0;PAIREDR=0;PAO=2;PQA=48;PQR=3419;PRO=105;QA=1359;QR=0;RO=0;RPL=2;RPP=81.9729;RPPR=0;RPR=42;RUN=1;SAF=37;SAP=47.4268;SAR=7;SRF=0;SRP=0;SRR=0;TYPE=del    GT:DP:AD:RO:QR:AO:QA:GL    1:45:0,44:0:0:44:1359:-115.127,0
```
Here, the DP is reported as if there was only 45 reads, but either on IGV or with a ```samtools mpileup``` the read count is correctly reported around 3,000 reads.

![igv_del10497](https://user-images.githubusercontent.com/30846320/119500610-4366ef80-bd68-11eb-8f6a-96f35e3e280a.png)

On a debug test run in a problematic region, freebayes seems to consider all the reads in the beginning, then forgets to take reads supporting reference allele into account.

The calling on this begins with:
```
filtering genotype alleles which are not supported by at least 4 observations comprising at least 0.00010 of the observations in a single individual
genotype allele: complex:1X72D1M:10496:2:GT qsum 36
genotype allele: deletion:1M72D1M:10496:72:TT qsum 1359
deletion:1M72D1M:10496:72:TT has support of 44 in individual unknown (3022 obs) and fraction 0.01456
genotype allele: reference:3M:10494:1:T qsum 105467
reference:3M:10494:1:T has support of 2977 in individual unknown (3022 obs) and fraction 0.98511
filtered genotype alleles
getting 2 best SNP alleles, and all other alleles
adding allele to result alleles T
allele quality sum 105467
adding allele to result alleles D:10496:1M72D1M
allele quality sum 1359
found 2 SNP/ref alleles of which we now have 2
and 0 INDEL and MNP alleles
building haplotype alleles, currently there are 2 genotype alleles
deletion:1M72D1M:10496:72:TT|reference:3M:10494:1:T
reference length of deletion:1M72D1M:10496:72:TT is 74 so extending haplotype
```
But it ends with:
```
filtering genotype alleles which are not supported by at least 4 observations comprising at least 0.00010 of the observations in a single individual
genotype allele: complex:1X72D1M:10496:2:GT qsum 72
genotype allele: deletion:1M72D1M:10496:72:TT qsum 2718
deletion:1M72D1M:10496:72:TT has support of 88 in individual unknown (90 obs) and fraction 0.97778
filtered genotype alleles
getting 2 best SNP alleles, and all other alleles
adding allele to result alleles D:10496:1M72D1M
allele quality sum 2718
found 1 SNP/ref alleles of which we now have 1
and 0 INDEL and MNP alleles
built haplotype alleles, now there are 2 genotype alleles
deletion:1M72D1M:10496:72:TT|reference:74M:10496:74:TTGGTTTTAACATAGATTATGACTGTGTCTCTTTTTGTTACATGCACCATATGGAATTACCAACTGGAGTTCAT
genotype alleles: deletion:1M72D1M:10496:72:TT|reference:74M:10496:74:TTGGTTTTAACATAGATTATGACTGTGTCTCTTTTTGTTACATGCACCATATGGAATTACCAACTGGAGTTCAT
searching genotype space
best combo: combo posterior prob: 0.00000
{"unknown":["D:10496:1M72D1M",0.00000]}
```
I could provide BAM, VCF, log files or other necessary files if you need it.
I would appreciate your support,

**Comment by ekg** [comment]
It appears that no reference supporting reads actually cover the full site.
That's a limitation of freebayes. It doesn't consider the partial
observations to be trustworthy and doesn't use them.

**Comment by sib0** [comment]
Thank your very much for your answer.
What would you advise to do in this situation?
Is there any workaround to keep using freebayes without being impaired by these "false" calls?

**Comment by sib0** [comment]
It seems this issue is also occuring on sites with short indels, where reference supporting reads should cover the full site.
I need a bit more time to provide the files necessary to illustrate this case.
