### ISSUE TITLE
DP not equal to the sum of AD

### ISSUE THREAD

**Issue by wshuai294** [freebayes/freebayes#707]
HI,

I ran Freebayes and get a locus like:

NODE_1_length_61974_cov_1313.632260     1       .       TCCGCA  ACGGTCCGCA      177.403 .       AB=0.297297;ABP=16.2152;AC=1;AF=0.5;AN=2;AO=11;CIGAR=1X1M1X4I3M;DP=37;DPB=56;DPRA=0;EPP=19.0002;EPPR=9.52472;GTI=0;LEN=10;MEANALT=5;MQM=40;MQMR=41.3333;NS=1;NUMALT=1;ODDS=2.05835;PAIRED=0;PAIREDR=0;PAO=5;PQA=175;PQR=0;PRO=0;QA=363;QR=101;RO=3;RPL=0;RPP=26.8965;RPPR=9.52472;RPR=11;RUN=1;SAF=1;SAP=19.0002;SAR=10;SRF=3;SRP=9.52472;SRR=0;TYPE=complex        GT:DP:AD:RO:QR:AO:QA:GL 0/1:37:3,11:3:101:11:363:-27.5206,0,-4.69051.

In which, I expect the depth of the locus is equal to the sum of each allele's depth. In other words, DP should be the sum of AD. However, they are not equal in this locus.

Could you help me with this?
Thanks,
WANG Shuai

**Comment by ekg** [comment]
This call is over more than one base, so that is probably causing the
difference. If I remember correctly, the DP counts the spanning reads,
while the others count partial observations.

**Comment by wshuai294** [comment]
Ok, Thanks for your help.
