### ISSUE TITLE
Unable to read file error when using long list of Bam files - solution

### ISSUE THREAD

**Issue by AntonS-bio** [freebayes/freebayes#710]
I saw this partially covered on google group [https://groups.google.com/g/freebayes/c/K4RFPVa_ziU], but it took a while to find, so I'll add it here.

I have a list of 1,200 small indexed bam files (5-15Mb each) and when running 

`freebayes -f ../ref.fasta -L bamList.txt ` 

i get an error:
```
ERROR(freebayes): Could not open input BAM files
BamMultiReader::Open: unable to open all files:
        unable to open file: Bafile1020.bam
        unable to open file: Bafile1021.bam
        [list continues until the last bam file]
```

The bam files can be analysed individually and when I remove first few hundred bam files, the error also goes away, so the issue is not in bam files themselves. After prodding around I was able to track it down to system's limit on number of open files as was mentioned on google group. On Linux system the limit can be checked via:
`ulimit -a`

and changed via 
`ulimit -n #` 
where # is new limit number.

**Comment by pjotrp** [comment]
This is linux level. Thanks for posting.
