### ISSUE TITLE
Sequence out of order

### ISSUE THREAD

**Issue by peflanag** [freebayes/freebayes#714]
Hi I am working with a diploid org for the first time and trying to figure out how to compare 7 samples in order to look at an MLT.

The org is C. parapsilosis and I have trimmed the fastq, performed BWA men and now using freebies before I figure out what to do next! While running freebies the terminal is saying that the portions seem to be out of order. Is this normal? I've added a screenshot.

Cheers,

P
![Screenshot 2021-08-04 at 12 26 21 (2)](https://user-images.githubusercontent.com/32863969/128173289-21f91435-5321-469b-8d50-7bd6bb8b3a7d.png)

**Comment by prpanigrahi** [comment]
Try sort the bam file wrt coordinate.
