### ISSUE TITLE
Freebayes stops after first chromosome

### ISSUE THREAD

**Issue by J-Pieplow** [freebayes/freebayes#721]
Hi everybody,

I'm trying to run freebayes over a set of bamfiles with another vcf as 'template', but it always stops after the first chromosome, without an error message.

This is the command I'm using to run freebayes:

cat $BAMLST | parallel --no-notice -k -j $NSLOTS "echo {} && freebayes \
--fasta-reference $REF \
--ploidy 2 \
--variant-input $REFVCF \
--only-use-input-alleles \
--report-genotype-likelihood-max \
--use-mapping-quality \
--genotype-qualities \
--haplotype-length -1 \
--min-mapping-quality 20 \
--min-base-quality 30 \
--min-alternate-fraction $MINALTFRAC \
--min-alternate-total $MINALTN \
--min-coverage $MINCOV \
--bam {} |\
bgzip -f -@ $NSLOTS -c /dev/stdin > $OUTPUTFOLDER/vcf-genotyping/raw2/{/.}.vcf.gz\
&& tabix -fp vcf $OUTPUTFOLDER/vcf-genotyping/raw2/{/.}.vcf.gz"

When I don't use the --variant-input and --only-use-input-alleles options freebayes is working fine.

I saw that there was a similar issue once, and it got resolved here:
https://github.com/freebayes/freebayes/commit/df23b3fcc1733c71e125a50752f26c3019af6519

Maybe it's the same problem in my case, but i wouldn't know how to implement this fix either. I installed freebayes via conda, and could not find any file called  AlleleParser.cpp .

I would include the reference-vcf, an example-bam-file and the reference genome I am using, but somehow I cannot upload them here within the issue, guess they are too large. But probably I could find another way to share them if necessary.

Any help on this would be much appreciated

**Comment by wzt1417** [comment]
I also want to know how to  implement this fix, please!
