### ISSUE TITLE
variant reported as SNV but showing additional bases in REF

### ISSUE THREAD

**Issue by splaisan** [freebayes/freebayes#734]
I am struggling with calling variants in 7 chicken lines.
I look for private variants to 4 lines vs each others (+ 3 parental lines as support) and all candidate I review in IGV are false positive in fact also variant in the other 3 lines.

I merged my calls using bcftools merge

I noticed that the candidates are selected because the call is not the same in the target line and the other samples.

Can you please explain why SNPs are reported with conserved based before the variant when there is an overlapping variant nearby. Can I avoid that with some command argument or post-processing?

In this example, the target is called: GTTTA => GTTTT (only the final A => T is the variant)

![Screenshot 2022-03-30 at 11 28 03](https://user-images.githubusercontent.com/858516/160800019-d5af3350-4e6c-4ed5-b558-db60ef74f80e.png)

```
1       101113848       .       GTTTA   GTTTT   693.08  .       AB=0;ABP=0;AC=2;AF=1;AN=2;AO=27;CIGAR=4M1X;DP=31;DPB=31.8;DPRA=0;EPP=5.02092;EPPR=0;GTI=0;LEN=1;MEANALT=2;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=15.4221;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=804;QR=0;RO=0;RPL=10;RPP=6.95112;RPPR=0;RPR=17;RUN=1;SAF=14;SAP=3.09072;SAR=13;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.Illumina=1      GT:DP:AD:RO:QR:AO:QA:GL 1/1:31:0,27:0:0:27:804:-72.3478,-8.12781,0
```

the other samples also have the variant but it is called: A => T (actually the exact same variant but reported with 1 nucleotides)

 ```
1       101113852       .       A       T       823.684 .       AB=0;ABP=0;AC=2;AF=1;AN=2;AO=32;CIGAR=1X;DP=32;DPB=32;DPRA=0;EPP=3.0103;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=48.9666;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=960;QR=0;RO=0;RPL=24;RPP=20.3821;RPPR=0;RPR=8;RUN=1;SAF=16;SAP=3.0103;SAR=16;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.Illumina=1     GT:DP:AD:RO:QR:AO:QA:GL 1/1:32:0,32:0:0:32:960:-86.6875,-9.63296,0

1       101113852       .       A       T       835.947 .       AB=0;ABP=0;AC=2;AF=1;AN=2;AO=32;CIGAR=1X;DP=32;DPB=32;DPRA=0;EPP=3.0103;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=48.9666;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=960;QR=0;RO=0;RPL=14;RPP=4.09604;RPPR=0;RPR=18;RUN=1;SAF=20;SAP=7.35324;SAR=12;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.Illumina=1   GT:DP:AD:RO:QR:AO:QA:GL 1/1:32:0,32:0:0:32:960:-86.6875,-9.63296,0

1       101113852       .       A       T       948.013 .       AB=0;ABP=0;AC=2;AF=1;AN=2;AO=36;CIGAR=1X;DP=36;DPB=36;DPRA=0;EPP=3.25157;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=54.5118;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=1080;QR=0;RO=0;RPL=18;RPP=3.0103;RPPR=0;RPR=18;RUN=1;SAF=19;SAP=3.25157;SAR=17;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.Illumina=1  GT:DP:AD:RO:QR:AO:QA:GL 1/1:36:0,36:0:0:36:1080:-97.4859,-10.8371,0
```

### called in parallel (I tried to output gvcf but did not manage merge and genotype them as done in GATK4 !!):

```
pfx=$(basename ${bam%_recal.bam})
freebayes-parallel <(fasta_generate_regions.py ${reference_fai} 100000) \
  84 \
  -f ${reference_fa} \
  ${bam} \
  > ${outfolder}/${pfx}_freebayes.vcf
```

**Comment by ekg** [comment]
The variant was called over this full locus. Only one of the potential SNPs
was found in a called genotype. You can post process to normalize this
using vt or bcftools functions. Your variant comparison should not get
tripped up so long as it compares local haplotypes, which is relatively
standard today.

**Comment by splaisan** [comment]
Hi @ekg, so if I understand you well I should run bcftools norm on each sample VCF before merging them with bcftools merge (or after the merging?)
Also, I have no experience running 'bcftools norm', should I include additional parameters there (-m- for instance?)
I also never used 'vt normalize', can you please suggest some command there?
Thanks in advance

**Comment by pjotrp** [comment]
Please use this issue tracker to post bugs. For other questions use the mailing list.

**Comment by splaisan** [comment]
Will do, just that I thought this could be a bug.
