### ISSUE TITLE
High number of low QUAL score observations and filtering by QUAL score

### ISSUE THREAD

**Issue by sid-krish** [freebayes/freebayes#737]
I am noticing a large number of observations where the QUAL scores are very small values such as 1.84432e-14 or 0, on high quality simulated datasets. I was wondering why this could be the case? Could simulating recombination be a factor?

I am unsure if I should apply the  "QUAL > 20" filter here, as suggested in the documentation, as it would remove too many observations.

The bam, fasta and vcf in question are attached (Archive.zip).

I used the following command with freebayes:
freebayes -f rho_0.025_theta_0.005_sample_size_100_depth_4_genome_size_100000_seed_1_final.fa -p 1 rho_0.025_theta_0.005_sample_size_100_depth_4_genome_size_100000_seed_1_final_s.bam > freebayes_raw.vcf

[Archive.zip](https://github.com/freebayes/freebayes/files/8558968/Archive.zip)

**Comment by ekg** [comment]
In general these are sequencing errors that can be filtered out. Do you see
that true variants in your simulation are called with low quality?

**Comment by sid-krish** [comment]
using the --pooled-continous option instead of -p 1 improves the QUAL scores. I am simulating bacterial genomes so I used a ploidy value of 1. I think I may have misunderstood how -p is used.

**Comment by AstrobioMike** [comment]
Just adding a note in case it helps others who come across this like I did. 

I don't think adding `--pooled-continuous` is "instead" of `-p 1`, or that adding it improved the QUAL scores as suggested above. My poking is telling me `--pooled-continuous` allows reporting of multiple variants at the same site regardless of what the `-p`/`--ploidy` parameter is set to, but adding `--pooled-continuous` or not is having no impact on the QUAL scores that I'm seeing. So i think when @sid-krish removed `-p 1` in their testing above, it defaulted to `-p 2` under the hood, and that is what actually improved the QUAL scores. 

(on the off chance it's relevant for this, i'm working with v1.3.6 at the time of posting)
