### ISSUE TITLE
Confusing information about freebayes-parallel

### ISSUE THREAD

**Issue by ryanrichholt** [freebayes/freebayes#743]
https://github.com/freebayes/freebayes/blob/1efed0f272aa63c61860e6032fc027fd050c3bd5/README.md?plain=1#L165

"...some cores can go unused for long periods, as they will not move onto the next job unless all cores in use have completed their respective genome chunk."

I think there is an error in this statement - gnu-parallel begins executing the next job as soon as a previous job is complete. Can anyone clarify the issue here?

**Comment by ekg** [comment]
Yes it seems confusing.

The default operation is running the jobs with ordered output, parallel -k.
This is undesirable actually. It does cause locking behavior when the
buffers for storing output get full.

**Comment by ryanrichholt** [comment]
@ekg Thanks, that makes sense. It does seem like it could be refactored so that the parallel steps write out to disk. After it's done cat them all through the stream processing steps to generate the final result. Do you see any issues with that approach that I'm missing?

**Comment by ekg** [comment]
This would be ideal, at least as good as possible without rewriting
freebayes to handle the parallelism internally.

**Comment by ryanrichholt** [comment]
Thanks for the help with this. I think that resolves the issue.
