### ISSUE TITLE
Outputting GL when calling variants on polyploids

### ISSUE THREAD

**Issue by trevorfaske** [freebayes/freebayes#744]
Hey, 

I saw this issue has been addressed before here (https://github.com/freebayes/freebayes/issues/152) but I am unaware if it was ever resolved or if the work around could be explained in more detail. I am currently calling variants on diploid and tetraploid individuals and everything is working just fine other than the lack of GL for each locus. I am interested in this rather than hard genotype calls because I want to incorporate genotype uncertainty in my data. 

Thank you ahead of time!

**Comment by YannDussert** [comment]
Hi,

Just wanted to mention I have the same issue (need genotype likelihoods for variants in polyploids) and would be very interested if a solution exists!

Thanks!
Yann
