### ISSUE TITLE
freebayes-parrallel Error: signal 11

### ISSUE THREAD

**Issue by dollykc** [freebayes/freebayes#752]
Hi all,
 I just installed freebayes and freebayes-parallel. My obstacle is the error message I've attached.  The commands that got me here were
freebayes-parallel <(fasta_generate_regions.py /path/to/sanVit.fa.fai 100000) 20 -f /path/to/sanVit.fa -m 30 -r R1_9 ../path/to/SviPEND18C_0002.merged.bam > test.vcf
The vcf file continued to populate as the errors accumulated. My plan was to replace the single bam file with a list of bam files, but I wanted to do a test run with a single bam file first. I went back to regular freebayes and it seems to be working, but will take a long time with 50 bam files.[](url
![Capture](https://user-images.githubusercontent.com/108284544/183822189-f2ac8a9a-2478-4bde-a83b-1388f3749d9d.JPG)
)

**Comment by benedict909** [comment]
Also having this problem, I have tried freebayes versions 1.3.2 and 1.3.6 both with the same error :(

**Comment by pjotrp** [comment]
If someone gives a way that we can reproducibly generate this segfault we can try to fix it.
