### ISSUE TITLE
Indels as single nucleotide indels

### ISSUE THREAD

**Issue by elsasverris** [freebayes/freebayes#754]
Hi,
I wonder if it's possible to get freebayes to report indels more simplistically, for example as a single nucleotide insertion/deletion instead of grouping them in haplotypes? I mean for example this deletion: 
GTTTAA    GTTAA
where I would like it to be reported as 
T    -
I have searched for the answer in your guide without luck, but maybe I'm missing something.

Best regards,
Elsa

**Comment by ekg** [comment]
You should apply vcfwave in vcflib to do this.

**Comment by elsasverris** [comment]
Hi Erik,
Yes, that sounds exactly what I need. Is v1.0.4 with vcfwave released yet? I can't find it on the github.

**Comment by ekg** [comment]
Hmmmm it should be in master now.

**Comment by ekg** [comment]
It hasn't been released yet. But it is available if you can build the repo.
It should be straightforward but let me know if it doesn't work.

**Comment by pjotrp** [comment]
vcflib just got released. Sorry for the wait.
