### ISSUE TITLE
population issues

### ISSUE THREAD

**Issue by yilevine** [freebayes/freebayes#759]
Hi,

I was using freebayes to call variants on a pooled bam file which contains 4 samples. And I was wondering how I can get a mixed genotype in the vcf file, rather than an individual genotype for each sample.
I read the manual, but unfortunately, I didn't find this function.
Do you have any idea?

Thanks
Yile

**Comment by Virginia-b** [comment]
Hello, I have the same question. Did you find it out?
Thank you, 
Virginia :)
