### ISSUE TITLE
Variant calling with nanopore data on multiple loci

### ISSUE THREAD

**Issue by Coryza** [freebayes/freebayes#760]
Hi,

I'm trying to get Freebayes working on a data-set that is rather simplistic; namely multiple sites in a genome with stacks of reads with roughly the same start/end/content. No matter what I try, I don't get any output except the headers. When I just want to run it on a very small piece of my data-set, I get output that looks like;

```
...
...
...
addAllele: mergeAllele/4: lastAllele complex@37696943:2D2I2D1I1D6I1D1I2D7I2D1I27D2I2D4I2D3I1D5I3D1I2D10I2D2I3D1I3D1I1D2I1D2I newAllele deletion@37697000:2D
addAllele: mergeAllele/4: lastAllele complex@37696943:2D2I2D1I1D6I1D1I2D7I2D1I27D2I2D4I2D3I1D5I3D1I2D10I2D2I3D1I3D1I1D2I1D2I2D newAllele insertion@37697002:1I
addAllele: mergeAllele/4: lastAllele complex@37696943:2D2I2D1I1D6I1D1I2D7I2D1I27D2I2D4I2D3I1D5I3D1I2D10I2D2I3D1I3D1I1D2I1D2I2D1I newAllele deletion@37697002:5D
addAllele: mergeAllele/4: lastAllele complex@37696943:2D2I2D1I1D6I1D1I2D7I2D1I27D2I2D4I2D3I1D5I3D1I2D10I2D2I3D1I3D1I1D2I1D2I2D1I5D newAllele insertion@37697007:15I
addAllele: mergeAllele/4: lastAllele complex@37696943:2D2I2D1I1D6I1D1I2D7I2D1I27D2I2D4I2D3I1D5I3D1I2D10I2D2I3D1I3D1I1D2I1D2I2D1I5D15I newAllele deletion@37697007:1D
...
...
...
position: Chr1:37699836 coverage: 0
no alleles left at this site after filtering
processing position 37699837 in sequence Chr1
position: Chr1:37699837 coverage: 0
no alleles left at this site after filtering
processing position 37699838 in sequence Chr1
position: Chr1:37699838 coverage: 0
no alleles left at this site after filtering
...
...
...
no more targets, finishing
total sites: 39
processed sites: 0
ratio: 0
```
![Freebayes](https://user-images.githubusercontent.com/7194842/203304048-67b27e85-a198-4575-8612-b163e74dab8b.png)

freebayes -d --min-alternate-count 0 --min-alternate-fraction 0 --min-alternate-total 0 --mismatch-base-quality-threshold 0 --min-supporting-mapping-qsum 0 --report-monomorphic --report-all-haplotype-alleles --min-coverage 0 --use-duplicate-reads --min-mapping-quality 0 --allele-balance-priors-off --binomial-obs-priors-off --hwe-priors-off -d -r Chr1:37699835-37699873 -f reference.fasta data.bam

Any clue?

**Comment by Coryza** [comment]
I've resolved the issue, although the bug remains; it seems like freebayes cannot deal with the old representation of a CIGAR string (minimap paramater --eqx)

**Comment by ekg** [comment]
The non X and = containing format is older. But interesting that this
regression happened. It should still work with the various standard cigar
formats.

**Comment by Coryza** [comment]
Thanks for the prompt response! Well, the software comes a long way as it for sures recognizes parts of the CIGAR string :). I usually stick to the old format of CIGAR string representation simply because it's more understandable for the eye when looking at the data as plain text.

**Comment by ekg** [comment]
Could you email me a minimal example of the problematic data?

**Comment by Coryza** [comment]
Unfortunately I can't, this example contains proprietary data :(
