### ISSUE TITLE
missing freebayes-1.3.7-src.tar.gz artifact for 1.3.7 release

### ISSUE THREAD

**Issue by chenrui333** [freebayes/freebayes#765]
👋 it looks like for the latest release, the `tar.gz` file is missing. Just create an issue for some awareness, thanks!

**Comment by lpryszcz** [comment]
also binary is missing `freebayes-1.3.7-linux-amd64-static.gz`

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-core/pull/123273

**Comment by chenrui333** [comment]
Any taker here?

**Comment by anderspitman** [comment]
Also hitting this

**Comment by chenrui333** [comment]
cc @pjotrp @martin-g

**Comment by martin-g** [comment]
I am not a maintainer of this project. I cannot help with this.
