### ISSUE TITLE
pre-built binary not available

### ISSUE THREAD

**Issue by vappiah** [freebayes/freebayes#770]
Dear Developer

You made mention there is a pre-built 64-bit static Linux binary. But I can't seem to find it in the releases (1.3.7).
I guess I have to build from source.

**Comment by pur80a** [comment]
related to #765

**Comment by ekg** [comment]
You can install in debian and Ubuntu. But the version may be slightly
older.

**Comment by pur80a** [comment]
@ekg thanks for the hint. This is what I did: 
```
VERSION=1.3.6
wget https://github.com/freebayes/freebayes/releases/download/v${VERSION}/freebayes-${VERSION}-linux-amd64-static.gz
gunzip freebayes-${VERSION}-linux-amd64-static.gz
mv freebayes-${INSTALLVERSION}-linux-amd64-static freebayes
chmod +x freebayes
wget https://raw.githubusercontent.com/freebayes/freebayes/v${VERSION}/scripts/freebayes-parallel -O freebayes-parallel
chmod +x freebayes-parallel
```
this unfortunately does not work for version 1.3.7.

**Comment by pjotrp** [comment]
you can test https://files.genenetwork.org/software/gemma/
