### ISSUE TITLE
Freebayes stuck

### ISSUE THREAD

**Issue by seynard** [freebayes/freebayes#774]
Hi,

I'm running freebayes for de novo variant calling on Oxford Nanopore Technology sequencing data (bam files produced by PromethION) for pool sequenced experiment. 
I'm testing freebayes on a chromosome for 15 pools and it stays stuck after 7Kb. It does not get killed but it also does not write anymore. I looked at my row data on IVG and I do not have a large coverage in this region (just a couple of X) as it as been mentioned in the issue #614 (https://github.com/freebayes/freebayes/issues/614).
If I run freebayes with 3 pools the calling is performed but form 4 pools onwards (any of them) it gets stuck. 
Here is the command i'm running:   
freebayes -f ${fasta} --min-alternate-count 1 --min-alternate-fraction 0.01 --use-best-n-alleles 2 --cnv-map ${bam_list} --pooled-discrete ${dir_work}/freebayes/*_${c}.header.sorted.rename.filter.bam | vcffilter -f "QUAL > 20" -f "AF < 1" | vcffilter --or -f "TYPE = del" --or -f "TYPE = ins" -f "TYPE = snp" > ${dir_work}/freebayes/${c}.freebayes.vcf

I already tried to ask for more memory (up to 500G), without success. 
Would you have an idea where this issue is coming from?

**Comment by friburgo-moc** [comment]
I have published an issue that may be similar (https://github.com/freebayes/freebayes/issues/777), does it work better if you used a higher min-alternate-fraction? does it work better if you use a freebayes version lower than 1.3.1?
