### ISSUE TITLE
Error during freebayes call for one single chromosome

### ISSUE THREAD

**Issue by floro5** [freebayes/freebayes#790]
Hi there,
I'm using freebayes (version 1.3.7 in conda) to call variants from a bam file (_dICP0_1.bam_) that contains both aligned/mapped human reads (indicated by _chr1_, _chr2_ etc. in the bam file) as well as viral reads (from HSV-1, indicated by _chrHsv1_s17_ in the bam file). I've got the reference genome for HSV-1 (_chrHsv1_s17.fa_) and now wanted to call variants using freebayes for only the mapped viral reads (so not for the human reads!). I therefore executed the following command: 
`freebayes -f chrHsv1_s17.fa -r chrHsv1_s17 dICP0_1.bam > outputVariants.vcf`. 
But the call raises the following error and I don't know how to fix it or if I simply used the command in a wrong way:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 0) >= this->size() (which is 0)
[1]    24475 abort (core dumped)  freebayes -f  -r chrHsv1_s17 > outputVariants.vcf
```
Does anyone have an idea or had a similar error?
Thanks for your help!!! :)

**Comment by dsobral** [comment]
Have you tried:
freebayes -f chrHsv1_s17.fa -r chrHsv1_s17 dICP0_1.bam -v outputVariants.vcf
?
