### ISSUE TITLE
variant calling

### ISSUE THREAD

**Issue by DaliBAmor** [freebayes/freebayes#791]
Hi
Difference among these mutations : All of them are insertions ( I'm sure about it ) :

**Variant 1: E203-DE-V204
Variant 2: E203-VE-V204
Variant 3: Glu203_Val204insAspGlu**

Thanks  :)

**Comment by Knight-JChev** [comment]
Hello,

I'm not sure you're on the right place to ask this kind of questions, only freebayes bug related topics are supposed to be here.

Still here are my thoughts. 

First you are on a protein sequence. 
Then, a bit of amino acid logic gives : 
- E = glutamate or Glu or glutamic acid
- V = valine or Val
- D = aspartate or aspartic acid or Asp 
- Number = position

So following this logic : 
- Variant 1 : insertion of Asp and Glu between Glu at position 203 and Val at position 204 of your reference
- Variant 2 : insertion of Val and Glu between Glu at position 203 and Val at position 204 of your reference
- Variant 3 : Same as variant 1 but with different writing.

**Comment by DaliBAmor** [comment]
> Hello,
> 
> I'm not sure you're on the right place to ask this kind of questions, only freebayes bug related topics are supposed to be here.
> 
> Still here are my thoughts.
> 
> First you are on a protein sequence. Then, a bit of amino acid logic gives :
> 
> * E = glutamate or Glu or glutamic acid
> * V = valine or Val
> * D = aspartate or aspartic acid or Asp
> * Number = position
> 
> So following this logic :
> 
> * Variant 1 : insertion of Asp and Glu between Glu at position 203 and Val at position 204 of your reference
> * Variant 2 : insertion of Val and Glu between Glu at position 203 and Val at position 204 of your reference
> * Variant 3 : Same as variant 1 but with different writing.
> 
> The three (more like two) of them exists in different sequences.

thank you very much !!!!
Can I contact you privately by email please ?
