### ISSUE TITLE
FreeBayes sudden error

### ISSUE THREAD

**Issue by emilydolivo97** [freebayes/freebayes#794]
I'm used to run the same freebayes code on my BAM files. I tried today to rerun the same code on the same bam files using the same conda env but I have this error. I'm using these packages version :

minimap2==2.26
samtools==1.19.2
freebayes==1.3.7
( in my script I combined minimap2 and freebayes)

**/opt/conda/conda-bld/freebayes_1711687983774/_build_env/x86_64-conda-linux-gnu/include/c++/12.3.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator [with _Tp = Allele; _Alloc = std::allocator<Allele>; reference = Allele*&; size_type = long unsigned int]: Assertion '__n < this->size()' failed. Aborted (core dumped)**

**Comment by ryan-earp** [comment]
I am having the same issues.

/opt/conda/conda-bld/freebayes_1711687983774/_build_env/x86_64-conda-linux-gnu/include/c++/12.3.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = Allele*; _Alloc = std::allocator<Allele*>; reference = Allele*&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)

**Comment by emilydolivo97** [comment]
> I am having the same issues.
> 
> /opt/conda/conda-bld/freebayes_1711687983774/_build_env/x86_64-conda-linux-gnu/include/c++/12.3.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator [with _Tp = Allele*; _Alloc = std::allocator<Allele*>; reference = Allele*&; size_type = long unsigned int]: Assertion '__n < this->size()' failed. Aborted (core dumped)

Please inform me when you have resolved this issue, and I will reciprocate.

**Comment by emilydolivo97** [comment]
> I am having the same issues.
> 
> /opt/conda/conda-bld/freebayes_1711687983774/_build_env/x86_64-conda-linux-gnu/include/c++/12.3.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator [with _Tp = Allele*; _Alloc = std::allocator<Allele*>; reference = Allele*&; size_type = long unsigned int]: Assertion '__n < this->size()' failed. Aborted (core dumped)

you need to downgrade freebayes version to 1.3.6

**Comment by emollier** [comment]
Hi Pjotr,

Symptoms described in this issue are matching the test errors I'm running into while trying to integrate freebayes 1.3.8 into Debian sid.  To reproduce the issue after building the binary:
```
$ cd test/
$ ../build/freebayes -f tiny/q.fa tiny/NA12878.chr22.tiny.bam
[...]
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	1
/usr/include/c++/13/bits/stl_vector.h:1125: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = Allele*; _Alloc = std::allocator<Allele*>; reference = Allele*&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted
$ echo $?
134
```

Is it something you run into on your side?  If not, I'd be curious about the difference between our platforms.

Cheers,
Étienne.
