### ISSUE TITLE
 Assertion '__n < this->size()' failed. Error when running freebayes 

### ISSUE THREAD

**Issue by kinchuhrithik** [freebayes/freebayes#796]
Hii I am trying to run freebayes-parallel on a list of 170 .bam files. I did the sorting and indexing with samtools, Then executed the following command-
freebayes-parallel <(fasta_generate_regions.py ~/Gossypium_hirsutum_v3.1_assembly/Ghirsutum_578_v3.0.fna.fai 100000) 20 -f ~/Gossypium_hirsutum_v3.1_assembly/Ghirsutum_578_v3.0.fna --bam-list bam.fofn >out.vcf

And got long stretches of  this error repeating -

/opt/conda/conda-bld/freebayes_1711687983774/_build_env/x86_64-conda-linux-gnu/include/c++/12.3.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = Allele*; _Alloc = std::allocator<Allele*>; reference = Allele*&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.

I am using freebayes  version1.3.7 via conda, does anyone know how to solve this issue?

**Comment by lianmsu** [comment]
I also meet this error when using freebayes version1.3.7 via conda.

$ freebayes -f /media/YL3/LPW/Defensome/all_DGs_sequence/dup_DGseq.fa /media/YL3/LPW/Defensome/all_DGs_sequence/BWA_MEM/sorted_bam/Cd11.sorted.bam > Cd11.try.vcf
/opt/conda/conda-bld/freebayes_1711687983774/_build_env/x86_64-conda-linux-gnu/include/c++/12.3.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = Allele*; _Alloc = std::allocator<Allele*>; reference = Allele*&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)

Thank you for anwser!

**Comment by lianmsu** [comment]
Thank you for your reply. My server is ubuntu and I still have the same error after updating freebayes in conda. Can you please tell me what is going on?
update with: mamba update freebayes

Is there something wrong with the way I'm downloading or updating?
Thank you for reply!

**Comment by SerhEL** [comment]
> Я также сталкиваюсь с этой ошибкой при использовании freebayes версии 1.3.7 через conda.
> 

Solution:
conda install freebayes=1.3.6
