### ISSUE TITLE
Freebayes & overlapping reads

### ISSUE THREAD

**Issue by gusevfe** [freebayes/freebayes#85]
Hello.

How does freebayes deal with overlapping reads (when insert_size is < 2*read_size)? If both reads have the same base in overlapping portion, does it account for non-independence of these two observations?

Thank you.

**Comment by tseemann** [comment]
@gusevfe Would pre-overlapping the reads with something like PEAR or FLASH help with this?

I guess it it could make things worse if the locus contained short tandem repeats?

**Comment by ekg** [comment]
It does not properly collapse these non independent overlaps. This could be
done upstream by merging overlapping read pairs into a single contig. I
would like to resolve this but think it may become easier in vg.
