### ISSUE TITLE
Support for CRAM files

### ISSUE THREAD

**Issue by tseemann** [freebayes/freebayes#90]
Now that SAMtools 1.0 is released and supports CRAM files, I was wondering if there were any plans to add CRAM support to Freebayes?

Reference: http://www.ebi.ac.uk/ena/about/cram_toolkit

(I understand you probably want to add it, but time to do these major things is scarce!)

**Comment by tseemann** [comment]
@ekg Now that you are migrat(ed/ing) to htslib, will native CRAM be possible?

**Comment by tseemann** [comment]
@ekg does freebayes 1.1 support CRAM now?

**Comment by drtjpemberton** [comment]
According to a recent paper by Wala et al. in [Bioinformatics](https://academic.oup.com/bioinformatics/article-abstract/33/5/751/2571356/SeqLib-a-C-API-for-rapid-BAM-manipulation-sequence) Freebayes supports CRAM files when it is compiled with the SeqLib package. Based on the [Freebayes documentation](https://github.com/ekg/freebayes#compilation), it is compiled with SeqLib by default. The latest release should therefore support CRAM files, although none of the documentation states this at the time of me writing this!
