### ISSUE TITLE
standard list of test cases

### ISSUE THREAD

**Issue by ekg** [freebayes/freebayes#99]
Before any new commit is registered I have been running a regression test based around the genome in a bottle truth set and a simulated dataset.

However, the coverage of this test is very limited. We need test cases, at least internally, before pushing code to the public repository.

Ideally, we do this in a very rigorous way prior to generating a new version release. (Which leads to another issue... versioned releases!)

**Comment by mdshw5** [comment]
+1 for seeing the regression tests. I'm assuming the tests take a while to run, and exclude a hosted CI platform like Travis-CI.org?
